import { frameworkBaseGame, objectTypes } from "@bonanzainteractive/slote_core";
frameworkBaseGame.data = {
    "POS_X": 0,
    "POS_Y": 0,
    "COMPONENTS": [
        {
            "id": "BMBaseGameContainer_baseLayer",
            "name": "BMBaseGameContainer_baseLayer",
            "type": "Container",
            "class": "",
            "x": 0,
            "y": 0,
            "filterTypes": [],
            "parentLayer": "baseLayer",
            child: [
                {
                    "id": "BMBaseGameComponent",
                    "name": "GofBaseGame",
                    "type": "Tag",
                    "class": "",
                    "filterTypes": [],
                    child: [
                        {
                            "name": "basegame_desk_Bg",
                            "image": "basegame_desk_Bg",
                            "type": "Image",
                            "uimode": "desktop",
                            "anchor": [0.5, 0.5],
                            "visible": true,
                            "width": 1920,
                            "height": 1920,
                            "x": 960,
                            "y": 566
                        },
                        // {
                        //     "id": "basegameAnimation_desktop",
                        //     "name": "basegame_animation",
                        //     "type": "Spine",
                        //     "width": 1922,
                        //     "height": 1082,
                        //     "image": "basegame",
                        //     "animationSpeed": 0.2,
                        //     "playing": false,
                        //     "uimode": "desktop",
                        //     "loop": false,
                        //     "visible": true,
                        //     "effectType": "abc",
                        //     "maskHeight": 336,
                        //     "spineAnimName": "basegame",
                        //     "anchor": [0.5, 0.5],
                        //     "x": 960,
                        //     "y": 540,
                        //     "spinedata": {
                        //         "spinename": "basegame_animation",
                        //         "animationname": "basegame",
                        //         "loop": true,
                        //         "timeScale": 0.5
                        //     },
                        // },
                        {
                            "name": "basegame_bg",
                            "image": "basegame_desk_Bg",
                            "type": "Image",
                            "layout": true,
                            "uimode": "mobile",
                            "anchor": [0.5, 0.5],
                            "visible": true,
                            "width": 1920,
                            "height": 1920,
                            "x": 540,
                            "y": 960
                        },
                        {
                            "name": "basegame_landscape_bg",
                            "image": "basegame_landscape_bg",
                            "type": "Image",
                            "layout": true,
                            "uimode": "mobile",
                            "class": "",
                            //"parentLayer": "baseLayer",
                            "anchor": [0.5, 0.5],
                            "visible": true,
                            "width": 1920,
                            "height": 1920,
                            "x": 960,
                            "y": 540
                        },
                        {
                            "name": "common_bgGraphic_for_feature",
                            "type": "Graphic",
                            "shape": "rectangle",
                            "visible": false,
                            "uimode": "desktop",
                            "alpha": 0.82,
                            // "alpha": 0.82,
                            "color": "0x000000",
                            "x": 0,
                            "y": 0,
                            "width": 1920,
                            "height": 1080,

                        }, 
                        {
                            "name": "common_bgGraphic_for_feature",
                            "type": "Graphic",
                            "shape": "rectangle",
                            "uimode": "mobile",
                            "visible": false,
                            "alpha": 0.82,
                            "color": "0x000000",
                            "x": 0,
                            "y": 0,
                            "width": 1920,
                            "height": 1920,

                        }, 
                        {
                            "name": "BG_Reel_Outer_Frame",
                            "image": "Bg_frame_Outer",
                            "type": "Image",
                            "uimode": "desktop",
                            "parentLayer": "specialAnimationLayer",
                            "anchor": [0.5, 0.5],
                            "visible": true,
                            "width": 1441,
                            "height": 949,
                            "x": 952,
                            "y": 475
                        },
                        {
                            "name": "BG_Reel_Outer_Frame",
                            "image": "Bg_frame_Outer",
                            "type": "Image",
                            "layout": true,
                            "uimode": "mobile",
                            "parentLayer": "specialAnimationLayer",
                            "anchor": [0.5, 0.5],
                            "visible": true,
                            "width": 1441,
                            "height": 949,
                            "x": 540,
                            "y": 871
                        },
                        {
                            "name": "BG_Reel_Outer_Frame_Landscape",
                            "image": "Bg_frame_Outer",
                            "type": "Image",
                            "layout": true,
                            "uimode": "mobile",
                            "class": "",
                            "parentLayer": "specialAnimationLayer",
                            "anchor": [0.5, 0.5],
                            "visible": true,
                            "width": 1441,
                            "height": 949,
                            "x": 947,
                            "y": 500
                        },
                    ]
                }
            ]
        },
        {
            "id": "BMBaseGameContainer_specialLayer",
            "name": "BMBaseGameContainer_specialLayer",
            "type": "Container",
            "class": "",
            "x": 0,
            "y": 0,
            "filterTypes": [],
            "parentLayer": "specialAnimationLayer",
            child: [
                {
                    "id": "BMBaseGameComponent",
                    "name": "GofBaseGame",
                    "type": "Tag",
                    "class": "",
                    "filterTypes": [],
                    child: [
                        {
                            "name": "BaseGameLogo",
                            "image": "bgLogo",
                            "type": "Image",
                            "layout": true,
                            "parentLayer": "specialAnimationLayer",
                            "visible": true,
                            "width": 327,
                            "height": 286,
                            "x": 2,
                            "y": -77
                        },
                        {
                            "name": "BaseGameLogo_Portrait",
                            "image": "bgLogo_Portrait",
                            "type": "Image",
                            "layout": true,
                            "parentLayer": "specialAnimationLayer",
                            "uimode": "mobile",
                            "visible": false,
                            "width": 587,
                            "height": 1051,
                            "x": 118,
                            "y": 18
                        },           
                        {
                            "id": "text_6",
                            "name": "text_win_value1",
                            "uimode": "desktop",
                            "type": "Text",
                            "x": 1350,
                            "y": 964.5,
                            "width": 400,
                            "visible": false,
                            "text": "     ",
                            "scaleToFit": true,
                            "anchor": [0.5, 0.5],
                            "textStyle": {
                                fontFamily: 'Arial',
                                fontSize: 36,
                                fontWeight: 'bold',
                                fill: ['#ffffff'],

                            },
                            "parentLayer": "specialAnimationLayer",
                        },

                        {
                            "id": "text_M1",
                            "name": "Mobiletext_win_label",
                            "type": "Text",
                            "layout": true,
                            "visible": false,
                            "uimode": "mobile",
                            "x": 1340,
                            "y": 1050,
                            "width": 200,
                            "text": "buttonPanelText_5",
                            "scaleToFit": true,
                            "anchor": [1, 0.5],
                            "textStyle": {
                                fontFamily: 'MYP Bold',
                                fontSize: 48,
                                fontWeight: 'bold',
                                fill: ['#e2be20'],
                            },
                            "parentLayer": "specialAnimationLayer",
                        },
                        {
                            "id": "text_M2",
                            "name": "Mobiletext_mobColonSymbol1",
                            "layout": true,
                            "visible": false,
                            "uimode": "mobile",
                            "type": "Text",
                            "x": 1349,
                            "y": 1048,
                            "width": 18,
                            "text": "buttonPanelText_13",
                            "scaleToFit": true,
                            "anchor": [0.5, 0.5],
                            "textStyle": {
                                fontFamily: 'Arial',
                                fontSize: 32,
                                fontWeight: 'bold',
                                fill: ['#ffffff'],
                            },
                            "parentLayer": "specialAnimationLayer",
                        },
                        {
                            "id": "text_M3",
                            "name": "Mobiletext_win_value",
                            "type": "Text",
                            "layout": true,
                            "visible": false,
                            "uimode": "mobile",
                            "x": 300,
                            "y": 1050,
                            "width": 200,
                            "text": "            ",
                            "scaleToFit": true,
                            "anchor": [0, 0.5],
                            "textStyle": {
                                fontFamily: 'Arial',
                                fontSize: 34,
                                fill: ['#ffffff'],
                            },
                            "parentLayer": "specialAnimationLayer",
                        },

                        {
                            "id": "text_M4",
                            "name": "Mobiletext_balance_label",
                            "type": "Text",
                            "layout": true,
                            "uimode": "mobile",
                            "x": 400,
                            "y": 1050,
                            "visible": false,
                            "width": 520,
                            "text": "buttonPanelText_3",
                            "scaleToFit": true,
                            "anchor": [1, 0.5],
                            "textStyle": {
                                fontFamily: 'MYP Bold',
                                fontSize: 40,
                                fontWeight: 'bold',
                                fill: ['#e2be20'],
                            },
                            "parentLayer": "specialAnimationLayer",
                        },
                        {
                            "id": "text_M5",
                            "name": "Mobiletext_mobColonSymbol2",
                            "layout": true,
                            "uimode": "mobile",
                            "type": "Text",
                            "x": 509,
                            "y": 1048,
                            "width": 18,
                            "visible": false,
                            "text": "buttonPanelText_13",
                            "scaleToFit": true,
                            "anchor": [0.5, 0.5],
                            "textStyle": {
                                fontFamily: 'Arial',
                                fontSize: 32,
                                fontWeight: 'bold',
                                fill: ['#ffffff'],
                            },
                            "parentLayer": "specialAnimationLayer",
                        },
                        {
                            "id": "text_M6",
                            "name": "Mobiletext_balance_value",
                            "type": "Text",
                            "layout": true,
                            "uimode": "mobile",
                            "x": 418,
                            "y": 1050,
                            "visible": false,
                            "width": 206,
                            "text": "MobViewButtonPanelText2",
                            "scaleToFit": true,
                            "anchor": [0, 0.5],
                            "textStyle": {
                                fontFamily: 'MYP Bold',
                                fontSize: 40,
                                fill: ['#ffffff'],
                            },
                            "parentLayer": "specialAnimationLayer",
                        },



                        {
                            "id": "text_M7",
                            "name": "Mobiletext_bet_label",
                            "type": "Text",
                            "layout": true,
                            "visible": false,
                            "uimode": "mobile",
                            "x": 968,
                            "y": 1050,
                            "width": 250,
                            "text": "buttonPanelText_1",
                            "scaleToFit": true,
                            "anchor": [1, 0.5],
                            "textStyle": {
                                fontFamily: 'MYP Bold',
                                fontSize: 40,
                                fontWeight: 'bold',
                                fill: ['#e2be20'],
                            },
                            "parentLayer": "specialAnimationLayer",
                        },
                        // {
                        //     "id": "text_M8",
                        //     "name": "Mobiletext_mobColonSymbol3",
                        //     "layout": true,
                        //     "visible": false,
                        //     "uimode": "mobile",
                        //     "type": "Text",
                        //     "x": 981,
                        //     "y": 1048,
                        //     "width": 18,
                        //     "text": "buttonPanelText_13",
                        //     "scaleToFit": true,
                        //     "anchor": [0.5, 0.5],
                        //     "textStyle": {
                        //         fontFamily: 'Arial',
                        //         fontSize: 32,
                        //         fontWeight: 'bold',
                        //         fill: ['#ffffff'],
                        //     },
                        //     "parentLayer": "specialAnimationLayer",
                        // },
                        // {
                        //     "id": "text_M9",
                        //     "name": "Mobiletext_bet_value",
                        //     "type": "Text",
                        //     "layout": true,
                        //     "visible": true,
                        //     "uimode": "mobile",
                        //     "x": 993,
                        //     "y": 1050,
                        //     "width": 100,
                        //     "text": "abcdef",
                        //     "scaleToFit": true,
                        //     "anchor": [0, 0.5],
                        //     "textStyle": {
                        //         fontFamily: 'Arial',
                        //         fontSize: 32,
                        //         fill: ['#ffffff'],

                        //     },
                        //     "parentLayer": "specialAnimationLayer",
                        // },

                        // {
                        //     "id": "text_7",
                        //     "name": "text_balance_label_mobile",
                        //     "type": "Text",
                        //     "uimode": "mobile",
                        //     "layout": true,
                        //     "x": 1630,
                        //     "y": 910,
                        //     "width": 890,
                        //     "visible": true,
                        //     "text": "buttonPanelText_0",
                        //     "scaleToFit": true,
                        //     "anchor": [1, 0.5],
                        //     "textStyle": {
                        //         fontFamily: 'Arial',
                        //         fontSize: 32,
                        //         fontWeight: 'bold',
                        //         fill: ['#ffffff'],
                        //         wordWrap: true,
                        //         align: 'center'
                        //     },
                        //     "parentLayer": "specialAnimationLayer",
                        // },
                        // {
                        //     "id": "text_M8",
                        //     "name": "Mobiletext_mobColonSymbol5",
                        //     "layout": true,
                        //     "uimode": "mobile",
                        //     "type": "Text",
                        //     "x": 512,
                        //     "y": 934,
                        //     "width": 18,
                        //     "text": "buttonPanelText_13",
                        //     "scaleToFit": true,
                        //     "anchor": [0.5, 0.5],
                        //     "textStyle": {
                        //         fontFamily: 'Arial',
                        //         fontSize: 32,
                        //         fontWeight: 'bold',
                        //         fill: ['#ffffff'],
                        //     },
                        //     "parentLayer": "specialAnimationLayer",
                        // },
                        {
                            "id": "text_8_mobile",
                            "name": "text_balance_value_mobile",
                            "uimode": "mobile",
                            "layout": true,
                            "type": "Text",
                            "x": 524,
                            "y": 935.5,
                            "width": 200,
                            "visible": false,
                            "text": "abcd",
                            "scaleToFit": true,
                            "anchor": [0, 0.5],
                            "textStyle": {
                                fontFamily: 'Arial',
                                fontSize: 34,
                                fontWeight: 'bold',
                                fill: ['#ffffff'],
                            },
                            "parentLayer": "specialAnimationLayer",
                        },

                        // {
                        //     "id": "text_M8",
                        //     "name": "Mobiletext_mobColonSymbol4",
                        //     "layout": true,
                        //     "visible": false,
                        //     "uimode": "mobile",
                        //     "type": "Text",
                        //     "x": 1655,
                        //     "y": 1048,
                        //     "width": 18,
                        //     "text": "buttonPanelText_13",
                        //     "scaleToFit": true,
                        //     "anchor": [0.5, 0.5],
                        //     "textStyle": {
                        //         fontFamily: 'Arial',
                        //         fontSize: 32,
                        //         fontWeight: 'bold',
                        //         fill: ['#ffffff'],
                        //     },
                        //     "parentLayer": "specialAnimationLayer",
                        // },

  
                        {
                            "id": "voucherGraphic_4",
                            "name": "voucherGraphic_4",
                            "type": "Graphic",
                            "uimode": "mobile",
                            "layout": true,
                            "shape": "rectangle",
                            "color": "0x000000",
                            "alpha": 0.89,
                            "x": 95,
                            "y": 533,
                            "width": 90,
                            "height": 90,
                            "visible": false,
                            "scaleToFit": true,
                        },
                        {
                            "id": "voucherText5",
                            "name": "voucherText5",
                            "type": "Text",
                            "uimode": "mobile",
                            "layout": true,
                            "x": 138,
                            "y": 578,
                            "width": 250,
                            "text": "0",
                            "scaleToFit": true,
                            "visible": false,
                            "anchor": [0.5, 0.5],
                            "textStyle": {
                                fontFamily: 'Arial',
                                fontSize: 40,
                                fontWeight: 'bold',
                                fill: ['#f8f8ff'],
                            },
                        },
                      
                        {
                            "id": "MobileSettingPanelTag",
                            "name": "MobileSettingPanel",
                            "type": "Tag",
                            "class": "",
                            "parentLayer": "specialAnimationLayer",
                            "filterTypes": [],
                            child: []
                        },

                        {
                            "id": "CanvasMobilePaytable",
                            "name": "CanvasMobilePaytable",
                            "type": "Tag",
                            "class": "",
                            child: []
                        },
                        {
                            "id": "CanvasMobileBet",
                            "name": "CanvasMobileBet",
                            "type": "Tag",
                            "class": "",
                            child: []
                        },
                        {
                            "id": "BetHistoryComponent2",
                            "name": "BetHistoryComponent2",
                            "type": "Tag",
                            "class": "",
                            "parentLayer": "specialAnimationLayer",
                            "filterTypes": [],
                            child: []
                        },

                        {
                            "id": "GameSettingsContainer",
                            "name": "GameSettingsContainer",
                            "type": "Tag",
                            "class": "",
                            "parentLayer": "specialAnimationLayer",
                            "filterTypes": [],
                            child: []
                        },
                        {
                            "id": "BetHistoryComponent",
                            "name": "BetHistoryComponent",
                            "type": "Tag",
                            "class": "",
                            "parentLayer": "specialAnimationLayer",
                            "filterTypes": [],
                            child: []
                        },

                        {
                            "id": "CanvasMobilePaytablePortrait",
                            "name": "CanvasMobilePaytablePortrait",
                            "type": "Tag",
                            "class": "",
                            child: []
                        },

                        {
                            "id": "CanvasAutoplayPortrait",
                            "name": "CanvasAutoplayPortrait",
                            "type": "Tag",
                            "class": "",
                            "parentLayer": "specialAnimationLayer",
                            "filterTypes": [],
                            child: []
                        },

                        {
                            "id": "SoundText",
                            "name": "SoundText",
                            "type": "Tag",
                            "class": "",
                            "parentLayer": "specialAnimationLayer",
                            "filterTypes": [],
                            child: []
                        },			            
                        {
                            "id": "voucherGraphic_4",
                            "name": "voucherGraphic_4",
                            "type": "Graphic",
                            "uimode": "desktop",
                            "shape": "rectangle",
                            "color": "0x000000",
                            "alpha": 0.89,
                            "x": 95,
                            "y": 533,
                            "width": 90,
                            "height": 90,
                            "visible": false,
                            "scaleToFit": true,
                        },
                        {
                            "id": "voucherText5",
                            "name": "voucherText5",
                            "type": "Text",
                            "uimode": "desktop",
                            "x": 138,
                            "y": 578,
                            "width": 300,
                            "text": "0",
                            "scaleToFit": true,
                            "visible": false,
                            "anchor": [0.5, 0.5],
                            "textStyle": {
                                fontFamily: 'Arial',
                                fontSize: 40,
                                fontWeight: 'bold',
                                fill: ['#f8f8ff'],
                            },
                        },
                        {
                            "name": "RevealFeature",
                            "type": "Tag",
                            child: []
                        },
                        {
                            "name": "CoinSymbolAnimation",
                            "type": "Tag",
                            child: []
                        },
                        {
                            "name": "LeftRevealMeter",
                            "type": "Tag",
                            child: []
                        },
                        {
                            "name": "ConvertSymbolAnimation",
                            "type": "Tag",
                            "x": 0,
                            "y": -70,
                            child: []
                        },
                        {
                            "name": "collecter_bg_feature",
                            "image": "wins_digit_base",
                            "type": "Image",
                            "layout": true,
                            "uimode": "desktop",
                            "anchor": [0.5, 0.5],
                            "visible": false,
                            "alpha": 0.5,
                            "width": 1080,
                            "height": 263,
                            "x": 950,
                            "y": 520,
                        },
                        {
                            "name": "collecter_bg_feature",
                            "image": "wins_digit_base",
                            "type": "Image",
                            "layout": true,
                            "uimode": "mobile",
                            "anchor": [0.5, 0.5],
                            "visible": false,
                            "alpha": 0.5,
                            "width": 1080,
                            "height": 263,
                            "x": 540.5,
                            "y": 1098.5,
                        },
                        {
                            "id": "winCelebrationContainerTag",
                            "name": "WinCelebration",
                            "type": "Tag",
                            "class": "",
                            "parentLayer": "specialAnimationLayer",
                            "filterTypes": [],
                            child: []
                        },
                        {
                            "id": "winShowerContainerTag",
                            "name": "WinShower",
                            "type": "Tag",
                            "class": "",
                            "parentLayer": "specialAnimationLayer",
                            "filterTypes": [],
                            child: []
                        },
                        // {
                        //     "name": "CoinSymbolAnimation",
                        //     "type": "Tag",
                        //     child: []
                        // },

                        {
                            "name": "ui_base",
                            "image": "ui_base.png",
                            "type": objectTypes.Sprite,
                            "layout": false,
                            "uimode": "desktop",
                            "visible": true,
                            "width": 1920,
                            "height": 124,
                            "x": 0,
                            "y": 958,
                        },
                        {
                            "name": "ui_base_portrait",
                            "image": "ui_base_mobile_portrait.png",
                            "type": objectTypes.Sprite,
                            "layout": true,
                            "uimode": "mobile",
                            "visible": true,
                            "width": 1080,
                            "height": 164,
                            "x": 0,
                            "y": 1762,
                        },
                        {
                            "name": "ui_base_landscape",
                            "image": "ui_base_moblie_landscape.png",
                            "type": objectTypes.Sprite,
                            "layout": true,
                            "uimode": "mobile",
                            "visible": true,
                            "width": 1920,
                            "height": 136,
                            "x": 0,
                            "y": 795,
                        },
                        // Anticipation Animation ----------------------
                        {
                            "name": "anticipation_Scatter",
                            "type": "Spine",
                            "width": 3479,
                            "height": 789,
                            "animationSpeed": 0.2,
                            "playing": false,
                            "uimode": "desktop",
                            "loop": false,
                            "visible": false,
                            "spineAnimName": "animation",
                            "parentLayer": "specialAnimationLayer",
                            "anchor": [0.5, 0.5],
                            "x": 1322.5,
                            "y": 555,
                            "spinedata": {
                                "spinename": "anticipation_Scatter",
                                "animationname": "animation",
                                "loop": true,
                                "timeScale": 0.5
                            },
                        },
                        {
                            "name": "anticipation_Scatter",
                            "type": "Spine",
                            "width": 3479,
                            "height": 200,
                            "animationSpeed": 0.2,
                            "playing": false,
                            "uimode": "mobile",
                            "layout": true,
                            "loop": false,
                            "visible": false,
                            "spineAnimName": "animation",
                            "parentLayer": "specialAnimationLayer",
                            "anchor": [0.5, 0.5],
                            "x": 1400,
                            "y": 500,
                            "spinedata": {
                                "spinename": "anticipation_Scatter",
                                "animationname": "animation",
                                "loop": true,
                                "timeScale": 0.5
                            },
                        },
                        // 2nd ----
                        {
                            "name": "anticipation_Scatter2",
                            "type": "Spine",
                            "width": 3479,
                            "height": 789,
                            "animationSpeed": 0.2,
                            "playing": false,
                            "uimode": "desktop",
                            "loop": false,
                            "visible": false,
                            "spineAnimName": "animation",
                            "parentLayer": "specialAnimationLayer",
                            "anchor": [0.5, 0.5],
                            "x": 1431,
                            "y": 555,
                            "spinedata": {
                                "spinename": "anticipation_Scatter",
                                "animationname": "animation",
                                "loop": true,
                                "timeScale": 0.5
                            },
                        },
                        {
                            "name": "anticipation_Scatter2",
                            "type": "Spine",
                            "width": 3479,
                            "height": 789,
                            "animationSpeed": 0.2,
                            "playing": false,
                            "visible": false,
                            "loop": false,
                            "uimode": "mobile",
                            "layout": true,
                            "spineAnimName": "animation",
                            "parentLayer": "specialAnimationLayer",
                            "anchor": [0.5, 0.5],
                            "x": 1550,
                            "y": 500,
                            "spinedata": {
                                "spinename": "anticipation_Scatter",
                                "animationname": "animation",
                                "loop": true,
                                "timeScale": 0.5
                            },
                        },
                                                                           
                    ]
                }
            ]
        },
    ]
}
