import React from "react";
interface IframeworkLeftRevealMeterConfiguration {
    data: {
    }
}

export const frameworkLeftRevealMeterConfiguration: IframeworkLeftRevealMeterConfiguration = {

    data: {
        "COMPONENTS": [
            {
                "name": "leftMeterDesktop",
                "type": "Container",
                "x": 0,
                "y": 0,
                "layout": false,
                "uimode": "desktop",
                child: [
                    {
                        "name": "meterSymbol_09",
                        "image": "meterHv2",
                        "type": "Image",
                        "visible": true,
                        "width": 59,
                        "height": 59,
                        "x": 1280,
                        "y": 170,
                    },

                    {
                        "name": "meterSymbol_08",
                        "image": "meterHv3",
                        "type": "Image",
                        "visible": true,
                        "width": 59,
                        "height": 59,
                        "x": 1200,
                        "y": 170,
                    },

                    {
                        "name": "meterSymbol_07",
                        "image": "meterHv4",
                        "type": "Image",
                        "visible": true,
                        "width": 59,
                        "height": 59,
                        "x": 1120,
                        "y": 170,
                    },

                    {
                        "name": "meterSymbol_06",
                        "image": "meterHv5",
                        "type": "Image",
                        "visible": true,
                        "width": 59,
                        "height": 59,
                        "x": 1040,
                        "y": 170,
                    },

                    {
                        "name": "meterSymbol_05",
                        "image": "meterLv1",
                        "type": "Image",
                        "visible": true,
                        "width": 59,
                        "height": 59,
                        "x": 960,
                        "y": 170,
                    },

                    {
                        "name": "meterSymbol_04",
                        "image": "meterLv2",
                        "type": "Image",
                        "visible": true,
                        "width": 59,
                        "height": 59,
                        "x": 880,
                        "y": 170,
                    },


                    {
                        "name": "meterSymbol_03",
                        "image": "meterLv3",
                        "type": "Image",
                        "visible": true,
                        "width": 59,
                        "height": 59,
                        "x": 800,
                        "y": 170,
                    },

                    {
                        "name": "meterSymbol_02",
                        "image": "meterLv4",
                        "type": "Image",
                        "visible": true,
                        "width": 59,
                        "height": 59,
                        "x": 720,
                        "y": 170,
                    },
                    {
                        "name": "meterSymbol_01",
                        "image": "meterLv5",
                        "type": "Image",
                        "visible": true,
                        "width": 59,
                        "height": 59,
                        "x": 640,
                        "y": 170,
                    },

                    {
                        "name": "meterSymbol_00",
                        "image": "meterLv6",
                        "type": "Image",
                        "visible": true,
                        "width": 59,
                        "height": 59,
                        "x": 560,
                        "y": 170,
                    },
                    {
                        "name": "meterButterfly_00_0",
                        "image": "meterButterfly",
                        "type": "Image",
                        "visible": false,
                        "width": 97,
                        "height": 81,
                        "x": 541,
                        y: 156,
                    },
                    {
                        "name": "meterButterfly_00_1",
                        "image": "meterButterfly",
                        "type": "Image",
                        "visible": false,
                        "width": 97,
                        "height": 81,
                        "x": 625,
                        y: 156,
                    },
                    {
                        "name": "meterButterfly_00_2",
                        "image": "meterButterfly",
                        "type": "Image",
                        "visible": false,
                        "width": 97,
                        "height": 81,
                        "x": 701,
                        y: 156,
                    },
                    {
                        "name": "meterButterfly_00_3",
                        "image": "meterButterfly",
                        "type": "Image",
                        "visible": false,
                        "width": 97,
                        "height": 81,
                        "x": 782,
                        y: 156,
                    },
                    {
                        "name": "meterButterfly_00_4",
                        "image": "meterButterfly",
                        "type": "Image",
                        "visible": false,
                        "width": 97,
                        "height": 81,
                        x: 860,
                        y: 156,
                    },
                    {
                        "name": "meterButterfly_00_5",
                        "image": "meterButterfly",
                        "type": "Image",
                        "visible": false,
                        "width": 97,
                        "height": 81,
                        x: 939,
                        y: 156,
                    },
                    {
                        "name": "meterButterfly_00_6",
                        "image": "meterButterfly",
                        "type": "Image",
                        "visible": false,
                        "width": 97,
                        "height": 81,
                        x: 1020,
                        y: 156,
                    },
                    {
                        "name": "meterButterfly_00_7",
                        "image": "meterButterfly",
                        "type": "Image",
                        "visible": false,
                        "width": 97,
                        "height": 81,
                        x: 1098,
                        y: 156,
                    },
                    {
                        "name": "meterButterfly_00_8",
                        "image": "meterButterfly",
                        "type": "Image",
                        "visible": false,
                        "width": 97,
                        "height": 81,
                        x: 1182,
                        y: 156,
                    },
                    {
                        "name": "meterButterfly_00_9",
                        "image": "meterButterfly",
                        "type": "Image",
                        "visible": false,
                        "width": 97,
                        "height": 81,
                        x: 1262,
                        y: 156,
                    },
                    {
                        "name": "meterButterfly_00",
                        "type": "Spine",
                        "width": 118,
                        "height": 98,
                        "image": "leftMeterAnim",
                        "animationSpeed": 0.9,
                        "playing": true,
                        "loop": true,
                        "visible": false,
                        "spineAnimName": "win_panel_butterfly",
                        "anchor": [0.5, 0.5],
                        x: 900,
                        y: 500,
                        "spinedata": {
                            "spinename": "leftMeterAnim",
                            "animationname": "win_panel_butterfly",
                            "loop": true,
                            "timeScale": 0.9,
                        },
                    },
                    // {
                    //     "name": "meterButterfly_00",
                    //     "type": "Spine",
                    //     "width": 118,
                    //     "height": 98,
                    //     "image": "meterButterfly",
                    //     "animationSpeed": 2,
                    //     "playing": true,
                    //     "loop": true,
                    //     "visible": false,
                    //      "spineAnimName": "win_panel_butterfly",
                    // "anchor": [0.5, 0.5],
                    //     x: 900,
                    //     y: 500,
                    //     "spinedata": {
                    //         "spinename": "leftMeterAnim",
                    //         "animationname": "win_panel_butterfly",
                    //         "loop": false,
                    //         "timeScale": 0.9,
                    //     },
                    // },
                    {
                        "name": "meterButterfly_01",
                        "type": "Spine",
                        "width": 118,
                        "height": 98,
                        "image": "leftMeterAnim",
                        "animationSpeed": 0.9,
                        "playing": true,
                        "loop": true,
                        "visible": false,
                        "spineAnimName": "win_panel_butterfly",
                        "anchor": [0.5, 0.5],

                        x: 900,
                        y: 500,
                        "spinedata": {
                            "spinename": "leftMeterAnim",
                            "animationname": "win_panel_butterfly",
                            "loop": true,
                            "timeScale": 0.9,
                        },
                    },
                    {
                        "name": "meterButterfly_02",
                        "type": "Spine",
                        "width": 118,
                        "height": 98,
                        "image": "leftMeterAnim",
                        "animationSpeed": 0.9,
                        "playing": true,
                        "loop": true,
                        "visible": false,
                        "spineAnimName": "win_panel_butterfly",
                        "anchor": [0.5, 0.5],
                        x: 900,
                        y: 500,
                        "spinedata": {
                            "spinename": "leftMeterAnim",
                            "animationname": "win_panel_butterfly",
                            "loop": true,
                            "timeScale": 0.9,
                        },

                    },
                    {
                        "name": "meterButterfly_03",
                        "type": "Spine",
                        "width": 118,
                        "height": 98,
                        "image": "leftMeterAnim",
                        "animationSpeed": 0.9,
                        "playing": true,
                        "loop": true,
                        "visible": false,
                        "spineAnimName": "win_panel_butterfly",
                        "anchor": [0.5, 0.5],
                        x: 900,
                        y: 500,
                        "spinedata": {
                            "spinename": "leftMeterAnim",
                            "animationname": "win_panel_butterfly",
                            "loop": true,
                            "timeScale": 0.9,
                        },
                    },
                    {
                        "name": "meterButterfly_04",
                        "type": "Spine",
                        "width": 118,
                        "height": 98,
                        "image": "leftMeterAnim",
                        "animationSpeed": 0.9,
                        "playing": true,
                        "loop": true,
                        "visible": false,
                        "spineAnimName": "win_panel_butterfly",
                        "anchor": [0.5, 0.5],
                        x: 900,
                        y: 500,
                        "spinedata": {
                            "spinename": "leftMeterAnim",
                            "animationname": "win_panel_butterfly",
                            "loop": true,
                            "timeScale": 0.9,
                        },
                    },
                    {
                        "name": "meterButterfly_05",
                        "type": "Spine",
                        "width": 118,
                        "height": 98,
                        "image": "leftMeterAnim",
                        "animationSpeed": 0.9,
                        "playing": true,
                        "loop": true,
                        "visible": false,
                        "spineAnimName": "win_panel_butterfly",
                        "anchor": [0.5, 0.5],
                        x: 900,
                        y: 500,
                        "spinedata": {
                            "spinename": "leftMeterAnim",
                            "animationname": "win_panel_butterfly",
                            "loop": true,
                            "timeScale": 0.9,
                        },
                    },
                    {
                        "name": "meterButterfly_06",
                        "type": "Spine",
                        "width": 118,
                        "height": 98,
                        "image": "leftMeterAnim",
                        "animationSpeed": 0.9,
                        "playing": true,
                        "loop": true,
                        "visible": false,
                        "spineAnimName": "win_panel_butterfly",
                        "anchor": [0.5, 0.5],
                        x: 900,
                        y: 500,
                        "spinedata": {
                            "spinename": "leftMeterAnim",
                            "animationname": "win_panel_butterfly",
                            "loop": true,
                            "timeScale": 0.9,
                        },
                    },
                    {
                        "name": "meterButterfly_07",
                        "type": "Spine",
                        "width": 118,
                        "height": 98,
                        "image": "leftMeterAnim",
                        "animationSpeed": 0.9,
                        "playing": true,
                        "loop": true,
                        "visible": false,
                        "spineAnimName": "win_panel_butterfly",
                        "anchor": [0.5, 0.5],
                        x: 900,
                        y: 500,
                        "spinedata": {
                            "spinename": "leftMeterAnim",
                            "animationname": "win_panel_butterfly",
                            "loop": true,
                            "timeScale": 0.9,
                        },
                    },
                    {
                        "name": "meterButterfly_08",
                        "type": "Spine",
                        "width": 118,
                        "height": 98,
                        "image": "leftMeterAnim",
                        "animationSpeed": 0.9,
                        "playing": true,
                        "loop": true,
                        "visible": false,
                        "spineAnimName": "win_panel_butterfly",
                        "anchor": [0.5, 0.5],
                        x: 900,
                        y: 500,
                        "spinedata": {
                            "spinename": "leftMeterAnim",
                            "animationname": "win_panel_butterfly",
                            "loop": true,
                            "timeScale": 0.9,
                        },
                    },
                    {
                        "name": "meterButterfly_09",
                        "type": "Spine",
                        "width": 118,
                        "height": 98,
                        "image": "leftMeterAnim",
                        "animationSpeed": 0.9,
                        "playing": true,
                        "loop": true,
                        "visible": false,
                        "spineAnimName": "win_panel_butterfly",
                        "anchor": [0.5, 0.5],
                        x: 900,
                        y: 500,
                        "spinedata": {
                            "spinename": "leftMeterAnim",
                            "animationname": "win_panel_butterfly",
                            "loop": true,
                            "timeScale": 0.9,
                        },
                    },
                    {
                        "name": "animGlowMeter_09",
                        "type": "Spine",
                        "width": 2001,
                        "height": 523,
                        "image": "leftMeterAnim",
                        "animationSpeed": 0.9,
                        "playing": false,
                        "loop": false,
                        "visible": false,
                        "spineAnimName": "win_panel_butterfly_glow",
                        "anchor": [0.5, 0.5],
                        x: 1310,
                        y: 200,
                        "spinedata": {
                            "spinename": "leftMeterAnim",
                            "animationname": "win_panel_butterfly_glow",
                            "loop": false,
                            "timeScale": 0.5,
                        },
                    },
                    {
                        "name": "animMeterButterfly_09",
                        "type": "Spine",
                        "width": 2001,
                        "height": 523,
                        "image": "leftMeterAnim",
                        "animationSpeed": 0.9,
                        "playing": false,
                        "loop": false,
                        "visible": false,
                        "spineAnimName": "win_panel_butterfly",
                        "anchor": [0.5, 0.5],
                        x: 1310,
                        y: 200,
                        "spinedata": {
                            "spinename": "leftMeterAnim",
                            "animationname": "win_panel_butterfly",
                            "loop": false,
                            "timeScale": 0.9,
                        },
                    },
                    {
                        "name": "animGlowMeter_08",
                        "type": "Spine",
                        "width": 2001,
                        "height": 523,
                        "image": "leftMeterAnim",
                        "animationSpeed": 0.9,
                        "playing": false,
                        "loop": false,
                        "visible": false,
                        "spineAnimName": "win_panel_butterfly_glow",
                        "anchor": [0.5, 0.5],
                        x: 1230,
                        y: 200,
                        "spinedata": {
                            "spinename": "leftMeterAnim",
                            "animationname": "win_panel_butterfly_glow",
                            "loop": false,
                            "timeScale": 0.5,
                        },
                    },
                    {
                        "name": "animMeterButterfly_08",
                        "type": "Spine",
                        "width": 2001,
                        "height": 523,
                        "image": "leftMeterAnim",
                        "animationSpeed": 0.9,
                        "playing": false,
                        "loop": false,
                        "visible": false,
                        "spineAnimName": "win_panel_butterfly",
                        "anchor": [0.5, 0.5],
                        x: 1230,
                        y: 200,
                        "spinedata": {
                            "spinename": "leftMeterAnim",
                            "animationname": "win_panel_butterfly",
                            "loop": false,
                            "timeScale": 0.9,
                        },
                    },
                    {
                        "name": "animGlowMeter_07",
                        "type": "Spine",
                        "width": 2001,
                        "height": 523,
                        "image": "leftMeterAnim",
                        "animationSpeed": 0.9,
                        "playing": false,
                        "loop": false,
                        "visible": false,
                        "spineAnimName": "win_panel_butterfly_glow",
                        "anchor": [0.5, 0.5],
                        x: 1150,
                        y: 200,
                        "spinedata": {
                            "spinename": "leftMeterAnim",
                            "animationname": "win_panel_butterfly_glow",
                            "loop": false,
                            "timeScale": 0.5,
                        },
                    },
                    {
                        "name": "animMeterButterfly_07",
                        "type": "Spine",
                        "width": 2001,
                        "height": 523,
                        "image": "leftMeterAnim",
                        "animationSpeed": 0.9,
                        "playing": false,
                        "loop": false,
                        "visible": false,
                        "spineAnimName": "win_panel_butterfly",
                        "anchor": [0.5, 0.5],
                        x: 1150,
                        y: 200,
                        "spinedata": {
                            "spinename": "leftMeterAnim",
                            "animationname": "win_panel_butterfly",
                            "loop": false,
                            "timeScale": 0.9,
                        },
                    },
                    {
                        "name": "animGlowMeter_06",
                        "type": "Spine",
                        "width": 2001,
                        "height": 523,
                        "image": "leftMeterAnim",
                        "animationSpeed": 0.9,
                        "playing": false,
                        "loop": false,
                        "visible": false,
                        "spineAnimName": "win_panel_butterfly_glow",
                        "anchor": [0.5, 0.5],
                        x: 1070,
                        y: 200,
                        "spinedata": {
                            "spinename": "leftMeterAnim",
                            "animationname": "win_panel_butterfly_glow",
                            "loop": false,
                            "timeScale": 0.5,
                        },
                    },
                    {
                        "name": "animMeterButterfly_06",
                        "type": "Spine",
                        "width": 2001,
                        "height": 523,
                        "image": "leftMeterAnim",
                        "animationSpeed": 0.9,
                        "playing": false,
                        "loop": false,
                        "visible": false,
                        "spineAnimName": "win_panel_butterfly",
                        "anchor": [0.5, 0.5],
                        x: 1070,
                        y: 200,
                        "spinedata": {
                            "spinename": "leftMeterAnim",
                            "animationname": "win_panel_butterfly",
                            "loop": false,
                            "timeScale": 0.9,
                        },
                    },
                    {
                        "name": "animGlowMeter_05",
                        "type": "Spine",
                        "width": 2001,
                        "height": 523,
                        "image": "leftMeterAnim",
                        "animationSpeed": 0.9,
                        "playing": false,
                        "loop": false,
                        "visible": false,
                        "spineAnimName": "win_panel_butterfly_glow",
                        "anchor": [0.5, 0.5],
                        x: 990,
                        y: 200,
                        "spinedata": {
                            "spinename": "leftMeterAnim",
                            "animationname": "win_panel_butterfly_glow",
                            "loop": false,
                            "timeScale": 0.5,
                        },
                    },
                    {
                        "name": "animMeterButterfly_05",
                        "type": "Spine",
                        "width": 2001,
                        "height": 523,
                        "image": "leftMeterAnim",
                        "animationSpeed": 0.9,
                        "playing": false,
                        "loop": false,
                        "visible": false,
                        "spineAnimName": "win_panel_butterfly",
                        "anchor": [0.5, 0.5],
                        x: 990,
                        y: 200,
                        "spinedata": {
                            "spinename": "leftMeterAnim",
                            "animationname": "win_panel_butterfly",
                            "loop": false,
                            "timeScale": 0.9,
                        },
                    },
                    {
                        "name": "animGlowMeter_04",
                        "type": "Spine",
                        "width": 2001,
                        "height": 523,
                        "image": "leftMeterAnim",
                        "animationSpeed": 0.9,
                        "playing": false,
                        "loop": false,
                        "visible": false,
                        "spineAnimName": "win_panel_butterfly_glow",
                        "anchor": [0.5, 0.5],
                        x: 910,
                        y: 200,
                        "spinedata": {
                            "spinename": "leftMeterAnim",
                            "animationname": "win_panel_butterfly_glow",
                            "loop": false,
                            "timeScale": 0.5,
                        },
                    },
                    {
                        "name": "animMeterButterfly_04",
                        "type": "Spine",
                        "width": 2001,
                        "height": 523,
                        "image": "leftMeterAnim",
                        "animationSpeed": 0.9,
                        "playing": false,
                        "loop": false,
                        "visible": false,
                        "spineAnimName": "win_panel_butterfly",
                        "anchor": [0.5, 0.5],
                        x: 910,
                        y: 200,
                        "spinedata": {
                            "spinename": "leftMeterAnim",
                            "animationname": "win_panel_butterfly",
                            "loop": false,
                            "timeScale": 0.9,
                        },
                    },

                    {
                        "name": "animGlowMeter_03",
                        "type": "Spine",
                        "width": 2001,
                        "height": 523,
                        "image": "leftMeterAnim",
                        "animationSpeed": 0.9,
                        "playing": false,
                        "loop": false,
                        "visible": false,
                        "spineAnimName": "win_panel_butterfly_glow",
                        "anchor": [0.5, 0.5],
                        x: 830,
                        y: 200,
                        "spinedata": {
                            "spinename": "leftMeterAnim",
                            "animationname": "win_panel_butterfly_glow",
                            "loop": false,
                            "timeScale": 0.5,
                        },
                    },
                    {
                        "name": "animMeterButterfly_03",
                        "type": "Spine",
                        "width": 2001,
                        "height": 523,
                        "image": "leftMeterAnim",
                        "animationSpeed": 0.9,
                        "playing": false,
                        "loop": false,
                        "visible": false,
                        "spineAnimName": "win_panel_butterfly",
                        "anchor": [0.5, 0.5],
                        x: 830,
                        y: 200,
                        "spinedata": {
                            "spinename": "leftMeterAnim",
                            "animationname": "win_panel_butterfly",
                            "loop": false,
                            "timeScale": 0.9,
                        },
                    },
                    {
                        "name": "animGlowMeter_02",
                        "type": "Spine",
                        "width": 2001,
                        "height": 523,
                        "image": "leftMeterAnim",
                        "animationSpeed": 0.9,
                        "playing": false,
                        "loop": false,
                        "visible": false,
                        "spineAnimName": "win_panel_butterfly_glow",
                        "anchor": [0.5, 0.5],
                        x: 750,
                        y: 200,
                        "spinedata": {
                            "spinename": "leftMeterAnim",
                            "animationname": "win_panel_butterfly_glow",
                            "loop": false,
                            "timeScale": 0.5,
                        },
                    },
                    {
                        "name": "animMeterButterfly_02",
                        "type": "Spine",
                        "width": 2001,
                        "height": 523,
                        "image": "leftMeterAnim",
                        "animationSpeed": 0.9,
                        "playing": false,
                        "loop": false,
                        "visible": false,
                        "spineAnimName": "win_panel_butterfly",
                        "anchor": [0.5, 0.5],
                        x: 750,
                        y: 200,
                        "spinedata": {
                            "spinename": "leftMeterAnim",
                            "animationname": "win_panel_butterfly",
                            "loop": false,
                            "timeScale": 0.9,
                        },
                    },
                    {
                        "name": "animGlowMeter_01",
                        "type": "Spine",
                        "width": 2001,
                        "height": 523,
                        "image": "leftMeterAnim",
                        "animationSpeed": 0.9,
                        "playing": false,
                        "loop": false,
                        "visible": false,
                        "spineAnimName": "win_panel_butterfly_glow",
                        "anchor": [0.5, 0.5],
                        x: 670,
                        y: 200,
                        "spinedata": {
                            "spinename": "leftMeterAnim",
                            "animationname": "win_panel_butterfly_glow",
                            "loop": false,
                            "timeScale": 0.5,
                        },
                    },
                    {
                        "name": "animMeterButterfly_01",
                        "type": "Spine",
                        "width": 2001,
                        "height": 523,
                        "image": "leftMeterAnim",
                        "animationSpeed": 0.9,
                        "playing": false,
                        "loop": false,
                        "visible": false,
                        "spineAnimName": "win_panel_butterfly",
                        "anchor": [0.5, 0.5],
                        x: 670,
                        y: 200,
                        "spinedata": {
                            "spinename": "leftMeterAnim",
                            "animationname": "win_panel_butterfly",
                            "loop": false,
                            "timeScale": 0.9,
                        },
                    },

                    {
                        "name": "animGlowMeter_00",
                        "type": "Spine",
                        "width": 2001,
                        "height": 523,
                        "image": "leftMeterAnim",
                        "animationSpeed": 0.9,
                        "playing": false,
                        "loop": false,
                        "visible": false,
                        "spineAnimName": "win_panel_butterfly_glow",
                        "anchor": [0.5, 0.5],
                        x: 590,
                        y: 200,
                        "spinedata": {
                            "spinename": "leftMeterAnim",
                            "animationname": "win_panel_butterfly_glow",
                            "loop": false,
                            "timeScale": 0.5,
                        },
                    },
                    {
                        "name": "animMeterButterfly_00",
                        "type": "Spine",
                        "width": 2001,
                        "height": 523,
                        "image": "leftMeterAnim",
                        "animationSpeed": 0.9,
                        "playing": false,
                        "loop": false,
                        "visible": false,
                        "spineAnimName": "win_panel_butterfly",
                        "anchor": [0.5, 0.5],
                        x: 590,
                        y: 200,
                        "spinedata": {
                            "spinename": "leftMeterAnim",
                            "animationname": "win_panel_butterfly",
                            "loop": false,
                            "timeScale": 0.9,
                        },
                    },
                ]
            },
            //ANCHOR - Mobile Container
            {
                "name": "leftMeterDesktop",
                "type": "Container",
                "x": 0,
                "y": 0,
                "layout": true,
                "uimode": "mobile",
                child: [
                    {
                        "name": "meterSymbol_09",
                        "image": "meterHv2",
                        "type": "Image",
                        "visible": true,
                        "layout": true,
                        "width": 59,
                        "height": 59,
                        "x": 0,
                        "y": 0,
                    },

                    {
                        "name": "meterSymbol_08",
                        "image": "meterHv3",
                        "type": "Image",
                        "layout": true,
                        "visible": true,
                        "width": 59,
                        "height": 59,
                        "x": 0,
                        "y": 0,
                    },

                    {
                        "name": "meterSymbol_07",
                        "image": "meterHv4",
                        "type": "Image",
                        "layout": true,
                        "visible": true,
                        "width": 59,
                        "height": 59,
                        "x": 0,
                        "y": 0,
                    },

                    {
                        "name": "meterSymbol_06",
                        "image": "meterHv5",
                        "type": "Image",
                        "layout": true,
                        "visible": true,
                        "width": 59,
                        "height": 59,
                        "x": 0,
                        "y": 0,
                    },

                    {
                        "name": "meterSymbol_05",
                        "image": "meterLv1",
                        "type": "Image",
                        "layout": true,
                        "visible": true,
                        "width": 59,
                        "height": 59,
                        "x": 0,
                        "y": 0,
                    },

                    {
                        "name": "meterSymbol_04",
                        "image": "meterLv2",
                        "type": "Image",
                        "layout": true,
                        "visible": true,
                        "width": 59,
                        "height": 59,
                        "x": 0,
                        "y": 0,
                    },


                    {
                        "name": "meterSymbol_03",
                        "image": "meterLv3",
                        "type": "Image",
                        "layout": true,
                        "visible": true,
                        "width": 59,
                        "height": 59,
                        "x": 0,
                        "y": 0,
                    },

                    {
                        "name": "meterSymbol_02",
                        "image": "meterLv4",
                        "type": "Image",
                        "layout": true,
                        "visible": true,
                        "width": 59,
                        "height": 59,
                        "x": 0,
                        "y": 0,
                    },
                    {
                        "name": "meterSymbol_01",
                        "image": "meterLv5",
                        "type": "Image",
                        "layout": true,
                        "visible": true,
                        "width": 59,
                        "height": 59,
                        "x": 0,
                        "y": 0,
                    },

                    {
                        "name": "meterSymbol_00",
                        "image": "meterLv6",
                        "type": "Image",
                        "layout": true,
                        "visible": true,
                        "width": 59,
                        "height": 59,
                        "x": 0,
                        "y": 0,
                    },
                    //ANCHOR - butterfly symbol Mobile -------------------
                    {
                        "name": "meterButterfly_00_0",
                        "image": "meterButterfly",
                        "type": "Image",
                        "visible": false,
                        "layout": true,
                        "width": 97,
                        "height": 81,
                        x: 35,
                        y: 665,
                    },
                    {
                        "name": "meterButterfly_00_1",
                        "image": "meterButterfly",
                        "type": "Image",
                        "visible": false,
                        "layout": true,
                        "width": 97,
                        "height": 81,
                        x: 135,
                        y: 665,
                    },
                    {
                        "name": "meterButterfly_00_2",
                        "image": "meterButterfly",
                        "type": "Image",
                        "visible": false,
                        "layout": true,
                        "width": 97,
                        "height": 81,
                        x: 235,
                        y: 665,
                    },
                    {
                        "name": "meterButterfly_00_3",
                        "image": "meterButterfly",
                        "type": "Image",
                        "visible": false,
                        "layout": true,
                        "width": 97,
                        "height": 81,
                        x: 335,
                        y: 665,
                    },
                    {
                        "name": "meterButterfly_00_4",
                        "image": "meterButterfly",
                        "type": "Image",
                        "visible": false,
                        "layout": true,
                        "width": 97,
                        "height": 81,
                        x: 435,
                        y: 665,
                    },
                    {
                        "name": "meterButterfly_00_5",
                        "image": "meterButterfly",
                        "type": "Image",
                        "visible": false,
                        "layout": true,
                        "width": 97,
                        "height": 81,
                        x: 535,
                        y: 665,
                    },
                    {
                        "name": "meterButterfly_00_6",
                        "image": "meterButterfly",
                        "type": "Image",
                        "visible": false,
                        "layout": true,
                        "width": 97,
                        "height": 81,
                        x: 635,
                        y: 665,
                    },
                    {
                        "name": "meterButterfly_00_7",
                        "image": "meterButterfly",
                        "type": "Image",
                        "visible": false,
                        "layout": true,
                        "width": 97,
                        "height": 81,
                        x: 735,
                        y: 665,
                    },
                    {
                        "name": "meterButterfly_00_8",
                        "image": "meterButterfly",
                        "type": "Image",
                        "visible": false,
                        "layout": true,
                        "width": 97,
                        "height": 81,
                        x: 595,
                        y: 665,
                    },
                    {
                        "name": "meterButterfly_00_9",
                        "image": "meterButterfly",
                        "type": "Image",
                        "visible": false,
                        "layout": true,
                        "width": 97,
                        "height": 81,
                        x: 935,
                        y: 665,
                    },
                    //SECTION - meterButterfly_00 -> meterButterfly_09
                    {
                        "name": "meterButterfly_00",
                        "type": "Spine",
                        "width": 118,
                        "height": 98,
                        "image": "leftMeterAnim",
                        "animationSpeed": 0.9,
                        "playing": true,
                        "loop": true,
                        "visible": false,
                        "spineAnimName": "win_panel_butterfly",
                        "anchor": [0.5, 0.5],
                        x: 540.5,
                        y: 1102,
                        "spinedata": {
                            "spinename": "leftMeterAnim",
                            "animationname": "win_panel_butterfly",
                            "loop": true,
                            "timeScale": 0.9,
                        },
                    },

                    {
                        "name": "meterButterfly_01",
                        "type": "Spine",
                        "width": 118,
                        "height": 98,
                        "image": "leftMeterAnim",
                        "animationSpeed": 0.9,
                        "playing": true,
                        "loop": true,
                        "visible": false,
                        "spineAnimName": "win_panel_butterfly",
                        "anchor": [0.5, 0.5],
                        x: 540.5,
                        y: 1102,
                        "spinedata": {
                            "spinename": "leftMeterAnim",
                            "animationname": "win_panel_butterfly",
                            "loop": true,
                            "timeScale": 0.9,
                        },
                    },
                    {
                        "name": "meterButterfly_02",
                        "type": "Spine",
                        "width": 118,
                        "height": 98,
                        "image": "leftMeterAnim",
                        "animationSpeed": 0.9,
                        "playing": true,
                        "loop": true,
                        "visible": false,
                        "spineAnimName": "win_panel_butterfly",
                        "anchor": [0.5, 0.5],
                        x: 540.5,
                        y: 1102,
                        "spinedata": {
                            "spinename": "leftMeterAnim",
                            "animationname": "win_panel_butterfly",
                            "loop": true,
                            "timeScale": 0.9,
                        },

                    },
                    {
                        "name": "meterButterfly_03",
                        "type": "Spine",
                        "width": 118,
                        "height": 98,
                        "image": "leftMeterAnim",
                        "animationSpeed": 0.9,
                        "playing": true,
                        "loop": true,
                        "visible": false,
                        "spineAnimName": "win_panel_butterfly",
                        "anchor": [0.5, 0.5],
                        x: 540.5,
                        y: 1102,
                        "spinedata": {
                            "spinename": "leftMeterAnim",
                            "animationname": "win_panel_butterfly",
                            "loop": true,
                            "timeScale": 0.9,
                        },
                    },
                    {
                        "name": "meterButterfly_04",
                        "type": "Spine",
                        "width": 118,
                        "height": 98,
                        "image": "leftMeterAnim",
                        "animationSpeed": 0.9,
                        "playing": true,
                        "loop": true,
                        "visible": false,
                        "spineAnimName": "win_panel_butterfly",
                        "anchor": [0.5, 0.5],
                        x: 540.5,
                        y: 1102,
                        "spinedata": {
                            "spinename": "leftMeterAnim",
                            "animationname": "win_panel_butterfly",
                            "loop": true,
                            "timeScale": 0.9,
                        },
                    },
                    {
                        "name": "meterButterfly_05",
                        "type": "Spine",
                        "width": 118,
                        "height": 98,
                        "image": "leftMeterAnim",
                        "animationSpeed": 0.9,
                        "playing": true,
                        "loop": true,
                        "visible": false,
                        "spineAnimName": "win_panel_butterfly",
                        "anchor": [0.5, 0.5],
                        x: 540.5,
                        y: 1102,
                        "spinedata": {
                            "spinename": "leftMeterAnim",
                            "animationname": "win_panel_butterfly",
                            "loop": true,
                            "timeScale": 0.9,
                        },
                    },
                    {
                        "name": "meterButterfly_06",
                        "type": "Spine",
                        "width": 118,
                        "height": 98,
                        "image": "leftMeterAnim",
                        "animationSpeed": 0.9,
                        "playing": true,
                        "loop": true,
                        "visible": false,
                        "spineAnimName": "win_panel_butterfly",
                        "anchor": [0.5, 0.5],
                        x: 540.5,
                        y: 1102,
                        "spinedata": {
                            "spinename": "leftMeterAnim",
                            "animationname": "win_panel_butterfly",
                            "loop": true,
                            "timeScale": 0.9,
                        },
                    },
                    {
                        "name": "meterButterfly_07",
                        "type": "Spine",
                        "width": 118,
                        "height": 98,
                        "image": "leftMeterAnim",
                        "animationSpeed": 0.9,
                        "playing": true,
                        "loop": true,
                        "visible": false,
                        "spineAnimName": "win_panel_butterfly",
                        "anchor": [0.5, 0.5],
                        x: 540.5,
                        y: 1102,
                        "spinedata": {
                            "spinename": "leftMeterAnim",
                            "animationname": "win_panel_butterfly",
                            "loop": true,
                            "timeScale": 0.9,
                        },
                    },
                    {
                        "name": "meterButterfly_08",
                        "type": "Spine",
                        "width": 118,
                        "height": 98,
                        "image": "leftMeterAnim",
                        "animationSpeed": 0.9,
                        "playing": true,
                        "loop": true,
                        "visible": false,
                        "spineAnimName": "win_panel_butterfly",
                        "anchor": [0.5, 0.5],
                        x: 540.5,
                        y: 1102,
                        "spinedata": {
                            "spinename": "leftMeterAnim",
                            "animationname": "win_panel_butterfly",
                            "loop": true,
                            "timeScale": 0.9,
                        },
                    },
                    {
                        "name": "meterButterfly_09",
                        "type": "Spine",
                        "width": 118,
                        "height": 98,
                        "image": "leftMeterAnim",
                        "animationSpeed": 0.9,
                        "playing": true,
                        "loop": true,
                        "visible": false,
                        "spineAnimName": "win_panel_butterfly",
                        "anchor": [0.5, 0.5],
                        x: 540.5,
                        y: 1102,
                        "spinedata": {
                            "spinename": "leftMeterAnim",
                            "animationname": "win_panel_butterfly",
                            "loop": true,
                            "timeScale": 0.9,
                        },
                    },
                    //SECTION - animGlowMeter_09 -> animGlowMeter_00
                    {
                        "name": "animGlowMeter_09",
                        "type": "Spine",
                        "width": 2001,
                        "height": 523,
                        "image": "leftMeterAnim",
                        "animationSpeed": 0.9,
                        "playing": false,
                        "loop": false,
                        "visible": false,
                        "layout": true,
                        "spineAnimName": "win_panel_butterfly_glow",
                        "anchor": [0.5, 0.5],
                        x: 998,
                        y: 710,
                        "spinedata": {
                            "spinename": "leftMeterAnim",
                            "animationname": "win_panel_butterfly_glow",
                            "loop": false,
                            "timeScale": 0.5,
                        },
                    },
                    {
                        "name": "animMeterButterfly_09",
                        "type": "Spine",
                        "width": 2001,
                        "height": 523,
                        "image": "leftMeterAnim",
                        "animationSpeed": 0.9,
                        "playing": false,
                        "loop": false,
                        "visible": false,
                        "layout": true,
                        "spineAnimName": "win_panel_butterfly",
                        "anchor": [0.5, 0.5],
                        x: 998,
                        y: 710,
                        "spinedata": {
                            "spinename": "leftMeterAnim",
                            "animationname": "win_panel_butterfly",
                            "loop": false,
                            "timeScale": 0.9,
                        },
                    },
                    {
                        "name": "animGlowMeter_08",
                        "type": "Spine",
                        "width": 2001,
                        "height": 523,
                        "image": "leftMeterAnim",
                        "animationSpeed": 0.9,
                        "playing": false,
                        "loop": false,
                        "visible": false,
                        "layout": true,
                        "spineAnimName": "win_panel_butterfly_glow",
                        "anchor": [0.5, 0.5],
                        x: 898,
                        y: 710,
                        "spinedata": {
                            "spinename": "leftMeterAnim",
                            "animationname": "win_panel_butterfly_glow",
                            "loop": false,
                            "timeScale": 0.5,
                        },
                    },
                    {
                        "name": "animMeterButterfly_08",
                        "type": "Spine",
                        "width": 2001,
                        "height": 523,
                        "image": "leftMeterAnim",
                        "animationSpeed": 0.9,
                        "playing": false,
                        "loop": false,
                        "visible": false,
                        "layout": true,
                        "spineAnimName": "win_panel_butterfly",
                        "anchor": [0.5, 0.5],
                        x: 898,
                        y: 710,
                        "spinedata": {
                            "spinename": "leftMeterAnim",
                            "animationname": "win_panel_butterfly",
                            "loop": false,
                            "timeScale": 0.9,
                        },
                    },
                    {
                        "name": "animGlowMeter_07",
                        "type": "Spine",
                        "width": 2001,
                        "height": 523,
                        "image": "leftMeterAnim",
                        "animationSpeed": 0.9,
                        "playing": false,
                        "loop": false,
                        "visible": false,
                        "layout": true,
                        "spineAnimName": "win_panel_butterfly_glow",
                        "anchor": [0.5, 0.5],
                        x: 798,
                        y: 710,
                        "spinedata": {
                            "spinename": "leftMeterAnim",
                            "animationname": "win_panel_butterfly_glow",
                            "loop": false,
                            "timeScale": 0.5,
                        },
                    },
                    {
                        "name": "animMeterButterfly_07",
                        "type": "Spine",
                        "width": 2001,
                        "height": 523,
                        "image": "leftMeterAnim",
                        "animationSpeed": 0.9,
                        "playing": false,
                        "loop": false,
                        "visible": false,
                        "layout": true,
                        "spineAnimName": "win_panel_butterfly",
                        "anchor": [0.5, 0.5],
                        x: 798,
                        y: 710,
                        "spinedata": {
                            "spinename": "leftMeterAnim",
                            "animationname": "win_panel_butterfly",
                            "loop": false,
                            "timeScale": 0.9,
                        },
                    },
                    {
                        "name": "animGlowMeter_06",
                        "type": "Spine",
                        "width": 2001,
                        "height": 523,
                        "image": "leftMeterAnim",
                        "animationSpeed": 0.9,
                        "playing": false,
                        "loop": false,
                        "visible": false,
                        "layout": true,
                        "spineAnimName": "win_panel_butterfly_glow",
                        "anchor": [0.5, 0.5],
                        x: 698,
                        y: 710,
                        "spinedata": {
                            "spinename": "leftMeterAnim",
                            "animationname": "win_panel_butterfly_glow",
                            "loop": false,
                            "timeScale": 0.5,
                        },
                    },
                    {
                        "name": "animMeterButterfly_06",
                        "type": "Spine",
                        "width": 2001,
                        "height": 523,
                        "image": "leftMeterAnim",
                        "animationSpeed": 0.9,
                        "playing": false,
                        "loop": false,
                        "visible": false,
                        "layout": true,
                        "spineAnimName": "win_panel_butterfly",
                        "anchor": [0.5, 0.5],
                        x: 698,
                        y: 710,
                        "spinedata": {
                            "spinename": "leftMeterAnim",
                            "animationname": "win_panel_butterfly",
                            "loop": false,
                            "timeScale": 0.9,
                        },
                    },
                    {
                        "name": "animGlowMeter_05",
                        "type": "Spine",
                        "width": 2001,
                        "height": 523,
                        "image": "leftMeterAnim",
                        "animationSpeed": 0.9,
                        "playing": false,
                        "loop": false,
                        "visible": false,
                        "layout": true,
                        "spineAnimName": "win_panel_butterfly_glow",
                        "anchor": [0.5, 0.5],
                        x: 598,
                        y: 710,
                        "spinedata": {
                            "spinename": "leftMeterAnim",
                            "animationname": "win_panel_butterfly_glow",
                            "loop": false,
                            "timeScale": 0.5,
                        },
                    },
                    {
                        "name": "animMeterButterfly_05",
                        "type": "Spine",
                        "width": 2001,
                        "height": 523,
                        "image": "leftMeterAnim",
                        "animationSpeed": 0.9,
                        "playing": false,
                        "loop": false,
                        "visible": false,
                        "layout": true,
                        "spineAnimName": "win_panel_butterfly",
                        "anchor": [0.5, 0.5],
                        x: 598,
                        y: 710,
                        "spinedata": {
                            "spinename": "leftMeterAnim",
                            "animationname": "win_panel_butterfly",
                            "loop": false,
                            "timeScale": 0.9,
                        },
                    },
                    {
                        "name": "animGlowMeter_04",
                        "type": "Spine",
                        "width": 2001,
                        "height": 523,
                        "image": "leftMeterAnim",
                        "animationSpeed": 0.9,
                        "playing": false,
                        "loop": false,
                        "visible": false,
                        "layout": true,
                        "spineAnimName": "win_panel_butterfly_glow",
                        "anchor": [0.5, 0.5],
                        x: 498,
                        y: 710,
                        "spinedata": {
                            "spinename": "leftMeterAnim",
                            "animationname": "win_panel_butterfly_glow",
                            "loop": false,
                            "timeScale": 0.5,
                        },
                    },
                    {
                        "name": "animMeterButterfly_04",
                        "type": "Spine",
                        "width": 2001,
                        "height": 523,
                        "image": "leftMeterAnim",
                        "animationSpeed": 0.9,
                        "playing": false,
                        "loop": false,
                        "visible": false,
                        "layout": true,
                        "spineAnimName": "win_panel_butterfly",
                        "anchor": [0.5, 0.5],
                        x: 498,
                        y: 710,
                        "spinedata": {
                            "spinename": "leftMeterAnim",
                            "animationname": "win_panel_butterfly",
                            "loop": false,
                            "timeScale": 0.9,
                        },
                    },
                    {
                        "name": "animGlowMeter_03",
                        "type": "Spine",
                        "width": 2001,
                        "height": 523,
                        "image": "leftMeterAnim",
                        "animationSpeed": 0.9,
                        "playing": false,
                        "loop": false,
                        "visible": false,
                        "layout": true,
                        "spineAnimName": "win_panel_butterfly_glow",
                        "anchor": [0.5, 0.5],
                        x: 398,
                        y: 710,
                        "spinedata": {
                            "spinename": "leftMeterAnim",
                            "animationname": "win_panel_butterfly_glow",
                            "loop": false,
                            "timeScale": 0.5,
                        },
                    },
                    {
                        "name": "animMeterButterfly_03",
                        "type": "Spine",
                        "width": 2001,
                        "height": 523,
                        "image": "leftMeterAnim",
                        "animationSpeed": 0.9,
                        "playing": false,
                        "loop": false,
                        "visible": false,
                        "layout": true,
                        "spineAnimName": "win_panel_butterfly",
                        "anchor": [0.5, 0.5],
                        x: 398,
                        y: 710,
                        "spinedata": {
                            "spinename": "leftMeterAnim",
                            "animationname": "win_panel_butterfly",
                            "loop": false,
                            "timeScale": 0.9,
                        },
                    },
                    {
                        "name": "animGlowMeter_02",
                        "type": "Spine",
                        "width": 2001,
                        "height": 523,
                        "image": "leftMeterAnim",
                        "animationSpeed": 0.9,
                        "playing": false,
                        "loop": false,
                        "visible": false,
                        "layout": true,
                        "spineAnimName": "win_panel_butterfly_glow",
                        "anchor": [0.5, 0.5],
                        x: 298,
                        y: 710,
                        "spinedata": {
                            "spinename": "leftMeterAnim",
                            "animationname": "win_panel_butterfly_glow",
                            "loop": false,
                            "timeScale": 0.5,
                        },
                    },
                    {
                        "name": "animMeterButterfly_02",
                        "type": "Spine",
                        "width": 2001,
                        "height": 523,
                        "image": "leftMeterAnim",
                        "animationSpeed": 0.9,
                        "playing": false,
                        "loop": false,
                        "visible": false,
                        "layout": true,
                        "spineAnimName": "win_panel_butterfly",
                        "anchor": [0.5, 0.5],
                        x: 298,
                        y: 710,
                        "spinedata": {
                            "spinename": "leftMeterAnim",
                            "animationname": "win_panel_butterfly",
                            "loop": false,
                            "timeScale": 0.9,
                        },
                    },
                    {
                        "name": "animGlowMeter_01",
                        "type": "Spine",
                        "width": 2001,
                        "height": 523,
                        "image": "leftMeterAnim",
                        "animationSpeed": 0.9,
                        "playing": false,
                        "loop": false,
                        "visible": false,
                        "layout": true,
                        "spineAnimName": "win_panel_butterfly_glow",
                        "anchor": [0.5, 0.5],
                        x: 198,
                        y: 710,
                        "spinedata": {
                            "spinename": "leftMeterAnim",
                            "animationname": "win_panel_butterfly_glow",
                            "loop": false,
                            "timeScale": 0.5,
                        },
                    },
                    {
                        "name": "animMeterButterfly_01",
                        "type": "Spine",
                        "width": 2001,
                        "height": 523,
                        "image": "leftMeterAnim",
                        "animationSpeed": 0.9,
                        "playing": false,
                        "loop": false,
                        "visible": false,
                        "layout": true,
                        "spineAnimName": "win_panel_butterfly",
                        "anchor": [0.5, 0.5],
                        x: 198,
                        y: 710,
                        "spinedata": {
                            "spinename": "leftMeterAnim",
                            "animationname": "win_panel_butterfly",
                            "loop": false,
                            "timeScale": 0.9,
                        },
                    },
                    {
                        "name": "animGlowMeter_00",
                        "type": "Spine",
                        "width": 2001,
                        "height": 523,
                        "image": "leftMeterAnim",
                        "animationSpeed": 0.9,
                        "playing": false,
                        "loop": false,
                        "visible": false,
                        "layout": true,
                        "spineAnimName": "win_panel_butterfly_glow",
                        "anchor": [0.5, 0.5],
                        x: 98,
                        y: 710,
                        "spinedata": {
                            "spinename": "leftMeterAnim",
                            "animationname": "win_panel_butterfly_glow",
                            "loop": false,
                            "timeScale": 0.5,
                        },
                    },
                    {
                        "name": "animMeterButterfly_00",
                        "type": "Spine",
                        "width": 2001,
                        "height": 523,
                        "image": "leftMeterAnim",
                        "animationSpeed": 0.9,
                        "playing": false,
                        "loop": false,
                        "visible": false,
                        "layout": true,
                        "spineAnimName": "win_panel_butterfly",
                        "anchor": [0.5, 0.5],
                        x: 98,
                        y: 710,
                        "spinedata": {
                            "spinename": "leftMeterAnim",
                            "animationname": "win_panel_butterfly",
                            "loop": false,
                            "timeScale": 0.9,
                        },
                    },
                ]
            }
        ],
    }

};

export const LeftRevealMeterContext = React.createContext(
    {}
);
