
import { frameworkButtonPanel, objectTypes } from "@bonanzainteractive/slote_core";

frameworkButtonPanel.data = {
    "alwaysEnableButtonNameList": [],
    "COREBUTTONPANEL": [],
    "COMPONENTS": [

        {
            "id": "GenericUIContainer",
            "name": "GenericUIContainer",
            "type": "Container",
            "class": "",
            "x": 0,
            "y": 0,
            "filterTypes": [],
            child: [
                {
                    "id": "GenericUIComponent",
                    "name": "ButtonPanelGenericUI",
                    "type": "Tag",
                    "class": "",
                    "filterTypes": [],
                    "alwaysEnableButtonNameList": ["btn_help", "btn_spinStop"],
                    child: [
                        {
                            "id": "stageClickContainer",
                            "name": "stageClickContainer",
                            "type": "Container",
                            "x": 0,
                            "y": 0,
                            "visible": true,
                            "filterTypes": [],
                            child: [
                                {
                                    "name": "winCelebration_Graphic",
                                    "type": "Graphic",
                                    "shape": "rectangle",
                                    "visible": true,
                                    "alpha": 0.001,
                                    "color": "0x000000",
                                    "x": 0,
                                    "y": 0,
                                    "width": 1920,
                                    "height": 1080,

                                },
                            ]
                        },

                        // -----------------------------------------------------------------------------





                        //MOBILE VIEW BUTTONS----------------------------------------


                    ]
                },

                {
                    "id": "GenericUIComponentdecreaseButtonUI",
                    "name": "decreaseButtonUI",
                    "type": "Tag",
                    "class": "",
                    "layout": true,
                    "filterTypes": [],
                    child: [
                        {
                            "id": "Button_4",
                            "name": "btn_bet_decrease",
                            "type": objectTypes.Sprite,
                            "buttonMode": true,
                            "uimode": "desktop",
                            "interactive": true,
                            "layout": false,
                            "x": 1354,
                            "y": 980,
                            "height": 30,
                            "width": 30,
                            "text": "",
                            "visible": true,
                            "buttonState": {
                                up: 'bet_minus_standard.png',
                                out: 'bet_minus_standard.png',
                                down: 'bet_minus_down.png',
                                disable: 'bet_minus_disable.png',
                                enable: 'bet_minus_standard.png',
                                hover: 'bet_minus_hover.png'
                            },
                            "hitareaVisible": false,
                            "shapeVisible": false,
                            "shape": {}
                        },
                        // Mobile
                        {
                            "id": "Button_4",
                            "name": "btn_bet_decrease",
                            "type": objectTypes.Sprite,
                            "buttonMode": true,
                            "uimode": "mobile",
                            "layout": true,
                            "interactive": true,
                            "x": 1330,
                            "y": 960,
                            "height": 52,
                            "width": 52,
                            "text": "",
                            "visible": true,
                            "buttonState": {
                                up: 'bet_minus_standard_moblie_landscape.png',
                                out: 'bet_minus_standard_moblie_landscape.png',
                                down: 'bet_minus_down_moblie_landscape.png',
                                disable: 'bet_minus_disable_moblie_landscape.png',
                                enable: 'bet_minus_standard_moblie_landscape.png',
                                hover: 'bet_minus_hover_moblie_landscape.png'
                            },
                            "hitareaVisible": false,
                            "shapeVisible": false,
                            "shape": {}
                        },
                    ]
                },
                {
                    "id": "GenericUIComponentincreaseButtonUI",
                    "name": "increaseButtonUI",
                    "type": "Tag",
                    "class": "",
                    "layout": true,
                    "filterTypes": [],
                    child: [
                        {
                            "id": "Button_3",
                            "name": "btn_bet_increase",
                            "type": objectTypes.Sprite,
                            "buttonMode": true,
                            "uimode": "desktop",
                            "layout": false,
                            "interactive": true,
                            "x": 1500,
                            "y": 979,
                            "height": 30,
                            "width": 30,
                            "text": "",
                            "visible": true,
                            "buttonState": {
                                up: 'bet_plus_standard.png',
                                out: 'bet_plus_standard.png',
                                down: 'bet_plus_down.png',
                                disable: 'bet_plus_disable.png',
                                enable: 'bet_plus_standard.png',
                                hover: 'bet_plus_hover.png'
                            },
                            "hitareaVisible": false,
                            "shapeVisible": false,
                            "shape": {}
                        },
                        // Mobile
                        {
                            "id": "Button_3",
                            "name": "btn_bet_increase",
                            "type": objectTypes.Sprite,
                            "buttonMode": true,
                            "uimode": "mobile",
                            "layout": true,
                            "interactive": true,
                            "x": 1600,
                            "y": 960,
                            "height": 52,
                            "width": 52,
                            "text": "",
                            "visible": true,
                            "buttonState": {
                                up: 'bet_plus_standard_moblie_landscape.png',
                                out: 'bet_plus_standard_moblie_landscape.png',
                                down: 'bet_plus_down_moblie_landscape.png',
                                disable: 'bet_plus_disable_moblie_landscape.png',
                                enable: 'bet_plus_standard_moblie_landscape.png',
                                hover: 'bet_plus_hover_moblie_landscape.png'
                            },
                            "hitareaVisible": false,
                            "shapeVisible": false,
                            "shape": {}
                        },
                        {
                            "name": "label_BonanzaGames",
                            "type": "Text",
                            "x": 1558,
                            "y": 1061.5,
                            "width": 200,
                            "visible": true,
                            uimode: "desktop",
                            "text": "BONANZA GAMES",
                            "scaleToFit": true,
                            "textStyle": {
                                fontFamily: 'MYP Bold',
                                fontSize: 16,
                                fontStyle: 'bold',
                                fill: ['#ababab'],
                            },
                        },
                    ]
                },
                {
                    "id": "GenericUIComponentBuyFeatureButtonUI",
                    "name": "buyFeatureButtonUI",
                    "type": "Tag",
                    "class": "",
                    "layout": true,
                    "filterTypes": [],
                    child: [
                        {
                            "id": "btn_buy_feature",
                            "name": "btn_buy_feature",
                            "type": objectTypes.Sprite,
                            "buttonMode": true,
                            "uimode": "desktop",
                            "layout": false,
                            "interactive": true,
                            "x": 1700,
                            "y": 650,
                            "width": 187,
                            "height": 74,
                            "text": "",
                            "visible": true,
                            "buttonState": {
                                up: 'buy_bonus_standard.png',
                                out: 'buy_bonus_standard.png',
                                down: 'buy_bonus_down.png',
                                disable: 'buy_bonus_disable.png',
                                enable: 'buy_bonus_standard.png',
                                hover: 'buy_bonus_hover.png'
                            },
                            "hitareaVisible": false,
                            "shapeVisible": false,
                            "shape": {}
                        },
                        // Mobile
                        {
                            "id": "btn_buy_feature",
                            "name": "btn_buy_feature",
                            "type": objectTypes.Sprite,
                            "buttonMode": true,
                            "uimode": "mobile",
                            "layout": true,
                            "interactive": true,
                            "x": 1700,
                            "y": 100,
                            "height": 71,
                            "width": 180,
                            "text": "",
                            "visible": true,
                            "buttonState": {
                                up: 'buy_bonus_standard.png',
                                out: 'buy_bonus_standard.png',
                                down: 'buy_bonus_down.png',
                                disable: 'buy_bonus_disable.png',
                                enable: 'buy_bonus_standard.png',
                                hover: 'buy_bonus_hover.png'
                            },
                            "hitareaVisible": false,
                            "shapeVisible": false,
                            "shape": {}
                        }
                    ]
                },
                {
                    "id": "GenericUIComponentautoPlayButtonUI",
                    "name": "autoPlayButtonUI",
                    "type": "Tag",
                    "class": "",
                    "filterTypes": [],
                    child: [
                        //// below one is added new
                        {
                            "id": "Button_7",
                            "name": "btn_autoplay_stop",
                            "type": objectTypes.Sprite,
                            "buttonMode": true,
                            "uimode": "desktop",
                            "interactive": false,
                            "layout": true,
                            "x": 1800.5,
                            "y": 895,
                            "height": 66,
                            "width": 66,
                            "text": "",
                            "visible": false,
                            "buttonState": {
                                up: 'autoplay_counter_up.png',
                                out: 'autoplay_counter_down.png',
                                down: 'autoplay_counter_down.png',
                                disable: 'autoplay_counter_up.png',
                                enable: 'autoplay_counter_up.png',
                                hover: 'autoplay_counter_up.png'
                            },
                            "hitareaVisible": false,
                            "shapeVisible": false,
                            "shape": {}
                        },

                        {
                            "id": "Button_8",
                            "name": "btn_autoplay_desktop",
                            "type": objectTypes.Sprite,
                            "buttonMode": true,
                            "uimode": "desktop",
                            "interactive": true,
                            "x": 1800.5,
                            "y": 895,
                            "height": 66,
                            "width": 66,
                            "text": "",
                            "visible": true,
                            "buttonState": {
                                up: 'autoplay_standard.png',
                                out: 'autoplay_standard.png',
                                down: 'autoplay_down.png',
                                disable: 'autoplay_disable.png',
                                enable: 'autoplay_standard.png',
                                hover: 'autoplay_hover.png'
                            },
                            "hitareaVisible": false,
                            "shapeVisible": false,
                            "shape": {
                                type: "rectangle",
                                x: 0,
                                y: 0,
                                w: 160,
                                h: 106
                            },

                        },


                        //Mobile View Text-----------------------------------------
                        {
                            "id": "Button_M14",
                            "name": "btn_autoplay_stop",
                            "type": objectTypes.Sprite,
                            "buttonMode": true,
                            "uimode": "mobile",
                            "interactive": false,
                            "layout": true,
                            "x": 690,
                            "y": 1648,
                            "height": 100,
                            "width": 100,
                            "text": "",
                            "visible": false,
                            "buttonState": {
                                up: 'autoplay_counter_up_moblie_landscape.png',
                                out: 'autoplay_counter_down_moblie_landscape.png',
                                down: 'autoplay_counter_down_moblie_landscape.png',
                                disable: 'autoplay_counter_down_moblie_landscape.png',
                                enable: 'autoplay_counter_up_moblie_landscape.png',
                                hover: 'autoplay_counter_hover_moblie_landscape.png'
                            },
                            "hitareaVisible": false,
                            "shapeVisible": false,
                            "shape": {}
                        },
                        {
                            "id": "Button_M1",
                            "name": "btn_autoplay_mobile",
                            "type": objectTypes.Sprite,
                            "interactive": true,
                            "layout": true,
                            "uimode": "mobile",
                            "x": 735,
                            "y": 1590,
                            "height": 98,
                            "width": 98,
                            "text": "",
                            "visible": true,
                            "buttonMode": true,
                            "buttonState": {
                                up: 'autoplay_standard_moblie_landscape.png',
                                out: 'autoplay_standard_moblie_landscape.png',
                                down: 'autoplay_down_moblie_landscape.png',
                                disable: 'autoplay_disable_moblie_landscape.png',
                                enable: 'autoplay_standard_moblie_landscape.png',
                                hover: 'autoplay_hover_moblie_landscape.png'
                            },
                            "hitareaVisible": false,
                            "shapeVisible": false,
                            "shape": {}
                        },
                        ////added new

                        {
                            "id": "btn_fullscreen",
                            "name": "btn_fullscreen",
                            "type": objectTypes.Sprite,
                            "buttonMode": true,
                            "uimode": "desktop",
                            "interactive": true,
                            "layout": true,
                            "x": 1850,
                            "y": 1050,
                            "height": 16,
                            "width": 16,
                            "text": "",
                            "visible": true,
                            "buttonState": {
                                up: 'fullscreen_up.png',
                                out: 'fullscreen_up.png',
                                down: 'fullscreen_down.png',
                                disable: 'fullscreen_disable.png',
                                enable: 'fullscreen_up.png',
                                hover: 'fullscreen_hover.png'
                            },
                            "hitareaVisible": false,
                            "shapeVisible": false,
                        },
                        {
                            "name": "label_Fullscreen",
                            "type": "Text",
                            "x": 1786,
                            "y": 1059,
                            "width": 200,
                            "visible": true,
                            "uimode": "desktop",
                            "text": "FULLSCREEN",
                            "scaleToFit": true,
                            "textStyle": {
                                fontFamily: 'MYP Bold',
                                fontSize: 16,
                                fontStyle: 'bold',
                                fill: ['#d8d6d6'],
                            },
                        },
                        {
                            "name": "label_Back",
                            "type": "Text",
                            "x": 71,
                            "y": 1058,
                            "width": 200,
                            "visible": true,
                            "uimode": "desktop",
                            "text": "BACK",
                            "scaleToFit": true,
                            "textStyle": {
                                fontFamily: 'MYP Bold',
                                fontSize: 16,
                                fontStyle: 'bold',
                                fill: ['#d8d6d6'],
                            },
                        },
                        {
                            "id": "btn_back",
                            "name": "btn_back",
                            "type": objectTypes.Sprite,
                            "buttonMode": true,
                            "uimode": "desktop",
                            "interactive": true,
                            "layout": false,
                            "x": 34.5,
                            "y": 1049,
                            "height": 16,
                            "width": 9,
                            "text": "",
                            "visible": true,
                            "buttonState": {
                                up: 'back_up.png',
                                out: 'back_up.png',
                                down: 'back_down.png',
                                disable: 'back_disable.png',
                                enable: 'back_up.png',
                                hover: 'back_hover.png'
                            },
                            "hitareaVisible": false,
                            "shapeVisible": false,
                        },

                    ]
                },
                {
                    "id": "GenericUIComponentsoundUI",
                    "name": "soundButtonUI",
                    "type": "Tag",
                    "class": "",
                    "filterTypes": [],
                    child: [
                        {
                            "name": "btn_sounddisable",
                            "type": objectTypes.Sprite,
                            "buttonMode": true,
                            "uimode": "desktop",
                            "interactive": false,
                            "x": 90,
                            "y": 969,
                            "height": 46,
                            "width": 46,
                            "text": "",
                            "visible": false,
                            "buttonState": {
                                up: 'sound_disable.png',
                            },
                            "hitareaVisible": false,
                            "shapeVisible": false,
                            "shape": {}
                        }, 
                        {
                            "id": "Button_5",
                            "name": "btn_sound",
                            "type": objectTypes.Sprite,
                            "buttonMode": true,
                            "uimode": "desktop",
                            "layout": false,
                            "interactive": false,
                            "x": 90,
                            "y": 969,
                            "height": 46,
                            "width": 46,
                            "text": "",
                            "visible": false,
                            "buttonState": {
                                up: 'sound_standard.png',
                                out: 'sound_standard.png',
                                down: 'sound_down.png',
                                disable: 'sound_disable.png',
                                enable: 'sound_standard.png',
                                hover: 'sound_hover.png'
                            },
                            "hitareaVisible": false,
                            "shapeVisible": false,
                            "shape": {}
                        },
                        {
                            "id": "Button_12",
                            "name": "btn_soundOff",
                            "type": objectTypes.Sprite,
                            "buttonMode": true,
                            "uimode": "desktop",
                            "layout": false,
                            "interactive": true,
                            "x": 90,
                            "y": 969,
                            "height": 46,
                            "width": 46,
                            "text": "",
                            "visible": true,
                            "buttonState": {
                                up: 'sound_off_symbol_standard.png',
                                out: 'sound_off_symbol_standard.png',
                                down: 'sound_off_symbol_down.png',
                                disable: 'sound_off_symbol_standard.png',
                                enable: 'sound_off_symbol_standard.png',
                                hover: 'sound_off_symbol_hover.png'

                            },
                            "hitareaVisible": false,
                            "shapeVisible": false,
                            "shape": {}
                        },
                        // Mobile
                        {
                            "id": "Button_5",
                            "name": "btn_sound",
                            "type": objectTypes.Sprite,
                            "buttonMode": true,
                            "uimode": "mobile",
                            "layout": true,
                            "interactive": false,
                            "x": 60,
                            "y": 1585,
                            "height": 74,
                            "width": 74,
                            "text": "",
                            "visible": false,
                            "buttonState": {
                                up: 'sound_standard.png',
                                out: 'sound_standard.png',
                                down: 'sound_down.png',
                                // disable: 'sound_disable.png',
                                enable: 'sound_standard.png',
                                hover: 'sound_hover.png'
                            },
                            "hitareaVisible": false,
                            "shapeVisible": false,
                            "shape": {}
                        },
                        {
                            "id": "Button_12",
                            "name": "btn_soundOff",
                            "type": objectTypes.Sprite,
                            "buttonMode": true,
                            "uimode": "mobile",
                            "layout": true,
                            "interactive": true,
                            "x": 60,
                            "y": 1585,
                            "height": 74,
                            "width": 74,
                            "text": "",
                            "visible": true,
                            "buttonState": {
                                up: 'sound_off_symbol_standard.png',
                                out: 'sound_off_symbol_standard.png',
                                down: 'sound_off_symbol_down.png',
                                // disable: 'sound_off_symbol_disable.png',
                                enable: 'sound_standard.png',
                                hover: 'sound_off_symbol_hover.png'
                            },
                            "hitareaVisible": false,
                            "shapeVisible": false,
                            "shape": {}
                        },

                    ]
                },
                {
                    "id": "GenericUIComponentspinButtonUI",
                    "name": "spinButtonUI",
                    "type": "Tag",
                    "class": "",
                    "filterTypes": [],
                    child: [
                        {
                            "id": "btn_spin",
                            "name": "btn_spin",
                            "type": objectTypes.Sprite,
                            "buttonMode": true,
                            "uimode": "desktop",
                            "layout": false,
                            "interactive": true,
                            "x": 1599,
                            "y": 750,
                            "height": 211,
                            "width": 211,
                            "text": "",
                            "visible": true,
                            "buttonState": {
                                up: 'spin_standard.png',
                                out: 'spin_standard.png',
                                down: 'spin_down.png',
                                disable: 'spin_disable.png',
                                enable: 'spin_standard.png',
                                hover: 'spin_hover.png'
                            },
                            "hitareaVisible": false,
                            "shapeVisible": false,
                            "shape": {
                                type: "circle",
                                x: 70,
                                y: 60,
                                r: 80,
                            },
                        },
                        // Mobile Buttons
                        {
                            "id": "Button_M2",
                            "name": "btn_spin",
                            "type": objectTypes.Sprite,
                            "interactive": true,
                            "uimode": "mobile",
                            "layout": true,
                            "x": 1620,
                            "y": 440,
                            "height": 292,
                            "width": 292,
                            "text": "",
                            "visible": true,
                            "buttonMode": true,
                            "buttonState": {
                                up: 'spin_standard_moblie_landscape.png',
                                out: 'spin_standard_moblie_landscape.png',
                                down: 'spin_down_moblie_landscape.png',
                                disable: 'spin_disable_moblie_landscape.png',
                                enable: 'spin_standard_moblie_landscape.png',
                                hover: 'spin_hover_moblie_landscape.png'
                            },
                            "hitareaVisible": false,
                            "shapeVisible": false,
                            "shape": {}
                        }
                    ]
                },
                {
                    "id": "GenericUIComponenthamburgerMenu",
                    "name": "hamburgerMenu",
                    "type": "Tag",
                    "class": "",
                    "layout": true,
                    "filterTypes": [],
                    child: [
                        {
                            "id": "Button_2",
                            "name": "btn_paytable",
                            "type": objectTypes.Sprite,
                            "buttonMode": true,
                            "uimode": "desktop",
                            "layout": false,
                            "interactive": true,
                            "x": 150,
                            "y": 969,
                            "height": 46,
                            "width": 46,
                            "text": "",
                            "visible": true,
                            "buttonState": {
                                up: 'info_standard.png',
                                out: 'info_standard.png',
                                down: 'info_down.png',
                                disable: 'info_disable.png',
                                enable: 'info_standard.png',
                                hover: 'info_hover.png'
                            },
                            "hitareaVisible": false,
                            "shapeVisible": false,
                            "shape": {}
                        },
                        {
                            "id": "Button_2",
                            "name": "btn_paytable",
                            "type": objectTypes.Sprite,
                            "buttonMode": true,
                            "uimode": "mobile",
                            "layout": true,
                            "interactive": true,
                            "x": 60,
                            "y": 700,
                            "height": 74,
                            "width": 74,
                            "text": "",
                            "visible": true,
                            "buttonState": {
                                up: 'info_standard_moblie_landscape.png',
                                out: 'info_standard_moblie_landscape.png',
                                down: 'info_down_moblie_landscape.png',
                                disable: 'info_disable_moblie_landscape.png',
                                enable: 'info_standard_moblie_landscape.png',
                                hover: 'info_hover_moblie_landscape.png'
                            },
                            "hitareaVisible": false,
                            "shapeVisible": false,
                            "shape": {}
                        },
                    ]
                },
                {
                    "id": "GenericUIComponentrespinStopButtonUI",
                    "name": "spinStopButtonUI",
                    "type": "Tag",
                    "class": "",
                    "filterTypes": [],
                    child: [
                        {
                            "id": "Button_15",
                            "name": "btn_spinStop",
                            "type": objectTypes.Sprite,
                            "buttonMode": true,
                            "uimode": "desktop",
                            "interactive": true,
                            "layout": false,
                            "x": 1599,
                            "y": 750,
                            "height": 212,
                            "width": 212,
                            "text": "",
                            "visible": true,
                            "buttonState": {
                                up: 'spin_stop_standard.png',
                                out: 'spin_stop_standard.png',
                                down: 'spin_stop_down.png',
                                disable: 'spin_stop_disable.png',
                                enable: 'spin_stop_hover.png',
                                hover: 'spin_stop_hover.png'
                            },
                            "hitareaVisible": false,
                            "shapeVisible": false,
                            "shape": {}
                        },
                        // Mobile
                        {
                            "id": "Button_M15",
                            "name": "btn_spinStop",
                            "type": objectTypes.Sprite,
                            "buttonMode": true,
                            "layout": true,
                            "uimode": "mobile",
                            "interactive": true,
                            "x": 420,
                            "y": 1460,
                            "height": 292,
                            "width": 292,
                            "text": "",
                            "visible": true,
                            "buttonState": {
                                up: 'spin_stop_standard_moblie_landscape.png',
                                out: 'spin_stop_standard_moblie_landscape.png',
                                down: 'spin_stop_down_moblie_landscape.png',
                                disable: 'spin_stop_disable_moblie_landscape.png',
                                enable: 'spin_stop_standard_moblie_landscape.png',
                                hover: 'spin_stop_hover_moblie_landscape.png'
                            },
                            "hitareaVisible": false,
                            "shapeVisible": false,
                            "shape": {}
                        },
                    ]
                },

                {
                    "id": "GenericUIComponentTurboButtonEnable",
                    "name": "turboButtonEnable",
                    "type": "Tag",
                    "class": "",
                    "filterTypes": [],
                    child: [
                        {
                            "id": "btn_turboEnable",
                            "name": "btn_turboEnable",
                            "type": objectTypes.Sprite,
                            "interactive": true,
                            "uimode": "desktop",
                            "layout": false,
                            "x": 1540.5,
                            "y": 889,
                            "height": 66,
                            "width": 66,
                            "text": "",
                            "visible": true,
                            "buttonMode": true,
                            "buttonState": {
                                up: 'turbo_spin_standard.png',
                                out: 'turbo_spin_standard.png',
                                down: 'turbo_spin_down.png',
                                disable: 'turbo_spin_disable.png',
                                enable: 'turbo_spin_standard.png',
                                hover: 'turbo_spin_hover.png'
                            },
                            "hitareaVisible": false,
                            "shapeVisible": false,
                            "shape": {}
                        },
                        {
                            "id": "btn_turboEnable",
                            "name": "btn_turboEnable",
                            "type": objectTypes.Sprite,
                            "interactive": true,
                            "uimode": "mobile",
                            "layout": true,
                            "x": 1690,
                            "y": 770,
                            "height": 100,
                            "width": 100,
                            "text": "",
                            "visible": true,
                            "buttonMode": true,
                            "buttonState": {
                                up: 'turbo_spin_standard_moblie_landscape.png',
                                out: 'turbo_spin_standard_moblie_landscape.png',
                                down: 'turbo_spin_on_down_moblie_landscape.png',
                                disable: 'turbo_spin_disable_moblie_landscape.png',
                                enable: 'turbo_spin_standard_moblie_landscape.png',
                                hover: 'turbo_spin_hover_moblie_landscape.png'
                            },
                            "hitareaVisible": false,
                            "shapeVisible": false,
                            "shape": {}
                        },
                    ]
                },
                {
                    "id": "GenericUIComponentTurboButton",
                    "name": "turboButtonDisable",
                    "type": "Tag",
                    "class": "",
                    "filterTypes": [],
                    child: [
                        {
                            "id": "btn_turDisable",
                            "name": "btn_turDisable",
                            "type": objectTypes.Sprite,
                            "interactive": true,
                            "layout": false,
                            "uimode": "desktop",
                            "x": 1540.5,
                            "y": 889,
                            "height": 66,
                            "width": 66,
                            "text": "",
                            "visible": true,
                            "buttonMode": true,
                            "buttonState": {
                                up: 'turbo_spin_on_up.png',
                                out: 'turbo_spin_on_down.png',
                                down: 'turbo_spin_on_down.png',
                                disable: 'turbo_spin_disable.png',
                                enable: 'turbo_spin_on_down.png',
                                hover: 'turbo_spin_on_down.png'
                            },
                            "hitareaVisible": false,
                            "shapeVisible": false,
                            "shape": {}
                        },
                        {
                            "id": "btn_turDisable",
                            "name": "btn_turDisable",
                            "type": objectTypes.Sprite,
                            "interactive": true,
                            "layout": true,
                            "uimode": "mobile",
                            "x": 1690,
                            "y": 770,
                            "height": 100,
                            "width": 100,
                            "text": "",
                            "visible": true,
                            "buttonMode": true,
                            "buttonState": {
                                up: 'turbo_spin_on_up_moblie_landscape.png',
                                out: 'turbo_spin_on_down_moblie_landscape.png',
                                down: 'turbo_spin_down_moblie_landscape.png',
                                disable: 'turbo_spin_disable_moblie_landscape.png',
                                enable: 'turbo_spin_standard_moblie_landscape.png',
                                hover: 'turbo_spin_hover_moblie_landscape.png'
                            },
                            "hitareaVisible": false,
                            "shapeVisible": false,
                            "shape": {}
                        },
                    ]
                },
                {
                    "id": "GenericUIComponentmenuButtonUI",
                    "name": "menuButton",
                    "type": "Tag",
                    "class": "",
                    "filterTypes": [],
                    child: [
                        {
                            "id": "popup_black",
                            "name": "popup_black",
                            "image": 'popup_black.png',
                            "type": "Image",
                            "uimode": "desktop",
                            "class": "",
                            "filterTypes": [],
                            "visible": false,
                            "interactive": false,
                            "x": 0,
                            "y": 0,
                            "height": 1080,
                            "width": 1920,
                        },
                        {
                            "id": "menu_base_line",
                            "name": "menu_base_line",
                            "image": 'autoplay_slider_base.png',
                            "type": "Image",
                            "uimode": "desktop",
                            "class": "",
                            "filterTypes": [],
                            "visible": false,
                            "interactive": false,
                            "x": 625,
                            "y": 790,
                            "height": 2,
                            "width": 700,
                        },
                        {
                            "id": "btn_menu_close",
                            "name": "btn_menu_close",
                            "type": objectTypes.Sprite,
                            "buttonMode": true,
                            "uimode": "desktop",
                            "interactive": false,
                            "x": 1650,
                            "y": 500,
                            "height": 141,
                            "width": 141,
                            "text": "",
                            "visible": false,
                            "buttonState": {
                                up: 'close_button_standard.png',
                                out: 'close_button_standard.png',
                                down: 'close_button_down.png',
                                disable: 'close_button_standard.png',
                                enable: 'close_button_standard.png',
                                hover: 'close_button_standard.png'
                            },
                            "hitareaVisible": false,
                            "shapeVisible": false,
                            "shape": {},
                        },
                        // {
                        //     "id": "btn_game_highlighted",
                        //     "name": "btn_game_highlighted",
                        //     "type": objectTypes.Sprite,
                        //     "buttonMode": true,
                        //     "uimode": "desktop",
                        //     "interactive": false,
                        //     "x": 920,
                        //     "y": 825,
                        //     "height": 80,
                        //     "width": 80,
                        //     "text": "",
                        //     "visible": false,
                        //     "buttonState": {
                        //         up: 'rules_symbol_selected.png',
                        //         out: 'rules_symbol_selected.png',
                        //         down: 'rules_symbol_selected.png',
                        //         disable: 'rules_symbol_selected.png',
                        //         enable: 'rules_symbol_selected.png',
                        //         hover: 'rules_symbol_selected.png'
                        //     },
                        //     "hitareaVisible": false,
                        //     "shapeVisible": false,
                        //     "shape": {},
                        // },
                        {
                            "id": "Button_6",
                            "name": "btn_gameRule",
                            "type": objectTypes.Sprite,
                            "buttonMode": true,
                            "uimode": "desktop",
                            "interactive": true,
                            "x": 920,
                            "y": 825,
                            "height": 80,
                            "width": 80,
                            "text": "",
                            "visible": false,
                            "buttonState": {
                                up: 'rules_symbol_unselected.png',
                                out: 'rules_symbol_unselected.png',
                                down: 'rules_symbol_unselected.png',
                                disable: 'rules_symbol_unselected.png',
                                enable: 'rules_symbol_unselected.png',
                                hover: 'rules_symbol_selected.png'
                            },
                            "hitareaVisible": false,
                            "shapeVisible": false,
                            "shape": {}
                        },

                        {
                            "id": "btn_history_highlighted",
                            "name": "btn_history_highlighted",
                            "type": objectTypes.Sprite,
                            "buttonMode": true,
                            "uimode": "desktop",
                            "interactive": false,
                            "x": 700,
                            "y": 825,
                            "height": 80,
                            "width": 80,
                            "text": "",
                            "visible": false,
                            "buttonState": {
                                up: 'history_symbol_selected.png',
                                out: 'history_symbol_selected.png',
                                down: 'history_symbol_selected.png',
                                disable: 'history_symbol_selected.png',
                                enable: 'history_symbol_selected.png',
                                hover: 'history_symbol_selected.png'
                            },
                            "hitareaVisible": false,
                            "shapeVisible": false,
                            "shape": {},

                        },
                        {
                            "id": "btn_history",
                            "name": "btn_history",
                            "type": objectTypes.Sprite,
                            "uimode": "desktop",
                            "buttonMode": true,
                            "interactive": true,
                            "x": 700,
                            "y": 825,
                            "height": 80,
                            "width": 80,
                            "text": "",
                            "visible": false,
                            "buttonState": {
                                up: 'history_symbol_unselected.png',
                                out: 'history_symbol_unselected.png',
                                down: 'history_symbol_unselected.png',
                                disable: 'history_symbol_unselected.png',
                                enable: 'history_symbol_unselected.png',
                                hover: 'history_symbol_selected.png'
                            },
                            "hitareaVisible": false,
                            "shapeVisible": false,
                            "shape": {},

                        },
                        /*   ]
                      }, */
                        // {
                        //     "id": "btn_menu_close",
                        //     "name": "btn_menu_close",
                        //     "type": objectTypes.Sprite,
                        //     "buttonMode": true,
                        //     "uimode": "desktop",
                        //     "interactive": true,
                        //     "layout": true,
                        //     "x": 35,
                        //     "y": 1005,
                        //     "height": 48,
                        //     "width": 48,
                        //     "text": "",
                        //     "visible": false,
                        //     "buttonState": {
                        //         up: 'menu_down.png',
                        //         out: 'menu_down.png',
                        //         down: 'menu_down.png',
                        //         disable: 'menu_down.png',
                        //         enable: 'menu_down.png',
                        //         hover: 'menu_down.png'
                        //     },
                        //     "hitareaVisible": false,
                        //     "shapeVisible": false,
                        // },
                        // {
                        //     "id": "btn_menu_close",
                        //     "name": "btn_menu_close",
                        //     "type": objectTypes.Sprite,
                        //     "buttonMode": true,
                        //     "uimode": "desktop",
                        //     "interactive": true,
                        //     "layout": true,
                        //     "x": 35,
                        //     "y": 1005,
                        //     "height": 48,
                        //     "width": 48,
                        //     "text": "",
                        //     "visible": false,
                        //     "buttonState": {
                        //         up: 'close_button_standard.png',
                        //         out: 'close_button_standard.png',
                        //         down: 'close_button_down.png',
                        //         disable: 'close_button_standard.png',
                        //         enable: 'close_button_standard.png',
                        //         hover: 'close_button_standard.png'
                        //     },
                        //     "hitareaVisible": false,
                        //     "shapeVisible": false,
                        // },
                        {
                            "id": "btn_menu",
                            "name": "btn_menu",
                            "type": objectTypes.Sprite,
                            "buttonMode": true,
                            "uimode": "desktop",
                            "interactive": true,
                            "layout": false,
                            "x": 30,
                            "y": 969,
                            "height": 48,
                            "width": 48,
                            "text": "",
                            "visible": true,
                            "buttonState": {
                                up: 'menu_standard.png',
                                out: 'menu_standard.png',
                                down: 'menu_down.png',
                                disable: 'menu_disable.png',
                                enable: 'menu_standard.png',
                                hover: 'menu_hover.png'
                            },
                            "hitareaVisible": false,
                            "shapeVisible": false,
                        },
                        // Mobile
                        {
                            "id": "Button_M4",
                            "name": "btn_menu",
                            "type": objectTypes.Sprite,
                            "buttonMode": true,
                            "layout": true,
                            "uimode": "mobile",
                            "interactive": true,
                            "x": 70,
                            "y": 300,
                            "height": 74,
                            "width": 74,
                            "text": "",
                            "visible": true,
                            "buttonState": {
                                up: 'menu_standard_moblie_landscape.png',
                                out: 'menu_standard_moblie_landscape.png',
                                down: 'menu_down_moblie_landscape.png',
                                disable: 'menu_disable_moblie_landscape.png',
                                enable: 'menu_standard_moblie_landscape.png',
                                hover: 'menu_hover_moblie_landscape.png'
                            },
                            "hitareaVisible": false,
                            "shapeVisible": false,
                            "shape": {}
                        },
                        // {
                        //     "name": "label_Back",
                        //     "type": "Text",
                        //     "x": 71,
                        //     "y": 1058,
                        //     "width": 200,
                        //     "visible": true,
                        //     "uimode": "desktop",
                        //     "text": "BACK",
                        //     "scaleToFit": true,
                        //     "textStyle": {
                        //         fontFamily: 'MYP Bold',
                        //         fontSize: 16,
                        //         fontStyle: 'bold',
                        //         fill: ['#d8d6d6'],
                        //     },
                        // },
                        // {
                        //     "id": "btn_back",
                        //     "name": "btn_back",
                        //     "type": objectTypes.Sprite,
                        //     "buttonMode": true,
                        //     "uimode": "desktop",
                        //     "interactive": true,
                        //     "layout": false,
                        //     "x": 34.5,
                        //     "y": 1049,
                        //     "height": 16,
                        //     "width": 9,
                        //     "text": "",
                        //     "visible": true,
                        //     "buttonState": {
                        //         up: 'back_up.png',
                        //         out: 'back_up.png',
                        //         down: 'back_down.png',
                        //         disable: 'back_disable.png',
                        //         enable: 'back_up.png',
                        //         hover: 'back_hover.png'
                        //     },
                        //     "hitareaVisible": false,
                        //     "shapeVisible": false,
                        // },
                        // {
                        //     "name": "btn_game_exit",
                        //     "type": objectTypes.Sprite,
                        //     "buttonMode": true,
                        //     "uimode": "desktop",
                        //     "interactive": true,
                        //     "x": 40,
                        //     "y": 954,
                        //     "width": 80,
                        //     "height": 80,
                        //     "text": "",
                        //     "visible": false,
                        //     "buttonState": {
                        //         up: 'exit_up.png',
                        //         out: 'exit_up.png',
                        //         down: 'exit_pressed.png',
                        //         disable: 'exit_disable.png',
                        //         enable: 'exit_up.png',
                        //         hover: 'exit_over.png'
                        //     },
                        //     "hitareaVisible": true,
                        // },
                        // {
                        //     "id": "scrollbarContainer",
                        //     "name": "scrollbarContainer",
                        //     "type": "Container",
                        //     "x": 230,
                        //     "y": 100,
                        //     "visible": false,
                        //     "filterTypes": [],
                        //     "parentLayer": "specialAnimationLayer",
                        //     child: [
                        //         {
                        //             "id": "page_slider_line",
                        //             "name": "page_slider_line",
                        //             "image": 'scroll_bar.png',
                        //             "type": "Image",
                        //             "uimode": "desktop",
                        //             "class": "",
                        //             "filterTypes": [],
                        //             "visible": true,
                        //             "interactive": false,
                        //             "x": 1310,
                        //             "y": 150,
                        //             "height": 500,
                        //             "width": 3,
                        //         },
                        //         {
                        //             "id": "page_slider_cylinder",
                        //             "name": "page_slider_cylinder",
                        //             "image": 'scroll_slider.png',
                        //             "type": "Image",
                        //             "uimode": "desktop",
                        //             "class": "",
                        //             "filterTypes": [],
                        //             "visible": true,
                        //             "interactive": false,
                        //             "x": 1303,
                        //             "y": 150,
                        //             "height": 61,
                        //             "width": 18,
                        //         },
                        //         {
                        //             "id": "page_arrow_up",
                        //             "name": "page_arrow_up",
                        //             "image": 'arrow_top.png',
                        //             "type": "Image",
                        //             "uimode": "desktop",
                        //             "class": "",
                        //             "filterTypes": [],
                        //             "visible": true,
                        //             "interactive": false,
                        //             "x": 1302,
                        //             "y": 120,
                        //             "height": 11,
                        //             "width": 19,
                        //         },
                        //         {
                        //             "id": "page_arrow_down",
                        //             "name": "page_arrow_down",
                        //             "image": 'arrow_bottom.png',
                        //             "type": "Image",
                        //             "uimode": "desktop",
                        //             "class": "",
                        //             "filterTypes": [],
                        //             "visible": true,
                        //             "interactive": false,
                        //             "x": 1301,
                        //             "y": 680,
                        //             "height": 11,
                        //             "width": 19,
                        //         },
                        //     ]
                        // },
                        {
                            "id": "GenericUIComponentsettingButtonUI",
                            "name": "settingButtonUI",
                            "type": "Tag",
                            "class": "",
                            "filterTypes": [],
                            child: [
                                // {
                                //     "id": "btn_setting_highlighted",
                                //     "name": "btn_setting_highlighted",
                                //     "type": objectTypes.Sprite,
                                //     "buttonMode": true,
                                //     "uimode": "desktop",
                                //     "interactive": false,
                                //     "x": 1150,
                                //     "y": 825,
                                //     "height": 80,
                                //     "width": 80,
                                //     "text": "",
                                //     "visible": false,
                                //     "buttonState": {
                                //         up: 'setting_symbol_selected.png',
                                //         out: 'setting_symbol_selected.png',
                                //         down: 'setting_symbol_selected.png',
                                //         disable: 'setting_symbol_selected.png',
                                //         enable: 'setting_symbol_selected.png',
                                //         hover: 'setting_symbol_selected.png'
                                //     },
                                //     "hitareaVisible": false,
                                //     "shapeVisible": false,
                                //     "shape": {},
                                // },
                                // {
                                //     "id": "Button_11",
                                //     "name": "btn_setting",
                                //     "type": objectTypes.Sprite,
                                //     "buttonMode": true,
                                //     "uimode": "desktop",
                                //     "interactive": true,
                                //     "x": 1150,
                                //     "y": 825,
                                //     "height": 80,
                                //     "width": 80,
                                //     "text": "",
                                //     "visible": false,
                                //     "buttonState": {
                                //         up: 'settings_symbol_unselected.png',
                                //         out: 'settings_symbol_unselected.png',
                                //         down: 'settings_symbol_unselected.png',
                                //         disable: 'settings_symbol_unselected.png',
                                //         enable: 'settings_symbol_unselected.png',
                                //         hover: 'setting_symbol_selected.png'
                                //     },
                                //     "hitareaVisible": false,
                                //     "shapeVisible": false,
                                //     "shape": {},

                                // },
                            ]
                        },
                        {
                            "id": "historyContainer",
                            "name": "historyContainer",
                            "type": "Container",
                            "x": 0,
                            "y": 0,
                            "visible": false,
                            "filterTypes": [],
                            "parentLayer": "specialAnimationLayer",
                            child: [
                                // {
                                //     "id": "history_heading",
                                //     "name": "history_heading",
                                //     "type": "Text",
                                //     "x": 865,
                                //     "y": 100,
                                //     "width": 300,
                                //     "visible": true,
                                //     "text": "HISTORY",
                                //     "scaleToFit": true,
                                //     "anchor": [0, 0],
                                //     "textStyle": {
                                //         fontFamily: 'Oswald-Regular',
                                //         fontSize: 50,
                                //         fontStyle: 'normal',
                                //         fill: ['#e2be20'],
                                //     },
                                // },
                                // {
                                //     "id": "history_divider",
                                //     "name": "history_divider",
                                //     "type": objectTypes.Sprite,
                                //     "buttonMode": true,
                                //     "uimode": "desktop",
                                //     "interactive": true,
                                //     "x": 860,
                                //     "y": 160,
                                //     "height": 2,
                                //     "width": 215,
                                //     "text": "",
                                //     "visible": true,
                                //     "buttonState": {
                                //         up: 'autoplay_slider_active.png',
                                //         out: 'autoplay_slider_active.png',
                                //         down: 'autoplay_slider_active.png',
                                //         disable: 'autoplay_slider_active.png',
                                //         enable: 'autoplay_slider_active.png',
                                //         hover: 'autoplay_slider_active.png'
                                //     },
                                //     "hitareaVisible": false,
                                //     "shapeVisible": false,
                                //     "shape": {},
                                // },
                                {
                                    "id": "Bet_History_bet",
                                    "name": "Bet_History_bet",
                                    "type": "Text",
                                    "x": 656,
                                    "y": 200,
                                    "width": 300,
                                    "visible": true,
                                    "text": "Bet",
                                    "scaleToFit": true,
                                    "anchor": [0, 0],
                                    "textStyle": {
                                        fontFamily: 'Oswald-Regular',
                                        fontSize: 50,
                                        fontStyle: 'normal',
                                        fill: ['#ffffff'],
                                    },
                                },
                                {
                                    "id": "Bet_History_win",
                                    "name": "Bet_History_win",
                                    "type": "Text",
                                    "x": 856,
                                    "y": 200,
                                    "width": 300,
                                    "visible": true,
                                    "text": "Win",
                                    "scaleToFit": true,
                                    "anchor": [0, 0],
                                    "textStyle": {
                                        fontFamily: 'Oswald-Regular',
                                        fontSize: 50,
                                        fontStyle: 'normal',
                                        fill: ['#ffffff'],
                                    },
                                },
                                {
                                    "id": "Bet_History_time",
                                    "name": "Bet_History_time",
                                    "type": "Text",
                                    "x": 1056,
                                    "y": 200,
                                    "width": 300,
                                    "visible": true,
                                    "text": "Time",
                                    "scaleToFit": true,
                                    "anchor": [0, 0],
                                    "textStyle": {
                                        fontFamily: 'Oswald-Regular',
                                        fontSize: 50,
                                        fontStyle: 'normal',
                                        fill: ['#ffffff'],
                                    },
                                },
                            ]
                        },
                        {
                            "id": "gameRuleContainer",
                            "name": "gameRuleContainer",
                            "type": "Container",
                            "x": 0,
                            "y": 0,
                            "visible": false,
                            "filterTypes": [],
                            "parentLayer": "specialAnimationLayer",
                            child: [
                                {
                                    "id": "gameRule_heading",
                                    "name": "gameRule_heading",
                                    "type": "Text",
                                    "x": 865,
                                    "y": 100,
                                    "width": 300,
                                    "visible": true,
                                    "text": "RULES",
                                    "scaleToFit": true,
                                    "anchor": [0, 0],
                                    "textStyle": {
                                        fontFamily: 'Oswald-Regular',
                                        fontSize: 50,
                                        fontStyle: 'normal',
                                        fill: ['#e2be20'],
                                    },
                                },
                                {
                                    "id": "gameRule_divider",
                                    "name": "gameRule_divider",
                                    "type": objectTypes.Sprite,
                                    "buttonMode": true,
                                    "uimode": "desktop",
                                    "interactive": true,
                                    "x": 855,
                                    "y": 160,
                                    "height": 2,
                                    "width": 175,
                                    "text": "",
                                    "visible": true,
                                    "buttonState": {
                                        up: 'autoplay_slider_active.png',
                                        out: 'autoplay_slider_active.png',
                                        down: 'autoplay_slider_active.png',
                                        disable: 'autoplay_slider_active.png',
                                        enable: 'autoplay_slider_active.png',
                                        hover: 'autoplay_slider_active.png'
                                    },
                                    "hitareaVisible": false,
                                    "shapeVisible": false,
                                    "shape": {},

                                },
                            ]
                        },

                        {
                            "id": "gameSettingsMainContainer",
                            "name": "gameSettingsMainContainer",
                            "type": "Container",
                            "x": 0,
                            "y": 0,
                            "visible": false,
                            "filterTypes": [],
                            "parentLayer": "specialAnimationLayer",
                            child: [
                                // {
                                //     "name": "backgroundGraphic",
                                //     "type": "Graphic",
                                //     "shape": "rectangle",
                                //     "visible": true,
                                //     "alpha": 1,
                                //     "color": "0x131313",
                                //     "x": 0,
                                //     "y": 0,
                                //     "width": 1920,
                                //     "height": 1080,

                                // },
                                {
                                    "id": "gameSettingsCont_white",
                                    "name": "gameSettingsCont_white",
                                    "type": "Container",
                                    "x": 0,
                                    "y": 190,
                                    "visible": false,
                                    "filterTypes": [],
                                    child: [
                                        {
                                            "id": "gameSettingsText_white",
                                            "name": "gameSettingsText_white",
                                            "type": "Text",
                                            "x": 750,
                                            "y": 130,
                                            "width": 500,
                                            "visible": true,
                                            "text": "menu-title_settings_general",
                                            "scaleToFit": true,
                                            "anchor": [0.5, 0.5],
                                            "textStyle": {
                                                fontFamily: 'Oswald-Regular',
                                                fontSize: 50,
                                                fontStyle: 'normal',
                                                fill: ['#ffffff'],
                                            },
                                        },
                                    ]
                                },
                                {
                                    "id": "gameSettingsCont_yellow",
                                    "name": "gameSettingsCont_yellow",
                                    "type": "Container",
                                    "x": 190,
                                    "y": 0,
                                    "visible": true,
                                    "filterTypes": [],
                                    child: [
                                        {
                                            "id": "gameSettingsText_yellow",
                                            "name": "gameSettingsText_yellow",
                                            "type": "Text",
                                            "x": 750,
                                            "y": 130,
                                            "width": 500,
                                            "visible": true,
                                            "text": "SETTINGS",
                                            "scaleToFit": true,
                                            "anchor": [0.5, 0.5],
                                            "textStyle": {
                                                fontFamily: 'Oswald-Regular',
                                                fontSize: 50,
                                                fontStyle: 'normal',
                                                fill: ['#e2be20'],
                                            },
                                        },

                                    ]
                                },
                                {
                                    "id": "setting_divider",
                                    "name": "setting_divider",
                                    "type": objectTypes.Sprite,
                                    "buttonMode": true,
                                    "uimode": "desktop",
                                    "interactive": true,
                                    "x": 820,
                                    "y": 160,
                                    "height": 2,
                                    "width": 240,
                                    "text": "",
                                    "visible": true,
                                    "buttonState": {
                                        up: 'autoplay_slider_active.png',
                                        out: 'autoplay_slider_active.png',
                                        down: 'autoplay_slider_active.png',
                                        disable: 'autoplay_slider_active.png',
                                        enable: 'autoplay_slider_active.png',
                                        hover: 'autoplay_slider_active.png'
                                    },
                                    "hitareaVisible": false,
                                    "shapeVisible": false,
                                    "shape": {},
                                },
                                // {
                                //     "name": "gameSettingsBtn",
                                //     "type": "Graphic",
                                //     "shape": "rectangle",
                                //     "interactive": true,
                                //     "buttonMode": true,
                                //     "visible": true,
                                //     "alpha": 0.01,
                                //     "color": "0xffffff",
                                //     "x": 793,
                                //     "y": 80,
                                //     "width": 300,
                                //     "height": 100,

                                // },
                                {
                                    "id": "GameGeneralComponent",
                                    "name": "GameGeneralComponent",
                                    "type": "Tag",
                                    "class": "",
                                    "parentLayer": "specialAnimationLayer",
                                    "filterTypes": [],
                                    child: [],
                                    "height": 100,
                                    "width": 200
                                },
                            ]
                        },


                    ]
                },

                {
                    "id": "GenericUIComponenttextCoinValueUI",
                    "name": "textCoinValueUI",
                    "type": "Tag",
                    "class": "",
                    "filterTypes": [],
                    child: [

                        {
                            "id": "text_4",
                            "name": "text_coinValue_value",
                            "uimode": "desktop",
                            "type": "Text",
                            "x": 960,
                            "y": 990,
                            "width": 150,
                            "visible": false,
                            "text": "00",
                            "scaleToFit": true,
                            "anchor": [0.5, 0.5],
                            "textStyle": {
                                fontFamily: 'Arial',
                                fontSize: 22,
                                fontWeight: 'bold',
                                fill: ['#ffffff'],
                            },
                            "parentLayer": "specialAnimationLayer",
                        }


                    ]
                },
                {
                    "id": "GenericUIComponenttextCountAP",
                    "name": "textCountAPUI",
                    "type": "Tag",
                    "class": "",
                    "filterTypes": [],
                    child: [
                        {
                            "id": "text_24",
                            "name": "Text_COUNT_AP",
                            "type": "Text",
                            "uimode": "desktop",
                            "x": 1832,
                            "y": 930,
                            "text": "",
                            "anchor": [0.5, 0.5],
                            "visible": true,
                            width: 64,
                            "scaleToFit": true,
                            "textStyle": {
                                fontFamily: 'MYP Bold',
                                fontSize: 18,
                                fontWeight: 'bold',
                                fill: ['#000000'],
                            },
                            "parentLayer": "specialAnimationLayer",
                        },
                        {
                            "id": "text_M10",
                            "name": "Text_COUNT_AP",
                            "type": "Text",
                            "layout": true,
                            "uimode": "mobile",
                            "x": 1748,
                            "y": 292,
                            "text": "",
                            "width": 50,
                            "anchor": [0.5, 0.5],
                            "visible": true,
                            "scaleToFit": true,
                            "textStyle": {
                                fontFamily: 'MYP Bold',
                                fontSize: 28,
                                fontWeight: 'bold',
                                fill: ['#000000'],
                            },
                            "parentLayer": "specialAnimationLayer",
                        },
                    ]
                },
                {
                    "id": "GenericUIComponentButtonUpdate",
                    "name": "buttonStateUpdate",
                    "type": "Tag",
                    "class": "",
                    "filterTypes": [],
                    child: []
                }
                //
            ]

        },

    ],
}
