import { frameworkPlayerMessage} from "@bonanzainteractive/slote_core"

frameworkPlayerMessage.data = {
    "leftContainerInterval": 4000,
    "rightContainerInterval": 2000,
    "COMPONENTS": [
        {
            "id": "BMPlayerMessageContainer",
            "name": "BMPlayerMessageContainer",
            "type": "Container",
            "class": "",
            "x": 0,
            "y": 0,
            "filterTypes": [],
            "parentLayer": "baseLayer",
            child: [
                {
                    "id": "BMPlayerMessageComponent",
                    "name": "GofPlayerMessage",
                    "type": "Tag",
                    "class": "",
                    "filterTypes": [],
                    child: [
                        {
                            id: "container_leftInfo",
                            "name": "leftInfoContainer",
                            "type": "Container",
                            "class": "",
                            "visible": true,
                            "uimode": "desktop",
                            "x": 0,
                            "y": 1022,
                            "width": 934,
                            "height": 58,
                            "filterTypes": [],
                            child: [
                                {
                                    id: "container_leftInfo1",
                                    "name": "leftInfoContainer1",
                                    "type": "Container",
                                    "class": "",
                                    "visible": true,
                                    "messageInLoop": true,
                                    "x": 0,
                                    "y": 0,
                                    "width": 934,
                                    "height": 58,
                                    "filterTypes": [],
                                    child: [
                                        {
                                            "id": "text_Good_Luck",
                                            "name": "good_Luck_Text",
                                            "uimode": "desktop",
                                            "type": "Text",
                                            "x": 520,
                                            "y": 32,
                                            "width": 500,
                                            "visible": false,
                                            "text": "buttonPanelText_18",
                                            "scaleToFit": true,
                                            "anchor": [0.5, 0.5],
                                            "textStyle": {
                                                fontFamily: 'Arial',
                                                fontSize: 30,
                                                fontWeight: 'bold',
                                                fill: ['#ffffff'],
                                            },
                                            "parentLayer": "specialAnimationLayer",
                                        },
                                        {
                                            "id": "MaxWinOdd_text",
                                            "name": "MaxWinOdd_text",
                                            "type": "Container",
                                            "class": "",
                                            "visible": true,
                                            "uimode": "desktop",
                                            "x": 10,
                                            "y": 0,
                                            "width": 1500,
                                            "height": 250,
                                            "filterTypes": [],
                                            child: [
                                                {
                                                    "id": "graphic_maxodd",
                                                    "name": "graphic_maxodd",
                                                    "type": "Graphic",
                                                    "shape": "rectangle",
                                                    "color": "0x000000",
                                                    "alpha": 0.75,
                                                    "x": -210,
                                                    "y": -25,
                                                    "width": 575,
                                                    "height": 30,
                                                    "visible": false,
                                                    "scaleToFit": true,
                                                },
                                                {
                                                    "id": "setMaxWinOdd_text",
                                                    "name": "setMaxWinOdd_text",
                                                    "type": "Text",
                                                    "uimode": "desktop",
                                                    "x": 255,
                                                    "y": -10,
                                                    "width": 1500,
                                                    "visible": true,
                                                    "text": "maxWinOdds",
                                                    "scaleToFit": true,
                                                    "anchor": [1, 0.5],
                                                    "textStyle": {
                                                        fontFamily: 'Arial',
                                                        fontWeight: 'bold',
                                                        fontSize: 24,
                                                        fill: ['#FFFFFF'],
                                                        backgroundColor: '#00000000',
                                                    },
                                                    "parentLayer": "specialAnimationLayer",
                                                },
                                                {
                                                    "id": "setMaxWinOdd",
                                                    "name": "setMaxWinOdd",
                                                    "type": "Text",
                                                    "uimode": "desktop",
                                                    "x": 256,
                                                    "y": -10,
                                                    "width": 500,
                                                    "visible": true,
                                                    "text": "maxWinOdds",
                                                    "scaleToFit": true,
                                                    "anchor": [0, 0.5],
                                                    "textStyle": {
                                                        fontFamily: 'Arial',
                                                        fontWeight: 'bold',
                                                        fontSize: 24,
                                                        fill: ['#FFFFFF'],
                                                    },
                                                    "parentLayer": "specialAnimationLayer",
                                                },
                                                
                                            ],
                                        },
                                        {
                                            "id": "game_clock",
                                            "name": "game_clock",
                                            "uimode": "desktop",
                                            "type": "Text",
                                            "x": 70,
                                            "y": -982,
                                            "width": 155,
                                            "visible": false,
                                            "text": "10:50",
                                            "scaleToFit": true,
                                            "anchor": [0.5, 0.5],
                                            "textStyle": {
                                                fontFamily: 'Arial',
                                                fontSize: 30,
                                                fontStyle: 'bold',
                                                fill: ['#FFFFFF'],
                                            },
                                            "parentLayer": "specialAnimationLayer",
                                        },
                                        {
                                            "id": "graphic_RTP",
                                            "name": "graphic_RTP",
                                            "type": "Graphic",
                                            "shape": "rectangle",
                                            "color": "0x000000",
                                            "alpha": 0.75,
                                            "x": 1760,
                                            "y": -25,
                                            "width": 160,
                                            "height": 30,
                                            "visible": false,
                                            "scaleToFit": true,
                                        },
                                        {
                                            "id": "game_rtp_text",
                                            "name": "game_rtp_text",
                                            "type": "Text",
                                            "x": 1764,
                                            "y": -10,
                                            "width": 100,
                                            "visible": true,
                                            "text": "gameGuideText2_7",
                                            "scaleToFit": true,
                                            "anchor": [0, 0.5],
                                            "textStyle": {
                                                fontFamily: 'Arial',
                                                fontSize: 24,
                                                fontStyle: 'bold',
                                                fill: ['#FFFFFF'],
                                            },
                                            "parentLayer": "specialAnimationLayer",
                                        },
                                        {
                                            "id": "game_rtp",
                                            "name": "game_rtp",
                                            "type": "Text",
                                            "x": 1870,
                                            "y": -10,
                                            "width": 100,
                                            "visible": false,
                                            "text": "0.00",
                                            "scaleToFit": true,
                                            "anchor": [0.5, 0.5],
                                            "textStyle": {
                                                fontFamily: 'Arial',
                                                fontSize: 24,
                                                fontStyle: 'bold',
                                                fill: ['#FFFFFF'],
                                            },
                                            "parentLayer": "specialAnimationLayer",
                                        },
                                        
                                        {
                                            "id": "textOfContainer1_2",
                                            "name": "text_colonSymbol1",
                                            "type": "Text",
                                            "x": 1470,
                                            "y": -2,
                                            "width": 12,
                                            "visible": false,
                                            "text": "buttonPanelText_19",
                                            "scaleToFit": true,
                                            "anchor": [0.5, 0.5],
                                            "textStyle": {
                                                fontFamily: 'Arial',
                                                fontSize: 22,
                                                fontWeight: 'normal',
                                                fill: ['#ffffff'],
                                            },
                                            "parentLayer": "specialAnimationLayer",
                                        }
                                    ]

                                },
                            ]
                        },
                        {
                            "name": "baseGameBlackScreen",
                            "type": "Graphic",
                            "shape": "rectangle",
                            "visible": false,
                            "alpha": 1,
                            "color": "0x000000",
                            "x": 0,
                            "y": 0,
                            "width": 1920,
                            "height": 1080,
                        },
                        {
                            "name": "baseGameBlackScreenPortrait",
                            "type": "Graphic",
                            "shape": "rectangle",
                            "visible": false,
                            "alpha": 1,
                            "color": "0x000000",
                            "x": 0,
                            "y": 0,
                            "width": 1080,
                            "height": 1920,
                        },
                        {
                            id: "container_rightInfo",
                            "name": "rightInfoContainer",
                            "type": "Container",
                            "class": "",
                            "visible": true,
                            "uimode": "desktop",
                            "x": 986,
                            "y": 1022,
                            "width": 934,
                            "height": 58,
                            "filterTypes": [],
                            child: [
                                {
                                    id: "container_rightInfo1",
                                    "name": "rightInfoContainer1",
                                    "type": "Container",
                                    "class": "",
                                    "visible": true,
                                    "messageInLoop": true,
                                    "x": 0,
                                    "y": 0,
                                    "width": 934,
                                    "height": 58,
                                    "filterTypes": [],
                                    child: [
                                        // WIN Text Desktop
                                        {
                                            "id": "textOfContainer2_1",
                                            "name": "text_Win_label_desktop",
                                            "type": "Text",
                                            "x": -51.5,
                                            "y": 3.5,
                                            "width": 210,
                                            "visible": true,
                                            "text": "buttonPanelText_5",
                                            "scaleToFit": true,
                                            "anchor": [1, 1.5],
                                            "textStyle": {
                                                fontFamily: 'MYP Bold',
                                                fontSize: 30,
                                                fontWeight: 'bold',
                                                fill: ['#f2ac31'],
                                            },
                                            "parentLayer": "specialAnimationLayer",
                                        },
                                        // WIN VALUE Desktop
                                        {
                                            "id": "textOfContainer2_3",
                                            "name": "text_Win_value_desktop",
                                            "type": "Text",
                                            "x": -35,
                                            "y": -33,
                                            "width": 1000,
                                            "visible": true,
                                            "text": "0.00",
                                            "scaleToFit": true,
                                            "anchor": [0, 0.5],
                                            "textStyle": {
                                                fontFamily: 'MYP Bold',
                                                fontSize: 30,
                                                fontWeight: 'bold',
                                                fill: ['#ffffff'],
                                            },
                                            "parentLayer": "specialAnimationLayer",
                                        },
                                        // CREDIT Text Desktop
                                        {
                                            "id": "textOfContainer2_4",
                                            "name": "text_Balance_label",
                                            "type": "Text",
                                            "x": -492.5,
                                            "y": -30,
                                            "width": 310,
                                            "visible": true,
                                            "text": "buttonPanelText_3",
                                            "scaleToFit": true,
                                            "anchor": [1, 0.5],
                                            "textStyle": {
                                                fontFamily: 'MYP Bold',
                                                fontSize: 30,
                                                fontWeight: 'bold',
                                                fill: ['#f2ac31'],
                                            },
                                            "parentLayer": "specialAnimationLayer",
                                        },
                                        // CREDIT AMOUNT Desktop
                                        {
                                            "id": "textOfContainer2_6",
                                            "name": "text_Balance_value_withSign",
                                            "type": "Text",
                                            "x": -477,
                                            "y": -30,
                                            "width": 200,
                                            "visible": true,
                                            "text": "buttonPanelText_16",
                                            "scaleToFit": true,
                                            "anchor": [0, 0.5],
                                            "textStyle": {
                                                fontFamily: 'MYP Bold',
                                                fontSize: 30,
                                                fontWeight: 'bold',
                                                fill: ['#ffffff'],
                                            },
                                            "parentLayer": "specialAnimationLayer",
                                        },
                                        // BET Text Desktop
                                        {
                                            "id": "textOfContainer1_1",
                                            "name": "text_bet_label",
                                            "type": "Text",
                                            "x": 332,
                                            "y": -26.5,
                                            "width": 200,
                                            "visible": true,
                                            "text": "buttonPanelText_1",
                                            "scaleToFit": true,
                                            "textStyle": {
                                                fontFamily: 'MYP Bold',
                                                fontSize: 30,
                                                fontStyle: 'bold',
                                                fill: ['#f2ac31'],
                                            },
                                            "parentLayer": "specialAnimationLayer",
                                        },
                                        // Bet Value Desktop
                                        {
                                            "id": "textOfContainer1_3",
                                            "name": "text_bet_value",
                                            "type": "Text",
                                            "x": 454.5,
                                            "y": -26.5,
                                            "width": 200,
                                            "visible": true,
                                            "text": "abcdef",
                                            "scaleToFit": true,
                                            "anchor": [0.5, 0.5],
                                            "textStyle": {
                                                fontFamily: 'MYP Bold',
                                                fontSize: 30,
                                                fontStyle: 'bold',
                                                fill: ['#ffffff'],
                                            },
                                            "parentLayer": "specialAnimationLayer",
                                        },
                                    ]
                                    
                                },
                            ]
                        },
//--------------------------------------------------------------    
                        {
                            id: "container_leftInfo",
                            "name": "leftInfoContainer",
                            "type": "Container",
                            "class": "",
                            "visible": true,
                            "layout": true,
                            "uimode": "mobile",
                            "x": 0,
                            "y": 1022,
                            "width": 934,
                            "height": 58,
                            "filterTypes": [],
                            child: [
                                {
                                    id: "container_leftInfo1",
                                    "name": "leftInfoContainer1",
                                    "type": "Container",
                                    "class": "",
                                    "visible": true,
                                    "messageInLoop": true,
                                    "x": 0,
                                    "y": 0,
                                    "width": 934,
                                    "height": 58,
                                    "filterTypes": [],
                                    child: [
                                         // WIN Text Mobile
                                        {
                                            "id": "textOfContainer2_1",
                                            "name": "text_Win_label_mobile",
                                            "type": "Text",
                                            "x": 0,
                                            "y": 0,
                                            "width": 300,
                                            "visible": true,
                                            "layout": true,
                                            "text": "buttonPanelText_5",
                                            "scaleToFit": true,
                                            "anchor": [1, 0.5],
                                            "textStyle": {
                                                fontFamily: 'MYP Bold',
                                                fontSize: 36,
                                                fontWeight: 'bold',
                                                fill: ['#f2ac31'],
                                            },
                                            "parentLayer": "specialAnimationLayer",
                                        },
                                         // WIN VALUE Mobile
                                        {
                                            "id": "textOfContainer2_3",
                                            "name": "text_Win_value_mobile",
                                            "type": "Text",
                                            "x": 0,
                                            "y": 0,
                                            "width": 200,
                                            "visible": true,
                                            "text": "abcdefg",
                                            "scaleToFit": true,
                                            "anchor": [0.5, 0.5],
                                            "textStyle": {
                                                fontFamily: 'MYP Bold',
                                                fontSize: 36,
                                                fontWeight: 'bold',
                                                fill: ['#ffffff'],
                                            },
                                            "parentLayer": "specialAnimationLayer",
                                        },
                                        // CREDIT Text Mobile
                                        {
                                            "id": "textOfContainer2_4",
                                            "name": "text_Balance_label",
                                            "type": "Text",
                                            "x": 0,
                                            "y": 0,
                                            "width": 310,
                                            "visible": true,
                                            "text": "buttonPanelText_3",
                                            "scaleToFit": true,
                                            "anchor": [1, 0.5],
                                            "textStyle": {
                                                fontFamily: 'MYP Bold',
                                                fontSize: 36,
                                                fontWeight: 'bold',
                                                fill: ['#f2ac31'],
                                            },
                                            "parentLayer": "specialAnimationLayer",
                                        },                        
                                        // CREDIT AMOUNT Mobile
                                        {
                                            "id": "textOfContainer2_6",
                                            "name": "text_Balance_value_withSign",
                                            "type": "Text",
                                            "x": 0,
                                            "y": 0,
                                            "width": 200,
                                            "visible": true,
                                            "text": "buttonPanelText_16",
                                            "scaleToFit": true,
                                            "anchor": [0, 0.5],
                                            "textStyle": {
                                                fontFamily: 'MYP Bold',
                                                fontSize: 36,
                                                fontWeight: 'bold',
                                                fill: ['#ffffff'],
                                            },
                                            "parentLayer": "specialAnimationLayer",
                                        },
                                        // BET Text Mobile
                                        {
                                            "id": "textOfContainer1_1",
                                            "name": "text_bet_label",
                                            "type": "Text",
                                            "x": 0,
                                            "y": 0,
                                            "width": 200,
                                            "visible": true,
                                            "text": "buttonPanelText_1",
                                            "scaleToFit": true,
                                            "textStyle": {
                                                fontFamily: 'MYP Bold',
                                                fontSize: 36,
                                                fontWeight: 'bold',
                                                fill: ['#f2ac31'],
                                            },
                                            "parentLayer": "specialAnimationLayer",
                                        },
                                        // Bet Value Mobile
                                        {
                                            "id": "textOfContainer1_3",
                                            "name": "text_bet_value",
                                            "type": "Text",
                                            "x": 0,
                                            "y": 0,
                                            "width": 200,
                                            "visible": true,
                                            "text": "abcdef",
                                            "scaleToFit": true,
                                            "anchor": [0.5, 0.5],
                                            "textStyle": {
                                                fontFamily: 'MYP Bold',
                                                fontSize: 36,
                                                fontWeight: 'bold',
                                                fill: ['#ffffff'],
                                            },
                                            "parentLayer": "specialAnimationLayer",
                                        },
                                        {
                                            "id": "game_clock_m",
                                            "name": "game_clock_m",
                                            "type": "Text",
                                            "x": 96,
                                            "y": -972,
                                            "width": 350,
                                            "visible": false,
                                            "text": "10:50",
                                            "scaleToFit": true,
                                            "anchor": [0.5, 0.5],
                                            "textStyle": {
                                                fontFamily: 'Arial',
                                                fontSize: 38,
                                                fontStyle: 'bold',
                                                fill: ['#FFFFFF'],
                                            },
                                            "parentLayer": "specialAnimationLayer",
                                        },
                                        {
                                            "id": "game_clock_m",
                                            "name": "game_clock_m_portrait",
                                            "type": "Text",
                                            "x": 300,
                                            "y": -972,
                                            "width": 350,
                                            "visible": false,
                                            "text": "10:50",
                                            "scaleToFit": true,
                                            "anchor": [0.5, 0.5],
                                            "textStyle": {
                                                fontFamily: 'Arial',
                                                fontSize: 38,
                                                fontStyle: 'bold',
                                                fill: ['#FFFFFF'],
                                            },
                                            "parentLayer": "specialAnimationLayer",
                                        },
                                        {
                                            "id": "graphic_RTP_mobile",
                                            "name": "graphic_RTP_mobile",
                                            "type": "Graphic",
                                            "uiMode": "mobile",
                                            "shape": "rectangle",
                                            "color": "0x000000",
                                            "alpha": 0.75,
                                            "x": 1720,
                                            "y": -43,
                                            "width": 180,
                                            "height": 30,
                                            "visible": false,
                                            "scaleToFit": true,
                                        },
                                        {
                                            "id": "game_rtp_m_text",
                                            "name": "game_rtp_m_text",
                                            "type": "Text",
                                            "x": 1725,
                                            "y": -28,
                                            "width": 400,
                                            "visible": false,
                                            "text": "gameGuideText2_7",
                                            "scaleToFit": true,
                                            "anchor": [0, 0.5],
                                            "textStyle": {
                                                fontFamily: 'Arial',
                                                fontSize: 28,
                                                fontStyle: 'bold',
                                                fill: ['#FFFFFF'],
                                            },
                                            "parentLayer": "specialAnimationLayer",
                                        },
                                        {
                                            "id": "game_rtp_m",
                                            "name": "game_rtp_m",
                                            "type": "Text",
                                            "x": 1852,
                                            "y": -28,
                                            "width": 400,
                                            "visible": false,
                                            "text": "0.00",
                                            "scaleToFit": true,
                                            "anchor": [0.5, 0.5],
                                            "textStyle": {
                                                fontFamily: 'Arial',
                                                fontSize: 28,
                                                fontStyle: 'bold',
                                                fill: ['#FFFFFF'],
                                            },
                                            "parentLayer": "specialAnimationLayer",
                                        },
                                        {
                                            "id": "graphic_RTP_portrait",
                                            "name": "graphic_RTP_portrait",
                                            "type": "Graphic",
                                            "uiMode": "mobile",
                                            "shape": "rectangle",
                                            "color": "0x000000",
                                            "alpha": 0.75,
                                            "x": 1108,
                                            "y": 632,
                                            "width": 180,
                                            "height": 30,
                                            "visible": false,
                                            "scaleToFit": true,
                                        },
                                        {
                                            "id": "game_rtp_m_text_portrait",
                                            "name": "game_rtp_m_text_portrait",
                                            "type": "Text",
                                            "x": 1115,
                                            "y": 647,
                                            "width": 400,
                                            "visible": false,
                                            "text": "gameGuideText2_7",
                                            "scaleToFit": true,
                                            "anchor": [0, 0.5],
                                            "textStyle": {
                                                fontFamily: 'Arial',
                                                fontSize: 28,
                                                fontStyle: 'bold',
                                                fill: ['#FFFFFF'],
                                            },
                                            "parentLayer": "specialAnimationLayer",
                                        },
                                        {
                                            "id": "game_rtp_m_portrait",
                                            "name": "game_rtp_m_portrait",
                                            "type": "Text",
                                            "x": 1242,
                                            "y": 647,
                                            "width": 400,
                                            "visible": false,
                                            "text": "0.00",
                                            "scaleToFit": true,
                                            "anchor": [0.5, 0.5],
                                            "textStyle": {
                                                fontFamily: 'Arial',
                                                fontSize: 28,
                                                fontStyle: 'bold',
                                                fill: ['#FFFFFF'],
                                            },
                                            "parentLayer": "specialAnimationLayer",
                                        },
                                        {
                                            "id": "MaxWinOdd_text_landscape",
                                            "name": "MaxWinOdd_text_landscape",
                                            "type": "Container",
                                            "class": "",
                                            "visible": true,
                                            "uimode": "mobile",
                                            "x": -270,
                                            "y": 3,
                                            "width": 1500,
                                            "height": 250,
                                            "filterTypes": [],
                                            child: [
                                                {
                                                    "id": "graphic_maxodd_mobile",
                                                    "name": "graphic_maxodd_mobile",
                                                    "type": "Graphic",
                                                    "shape": "rectangle",
                                                    "color": "0x000000",
                                                    "alpha": 0.75,
                                                    "x": 30,
                                                    "y": -42,
                                                    "width": 680,
                                                    "height": 30,
                                                    "visible": false,
                                                    "scaleToFit": true,
                                                },
                                                {
                                                    "id": "setMaxWinOdd_m",
                                                    "name": "setMaxWinOdd_m",
                                                    "type": "Text",
                                                    "x": 576,
                                                    "y": -29,
                                                    "width": 1500,
                                                    "visible": false,
                                                    "text": "maxWinOdds",
                                                    "scaleToFit": true,
                                                    "anchor": [1, 0.5],
                                                    "textStyle": {
                                                        fontFamily: 'Arial',
                                                        fontSize: 28,
                                                        fontStyle: 'bold',
                                                        fill: ['#FFFFFF'],
                                                    },
                                                    "parentLayer": "specialAnimationLayer",
                                                },
                                                {
                                                    "id": "setMaxWinOdd_m2",
                                                    "name": "setMaxWinOdd_m2",
                                                    "type": "Text",
                                                    "x": 578,
                                                    "y": -28,
                                                    "width": 1500,
                                                    "visible": false,
                                                    "text": "maxWinOdds",
                                                    "scaleToFit": true,
                                                    "anchor": [0, 0.5],
                                                    "textStyle": {
                                                        fontFamily: 'Arial',
                                                        fontStyle: 'bold',
                                                        fontSize: 28,
                                                        fill: ['#FFFFFF'],
                                                    },
                                                    "parentLayer": "specialAnimationLayer",
                                                },
                                            ],
                                        },
                                        {
                                            "id": "MaxWinOdd_text_portrait",
                                            "name": "MaxWinOdd_text_portrait",
                                            "type": "Container",
                                            "class": "",
                                            "visible": true,
                                            "uimode": "mobile",
                                            "x": 5,
                                            "y": 3,
                                            "width": 1500,
                                            "height": 250,
                                            "filterTypes": [],
                                            child: [
                                                {
                                                    "id": "graphic_maxodd_portrait",
                                                    "name": "graphic_maxodd_portrait",
                                                    "type": "Graphic",
                                                    "shape": "rectangle",
                                                    "color": "0x000000",
                                                    "alpha": 0.75,
                                                    "x": 0,
                                                    "y": 630,
                                                    "width": 668,
                                                    "height": 30,
                                                    "visible": false,
                                                    "scaleToFit": true,
                                                },
                                                {
                                                    "id": "setMaxWinOdd_portrait",
                                                    "name": "setMaxWinOdd_portrait",
                                                    "type": "Text",
                                                    "x": 538,
                                                    "y": 645,
                                                    "width": 1500,
                                                    "visible": false,
                                                    "text": "maxWinOdds",
                                                    "scaleToFit": true,
                                                    "anchor": [1, 0.5],
                                                    "textStyle": {
                                                        fontFamily: 'Arial',
                                                        fontSize: 28,
                                                        fontStyle: 'bold',
                                                        fill: ['#FFFFFF'],
                                                    },
                                                    "parentLayer": "specialAnimationLayer",
                                                },

                                                {
                                                    "id": "setMaxWinOdd_m2_portrait",
                                                    "name": "setMaxWinOdd_m2_portrait",
                                                    "type": "Text",
                                                    "x": 539,
                                                    "y": 645,
                                                    "width": 1500,
                                                    "visible": false,
                                                    "text": "maxWinOdds",
                                                    "scaleToFit": true,
                                                    "anchor": [0, 0.5],
                                                    "textStyle": {
                                                        fontFamily: 'Arial',
                                                        fontStyle: 'bold',
                                                        fontSize: 28,
                                                        fill: ['#FFFFFF'],
                                                    },
                                                    "parentLayer": "specialAnimationLayer",
                                                },
                                            ]
                                        },
                                    ]
                                },
                            ]
                        },
                    ]
                },
                {
                    "name": "BuyFeature",
                    "type": "Tag",
                    child: []
                },
            ]
        }
    ]
}
