import { frameworkLayouts } from "@bonanzainteractive/core";

frameworkLayouts.data = {
  layouts: [
    {
      name: "mobile_settingHeading",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: true,
      x: 940,
      y: 500,
    },
    {
      name: "mobile_settingHeading",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: true,
      x: 980,
      y: 700,
    },

    {
      name: "realityCheckContainer_mobile",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: true,
      x: 0,
      y: 400,
    },
    {
      name: "realityCheckContainer_mobile",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: true,
      x: -480,
      y: 690,
    },
    {
      name: "noInternetPopUpContainerMobile",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: true,
      x: 0,
      y: 0,
    },
    {
      name: "noInternetPopUpContainerMobile",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: true,
      x: -480,
      y: 250,
    },

    {
      name: "leftInfoContainer",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: true,
      x: 0,
      y: 1022,
    },
    {
      name: "leftInfoContainer",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: true,
      x: -231,
      y: 1052,
    },

    //****************************************************************************** //
    {
      name: "bottomSpritLineMobile",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: true,
      x: 0,
      y: 443,
    },
    {
      name: "bottomSpritLineMobile",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: true,
      x: 0,
      y: 600,
    },


    {
      name: "mobile_turboSpinText",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: true,
      x: 1030,
      y: 746,
    },
    {
      name: "mobile_turboSpinText",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: true,
      x: 955,
      y: 1060,
    },
    {
      name: "mobile_turboSpinRadioButtonOff",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: true,
      x: 534,
      y: 758,
    },
    {
      name: "mobile_turboSpinRadioButtonOff",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: true,
      x: 534,
      y: 1060,
    },
    {
      name: "mobile_turboSpinRadioButtonOn",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: true,
      x: 530,
      y: 758,
    },
    {
      name: "mobile_turboSpinRadioButtonOn",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: true,
      x: 530,
      y: 1060,
    },
    {
      name: "showIntroScreenRadioButtonMobileOn",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: true,
      x: 460,
      y: 657,
    },
    {
      name: "showIntroScreenRadioButtonMobileOn",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: true,
      x: 460,
      y: 944,
    },
    {
      name: "musicRadioButtonMobileOn",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: true,
      x: 536,
      y: 603,
    },
    {
      name: "musicRadioButtonMobileOn",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: true,
      x: 535,
      y: 877,
    },

    {
      name: "musicRadioButtonMobileOff",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: true,
      x: 536,
      y: 603,
    },
    {
      name: "musicRadioButtonMobileOff",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: true,
      x: 535,
      y: 877,
    },

    {
      name: "showIntroScreenRadioButtonMobileOff",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: true,
      x: 460,
      y: 657,
    },
    {
      name: "showIntroScreenRadioButtonMobileOff",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: true,
      x: 460,
      y: 944,
    },
    {
      name: "showIntroScreenTextMobile",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: true,
      x: 1030,
      y: 676,
    },
    {
      name: "showIntroScreenTextMobile",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: true,
      x: 955,
      y: 959,
    },
    {
      name: "musicTextMobile",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: true,
      x: 1030,
      y: 606,
    },
    {
      name: "musicTextMobile",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: true,
      x: 955,
      y: 864,
    },

    //****************************************************************************** //
    {
      name: "mobileSettingPanelBottomSpriteLineBar1",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: true,
      x: 400,
      y: 880,
    },
    {
      name: "mobileSettingPanelBottomSpriteLineBar1",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: true,
      x: 195,
      y: 1780,
    },
    {
      name: "mobileSettingPanelBottomSpriteLineBar2",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: true,
      x: 780,
      y: 880,
    },
    {
      name: "mobileSettingPanelBottomSpriteLineBar2",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: true,
      x: 430,
      y: 1780,
    },
    {
      name: "mobileSettingPanelBottomSpriteLineBar3",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: true,
      x: 1120,
      y: 880,
    },
    {
      name: "mobileSettingPanelBottomSpriteLineBar3",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: true,
      x: 650,
      y: 1780,
    },
    {
      name: "mobileSettingPanelBottomSpriteLineBar4",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: true,
      x: 1500,
      y: 880,
    },
    {
      name: "mobileSettingPanelBottomSpriteLineBar4",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: true,
      x: 870,
      y: 1780,
    },
    {
      name: "autoplayHeading_mobile",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: false,
      x: 970,
      y: 91,
    },
    {
      name: "autoplayHeading_mobile",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: false,
      x: 555,
      y: 91,
    },
    {
      name: "betHeading_mobile",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: false,
      x: 970,
      y: 91,
    },
    {
      name: "betHeading_mobile",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: false,
      x: 555,
      y: 91,
    },
    {
      name: "GameGuideHeading_mobile",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: false,
      x: 970,
      y: 91,
    },
    {
      name: "GameGuideHeading_mobile",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: false,
      x: 555,
      y: 91,
    },
    {
      name: "payTableHeading_mobile",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: false,
      x: 970,
      y: 91,
    },
    {
      name: "payTableHeading_mobile",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: false,
      x: 555,
      y: 91,
    },
    {
      name: "mobileSettingPanelTopSpriteLine",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: true,
      x: 0,
      y: 155,
    },
    {
      name: "mobileSettingPanelTopSpriteLine",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: true,
      x: 0,
      y: 191,
    },
    {
      name: "mobileSettingPanelBottomSprite",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: true,
      x: 958,
      y: 937,
    },
    {
      name: "mobileSettingPanelBottomSprite",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: true,
      x: 126,
      y: 1848,
    },

    {
      name: "mobileSettingPanelBg",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: true,
      x: 0,
      y: 0,
    },
    {
      name: "mobileSettingPanelBg",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: true,
      x: 0,
      y: 0,
    },
    {
      name: "image_basegame-bg1",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: true,
      x: 0,
      y: 0,
    },
    {
      name: "image_cloud_a_mobile",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: true,
      x: -46,
      y: 0,
    },
    {
      name: "image_cloud_b_mobile",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: true,
      x: 1065,
      y: 0,
    },
    {
      name: "image_basegameSky-bg_mobile",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: true,
      x: 0,
      y: 0,
    },

    {
      name: "image_freegame-fg1",
      screenMode: "Landscape",
      uiMode: "mobile",
      x: 0,
      y: 0,
    },
    {
      name: "image_freegameTop-fg_mobile",
      screenMode: "Landscape",
      uiMode: "mobile",
      x: 0,
      y: 0,
    },
    {
      name: "mobileViewBottomBArImage1",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: true,
      x: 0,
      y: 872,
    },
    {
      name: "mobileViewBottomBArImage1",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: true,
      x: 0,
      y: 1790,
    },

    {
      name: "mobileViewBottomBArImage2",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: true,
      x: 0,
      y: 1010,
    },
    {
      name: "mobileViewBottomBArImage2",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: true,
      x: 0,
      y: 1720,
    },
    {
      name: "betContent",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: true,
      x: 37,
      y: 40,
    },
    {
      name: "betContent",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: true,
      x: -202,
      y: 215,
    },
    {
      name: "Bet_Container1Mobile",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: false,
      x: 0,
      y: 0,
    },
    {
      name: "Bet_Container1Mobile",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: false,
      x: -493,
      y: 76,
    },

    {
      id: "Button_M4",
      name: "btn_autoplay",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: true,
      x: 1760,
      y: 890,
    },
    {
      id: "Button_M4",
      name: "btn_autoplay",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: true,
      x: 920,
      y: 1820,
    },
    {
      name: "BG_gameLogo_Anim_mobile",
      uiMode: "mobile",
      screenMode: "Landscape",
      visible: true,
      x: 128.5,
      y: 186.5,
    },
    {
      name: "FG_gameLogo_Anim_mobile",
      uiMode: "mobile",
      screenMode: "Landscape",
      visible: true,
      x: 118.5,
      y: 186.5,
    },
    {
      name: "FG_gameLogo_Anim_mobile",
      uiMode: "mobile",
      screenMode: "Portrait",
      visible: true,
      x: 538.5,
      y: 176.5,
    },
    {
      name: "BG_gameLogo_Anim_mobile",
      uiMode: "mobile",
      screenMode: "Portrait",
      visible: true,
      x: 538.5,
      y: 176.5,
    },
    {
      name: "BG_reelOfFrame_Image_Mobile",
      uiMode: "mobile",
      screenMode: "Landscape",
      visible: true,
      x: 959.5,
      y: 502.5,
    },
    {
      name: "BG_reelOfFrame_Image_Mobile",
      uiMode: "mobile",
      screenMode: "Portrait",
      visible: true,
      x: 545,
      y: 772,
    },
    {
      name: "btn_autoplay",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: true,
      x: 1760,
      y: 890,
    },
    {
      name: "btn_autoplay",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: true,
      x: 920,
      y: 1820,
    },
    {
      name: "btn_autoplayFG",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: true,
      x: 1760,
      y: 890,
    },
    {
      name: "btn_autoplayFG",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: true,
      x: 920,
      y: 1750,
    },

    {
      name: "mobileViewBottomBArImage1FG",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: true,
      x: 0,
      y: 860,
    },
    {
      name: "mobileViewBottomBArImage1FG",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: true,
      x: 0,
      y: 1710,
    },
    {
      name: "mobileViewBottomBArImage2FG",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: true,
      x: 0,
      y: 1010,
    },
    {
      name: "mobileViewBottomBArImage2FG",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: true,
      x: 0,
      y: 1850,
    },

    {
      name: "text_FreeGame_OF_label_mobileFG",
      uiMode: "mobile",
      screenMode: "Landscape",
      visible: false,
      x: 810,
      y: 940,
    },
    {
      name: "text_FreeGame_OF_label_mobileFG",
      uiMode: "mobile",
      screenMode: "Portrait",
      visible: false,
      x: 547,
      y: 1806,
    },

    {
      name: "text_FreeGame_value2_mobileFG",
      uiMode: "mobile",
      screenMode: "Landscape",
      visible: false,
      x: 1090,
      y: 940,
    },
    {
      name: "text_FreeGame_value2_mobileFG",
      uiMode: "mobile",
      screenMode: "Portrait",
      visible: false,
      x: 650,
      y: 1806,
    },

    {
      name: "mobileViewBottomBArLineImageFG_1",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: true,
      x: 270,
      y: 872,
    },
    {
      name: "mobileViewBottomBArLineImageFG_1",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: true,
      x: 210,
      y: 1736,
    },
    {
      name: "mobileViewBottomBArLineImageFG_2",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: true,
      x: 870,
      y: 1736,
    },

    {
      name: "mobileViewBottomBArLineImageFG_2",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: true,
      x: 940,
      y: 872,
    },
    {
      name: "Mobiletext_win_value_FG",
      screenMode: "Portrait",
      uiMode: "mobile",
      x: 630,
      y: 1640,
    },

    {
      name: "BG_manywaysText_mobile",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: true,
      x: 950,
      y: -152,
    },
    {
      name: "BG_manywaysText_mobile",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: true,
      x: 550,
      y: 158,
    },

    {
      name: "FG_manywaysText_mobile",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: true,
      x: 960,
      y: -154,
    },
    {
      name: "FG_manywaysText_mobile",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: true,
      x: 550,
      y: 162,
    },
    {
      name: "BG_textManyWays_Image_mobile",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: true,
      x: 598,
      y: 353,
    },
    {
      name: "text_WinCelebration_label_mobile",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: true,
      x: 940,
      y: 475,
    },
    {
      name: "text_WinCelebration_label_mobile",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: false,
      x: 551,
      y: 937,
    },
    {
      name: "text_WinCelebration_label_mobile_portrait",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: false,
      x: 940,
      y: 475,
    },
    {
      name: "text_WinCelebration_label_mobile_portrait",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: true,
      x: 551,
      y: 653,
    },
    {
      name: "bgSpine_mobile",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: true,
      x: 932,
      y: 550,
    },
    {
      name: "bgSpine_mobile",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: true,
      x: 550,
      y: 700,
    },
    {
      name: "amount_tickup_mobile",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: true,
      x: 960,
      y: 618,
    },
    {
      name: "amount_tickup_mobile",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: true,
      x: 534,
      y: 1150,
    },

    {
      name: "winShower_Container_mobile",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: true,
      x: 0,
      y: 0,
    },
    {
      name: "winShower_Container_mobile",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: true,
      x: -350,
      y: 460,
    },
    {
      name: "winCelebration_Container_mobile",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: true,
      x: 0,
      y: 0,
    },

    {
      name: "winCelebration_Container_mobile",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: true,
      x: -350,
      y: 440,
    },

    //outroBImage_mobile
    {
      name: "soundText_mobile",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: true,
      x: 0,
      y: 0,
    },
    {
      name: "soundText_mobile",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: true,
      x: -400,
      y: 500,
    },

    // voucherContainer_mobile
    {
      name: "voucherContainerMobile",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: true,
      x: 0,
      y: 0,
    },
    {
      name: "voucherContainerMobile",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: true,
      x: -425,
      y: 235,
    },
    {
      name: "voucherGraphic_4",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: false,
      x: 95,
      y: 533,
    },
    {
      name: "voucherGraphic_4",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: false,
      x: 95,
      y: 1200,
    },
    {
      name: "voucherText5",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: false,
      x: 138,
      y: 578,
    },
    {
      name: "voucherText5",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: false,
      x: 142,
      y: 1246,
    },
    //-----------------------------------------------------------------------------------------------------------

    {
      name: "postIntro_continueButton_mobile",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: true,
      x: 415,
      y: 1700,
    },
    {
      name: "postIntro_continueButton_mobile",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: true,
      x: 845,
      y: 940,
    },
    {
      name: "Text_Continue_mobile",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: true,
      x: 550,
      y: 1750,
    },
    {
      name: "Text_Continue_mobile",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: true,
      x: 980,
      y: 990,
    },
    {
      name: "basegame_landscape_bg",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: false,
      x: 960,
      y: 560,
    },
    {
      name: "basegame_bg",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: true,
      x: 540,
      y: 960,
    },
    {
      name: "basegame_landscape_bg",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: true,
      x: 960,
      y: 560,
    },
    {
      name: "basegame_bg",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: false,
      x: 540,
      y: 960,
    },

    {
      name: "BaseGameLogo",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: false,
      x: 0,
      y: 0,
    },
    {
      name: "BaseGameLogo",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: true,
      x: 2,
      y: -70,
    },
    {
      name: "BaseGameLogo_Portrait",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: true,
      x: 280,
      y: -640,
    },
    {
      name: "BaseGameLogo_Portrait",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: false,
      x: 0,
      y: 0,
    },

    {
      name: "BG_Reel_Outer_Frame_Landscape",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: false,
      x: 947,
      y: 500,
    },
    {
      name: "BG_Reel_Outer_Frame",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: true,
      x: 540,
      y: 871,
    },
    {
      name: "BG_Reel_Outer_Frame_Landscape",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: true,
      x: 952,
      y: 473,
    },
    {
      name: "BG_Reel_Outer_Frame",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: false,
      x: 118,
      y: 18,
    },
    {
      name: "BG_frame_Image_Mobile_Landscape",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: false,
      x: 947,
      y: 500,
    },
    {
      name: "frameReel_FG_Image_Mob",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: true,
      x: 322,
      y: 130,
    },
    {
      name: "frameReel_FG_Image_Mob",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: true,
      x: 7,
      y: 790.5,
    },
    {
      name: "BG_frame_Image_Mobile",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: true,
      x: 538,
      y: 1105,
    },
    {
      name: "BG_frame_Image_Mobile_Landscape",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: true,
      x: 958,
      y: 507,
    },
    {
      name: "BG_frame_Image_Mobile",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: false,
      x: 300,
      y: 500,
    },
     
    {
      name: "ui_base_landscape",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: true,
      x: 0,
      y: 940,
    },
    {
      name: "ui_base_landscape",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: false,
      x: 0,
      y: 1762,
    },
    {
      name: "ui_base",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: false,
      x: 70,
      y: 300,
    },
    {
      name: "ui_base",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: true,
      x: 0,
      y: 1762,
    },

    //---------------------------------------------------------------------------


    //NOTE - Intro & Outro Layout------------------------------------------------------

    {
      name: "intro_frame",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: true,
      x: 421,
      y: 110,
    },
    {
      name: "intro_frame",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: true,
      x: 0,
      y: 575,
    },
    {
      name: "text_3_intro_mobile",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: true,
      x: 949.5,
      y: 250,
    },
    {
      name: "text_3_intro_mobile",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: true,
      x: 533.5,
      y: 750,
    },
    {
      name: "text_2_intro_mobile",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: true,
      x: 958,
      y: 358,
    },
    {
      name: "text_2_intro_mobile",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: true,
      x: 533.5,
      y: 870,
    },
    {
      name: "btn_introBanner_mobile",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: true,
      x: 940,
      y: 748.5,
    },
    {
      name: "btn_introBanner_mobile",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: true,
      x: 530,
      y: 1200,
    },
    {
      name: "ContinueButton_mobile",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: true,
      x: 947,
      y: 731.1,
    },
    {
      name: "ContinueButton_mobile",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: true,
      x: 530,
      y: 1180,
    },
    {
      name: "text_freeSpinAward_mobile",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: true,
      x: 948,
      y: 641,
    },
    {
      name: "text_freeSpinAward_mobile",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: true,
      x: 533,
      y: 1104,
    },
    {
      name: "text_IntroScreenFG_mobile",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: true,
      x: 948,
      y: 504.5,
    },
    {
      name: "text_IntroScreenFG_mobile",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: true,
      x: 533,
      y: 992,
    },
    {
      name: "betterlucknext_mobile",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: true,
      x: 948,
      y: 239.5,
    },
    {
      name: "betterlucknext_mobile",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: true,
      x: 533.5,
      y: 852,
    },
    {
      name: "outroText1_mobile",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: true,
      x: 948,
      y: 280.5,
    },
    {
      name: "outroText1_mobile",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: true,
      x: 533.5,
      y: 750,
    },
    {
      name: "outroText2_mobile",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: true,
      x: 948,
      y: 388.5,
    },
    {
      name: "outroText2_mobile",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: true,
      x: 533.5,
      y: 865,
    },
    {
      name: "Wintext_Outro_mobile",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: true,
      x: 948,
      y: 546.5,
    },
    {
      name: "Wintext_Outro_mobile",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: true,
      x: 525,
      y: 1005
    },
    //---------------------------------------------------------------------------

    //NOTE - Freegame Layout ---------------------------------

    {
      name: "freegame_landscape_bg",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: false,
      x: 960,
      y: 720,
    },
    {
      name: "freegame_bg",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: true,
      x: 540,
      y: 960,
    },
    {
      name: "freegame_landscape_bg",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: true,
      x: 960,
      y: 720,
    },
    {
      name: "freegame_bg",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: false,
      x: 540,
      y: 960,
    },
    {
      name: "freegame_Background",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: false,
      x: 960,
      y: 540,
    },
    {
      name: "freegame_Background",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: true,
      x: 960,
      y: 545,
    },

    {
      name: "FreeGameLogo",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: true,
      x: 0,
      y: -80,
    },
    {
      name: "FreeGameLogo",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: false,
      x: 0,
      y: 0,
    },

    {
      name: "FreeGameLogo_Portrait",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: true,
      x: 280,
      y: -640,
    },

    {
      name: "FreeGameLogo_Portrait",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: false,
      x: 0,
      y: 0,
    },
    {
      name: "frame_FG_Image_Mob",
      uiMode: "mobile",
      screenMode: "Landscape",
      visible: true,
      x: 231,
      y: 0,
    },
    {
      name: "frame_FG_Image_Mob",
      uiMode: "mobile",
      screenMode: "Portrait",
      visible: true,
      x: -180,
      y: 396,
    },
    {
      name: "freeGameCounter",
      uiMode: "mobile",
      screenMode: "Landscape",
      visible: true,
      x: 378,
      y: 35,
    },
    {
      name: "freeGameCounter",
      uiMode: "mobile",
      screenMode: "Portrait",
      visible: true,
      x: 44,
      y: 346,
    },
    {
      name: "featureCountMeter",
      uiMode: "mobile",
      screenMode: "Landscape",
      visible: true,
      x: 1200,
      y: 35,
    },
    {
      name: "featureCountMeter",
      uiMode: "mobile",
      screenMode: "Portrait",
      visible: true,
      x: 770,
      y: 346,
    },
    {
      name: "freegame_ui_landscape",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: true,
      x: 0,
      y: 940,
    },
    {
      name: "freegame_ui_landscape",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: false,
      x: 0,
      y: 1762,
    },
    {
      name: "freegame_ui_base",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: false,
      x: 70,
      y: 300,
    },
    {
      name: "freegame_ui_base",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: true,
      x: 0,
      y: 1762,
    },
    {
      name: "currentCounter",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: true,
      x: 109,
      y: 386,
    },
    {
      name: "currentCounter",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: true,
      x: 443,
      y: 75,
    },
    {
      name: "slashText",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: true,
      x: 124,
      y: 386,
    },
    {
      name: "slashText",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: true,
      x: 457.5,
      y: 75,
    },
    {
      name: "totalCounter",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: true,
      x: 150,
      y: 386,
    },
    {
      name: "totalCounter",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: true,
      x: 480,
      y: 75,
    },
    {
      name: "collectedText",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: true,
      x: 227.8,
      y: 386,
    },
    {
      name: "collectedText",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: true,
      x: 558,
      y: 75,
    },
    {
      name: "text_FreeGame_value1",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: true,
      x: 837,
      y: 386,
    },
    {
      name: "text_FreeGame_value1",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: true,
      x: 1269,
      y: 75,
    },
    {
      name: "text_FreeGame_OF_label",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: true,
      x: 908,
      y: 386,
    },
    {
      name: "text_FreeGame_OF_label",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: true,
      x: 1337,
      y: 75,
    },
    {
      name: "text_FreeGame_value2",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: true,
      x: 978,
      y: 386,
    },
    {
      name: "text_FreeGame_value2",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: true,
      x: 1408,
      y: 75,
    },
    //SECTION - multiplier
    {
      name: "multiplierTopText",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: true,
      x: 325,
      y: 386,
    },
    {
      name: "multiplierTopText",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: true,
      x: 658,
      y: 72,
    },
    {
      name: "multiplierIncreaseAnim",
      screenMode: "Portrait",
      uiMode: "mobile",
      // visible: true,
      x: 325,
      y: 386,
    },
    {
      name: "multiplierIncreaseAnim",
      screenMode: "Landscape",
      uiMode: "mobile",
      // visible: true,
      x: 658,
      y: 72,
    },
    {
      name: "multiplierIncreaseAnimButterFly",
      screenMode: "Portrait",
      uiMode: "mobile",
      // visible: true,
      x: 325,
      y: 386,
    },
    {
      name: "multiplierIncreaseAnimButterFly",
      screenMode: "Landscape",
      uiMode: "mobile",
      // visible: true,
      x: 658,
      y: 72,
    },
    {
      name: "multiplierIncreaseText",
      screenMode: "Portrait",
      uiMode: "mobile",
      // visible: true,
      x: 540.5,
      y: 955,
    },
    {
      name: "multiplierIncreaseText",
      screenMode: "Landscape",
      uiMode: "mobile",
      // visible: true,
      x: 960.5,
      y: 549,
    },
    {
      name: "text_FreeGame_levelUp",
      screenMode: "Portrait",
      uiMode: "mobile",
      // visible: true,
      x: 540.5,
      y: 955,
    },
    {
      name: "text_FreeGame_levelUp",
      screenMode: "Landscape",
      uiMode: "mobile",
      // visible: true,
      x: 949.9,
      y: 550.1,
    },
    {
      name: "blast",
      screenMode: "Portrait",
      uiMode: "mobile",
      // visible: true,
      x: 529,
      y: 1106,
    },
    {
      name: "blast",
      screenMode: "Landscape",
      uiMode: "mobile",
      // visible: true,
      x: 950,
      y: 550,
    },
    //!SECTION

    //---------------------------------------------------------------------------
    //NOTE - Left Reveal Meter Layout ---------------------------------------------------------------------------

    {
      name: "meterSymbol_09",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: true,
      x: 1267,
      y: 168,
    },
    {
      name: "meterSymbol_09",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: true,
      x: 874,
      y: 566,
    },
    {
      name: "meterSymbol_08",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: true,
      x: 1189,
      y: 168,
    },
    {
      name: "meterSymbol_08",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: true,
      x: 794,
      y: 566,
    },
    {
      name: "meterSymbol_07",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: true,
      x: 1111,
      y: 168,
    },
    {
      name: "meterSymbol_07",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: true,
      x: 714,
      y: 566,
    },
    {
      name: "meterSymbol_06",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: true,
      x: 1033,
      y: 168,
    },
    {
      name: "meterSymbol_06",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: true,
      x: 634,
      y: 566,
    },
    {
      name: "meterSymbol_05",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: true,
      x: 955,
      y: 168,
    },
    {
      name: "meterSymbol_05",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: true,
      x: 554,
      y: 566,
    },
    {
      name: "meterSymbol_04",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: true,
      x: 877,
      y: 168,
    },
    {
      name: "meterSymbol_04",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: true,
      x: 474,
      y: 566,
    },
    {
      name: "meterSymbol_03",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: true,
      x: 799,
      y: 168,
    },
    {
      name: "meterSymbol_03",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: true,
      x: 394,
      y: 566,
    },
    {
      name: "meterSymbol_02",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: true,
      x: 721,
      y: 168,
    },
    {
      name: "meterSymbol_02",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: true,
      x: 314,
      y: 566,
    },
    {
      name: "meterSymbol_01",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: true,
      x: 643,
      y: 168,
    },
    {
      name: "meterSymbol_01",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: true,
      x: 234,
      y: 566,
    },
    {
      name: "meterSymbol_00",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: true,
      x: 565,
      y: 168,
    },
    {
      name: "meterSymbol_00",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: true,
      x: 154.5,
      y: 566,
    },
    //SECTION - Butterfly Symbol Layout below -----------

    {
      name: "meterButterfly_00_9",
      screenMode: "Landscape",
      uiMode: "mobile",
      // visible: true,
      x: 1247,
      y: 155,
    },
    {
      name: "meterButterfly_00_9",
      screenMode: "Portrait",
      uiMode: "mobile",
      // visible: true,
      x: 856,
      y: 552,
    },
    {
      name: "meterButterfly_00_8",
      screenMode: "Landscape",
      uiMode: "mobile",
      // visible: true,
      x: 1169,
      y: 155,
    },
    {
      name: "meterButterfly_00_8",
      screenMode: "Portrait",
      uiMode: "mobile",
      // visible: true,
      x: 775,
      y: 552,
    },
    {
      name: "meterButterfly_00_7",
      screenMode: "Landscape",
      uiMode: "mobile",
      // visible: true,
      x: 1091,
      y: 155,
    },
    {
      name: "meterButterfly_00_7",
      screenMode: "Portrait",
      uiMode: "mobile",
      // visible: true,
      x: 694,
      y: 552,
    },
    {
      name: "meterButterfly_00_6",
      screenMode: "Landscape",
      uiMode: "mobile",
      // visible: true,
      x: 1013,
      y: 155,
    },
    {
      name: "meterButterfly_00_6",
      screenMode: "Portrait",
      uiMode: "mobile",
      // visible: true,
      x: 613,
      y: 552,
    },
    {
      name: "meterButterfly_00_5",
      screenMode: "Landscape",
      uiMode: "mobile",
      // visible: true,
      x: 935,
      y: 155,
    },
    {
      name: "meterButterfly_00_5",
      screenMode: "Portrait",
      uiMode: "mobile",
      // visible: true,
      x: 532,
      y: 552,
    },
    {
      name: "meterButterfly_00_4",
      screenMode: "Landscape",
      uiMode: "mobile",
      // visible: true,
      x: 857,
      y: 155,
    },
    {
      name: "meterButterfly_00_4",
      screenMode: "Portrait",
      uiMode: "mobile",
      // visible: true,
      x: 451,
      y: 552,
    },
    {
      name: "meterButterfly_00_3",
      screenMode: "Landscape",
      uiMode: "mobile",
      // visible: true,
      x: 779,
      y: 155,
    },
    {
      name: "meterButterfly_00_3",
      screenMode: "Portrait",
      uiMode: "mobile",
      // visible: true,
      x: 370,
      y: 552,
    },
    {
      name: "meterButterfly_00_2",
      screenMode: "Landscape",
      uiMode: "mobile",
      // visible: true,
      x: 701,
      y: 155,
    },
    {
      name: "meterButterfly_00_2",
      screenMode: "Portrait",
      uiMode: "mobile",
      // visible: true,
      x: 289,
      y: 552,
    },
    {
      name: "meterButterfly_00_1",
      screenMode: "Landscape",
      uiMode: "mobile",
      // visible: true,
      x: 623,
      y: 155,
    },
    {
      name: "meterButterfly_00_1",
      screenMode: "Portrait",
      uiMode: "mobile",
      // visible: true,
      x: 208,
      y: 552,
    },
    {
      name: "meterButterfly_00_0",
      screenMode: "Landscape",
      uiMode: "mobile",
      // visible: true,
      x: 545,
      y: 155,
    },
    {
      name: "meterButterfly_00_0",
      screenMode: "Portrait",
      uiMode: "mobile",
      // visible: true,
      x: 127,
      y: 552,
    },
    //!SECTION
    //SECTION - animGlowMeter_09 -> animGlowMeter_00

    {
      name: "animGlowMeter_00",
      screenMode: "Landscape",
      uiMode: "mobile",
      // visible: true,
      x: 595,
      y: 195,
    },
    {
      name: "animGlowMeter_00",
      screenMode: "Portrait",
      uiMode: "mobile",
      // visible: true,
      x: 175,
      y: 590,
    },
    {
      name: "animGlowMeter_01",
      screenMode: "Landscape",
      uiMode: "mobile",
      // visible: true,
      x: 673,
      y: 195,
    },
    {
      name: "animGlowMeter_01",
      screenMode: "Portrait",
      uiMode: "mobile",
      // visible: true,
      x: 265,
      y: 590,
    },
    {
      name: "animGlowMeter_02",
      screenMode: "Landscape",
      uiMode: "mobile",
      // visible: true,
      x: 751,
      y: 195,
    },
    {
      name: "animGlowMeter_02",
      screenMode: "Portrait",
      uiMode: "mobile",
      // visible: true,
      x: 345,
      y: 590,
    },
    {
      name: "animGlowMeter_03",
      screenMode: "Landscape",
      uiMode: "mobile",
      // visible: true,
      x: 829,
      y: 195,
    },
    {
      name: "animGlowMeter_03",
      screenMode: "Portrait",
      uiMode: "mobile",
      // visible: true,
      x: 425,
      y: 590,
    },
    {
      name: "animGlowMeter_04",
      screenMode: "Landscape",
      uiMode: "mobile",
      // visible: true,
      x: 907,
      y: 195,
    },
    {
      name: "animGlowMeter_04",
      screenMode: "Portrait",
      uiMode: "mobile",
      // visible: true,
      x: 505,
      y: 590,
    },
    {
      name: "animGlowMeter_05",
      screenMode: "Landscape",
      uiMode: "mobile",
      // visible: true,
      x: 985,
      y: 195,
    },
    {
      name: "animGlowMeter_05",
      screenMode: "Portrait",
      uiMode: "mobile",
      // visible: true,
      x: 585,
      y: 590,
    },
    {
      name: "animGlowMeter_06",
      screenMode: "Landscape",
      uiMode: "mobile",
      // visible: true,
      x: 1063,
      y: 195,
    },
    {
      name: "animGlowMeter_06",
      screenMode: "Portrait",
      uiMode: "mobile",
      // visible: true,
      x: 665,
      y: 590,
    },
    {
      name: "animGlowMeter_07",
      screenMode: "Landscape",
      uiMode: "mobile",
      // visible: true,
      x: 1141,
      y: 195,
    },
    {
      name: "animGlowMeter_07",
      screenMode: "Portrait",
      uiMode: "mobile",
      // visible: true,
      x: 745,
      y: 590,
    },
    {
      name: "animGlowMeter_08",
      screenMode: "Landscape",
      uiMode: "mobile",
      // visible: true,
      x: 1219,
      y: 195,
    },
    {
      name: "animGlowMeter_08",
      screenMode: "Portrait",
      uiMode: "mobile",
      // visible: true,
      x: 825,
      y: 590,
    },
    {
      name: "animGlowMeter_09",
      screenMode: "Landscape",
      uiMode: "mobile",
      // visible: true,
      x: 1297,
      y: 195,
    },
    {
      name: "animGlowMeter_09",
      screenMode: "Portrait",
      uiMode: "mobile",
      // visible: true,
      x: 905,
      y: 590,
    },

    //!SECTION
    //SECTION - animMeterButterfly_09 -> animMeterButterfly_00

    {
      name: "animMeterButterfly_00",
      screenMode: "Landscape",
      uiMode: "mobile",
      // visible: true,
      x: 595,
      y: 195,
    },
    {
      name: "animMeterButterfly_00",
      screenMode: "Portrait",
      uiMode: "mobile",
      // visible: true,
      x: 175,
      y: 590,
    },
    {
      name: "animMeterButterfly_01",
      screenMode: "Landscape",
      uiMode: "mobile",
      // visible: true,
      x: 673,
      y: 195,
    },
    {
      name: "animMeterButterfly_01",
      screenMode: "Portrait",
      uiMode: "mobile",
      // visible: true,
      x: 265,
      y: 590,
    },
    {
      name: "animMeterButterfly_02",
      screenMode: "Landscape",
      uiMode: "mobile",
      // visible: true,
      x: 751,
      y: 195,
    },
    {
      name: "animMeterButterfly_02",
      screenMode: "Portrait",
      uiMode: "mobile",
      // visible: true,
      x: 345,
      y: 590,
    },
    {
      name: "animMeterButterfly_03",
      screenMode: "Landscape",
      uiMode: "mobile",
      // visible: true,
      x: 829,
      y: 195,
    },
    {
      name: "animMeterButterfly_03",
      screenMode: "Portrait",
      uiMode: "mobile",
      // visible: true,
      x: 425,
      y: 590,
    },
    {
      name: "animMeterButterfly_04",
      screenMode: "Landscape",
      uiMode: "mobile",
      // visible: true,
      x: 907,
      y: 195,
    },
    {
      name: "animMeterButterfly_04",
      screenMode: "Portrait",
      uiMode: "mobile",
      // visible: true,
      x: 505,
      y: 590,
    },
    {
      name: "animMeterButterfly_05",
      screenMode: "Landscape",
      uiMode: "mobile",
      // visible: true,
      x: 985,
      y: 195,
    },
    {
      name: "animMeterButterfly_05",
      screenMode: "Portrait",
      uiMode: "mobile",
      // visible: true,
      x: 585,
      y: 590,
    },
    {
      name: "animMeterButterfly_06",
      screenMode: "Landscape",
      uiMode: "mobile",
      // visible: true,
      x: 1063,
      y: 195,
    },
    {
      name: "animMeterButterfly_06",
      screenMode: "Portrait",
      uiMode: "mobile",
      // visible: true,
      x: 665,
      y: 590,
    },
    {
      name: "animMeterButterfly_07",
      screenMode: "Landscape",
      uiMode: "mobile",
      // visible: true,
      x: 1141,
      y: 195,
    },
    {
      name: "animMeterButterfly_07",
      screenMode: "Portrait",
      uiMode: "mobile",
      // visible: true,
      x: 745,
      y: 590,
    },
    {
      name: "animMeterButterfly_08",
      screenMode: "Landscape",
      uiMode: "mobile",
      // visible: true,
      x: 1219,
      y: 195,
    },
    {
      name: "animMeterButterfly_08",
      screenMode: "Portrait",
      uiMode: "mobile",
      // visible: true,
      x: 825,
      y: 590,
    },
    {
      name: "animMeterButterfly_09",
      screenMode: "Landscape",
      uiMode: "mobile",
      // visible: true,
      x: 1297,
      y: 195,
    },
    {
      name: "animMeterButterfly_09",
      screenMode: "Portrait",
      uiMode: "mobile",
      // visible: true,
      x: 905,
      y: 590,
    },

    //!SECTION



    //---------------------------------------------------------------------------
    //NOTE - BIG WIN LAYOUT ---------------------------------------------------------------------------

    {
      name: "collecter_bg_feature",
      screenMode: "Landscape",
      uiMode: "mobile",
      // visible: true,
      x: 950,
      y: 560,
    },
    {
      name: "collecter_bg_feature",
      screenMode: "Portrait",
      uiMode: "mobile",
      // visible: true,
      x: 540.5,
      y: 957.5,
    },

    //---------------------------------------------------------------------------
    //NOTE - GOLDEN COIN SYMBOL LAYOUT ---------------------------------------------------------------------------
    //SECTION - 00
    {
      name: "ani_coin0_0",
      screenMode: "Landscape",
      uiMode: "mobile",
      // visible: true,
      x: 522,
      y: 333,
    },
    {
      name: "ani_coin0_0",
      screenMode: "Portrait",
      uiMode: "mobile",
      // visible: true,
      x: 120,
      y: 738,
    },
    {
      name: "ani_coin0_1",
      screenMode: "Landscape",
      uiMode: "mobile",
      // visible: true,
      x: 522,
      y: 551,
    },
    {
      name: "ani_coin0_1",
      screenMode: "Portrait",
      uiMode: "mobile",
      // visible: true,
      x: 120,
      y: 947,
    },
    {
      name: "ani_coin0_2",
      screenMode: "Landscape",
      uiMode: "mobile",
      // visible: true,
      x: 522,
      y: 759,
    },
    {
      name: "ani_coin0_2",
      screenMode: "Portrait",
      uiMode: "mobile",
      // visible: true,
      x: 120,
      y: 1156,
    },
    // //SECTION - 10
    {
      name: "ani_coin1_0",
      screenMode: "Landscape",
      uiMode: "mobile",
      // visible: true,
      x: 738,
      y: 333,
    },
    {
      name: "ani_coin1_0",
      screenMode: "Portrait",
      uiMode: "mobile",
      // visible: true,
      x: 328,
      y: 738,
    },
    {
      name: "ani_coin1_1",
      screenMode: "Landscape",
      uiMode: "mobile",
      // visible: true,
      x: 738,
      y: 551,
    },
    {
      name: "ani_coin1_1",
      screenMode: "Portrait",
      uiMode: "mobile",
      // visible: true,
      x: 328,
      y: 947,
    },
    {
      name: "ani_coin1_2",
      screenMode: "Landscape",
      uiMode: "mobile",
      // visible: true,
      x: 738,
      y: 759,
    },
    {
      name: "ani_coin1_2",
      screenMode: "Portrait",
      uiMode: "mobile",
      // visible: true,
      x: 328,
      y: 1156,
    },
    //SECTION - 20
    {
      name: "ani_coin2_0",
      screenMode: "Landscape",
      uiMode: "mobile",
      // visible: true,
      x: 957,
      y: 333,
    },
    {
      name: "ani_coin2_0",
      screenMode: "Portrait",
      uiMode: "mobile",
      // visible: true,
      x: 535,
      y: 738,
    },
    {
      name: "ani_coin2_1",
      screenMode: "Landscape",
      uiMode: "mobile",
      // visible: true,
      x: 957,
      y: 551,
    },
    {
      name: "ani_coin2_1",
      screenMode: "Portrait",
      uiMode: "mobile",
      // visible: true,
      x: 535,
      y: 947,
    },
    {
      name: "ani_coin2_2",
      screenMode: "Landscape",
      uiMode: "mobile",
      // visible: true,
      x: 957,
      y: 759,
    },
    {
      name: "ani_coin2_2",
      screenMode: "Portrait",
      uiMode: "mobile",
      // visible: true,
      x: 535,
      y: 1156,
    },
    //SECTION - 30
    {
      name: "ani_coin3_0",
      screenMode: "Landscape",
      uiMode: "mobile",
      // visible: true,
      x: 1163,
      y: 333,
    },
    {
      name: "ani_coin3_0",
      screenMode: "Portrait",
      uiMode: "mobile",
      // visible: true,
      x: 757,
      y: 738,
    },
    {
      name: "ani_coin3_1",
      screenMode: "Landscape",
      uiMode: "mobile",
      // visible: true,
      x: 1163,
      y: 551,
    },
    {
      name: "ani_coin3_1",
      screenMode: "Portrait",
      uiMode: "mobile",
      // visible: true,
      x: 757,
      y: 947,
    },
    {
      name: "ani_coin3_2",
      screenMode: "Landscape",
      uiMode: "mobile",
      // visible: true,
      x: 1163,
      y: 759,
    },
    {
      name: "ani_coin3_2",
      screenMode: "Portrait",
      uiMode: "mobile",
      // visible: true,
      x: 757,
      y: 1156,
    },
    //SECTION - 40
    {
      name: "ani_coin4_0",
      screenMode: "Landscape",
      uiMode: "mobile",
      // visible: true,
      x: 1387,
      y: 333,
    },
    {
      name: "ani_coin4_0",
      screenMode: "Portrait",
      uiMode: "mobile",
      // visible: true,
      x: 966,
      y: 738,
    },
    {
      name: "ani_coin4_1",
      screenMode: "Landscape",
      uiMode: "mobile",
      // visible: true,
      x: 1387,
      y: 551,
    },
    {
      name: "ani_coin4_1",
      screenMode: "Portrait",
      uiMode: "mobile",
      // visible: true,
      x: 966,
      y: 947,
    },
    {
      name: "ani_coin4_2",
      screenMode: "Landscape",
      uiMode: "mobile",
      // visible: true,
      x: 1387,
      y: 759,
    },
    {
      name: "ani_coin4_2",
      screenMode: "Portrait",
      uiMode: "mobile",
      // visible: true,
      x: 966,
      y: 1156,
    },

    //---------------------------------------------------------------------------
    //NOTE - Butterfly on the Symbol ---------------------------------------------------------------------------

    // //SECTION - 00
    {
      name: "ani_reveal00",
      screenMode: "Landscape",
      uiMode: "mobile",
      // visible: true,
      x: 530,
      y: 340,
    },
    { 
      name: "ani_reveal00",
      screenMode: "Portrait",
      uiMode: "mobile",
      // visible: true,
      x: 120,
      y: 730,
    },
    {
      name: "ani_reveal01",
      screenMode: "Landscape",
      uiMode: "mobile",
      // visible: true,
      x: 530,
      y: 545,
    },
    {
      name: "ani_reveal01",
      screenMode: "Portrait",
      uiMode: "mobile",
      // visible: true,
      x: 120,
      y: 939,
    },
    {
      name: "ani_reveal02",
      screenMode: "Landscape",
      uiMode: "mobile",
      // visible: true,
      x: 530,
      y: 748,
    },
    {
      name: "ani_reveal02",
      screenMode: "Portrait",
      uiMode: "mobile",
      // visible: true,
      x: 120,
      y: 1148,
    },
    // //SECTION - 10
    {
      name: "ani_reveal10",
      screenMode: "Landscape",
      uiMode: "mobile",
      // visible: true,
      x: 740,
      y: 340,
    },
    {
      name: "ani_reveal10",
      screenMode: "Portrait",
      uiMode: "mobile",
      // visible: true,
      x: 328,
      y: 730,
    },
    {
      name: "ani_reveal11",
      screenMode: "Landscape",
      uiMode: "mobile",
      // visible: true,
      x: 740,
      y: 545,
    },
    {
      name: "ani_reveal11",
      screenMode: "Portrait",
      uiMode: "mobile",
      // visible: true,
      x: 328,
      y: 939,
    },
    {
      name: "ani_reveal12",
      screenMode: "Landscape",
      uiMode: "mobile",
      // visible: true,
      x: 740,
      y: 748,
    },
    {
      name: "ani_reveal12",
      screenMode: "Portrait",
      uiMode: "mobile",
      // visible: true,
      x: 328,
      y: 1148,
    },
    //SECTION - 20
    {
      name: "ani_reveal20",
      screenMode: "Landscape",
      uiMode: "mobile",
      // visible: true,
      x: 955,
      y: 340,
    },
    {
      name: "ani_reveal20",
      screenMode: "Portrait",
      uiMode: "mobile",
      // visible: true,
      x: 535,
      y: 730,
    },
    {
      name: "ani_reveal21",
      screenMode: "Landscape",
      uiMode: "mobile",
      // visible: true,
      x: 955,
      y: 545,
    },
    {
      name: "ani_reveal21",
      screenMode: "Portrait",
      uiMode: "mobile",
      // visible: true,
      x: 535,
      y: 939,
    },
    {
      name: "ani_reveal22",
      screenMode: "Landscape",
      uiMode: "mobile",
      // visible: true,
      x: 955,
      y: 748,
    },
    {
      name: "ani_reveal22",
      screenMode: "Portrait",
      uiMode: "mobile",
      // visible: true,
      x: 535,
      y: 1148,
    },
    // //SECTION - 30
    {
      name: "ani_reveal30",
      screenMode: "Landscape",
      uiMode: "mobile",
      // visible: true,
      x: 1165,
      y: 340,
    },
    {
      name: "ani_reveal30",
      screenMode: "Portrait",
      uiMode: "mobile",
      // visible: true,
      x: 757,
      y: 730,
    },
    {
      name: "ani_reveal31",
      screenMode: "Landscape",
      uiMode: "mobile",
      // visible: true,
      x: 1165,
      y: 545,
    },
    {
      name: "ani_reveal31",
      screenMode: "Portrait",
      uiMode: "mobile",
      // visible: true,
      x: 757,
      y: 939,
    },
    {
      name: "ani_reveal32",
      screenMode: "Landscape",
      uiMode: "mobile",
      // visible: true,
      x: 1165,
      y: 748,
    },
    {
      name: "ani_reveal32",
      screenMode: "Portrait",
      uiMode: "mobile",
      // visible: true,
      x: 757,
      y: 1148,
    },
    //SECTION - 40
    {
      name: "ani_reveal40",
      screenMode: "Landscape",
      uiMode: "mobile",
      // visible: true,
      x: 1380,
      y: 340,
    },
    {
      name: "ani_reveal40",
      screenMode: "Portrait",
      uiMode: "mobile",
      // visible: true,
      x: 966,
      y: 730,
    },
    {
      name: "ani_reveal41",
      screenMode: "Landscape",
      uiMode: "mobile",
      // visible: true,
      x: 1380,
      y: 545,
    },
    {
      name: "ani_reveal41",
      screenMode: "Portrait",
      uiMode: "mobile",
      // visible: true,
      x: 966,
      y: 939,
    },
    {
      name: "ani_reveal42",
      screenMode: "Landscape",
      uiMode: "mobile",
      // visible: true,
      x: 1380,
      y: 748,
    },
    {
      name: "ani_reveal42",
      screenMode: "Portrait",
      uiMode: "mobile",
      // visible: true,
      x: 966,
      y: 1148,
    },

    //--------------------------------------------------------------
    //NOTE - Win Celebration Layout--------------------------------------------------------------
    {
      name: "Text_amount_tickup_mobile",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: true,
      x: 920,
      y: 780,
    },
    {
      name: "Text_amount_tickup_mobile",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: true,
      x: 550,
      y: 1170,
    },

    //--------------------------------------------------------------


    //ANCHOR Button panel buttons-----------------------------------


    {
      name: "btn_buy_feature",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: true,
      x: 1700,
      y: 100,
    },
    {
      name: "btn_buy_feature",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: true,
      x: 880,
      y: 1528,
    },
    {
      name: "btn_bet_decrease",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: true,
      x: 1440,
      y: 957,
    },
    {
      name: "btn_bet_decrease",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: true,
      x: 740,
      y: 1770,
    },

    {
      name: "btn_bet_increase",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: true,
      x: 1649,
      y: 957,
    },
    {
      name: "btn_bet_increase",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: true,
      x: 885,
      y: 1770,
    },


    {
      name: "btn_paytable",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: true,
      x: 70,
      y: 700,
    },
    {
      name: "btn_paytable",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: true,
      x: 990,
      y: 1799,
    },

    {
      name: "btn_menu",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: true,
      x: 70,
      y: 300,
    },
    {
      name: "btn_menu",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: true,
      x: 15,
      y: 1776,
    },

    {
      name: "btn_turboEnable",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: true,
      x: 1705,
      y: 755,
    },
    {
      name: "btn_turboEnable",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: true,
      x: 290,
      y: 1648,
    },

    {
      name: "btn_turboEnableFreegame",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: true,
      x: 1705,
      y: 755,
    },
    {
      name: "btn_turboEnableFreegame",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: true,
      x: 290,
      y: 1648,
    },


    {
      name: "btn_turDisable",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: true,
      x: 1705,
      y: 755,
    },
    {
      name: "btn_turDisable",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: true,
      x: 290,
      y: 1648,
    },
    {
      name: "btn_turDisableFreegame",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: true,
      x: 1705,
      y: 755,
    },
    {
      name: "btn_turDisableFreegame",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: true,
      x: 290,
      y: 1648,
    },

    // {
    //   name: "btn_autoplay2",
    //   screenMode: "Landscape",
    //   uiMode: "mobile",
    //   visible: true,
    //   x: 1705,
    //   y: 240,
    // },
    // {
    //   name: "btn_autoplay2",
    //   screenMode: "Portrait",
    //   uiMode: "mobile",
    //   visible: true,
    //   x: 685,
    //   y: 1648,
    // },

    // {
    //   name: "btn_autoplay_stop",
    //   screenMode: "Landscape",
    //   uiMode: "mobile",
    //   visible: false,
    //   x: 1690,
    //   y: 240,
    // },
    // {
    //   name: "btn_autoplay_stop",
    //   screenMode: "Portrait",
    //   uiMode: "mobile",
    //   visible: false,
    //   x: 570,
    //   y: 1600,
    // },
    {
      name: "btn_spin",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: true,
      x: 1612,
      y: 396,
    },
    {
      name: "btn_spin",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: true,
      x: 392,
      y: 1450,
    },

    {
      name: "btn_spinStop",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: true,
      x: 1612,
      y: 396,
    },
    {
      name: "btn_spinStop",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: true,
      x: 392,
      y: 1450,
    },

    {
      name: "btn_sound",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: false,
      x: 70,
      y: 490,
    },
    {
      name: "btn_sound",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: false,
      x: 990,
      y: 1705,
    },

    {
      name: "btn_soundOff",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: true,
      x: 70,
      y: 490,
    },
    {
      name: "btn_soundOff",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: true,
      x: 990,
      y: 1705,
    },

    //----------------------------------------------------------------------
    //NOTE - Anticipation Layout ----------------------------------------------------------------------

    {
      name: "anticipation_Scatter",
      screenMode: "Landscape",
      uiMode: "mobile",
      // visible: true,
      x: 1320,
      y: 553,
    },
    {
      name: "anticipation_Scatter",
      screenMode: "Portrait",
      uiMode: "mobile",
      // visible: true,
      x: 900,
      y: 954,
    },
    {
      name: "anticipation_Scatter2",
      screenMode: "Landscape",
      uiMode: "mobile",
      // visible: true,
      x: 1432,
      y: 553,
    },
    {
      name: "anticipation_Scatter2",
      screenMode: "Portrait",
      uiMode: "mobile",
      // visible: true,
      x: 1025,
      y: 954,
    },
    //----------------------------------------------------------------------

    //NOTE -> Coin Layout ---------------------------------------------
    //SECTION - 00
    {
      name: "coin_symbol0_0",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: false,
      x: 17,
      y: 640.5,
    },
    {
      name: "coin_symbol0_0",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: false,
      x: 420,
      y: 245,
    },
    {
      name: "coin_symbol0_1",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: false,
      x: 17,
      y: 850.5,
    },
    {
      name: "coin_symbol0_1",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: false,
      x: 420,
      y: 451,
    },
    {
      name: "coin_symbol0_2",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: false,
      x: 17,
      y: 1057,
    },
    {
      name: "coin_symbol0_2",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: false,
      x: 420,
      y: 655,
    },
    //SECTION - 10
    {
      name: "coin_symbol1_0",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: false,
      x: 220,
      y: 640.5,
    },
    {
      name: "coin_symbol1_0",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: false,
      x: 633,
      y: 245,
    },
    {
      name: "coin_symbol1_1",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: false,
      x: 220,
      y: 850.5,
    },
    {
      name: "coin_symbol1_1",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: false,
      x: 633,
      y: 451,
    },
    {
      name: "coin_symbol1_2",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: false,
      x: 220,
      y: 1057,
    },
    {
      name: "coin_symbol1_2",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: false,
      x: 633,
      y: 655,
    },
    //SECTION - 20
    {
      name: "coin_symbol2_0",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: false,
      x: 437,
      y: 640.5,
    },
    {
      name: "coin_symbol2_0",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: false,
      x: 842,
      y: 245,
    },
    {
      name: "coin_symbol2_1",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: false,
      x: 437,
      y: 850.5,
    },
    {
      name: "coin_symbol2_1",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: false,
      x: 842,
      y: 451,
    },
    {
      name: "coin_symbol2_2",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: false,
      x: 437,
      y: 1057,
    },
    {
      name: "coin_symbol2_2",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: false,
      x: 842,
      y: 655,
    },
    //SECTION - 30
    {
      name: "coin_symbol3_0",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: false,
      x: 647,
      y: 640.5,
    },
    {
      name: "coin_symbol3_0",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: false,
      x: 1059,
      y: 245,
    },
    {
      name: "coin_symbol3_1",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: false,
      x: 647,
      y: 850.5,
    },
    {
      name: "coin_symbol3_1",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: false,
      x: 1059,
      y: 451,
    },
    {
      name: "coin_symbol3_2",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: false,
      x: 647,
      y: 1057,
    },
    {
      name: "coin_symbol3_2",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: false,
      x: 1059,
      y: 655,
    },
    //SECTION - 40
    {
      name: "coin_symbol4_0",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: false,
      x: 858,
      y: 640.5,
    },
    {
      name: "coin_symbol4_0",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: false,
      x: 1270,
      y: 245,
    },
    {
      name: "coin_symbol4_1",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: false,
      x: 858,
      y: 850.5,
    },
    {
      name: "coin_symbol4_1",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: false,
      x: 1270,
      y: 451,
    },
    {
      name: "coin_symbol4_2",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: false,
      x: 858,
      y: 1057,
    },
    {
      name: "coin_symbol4_2",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: false,
      x: 1270,
      y: 655,
    },
    //-----------------------------------------------------------------------------------
    //NOTE - coin text -----------------------------------------------------------------------------------
    //coin_symbol0_0_text
    //SECTION - 00
    {
      name: "coin_symbol0_0_text",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: false,
      x: 118,
      y: 730.5,
    },
    {
      name: "coin_symbol0_0_text",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: false,
      x: 530,
      y: 334,
    },
    {
      name: "coin_symbol0_1_text",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: false,
      x: 118,
      y: 940.5,
    },
    {
      name: "coin_symbol0_1_text",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: false,
      x: 530,
      y: 546,
    },
    {
      name: "coin_symbol0_2_text",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: false,
      x: 118,
      y: 1149,
    },
    {
      name: "coin_symbol0_2_text",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: false,
      x: 530,
      y: 750,
    },
    //SECTION - 10
    {
      name: "coin_symbol1_0_text",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: false,
      x: 329,
      y: 730.5,
    },
    {
      name: "coin_symbol1_0_text",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: false,
      x: 740,
      y: 334,
    },
    {
      name: "coin_symbol1_1_text",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: false,
      x: 329,
      y: 940.5,
    },
    {
      name: "coin_symbol1_1_text",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: false,
      x: 740,
      y: 546,
    },
    {
      name: "coin_symbol1_2_text",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: false,
      x: 329,
      y: 1149,
    },
    {
      name: "coin_symbol1_2_text",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: false,
      x: 740,
      y: 750,
    },
    //SECTION - 20
    {
      name: "coin_symbol2_0_text",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: false,
      x: 539,
      y: 730.5,
    },
    {
      name: "coin_symbol2_0_text",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: false,
      x: 960,
      y: 334,
    },
    {
      name: "coin_symbol2_1_text",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: false,
      x: 539,
      y: 940.5,
    },
    {
      name: "coin_symbol2_1_text",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: false,
      x: 960,
      y: 546,
    },
    {
      name: "coin_symbol2_2_text",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: false,
      x: 539,
      y: 1149,
    },
    {
      name: "coin_symbol2_2_text",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: false,
      x: 960,
      y: 750,
    },
    //SECTION - 30
    {
      name: "coin_symbol3_0_text",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: false,
      x: 755,
      y: 730.5,
    },
    {
      name: "coin_symbol3_0_text",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: false,
      x: 1168,
      y: 334,
    },
    {
      name: "coin_symbol3_1_text",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: false,
      x: 755,
      y: 940.5,
    },
    {
      name: "coin_symbol3_1_text",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: false,
      x: 1168,
      y: 546,
    },
    {
      name: "coin_symbol3_2_text",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: false,
      x: 755,
      y: 1149,
    },
    {
      name: "coin_symbol3_2_text",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: false,
      x: 1168,
      y: 750,
    },
    //SECTION - 40
    {
      name: "coin_symbol4_0_text",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: false,
      x: 967,
      y: 730.5,
    },
    {
      name: "coin_symbol4_0_text",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: false,
      x: 1375,
      y: 334,
    },
    {
      name: "coin_symbol4_1_text",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: false,
      x: 967,
      y: 940.5,
    },
    {
      name: "coin_symbol4_1_text",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: false,
      x: 1375,
      y: 546,
    },
    {
      name: "coin_symbol4_2_text",
      screenMode: "Portrait",
      uiMode: "mobile",
      visible: false,
      x: 967,
      y: 1149,
    },
    {
      name: "coin_symbol4_2_text",
      screenMode: "Landscape",
      uiMode: "mobile",
      visible: false,
      x: 1375,
      y: 745,
    },
    //-------------------------------------------------------------------------
  ],
};
