import React from "react";
import { Icomponent } from "@bonanzainteractive/slote_core";
import { configGame } from "../../../slot/data/config";

interface IframeworkCoinSymbolAnimationConfiguration {
  data: {
    COMPONENTS: Icomponent[];
  };
}

export const frameworkCoinSymbolAnimationConfiguration: IframeworkCoinSymbolAnimationConfiguration =
{
  data: {
    COMPONENTS: [
      {
        name: "desktopConvertContainer",
        type: "Container",
        class: "",
        x: configGame.REEL_CONTAINER_X,
        y: configGame.REEL_CONTAINER_Y,
        layout: true,
        filterTypes: [],
        child: [
          {
            id: "ConvertWildContainer",
            name: "ConvertWildContainer",
            type: "Container",
            x: 0,
            y: 0,
            visible: false,
            filterTypes: [],
            child: [],
          },
          //SECTION - : 00
          {
            name: "ani_coin0_0",
            type: "Spine",
            width: 2012,
            height: 1284,
            image: "ani_coin_queen",
            animationSpeed: 0.8,
            playing: true,
            effectType: "abc",
            maskHeight: 0,
            loop: true,
            visible: false,
            uimode: "desktop",
            spineAnimName: "animation",
            anchor: [0, 0],
            "x": 530,
            "y": 340,
            spinedata: {
              spinename: "ani_coin_queen",
              animationname: "animation",
              loop: true,
              timeScale: 1,
            },
          },
          {
            name: "ani_coin0_0",
            type: "Spine",
            width: 2012,
            height: 1284,
            image: "ani_coin_queen",
            animationSpeed: 0.8,
            playing: true,
            effectType: "abc",
            maskHeight: 0,
            loop: true,
            visible: false,
            layout: true,
            uimode: "mobile",
            spineAnimName: "animation",
            anchor: [0, 0],
            x: 88.5,
            y: 103.5,
            spinedata: {
              spinename: "ani_coin_queen",
              animationname: "animation",
              loop: true,
              timeScale: 1,
            },
          },
          {
            name: "ani_coin0_1",
            type: "Spine",
            width: 2012,
            height: 1284,
            image: "ani_coin_queen",
            animationSpeed: 0.8,
            playing: false,
            effectType: "abc",
            maskHeight: 0,
            loop: true,
            visible: false,
            uimode: "desktop",
            spineAnimName: "animation",
            anchor: [0, 0],
            "x": 530,
            "y": 340 + configGame.SYMBOL_HEIGHT,
            spinedata: {
              spinename: "ani_coin_queen",
              animationname: "animation",
              loop: true,
              timeScale: 1,
            },
          },
          {
            name: "ani_coin0_1",
            type: "Spine",
            width: 2012,
            height: 1284,
            image: "ani_coin_queen",
            animationSpeed: 0.8,
            playing: false,
            effectType: "abc",
            maskHeight: 0,
            loop: true,
            layout: true,
            visible: false,
            uimode: "mobile",
            spineAnimName: "animation",
            anchor: [0, 0],
            x: 94.5,
            y: 64.5 + configGame.SYMBOL_HEIGHT,
            spinedata: {
              spinename: "ani_coin_queen",
              animationname: "animation",
              loop: true,
              timeScale: 1,
            },
          },
          {
            name: "ani_coin0_2",
            type: "Spine",
            width: 2012,
            height: 1284,
            image: "ani_coin_queen",
            animationSpeed: 0.8,
            playing: false,
            effectType: "abc",
            maskHeight: 0,
            loop: true,
            visible: false,
            uimode: "desktop",
            spineAnimName: "animation",
            anchor: [0, 0],
            "x": 530,
            "y": 340 + configGame.SYMBOL_HEIGHT * 2,
            spinedata: {
              spinename: "ani_coin_queen",
              animationname: "animation",
              loop: true,
              timeScale: 1,
            },
          },
          {
            name: "ani_coin0_2",
            type: "Spine",
            width: 2012,
            height: 1284,
            image: "ani_coin_queen",
            animationSpeed: 0.8,
            playing: false,
            effectType: "abc",
            maskHeight: 0,
            loop: true,
            layout: true,
            visible: false,
            uimode: "mobile",
            spineAnimName: "animation",
            anchor: [0, 0],
            x: 94.5,
            y: 21.5 + configGame.SYMBOL_HEIGHT * 2,
            spinedata: {
              spinename: "ani_coin_queen",
              animationname: "animation",
              loop: true,
              timeScale: 1,
            },
          },
          //SECTION - 10
          {
            name: "ani_coin1_0",
            type: "Spine",
            width: 2012,
            height: 1284,
            image: "ani_coin_queen",
            animationSpeed: 0.8,
            playing: false,
            effectType: "abc",
            maskHeight: 0,
            loop: true,
            visible: false,
            uimode: "desktop",
            spineAnimName: "animation",
            anchor: [0, 0],
            "x": 530 + configGame.REEL_GAP + configGame.SYMBOL_WIDTH,
            "y": 340,
            spinedata: {
              spinename: "ani_coin_queen",
              animationname: "animation",
              loop: true,
              timeScale: 1,
            },
          },
          {
            name: "ani_coin1_0",
            type: "Spine",
            width: 2012,
            height: 1284,
            image: "ani_coin_queen",
            animationSpeed: 0.8,
            playing: false,
            effectType: "abc",
            maskHeight: 0,
            loop: true,
            layout: true,
            visible: false,
            uimode: "mobile",
            spineAnimName: "animation",
            anchor: [0, 0],
            x: 43 + configGame.REEL_GAP + configGame.SYMBOL_WIDTH,
            y: 104.5,
            spinedata: {
              spinename: "ani_coin_queen",
              animationname: "animation",
              loop: true,
              timeScale: 1,
            },
          },
          {
            name: "ani_coin1_1",
            type: "Spine",
            width: 2012,
            height: 1284,
            image: "ani_coin_queen",
            animationSpeed: 0.8,
            playing: true,
            effectType: "false",
            maskHeight: 0,
            loop: true,
            visible: false,
            uimode: "desktop",
            spineAnimName: "animation",
            anchor: [0, 0],
            x: 530 + configGame.REEL_GAP + configGame.SYMBOL_WIDTH,
            y: 340 + configGame.SYMBOL_HEIGHT,
            spinedata: {
              spinename: "ani_coin_queen",
              animationname: "animation",
              loop: true,
              timeScale: 1,
            },
          },
          {
            name: "ani_coin1_1",
            type: "Spine",
            width: 2012,
            height: 1284,
            image: "ani_coin_queen",
            animationSpeed: 0.8,
            playing: true,
            effectType: "false",
            maskHeight: 0,
            loop: true,
            layout: true,
            visible: false,
            uimode: "mobile",
            spineAnimName: "animation",
            anchor: [0, 0],
            x: 47 + configGame.REEL_GAP + configGame.SYMBOL_WIDTH,
            y: 64 + configGame.SYMBOL_HEIGHT,
            spinedata: {
              spinename: "ani_coin_queen",
              animationname: "animation",
              loop: true,
              timeScale: 1,
            },
          },
          {
            name: "ani_coin1_2",
            type: "Spine",
            width: 2012,
            height: 1284,
            image: "ani_coin_queen",
            animationSpeed: 0.8,
            playing: true,
            effectType: "abc",
            maskHeight: 0,
            loop: true,
            visible: false,
            uimode: "desktop",
            spineAnimName: "animation",
            anchor: [0, 0],
            x: 530 + configGame.REEL_GAP + configGame.SYMBOL_WIDTH,
            y: 340 + configGame.SYMBOL_HEIGHT * 2,
            spinedata: {
              spinename: "ani_coin_queen",
              animationname: "animation",
              loop: true,
              timeScale: 1,
            },
          },
          {
            name: "ani_coin1_2",
            type: "Spine",
            width: 2012,
            height: 1284,
            image: "ani_coin_queen",
            animationSpeed: 0.8,
            playing: true,
            effectType: "abc",
            maskHeight: 0,
            loop: true,
            layout: true,
            visible: false,
            uimode: "mobile",
            spineAnimName: "animation",
            anchor: [0, 0],
            x: 47 + configGame.REEL_GAP + configGame.SYMBOL_WIDTH,
            y: 20 + configGame.SYMBOL_HEIGHT * 2,
            spinedata: {
              spinename: "ani_coin_queen",
              animationname: "animation",
              loop: true,
              timeScale: 1,
            },
          },
          //SECTION - 20
          {
            name: "ani_coin2_0",
            type: "Spine",
            width: 2012,
            height: 1284,
            image: "ani_coin_queen",
            animationSpeed: 0.8,
            playing: true,
            effectType: "abc",
            maskHeight: 0,
            loop: true,
            visible: false,
            uimode: "desktop",
            spineAnimName: "animation",
            anchor: [0, 0],
            x: 530 + (configGame.REEL_GAP + configGame.SYMBOL_WIDTH) * 2,
            y: 340,
            spinedata: {
              spinename: "ani_coin_queen",
              animationname: "animation",
              loop: true,
              timeScale: 1,
            },
          },
          {
            name: "ani_coin2_0",
            type: "Spine",
            width: 2012,
            height: 1284,
            image: "ani_coin_queen",
            animationSpeed: 0.8,
            playing: true,
            effectType: "abc",
            maskHeight: 0,
            loop: true,
            layout: true,
            visible: false,
            uimode: "mobile",
            spineAnimName: "animation",
            anchor: [0, 0],
            x: 0 + (configGame.REEL_GAP + configGame.SYMBOL_WIDTH) * 2,
            y: 103,
            spinedata: {
              spinename: "ani_coin_queen",
              animationname: "animation",
              loop: true,
              timeScale: 1,
            },
          },
          {
            name: "ani_coin2_1",
            type: "Spine",
            width: 2012,
            height: 1284,
            image: "ani_coin_queen",
            animationSpeed: 0.8,
            playing: false,
            effectType: "abc",
            maskHeight: 0,
            loop: false,
            visible: false,
            uimode: "desktop",
            spineAnimName: "animation",
            anchor: [0, 0],
            x: 530 + (configGame.REEL_GAP + configGame.SYMBOL_WIDTH) * 2,
            y: 340 + configGame.SYMBOL_HEIGHT,
            spinedata: {
              spinename: "ani_coin_queen",
              animationname: "animation",
              loop: false,
              timeScale: 1,
            },
          },
          {
            name: "ani_coin2_1",
            type: "Spine",
            width: 2012,
            height: 1284,
            image: "ani_coin_queen",
            animationSpeed: 0.8,
            playing: false,
            effectType: "abc",
            maskHeight: 0,
            loop: false,
            layout: true,
            visible: false,
            uimode: "mobile",
            spineAnimName: "animation",
            anchor: [0, 0],
            x: 0 + (configGame.REEL_GAP + configGame.SYMBOL_WIDTH) * 2,
            y: 62 + configGame.SYMBOL_HEIGHT,
            spinedata: {
              spinename: "ani_coin_queen",
              animationname: "animation",
              loop: false,
              timeScale: 1,
            },
          },
          {
            name: "ani_coin2_2",
            type: "Spine",
            width: 2012,
            height: 1284,
            image: "ani_coin_queen",
            animationSpeed: 0.8,
            playing: false,
            effectType: "abc",
            maskHeight: 0,
            loop: false,
            visible: false,
            uimode: "desktop",
            spineAnimName: "animation",
            anchor: [0, 0],
            x: 530 + (configGame.REEL_GAP + configGame.SYMBOL_WIDTH) * 2,
            y: 340 + configGame.SYMBOL_HEIGHT * 2,
            spinedata: {
              spinename: "ani_coin_queen",
              animationname: "animation",
              loop: false,
              timeScale: 1,
            },
          },
          {
            name: "ani_coin2_2",
            type: "Spine",
            width: 2012,
            height: 1284,
            image: "ani_coin_queen",
            animationSpeed: 0.8,
            playing: false,
            effectType: "abc",
            maskHeight: 0,
            loop: false,
            layout: true,
            visible: false,
            uimode: "mobile",
            spineAnimName: "animation",
            anchor: [0, 0],
            x: 0 + (configGame.REEL_GAP + configGame.SYMBOL_WIDTH) * 2,
            y: 28 + configGame.SYMBOL_HEIGHT * 2,
            spinedata: {
              spinename: "ani_coin_queen",
              animationname: "animation",
              loop: false,
              timeScale: 1,
            },
          },
          //SECTION - 30
          {
            name: "ani_coin3_0",
            type: "Spine",
            width: 2012,
            height: 1284,
            image: "ani_coin_queen",
            animationSpeed: 0.8,
            playing: true,
            effectType: "abc",
            maskHeight: 0,
            loop: true,
            visible: false,
            uimode: "desktop",
            anchor: [0, 0],
            spineAnimName: "animation",
            x: 530 + (configGame.REEL_GAP + configGame.SYMBOL_WIDTH) * 3,
            y: 340,
            spinedata: {
              spinename: "ani_coin_queen",
              animationname: "animation",
              loop: true,
              timeScale: 1,
            },
          },
          {
            name: "ani_coin3_0",
            type: "Spine",
            width: 2012,
            height: 1284,
            image: "ani_coin_queen",
            animationSpeed: 0.8,
            playing: true,
            effectType: "abc",
            maskHeight: 0,
            loop: true,
            layout: true,
            visible: false,
            uimode: "mobile",
            anchor: [0, 0],
            spineAnimName: "animation",
            x: -48 + (configGame.REEL_GAP + configGame.SYMBOL_WIDTH) * 3,
            y: 106,
            spinedata: {
              spinename: "ani_coin_queen",
              animationname: "animation",
              loop: true,
              timeScale: 1,
            },
          },
          {
            name: "ani_coin3_1",
            type: "Spine",
            width: 2012,
            height: 1284,
            image: "ani_coin_queen",
            animationSpeed: 0.8,
            playing: true,
            effectType: "abc",
            maskHeight: 0,
            loop: true,
            visible: false,
            uimode: "desktop",
            spineAnimName: "animation",
            anchor: [0, 0],
            x: 530 + (configGame.REEL_GAP + configGame.SYMBOL_WIDTH) * 3,
            y: 340 + configGame.SYMBOL_HEIGHT,
            spinedata: {
              spinename: "ani_coin_queen",
              animationname: "animation",
              loop: true,
              timeScale: 1,
            },
          },
          {
            name: "ani_coin3_1",
            type: "Spine",
            width: 2012,
            height: 1284,
            image: "ani_coin_queen",
            animationSpeed: 0.8,
            playing: true,
            effectType: "abc",
            maskHeight: 0,
            loop: true,
            layout: true,
            visible: false,
            uimode: "mobile",
            spineAnimName: "animation",
            anchor: [0, 0],
            x: -50 + (configGame.REEL_GAP + configGame.SYMBOL_WIDTH) * 3,
            y: 70 + configGame.SYMBOL_HEIGHT,
            spinedata: {
              spinename: "ani_coin_queen",
              animationname: "animation",
              loop: true,
              timeScale: 1,
            },
          },
          {
            name: "ani_coin3_2",
            type: "Spine",
            width: 2012,
            height: 1284,
            image: "ani_coin_queen",
            animationSpeed: 0.8,
            playing: true,
            effectType: "abc",
            maskHeight: 0,
            loop: true,
            visible: false,
            uimode: "desktop",
            spineAnimName: "animation",
            anchor: [0, 0],
            x: 530 + (configGame.REEL_GAP + configGame.SYMBOL_WIDTH) * 3,
            y: 340 + configGame.SYMBOL_HEIGHT * 2,
            spinedata: {
              spinename: "ani_coin_queen",
              animationname: "animation",
              loop: true,
              timeScale: 1,
            },
          },
          {
            name: "ani_coin3_2",
            type: "Spine",
            width: 2012,
            height: 1284,
            image: "ani_coin_queen",
            animationSpeed: 0.8,
            playing: true,
            effectType: "abc",
            maskHeight: 0,
            loop: true,
            layout: true,
            visible: false,
            uimode: "mobile",
            spineAnimName: "animation",
            anchor: [0, 0],
            x: -50 + (configGame.REEL_GAP + configGame.SYMBOL_WIDTH) * 3,
            y: 24 + configGame.SYMBOL_HEIGHT * 2,
            spinedata: {
              spinename: "ani_coin_queen",
              animationname: "animation",
              loop: true,
              timeScale: 1,
            },
          },
          //SECTION - 40
          {
            name: "ani_coin4_0",
            type: "Spine",
            width: 2012,
            height: 1284,
            image: "ani_coin_queen",
            animationSpeed: 0.8,
            playing: true,
            effectType: "abc",
            maskHeight: 0,
            loop: true,
            visible: false,
            uimode: "desktop",
            spineAnimName: "animation",
            anchor: [0, 0],
            x: 530 + (configGame.REEL_GAP + configGame.SYMBOL_WIDTH) * 4,
            y: 340,
            spinedata: {
              spinename: "ani_coin_queen",
              animationname: "animation",
              loop: true,
              timeScale: 1,
            },
          },
          {
            name: "ani_coin4_0",
            type: "Spine",
            width: 2012,
            height: 1284,
            image: "ani_coin_queen",
            animationSpeed: 0.8,
            playing: true,
            effectType: "abc",
            maskHeight: 0,
            loop: true,
            layout: true,
            visible: false,
            uimode: "mobile",
            spineAnimName: "animation",
            anchor: [0, 0],
            x: -100 + (configGame.REEL_GAP + configGame.SYMBOL_WIDTH) * 4,
            y: 106,
            spinedata: {
              spinename: "ani_coin_queen",
              animationname: "animation",
              loop: true,
              timeScale: 1,
            },
          },
          {
            name: "ani_coin4_1",
            type: "Spine",
            width: 2012,
            height: 1284,
            image: "ani_coin_queen",
            animationSpeed: 0.8,
            playing: true,
            effectType: "abc",
            maskHeight: 0,
            loop: true,
            visible: false,
            uimode: "desktop",
            spineAnimName: "animation",
            anchor: [0, 0],
            x: 530 + (configGame.REEL_GAP + configGame.SYMBOL_WIDTH) * 4,
            y: 340 + configGame.SYMBOL_HEIGHT,
            spinedata: {
              spinename: "ani_coin_queen",
              animationname: "animation",
              loop: true,
              timeScale: 1,
            },
          },
          {
            name: "ani_coin4_1",
            type: "Spine",
            width: 2012,
            height: 1284,
            image: "ani_coin_queen",
            animationSpeed: 0.8,
            playing: true,
            effectType: "abc",
            maskHeight: 0,
            loop: true,
            layout: true,
            visible: false,
            uimode: "mobile",
            spineAnimName: "animation",
            anchor: [0, 0],
            x: -99 + (configGame.REEL_GAP + configGame.SYMBOL_WIDTH) * 4,
            y: 60 + configGame.SYMBOL_HEIGHT,
            spinedata: {
              spinename: "ani_coin_queen",
              animationname: "animation",
              loop: true,
              timeScale: 1,
            },
          },
          {
            name: "ani_coin4_2",
            type: "Spine",
            width: 2012,
            height: 1284,
            image: "ani_coin_queen",
            animationSpeed: 0.8,
            playing: true,
            effectType: "abc",
            maskHeight: 0,
            loop: true,
            visible: false,
            uimode: "desktop",
            spineAnimName: "animation",
            anchor: [0, 0],
            x: 530 + (configGame.REEL_GAP + configGame.SYMBOL_WIDTH) * 4,
            y: 340 + configGame.SYMBOL_HEIGHT * 2,
            spinedata: {
              spinename: "ani_coin_queen",
              animationname: "animation",
              loop: true,
              timeScale: 1,
            },
          },
          {
            name: "ani_coin4_2",
            type: "Spine",
            width: 2012,
            height: 1284,
            image: "ani_coin_queen",
            animationSpeed: 0.8,
            playing: true,
            effectType: "abc",
            maskHeight: 0,
            loop: true,
            layout: true,
            uimode: "mobile",
            visible: false,
            spineAnimName: "animation",
            anchor: [0, 0],
            x: -99 + (configGame.REEL_GAP + configGame.SYMBOL_WIDTH) * 4,
            y: 20 + configGame.SYMBOL_HEIGHT * 2,
            spinedata: {
              spinename: "ani_coin_queen",
              animationname: "animation",
              loop: true,
              timeScale: 1,
            }
          },

          //NOTE - coin Symbol ------------------------------------------------------

          //SECTION - 00
          {
            name: "coin_symbol0_0",
            type: "Image",
            width: 230,
            height: 230,
            image: "symbol_Coin",
            maskHeight: 0,
            visible: false,
            uimode: "desktop",
            anchor: [0, 0],
            x: 417,
            y: 236,
          },
          {
            name: "coin_symbol0_0",
            type: "Image",
            width: 209,
            height: 209,
            image: "symbol_Coin",
            maskHeight: 0,
            visible: false,
            uimode: "mobile",
            layout: true,
            anchor: [0, 0],
            x: 320,
            y: 139,
          },
          {
            name: "coin_symbol0_1",
            type: "Image",
            width: 230,
            height: 230,
            image: "symbol_Coin",
            maskHeight: 0,
            visible: false,
            uimode: "desktop",
            anchor: [0, 0],
            x: 417,
            y: 446,
          },
          {
            name: "coin_symbol0_1",
            type: "Image",
            width: 209,
            height: 209,
            image: "symbol_Coin",
            maskHeight: 0,
            visible: false,
            uimode: "mobile",
            layout: true,
            anchor: [0, 0],
            x: 320,
            y: 386,
          },
          {
            name: "coin_symbol0_2",
            type: "Image",
            width: 230,
            height: 230,
            image: "symbol_Coin",
            maskHeight: 0,
            visible: false,
            uimode: "desktop",
            anchor: [0, 0],
            x: 417,
            y: 655,
          },
          {
            name: "coin_symbol0_2",
            type: "Image",
            width: 209,
            height: 209,
            image: "symbol_Coin",
            maskHeight: 0,
            visible: false,
            uimode: "mobile",
            layout: true,
            anchor: [0, 0],
            x: 320,
            y: 636,
          },
          //SECTION - 10
          {
            name: "coin_symbol1_0",
            type: "Image",
            width: 230,
            height: 230,
            image: "symbol_Coin",
            maskHeight: 0,
            visible: false,
            uimode: "desktop",
            anchor: [0, 0],
            x: 630,
            y: 236,
          },
          {
            name: "coin_symbol1_0",
            type: "Image",
            width: 209,
            height: 209,
            image: "symbol_Coin",
            maskHeight: 0,
            visible: false,
            uimode: "mobile",
            layout: true,
            anchor: [0, 0],
            x: 580,
            y: 139,
          },
          {
            name: "coin_symbol1_1",
            type: "Image",
            width: 230,
            height: 230,
            image: "symbol_Coin",
            maskHeight: 0,
            visible: false,
            uimode: "desktop",
            anchor: [0, 0],
            x: 630,
            y: 446,
          },
          {
            name: "coin_symbol1_1",
            type: "Image",
            width: 209,
            height: 209,
            image: "symbol_Coin",
            maskHeight: 0,
            visible: false,
            uimode: "mobile",
            layout: true,
            anchor: [0, 0],
            x: 580,
            y: 386,
          },
          {
            name: "coin_symbol1_2",
            type: "Image",
            width: 230,
            height: 230,
            image: "symbol_Coin",
            maskHeight: 0,
            visible: false,
            uimode: "desktop",
            anchor: [0, 0],
            x: 630,
            y: 655,
          },
          {
            name: "coin_symbol1_2",
            type: "Image",
            width: 209,
            height: 209,
            image: "symbol_Coin",
            maskHeight: 0,
            visible: false,
            uimode: "mobile",
            layout: true,
            anchor: [0, 0],
            x: 580,
            y: 636,
          },
          //SECTION - 20
          {
            name: "coin_symbol2_0",
            type: "Image",
            width: 230,
            height: 230,
            image: "symbol_Coin",
            maskHeight: 0,
            visible: false,
            uimode: "desktop",
            anchor: [0, 0],
            x: 836,
            y: 236,
          },
          {
            name: "coin_symbol2_0",
            type: "Image",
            width: 209,
            height: 209,
            image: "symbol_Coin",
            maskHeight: 0,
            visible: false,
            uimode: "mobile",
            layout: true,
            anchor: [0, 0],
            x: 835,
            y: 139,
          },
          {
            name: "coin_symbol2_1",
            type: "Image",
            width: 230,
            height: 230,
            image: "symbol_Coin",
            maskHeight: 0,
            visible: false,
            uimode: "desktop",
            anchor: [0, 0],
            x: 836,
            y: 446,
          },
          {
            name: "coin_symbol2_1",
            type: "Image",
            width: 209,
            height: 209,
            image: "symbol_Coin",
            maskHeight: 0,
            visible: false,
            uimode: "mobile",
            layout: true,
            anchor: [0, 0],
            x: 835,
            y: 386,
          },
          {
            name: "coin_symbol2_2",
            type: "Image",
            width: 230,
            height: 230,
            image: "symbol_Coin",
            maskHeight: 0,
            visible: false,
            uimode: "desktop",
            anchor: [0, 0],
            x: 836,
            y: 655,
          },
          {
            name: "coin_symbol2_2",
            type: "Image",
            width: 230,
            height: 230,
            image: "symbol_Coin",
            maskHeight: 0,
            visible: false,
            uimode: "mobile",
            layout: true,
            anchor: [0, 0],
            x: 835,
            y: 636,
          },
          //SECTION - 30
          {
            name: "coin_symbol3_0",
            type: "Image",
            width: 230,
            height: 230,
            image: "symbol_Coin",
            maskHeight: 0,
            visible: false,
            uimode: "desktop",
            anchor: [0, 0],
            x: 1050,
            y: 236,
          },
          {
            name: "coin_symbol3_0",
            type: "Image",
            width: 209,
            height: 209,
            image: "symbol_Coin",
            maskHeight: 0,
            visible: false,
            uimode: "mobile",
            layout: true,
            anchor: [0, 0],
            x: 1086,
            y: 139,
          },
          {
            name: "coin_symbol3_1",
            type: "Image",
            width: 230,
            height: 230,
            image: "symbol_Coin",
            maskHeight: 0,
            visible: false,
            uimode: "desktop",
            anchor: [0, 0],
            x: 1050,
            y: 446,
          },
          {
            name: "coin_symbol3_1",
            type: "Image",
            width: 209,
            height: 209,
            image: "symbol_Coin",
            maskHeight: 0,
            visible: false,
            uimode: "mobile",
            layout: true,
            anchor: [0, 0],
            x: 1086,
            y: 386,
          },
          {
            name: "coin_symbol3_2",
            type: "Image",
            width: 230,
            height: 230,
            image: "symbol_Coin",
            maskHeight: 0,
            visible: false,
            uimode: "desktop",
            anchor: [0, 0],
            x: 1050,
            y: 655,
          },
          {
            name: "coin_symbol3_2",
            type: "Image",
            width: 209,
            height: 209,
            image: "symbol_Coin",
            maskHeight: 0,
            visible: false,
            uimode: "mobile",
            layout: true,
            anchor: [0, 0],
            x: 1086,
            y: 636,
          },
          //SECTION - 40
          {
            name: "coin_symbol4_0",
            type: "Image",
            width: 230,
            height: 230,
            image: "symbol_Coin",
            maskHeight: 0,
            visible: false,
            uimode: "desktop",
            anchor: [0, 0],
            x: 1260,
            y: 236,
          },
          {
            name: "coin_symbol4_0",
            type: "Image",
            width: 209,
            height: 209,
            image: "symbol_Coin",
            maskHeight: 0,
            visible: false,
            uimode: "mobile",
            layout: true,
            anchor: [0, 0],
            x: 1344,
            y: 139,
          },
          {
            name: "coin_symbol4_1",
            type: "Image",
            width: 230,
            height: 230,
            image: "symbol_Coin",
            maskHeight: 0,
            visible: false,
            uimode: "desktop",
            anchor: [0, 0],
            x: 1260,
            y: 446,
          },
          {
            name: "coin_symbol4_1",
            type: "Image",
            width: 209,
            height: 209,
            image: "symbol_Coin",
            maskHeight: 0,
            visible: false,
            uimode: "mobile",
            layout: true,
            anchor: [0, 0],
            x: 1344,
            y: 386,
          },
          {
            name: "coin_symbol4_2",
            type: "Image",
            width: 230,
            height: 230,
            image: "symbol_Coin",
            maskHeight: 0,
            visible: false,
            uimode: "desktop",
            anchor: [0, 0],
            x: 1260,
            y: 655,
          },
          {
            name: "coin_symbol4_2",
            type: "Image",
            width: 209,
            height: 209,
            image: "symbol_Coin",
            maskHeight: 0,
            visible: false,
            uimode: "mobile",
            layout: true,
            anchor: [0, 0],
            x: 1344,
            y: 636,
          },

          //NOTE -  coin Text -----------------------------------------
          //SECTION - 00
          {
            name: "coin_symbol0_0_text",
            type: "BitMapText",
            width: 100,
            alpha: 0,
            image: "symbol_Coin",
            maskHeight: 0,
            visible: false,
            uimode: "desktop",
            anchor: [0.5, 0.5],
            x: 530,
            y: 340,
            text: "999",
            scaleToFit: true,
            textStyle: {
              font: "100px coin_digits-export"
            }
          },
          {
            name: "coin_symbol0_0_text",
            type: "BitMapText",
            width: 100,
            alpha: 0,
            image: "symbol_Coin",
            maskHeight: 0,
            visible: false,
            uimode: "mobile",
            layout: true,
            anchor: [0.5, 0.5],
            x: 450,
            y: 209,
            text: "999",
            scaleToFit: true,
            textStyle: {
              font: "100px coin_digits-export"
            }
          },
          {
            name: "coin_symbol0_1_text",
            type: "BitMapText",
            width: 100,
            alpha: 0,
            image: "symbol_Coin",
            maskHeight: 0,
            visible: false,
            uimode: "desktop",
            anchor: [0.5, 0.5],
            x: 530,
            y: 550,
            text: "999",
            scaleToFit: true,
            textStyle: {
              font: "100px coin_digits-export"
            }
          },
          {
            name: "coin_symbol0_1_text",
            type: "BitMapText",
            width: 100,
            alpha: 0,
            image: "symbol_Coin",
            maskHeight: 0,
            visible: false,
            uimode: "mobile",
            layout: true,
            anchor: [0.5, 0.5],
            x: 450,
            y: 500,
            text: "999",
            scaleToFit: true,
            textStyle: {
              font: "100px coin_digits-export"
            }
          },
          {
            name: "coin_symbol0_2_text",
            type: "BitMapText",
            width: 100,
            alpha: 0,
            image: "symbol_Coin",
            maskHeight: 0,
            visible: false,
            uimode: "desktop",
            anchor: [0.5, 0.5],
            x: 530,
            y: 760,
            text: "999",
            scaleToFit: true,
            textStyle: {
              font: "100px coin_digits-export"
            }
          },
          {
            name: "coin_symbol0_2_text",
            type: "BitMapText",
            width: 100,
            alpha: 0,
            image: "symbol_Coin",
            maskHeight: 0,
            visible: false,
            uimode: "mobile",
            layout: true,
            anchor: [0.5, 0.5],
            x: 450,
            y: 750,
            text: "999",
            scaleToFit: true,
            textStyle: {
              font: "100px coin_digits-export"
            }
          },
          //SECTION - 10
          {
            name: "coin_symbol1_0_text",
            type: "BitMapText",
            width: 100,
            alpha: 0,
            image: "symbol_Coin",
            maskHeight: 0,
            visible: false,
            uimode: "desktop",
            anchor: [0.5, 0.5],
            x: 750,
            y: 340,
            text: "999",
            scaleToFit: true,
            textStyle: {
              font: "100px coin_digits-export"
            }
          },
          {
            name: "coin_symbol1_0_text",
            type: "BitMapText",
            width: 100,
            alpha: 0,
            image: "symbol_Coin",
            maskHeight: 0,
            visible: false,
            uimode: "mobile",
            layout: true,
            anchor: [0.5, 0.5],
            x: 705,
            y: 209,
            text: "999",
            scaleToFit: true,
            textStyle: {
              font: "100px coin_digits-export"
            }
          },
          {
            name: "coin_symbol1_1_text",
            type: "BitMapText",
            width: 100,
            alpha: 0,
            image: "symbol_Coin",
            maskHeight: 0,
            visible: false,
            uimode: "desktop",
            anchor: [0.5, 0.5],
            x: 750,
            y: 550,
            text: "999",
            scaleToFit: true,
            textStyle: {
              font: "100px coin_digits-export"
            }
          },
          {
            name: "coin_symbol1_1_text",
            type: "BitMapText",
            width: 100,
            alpha: 0,
            image: "symbol_Coin",
            maskHeight: 0,
            visible: false,
            uimode: "mobile",
            layout: true,
            anchor: [0.5, 0.5],
            x: 705,
            y: 502,
            text: "999",
            scaleToFit: true,
            textStyle: {
              font: "100px coin_digits-export"
            }
          },
          {
            name: "coin_symbol1_2_text",
            type: "BitMapText",
            width: 100,
            alpha: 0,
            image: "symbol_Coin",
            maskHeight: 0,
            visible: false,
            uimode: "desktop",
            anchor: [0.5, 0.5],
            x: 750,
            y: 760,
            text: "999",
            scaleToFit: true,
            textStyle: {
              font: "100px coin_digits-export"
            }
          },
          {
            name: "coin_symbol1_2_text",
            type: "BitMapText",
            width: 100,
            alpha: 0,
            image: "symbol_Coin",
            maskHeight: 0,
            visible: false,
            uimode: "mobile",
            layout: true,
            anchor: [0.5, 0.5],
            x: 705,
            y: 750,
            text: "999",
            scaleToFit: true,
            textStyle: {
              font: "100px coin_digits-export"
            }
          },
          //SECTION - 20
          {
            name: "coin_symbol2_0_text",
            type: "BitMapText",
            width: 100,
            alpha: 0,
            image: "symbol_Coin",
            maskHeight: 0,
            visible: false,
            uimode: "desktop",
            anchor: [0.5, 0.5],
            x: 956,
            y: 340,
            text: "999",
            scaleToFit: true,
            textStyle: {
              font: "100px coin_digits-export"
            }
          },
          {
            name: "coin_symbol2_0_text",
            type: "BitMapText",
            width: 100,
            alpha: 0,
            image: "symbol_Coin",
            maskHeight: 0,
            visible: false,
            uimode: "mobile",
            layout: true,
            anchor: [0.5, 0.5],
            x: 965,
            y: 209,
            text: "999",
            scaleToFit: true,
            textStyle: {
              font: "100px coin_digits-export"
            }
          },
          {
            name: "coin_symbol2_1_text",
            type: "BitMapText",
            width: 100,
            alpha: 0,
            image: "symbol_Coin",
            maskHeight: 0,
            visible: false,
            uimode: "desktop",
            anchor: [0.5, 0.5],
            x: 956,
            y: 550,
            text: "999",
            scaleToFit: true,
            textStyle: {
              font: "100px coin_digits-export"
            }
          },
          {
            name: "coin_symbol2_1_text",
            type: "BitMapText",
            width: 100,
            alpha: 0,
            image: "symbol_Coin",
            maskHeight: 0,
            visible: false,
            uimode: "mobile",
            layout: true,
            anchor: [0.5, 0.5],
            x: 965,
            y: 500,
            text: "999",
            scaleToFit: true,
            textStyle: {
              font: "100px coin_digits-export"
            }
          },
          {
            name: "coin_symbol2_2_text",
            type: "BitMapText",
            width: 100,
            alpha: 0,
            image: "symbol_Coin",
            maskHeight: 0,
            visible: false,
            uimode: "desktop",
            anchor: [0.5, 0.5],
            x: 956,
            y: 760,
            text: "999",
            scaleToFit: true,
            textStyle: {
              font: "100px coin_digits-export"
            }
          },
          {
            name: "coin_symbol2_2_text",
            type: "BitMapText",
            width: 100,
            alpha: 0,
            image: "symbol_Coin",
            maskHeight: 0,
            visible: false,
            uimode: "mobile",
            layout: true,
            anchor: [0.5, 0.5],
            x: 965,
            y: 750,
            text: "999",
            scaleToFit: true,
            textStyle: {
              font: "100px coin_digits-export"
            }
          },
          //SECTION - 30
          {
            name: "coin_symbol3_0_text",
            type: "BitMapText",
            width: 100,
            alpha: 0,
            image: "symbol_Coin",
            maskHeight: 0,
            visible: false,
            uimode: "desktop",
            anchor: [0.5, 0.5],
            x: 1168,
            y: 340,
            text: "999",
            scaleToFit: true,
            textStyle: {
              font: "100px coin_digits-export"
            }
          },
          {
            name: "coin_symbol3_0_text",
            type: "BitMapText",
            width: 100,
            alpha: 0,
            image: "symbol_Coin",
            maskHeight: 0,
            visible: false,
            uimode: "mobile",
            layout: true,
            anchor: [0.5, 0.5],
            x: 1215,
            y: 209,
            text: "999",
            scaleToFit: true,
            textStyle: {
              font: "100px coin_digits-export"
            }
          },
          {
            name: "coin_symbol3_1_text",
            type: "BitMapText",
            width: 100,
            alpha: 0,
            image: "symbol_Coin",
            maskHeight: 0,
            visible: false,
            uimode: "desktop",
            anchor: [0.5, 0.5],
            x: 1168,
            y: 550,
            text: "999",
            scaleToFit: true,
            textStyle: {
              font: "100px coin_digits-export"
            }
          },
          {
            name: "coin_symbol3_1_text",
            type: "BitMapText",
            width: 100,
            alpha: 0,
            image: "symbol_Coin",
            maskHeight: 0,
            visible: false,
            uimode: "mobile",
            layout: true,
            anchor: [0.5, 0.5],
            x: 1215,
            y: 500,
            text: "999",
            scaleToFit: true,
            textStyle: {
              font: "100px coin_digits-export"
            }
          },
          {
            name: "coin_symbol3_2_text",
            type: "BitMapText",
            width: 100,
            alpha: 0,
            image: "symbol_Coin",
            maskHeight: 0,
            visible: false,
            uimode: "desktop",
            anchor: [0.5, 0.5],
            x: 1168,
            y: 760,
            text: "999",
            scaleToFit: true,
            textStyle: {
              font: "100px coin_digits-export"
            }
          },
          {
            name: "coin_symbol3_2_text",
            type: "BitMapText",
            width: 100,
            alpha: 0,
            image: "symbol_Coin",
            maskHeight: 0,
            visible: false,
            uimode: "mobile",
            layout: true,
            anchor: [0.5, 0.5],
            x: 1215,
            y: 750,
            text: "999",
            scaleToFit: true,
            textStyle: {
              font: "100px coin_digits-export"
            }
          },
          //SECTION - 40
          {
            name: "coin_symbol4_0_text",
            type: "BitMapText",
            width: 100,
            alpha: 0,
            image: "symbol_Coin",
            maskHeight: 0,
            visible: false,
            uimode: "desktop",
            anchor: [0.5, 0.5],
            x: 1378,
            y: 340,
            text: "999",
            scaleToFit: true,
            textStyle: {
              font: "100px coin_digits-export"
            }
          },
          {
            name: "coin_symbol4_0_text",
            type: "BitMapText",
            width: 100,
            alpha: 0,
            image: "symbol_Coin",
            maskHeight: 0,
            visible: false,
            uimode: "mobile",
            layout: true,
            anchor: [0.5, 0.5],
            x: 1470,
            y: 255,
            text: "999",
            scaleToFit: true,
            textStyle: {
              font: "100px coin_digits-export"
            }
          },
          {
            name: "coin_symbol4_1_text",
            type: "BitMapText",
            width: 100,
            alpha: 0,
            image: "symbol_Coin",
            maskHeight: 0,
            visible: false,
            uimode: "desktop",
            anchor: [0.5, 0.5],
            x: 1378,
            y: 550,
            text: "999",
            scaleToFit: true,
            textStyle: {
              font: "100px coin_digits-export"
            }
          },
          {
            name: "coin_symbol4_1_text",
            type: "BitMapText",
            width: 100,
            alpha: 0,
            image: "symbol_Coin",
            maskHeight: 0,
            visible: false,
            uimode: "mobile",
            layout: true,
            anchor: [0.5, 0.5],
            x: 1470,
            y: 500,
            text: "999",
            scaleToFit: true,
            textStyle: {
              font: "100px coin_digits-export"
            }
          },
          {
            name: "coin_symbol4_2_text",
            type: "BitMapText",
            width: 100,
            alpha: 0,
            image: "symbol_Coin",
            maskHeight: 0,
            visible: false,
            uimode: "desktop",
            anchor: [0.5, 0.5],
            x: 1378,
            y: 760,
            text: "999",
            scaleToFit: true,
            textStyle: {
              font: "100px coin_digits-export"
            }
          },
          {
            name: "coin_symbol4_2_text",
            type: "BitMapText",
            width: 100,
            alpha: 0,
            image: "symbol_Coin",
            maskHeight: 0,
            visible: false,
            uimode: "mobile",
            layout: true,
            anchor: [0.5, 0.5],
            x: 1470,
            y: 745,
            text: "999",
            scaleToFit: true,
            textStyle: {
              font: "100px coin_digits-export"
            }
          },
        ],
      },

    ]
  }
};

export const CoinSymbolAnimationContext = React.createContext({});
