import React from "react";
import { Icomponent } from "@bonanzainteractive/slote_core";


interface IframeworkRevealFeature {
    data: {
        COMPONENTS: Icomponent[]
    }

}

export const frameworkRevealFeature: IframeworkRevealFeature = {

    data: {
        "COMPONENTS": [
            {
                "id": "desktopMainContainer",
                "name": "desktopMainContainer",
                "type": "Container",
                "class": "",
                "x": 0,
                "y": 0,
                "layout": false,
                "uimode": "desktop",
                "filterTypes": [],
                "parentLayer": "baseLayer",
                child: [

                    {
                        "name": "bg_reveal_sym1",
                        "image": "bg_reveal_sym",
                        "type": "Image",
                        "layout": false,
                        "uimode": "desktop",
                        "class": "",
                        "anchor": [0.5, 0.5],
                        "visible": false,
                        "width": 66,
                        "height": 66,
                        "x": 673,
                        "y": 110
                    },
                    {
                        "id": "ani_bg_reveal_sym1",
                        "name": "ani_bg_reveal_sym1",
                        "type": "Spine",
                        "width": 356.85,
                        "height": 279,
                        "image": "ani_reveal",
                        "animationSpeed": 0.2,
                        "playing": false,
                        "loop": false,
                        "visible": true,
                        "effectType": "abc",
                        "maskHeight": 336,
                        "spineAnimName": "reveal_sym_meter",
                        "anchor": [0.5, 0.5],
                        "x": 673,
                        "y": 110,
                        "spinedata": {
                            "spinename": "ani_reveal",
                            "animationname": "reveal_sym_meter",
                            "loop": false,
                            "timeScale": 0.9

                        },
                    },
                    {
                        "name": "bg_reveal_sym2",
                        "image": "bg_reveal_sym",
                        "type": "Image",
                        "layout": false,
                        "uimode": "desktop",
                        "class": "",
                        "anchor": [0.5, 0.5],
                        "visible": false,
                        "width": 66,
                        "height": 66,
                        "x": 752,
                        "y": 110
                    },
                    {
                        "id": "ani_bg_reveal_sym2",
                        "name": "ani_bg_reveal_sym2",
                        "type": "Spine",
                        "width": 356.85,
                        "height": 279,
                        "image": "ani_reveal",
                        "animationSpeed": 0.2,
                        "playing": false,
                        "loop": false,
                        "visible": true,
                        "effectType": "abc",
                        "maskHeight": 336,
                        "spineAnimName": "reveal_sym_meter",
                        "anchor": [0.5, 0.5],

                        "x": 752,
                        "y": 110,
                        "spinedata": {
                            "spinename": "ani_reveal",
                            "animationname": "reveal_sym_meter",
                            "loop": false,
                            "timeScale": 0.9

                        },
                    },
                    {
                        "name": "bg_reveal_sym3",
                        "image": "bg_reveal_sym",
                        "type": "Image",
                        "layout": false,
                        "uimode": "desktop",
                        "class": "",
                        "anchor": [0.5, 0.5],
                        "visible": false,
                        "width": 66,
                        "height": 66,
                        "x": 832,
                        "y": 110
                    },
                    {
                        "id": "ani_bg_reveal_sym3",
                        "name": "ani_bg_reveal_sym3",
                        "type": "Spine",
                        "width": 356.85,
                        "height": 279,
                        "image": "ani_reveal",
                        "animationSpeed": 0.2,
                        "playing": false,
                        "loop": false,
                        "visible": true,
                        "effectType": "abc",
                        "maskHeight": 336,
                        "spineAnimName": "reveal_sym_meter",
                        "anchor": [0.5, 0.5],

                        "x": 832,
                        "y": 110,
                        "spinedata": {
                            "spinename": "ani_reveal",
                            "animationname": "reveal_sym_meter",
                            "loop": false,
                            "timeScale": 0.9

                        },
                    },
                    {
                        "name": "bg_reveal_sym4",
                        "image": "bg_reveal_sym",
                        "type": "Image",
                        "layout": false,
                        "uimode": "desktop",
                        "class": "",
                        "anchor": [0.5, 0.5],
                        "visible": false,
                        "width": 66,
                        "height": 66,
                        "x": 912,
                        "y": 110
                    },
                    {
                        "id": "ani_bg_reveal_sym4",
                        "name": "ani_bg_reveal_sym4",
                        "type": "Spine",
                        "width": 356.85,
                        "height": 279,
                        "image": "ani_reveal",
                        "animationSpeed": 0.2,
                        "playing": false,
                        "loop": false,
                        "visible": true,
                        "effectType": "abc",
                        "maskHeight": 336,
                        "spineAnimName": "reveal_sym_meter",
                        "anchor": [0.5, 0.5],

                        "x": 912,
                        "y": 110,
                        "spinedata": {
                            "spinename": "ani_reveal",
                            "animationname": "reveal_sym_meter",
                            "loop": false,
                            "timeScale": 0.9

                        },
                    },
                    {
                        "name": "bg_reveal_sym5",
                        "image": "bg_reveal_sym",
                        "type": "Image",
                        "layout": false,
                        "uimode": "desktop",
                        "class": "",
                        "anchor": [0.5, 0.5],
                        "visible": false,
                        "width": 66,
                        "height": 66,
                        "x": 992,
                        "y": 110
                    },
                    {
                        "id": "ani_bg_reveal_sym5",
                        "name": "ani_bg_reveal_sym5",
                        "type": "Spine",
                        "width": 356.85,
                        "height": 279,
                        "image": "ani_reveal",
                        "animationSpeed": 0.2,
                        "playing": false,
                        "loop": false,
                        "visible": true,
                        "effectType": "abc",
                        "maskHeight": 336,
                        "spineAnimName": "reveal_sym_meter",
                        "anchor": [0.5, 0.5],

                        "x": 992,
                        "y": 110,
                        "spinedata": {
                            "spinename": "ani_reveal",
                            "animationname": "reveal_sym_meter",
                            "loop": false,
                            "timeScale": 0.9

                        },
                    },
                    {
                        "name": "bg_reveal_sym6",
                        "image": "bg_reveal_sym",
                        "type": "Image",
                        "layout": false,
                        "uimode": "desktop",
                        "class": "",
                        "anchor": [0.5, 0.5],
                        "visible": false,
                        "width": 66,
                        "height": 66,
                        "x": 1072,
                        "y": 110
                    },
                    {
                        "id": "ani_bg_reveal_sym6",
                        "name": "ani_bg_reveal_sym6",
                        "type": "Spine",
                        "width": 356.85,
                        "height": 279,
                        "image": "ani_reveal",
                        "animationSpeed": 0.2,
                        "playing": false,
                        "loop": false,
                        "visible": true,
                        "effectType": "abc",
                        "maskHeight": 336,
                        "spineAnimName": "reveal_sym_meter",
                        "anchor": [0.5, 0.5],

                        "x": 1072,
                        "y": 110,
                        "spinedata": {
                            "spinename": "ani_reveal",
                            "animationname": "reveal_sym_meter",
                            "loop": false,
                            "timeScale": 0.9

                        },
                    },
                    {
                        "name": "bg_reveal_sym7",
                        "image": "bg_reveal_sym",
                        "type": "Image",
                        "layout": false,
                        "uimode": "desktop",
                        "class": "",
                        "anchor": [0.5, 0.5],
                        "visible": false,
                        "width": 66,
                        "height": 66,
                        "x": 1152,
                        "y": 110
                    },
                    {
                        "id": "ani_bg_reveal_sym7",
                        "name": "ani_bg_reveal_sym7",
                        "type": "Spine",
                        "width": 356.85,
                        "height": 279,
                        "image": "ani_reveal",
                        "animationSpeed": 0.2,
                        "playing": false,
                        "loop": false,
                        "visible": true,
                        "effectType": "abc",
                        "maskHeight": 336,
                        "spineAnimName": "reveal_sym_meter",
                        "anchor": [0.5, 0.5],

                        "x": 1152,
                        "y": 110,
                        "spinedata": {
                            "spinename": "ani_reveal",
                            "animationname": "reveal_sym_meter",
                            "loop": false,
                            "timeScale": 0.9

                        },
                    },
                    {
                        "name": "bg_reveal_sym8",
                        "image": "bg_reveal_sym",
                        "type": "Image",
                        "layout": false,
                        "uimode": "desktop",
                        "class": "",
                        "anchor": [0.5, 0.5],
                        "visible": false,
                        "width": 66,
                        "height": 66,
                        "x": 1232,
                        "y": 110
                    },
                    {
                        "id": "ani_bg_reveal_sym8",
                        "name": "ani_bg_reveal_sym8",
                        "type": "Spine",
                        "width": 356.85,
                        "height": 279,
                        "image": "ani_reveal",
                        "animationSpeed": 0.2,
                        "playing": false,
                        "loop": false,
                        "visible": true,
                        "effectType": "abc",
                        "maskHeight": 336,
                        "spineAnimName": "reveal_sym_meter",
                        "anchor": [0.5, 0.5],

                        "x": 1232,
                        "y": 110,
                        "spinedata": {
                            "spinename": "ani_reveal",
                            "animationname": "reveal_sym_meter",
                            "loop": false,
                            "timeScale": 0.9

                        },
                    },
                    {
                        "name": "bg_reveal_sym9",
                        "image": "bg_reveal_sym",
                        "type": "Image",
                        "layout": false,
                        "uimode": "desktop",
                        "class": "",
                        "anchor": [0.5, 0.5],
                        "visible": false,
                        "width": 66,
                        "height": 66,
                        "x": 1312,
                        "y": 110
                    },
                    {
                        "id": "ani_bg_reveal_sym9",
                        "name": "ani_bg_reveal_sym9",
                        "type": "Spine",
                        "width": 356.85,
                        "height": 279,
                        "image": "ani_reveal",
                        "animationSpeed": 0.2,
                        "playing": false,
                        "loop": false,
                        "visible": true,
                        "effectType": "abc",
                        "maskHeight": 336,
                        "spineAnimName": "reveal_sym_meter",
                        "anchor": [0.5, 0.5],
                        "x": 1312,
                        "y": 110,
                        "spinedata": {
                            "spinename": "ani_reveal",
                            "animationname": "reveal_sym_meter",
                            "loop": false,
                            "timeScale": 0.9

                        },
                    },

                ]
            },
            {
                "id": "mobileMainContainerReveal",
                "name": "mobileMainContainerReveal",
                "type": "Container",
                "class": "",
                "x": 0,
                "y": 0,
                "layout": true,
                "uimode": "mobile",
                "filterTypes": [],
                "parentLayer": "baseLayer",
                child: [
                    {
                        "name": "bg_reveal_sym1",
                        "image": "bg_reveal_sym",
                        "type": "Image",
                        "layout": true,
                        "uimode": "mobile",
                        "class": "",
                        "anchor": [0.5, 0.5],
                        "visible": false,
                        "width": 66,
                        "height": 66,
                        "x": 673,
                        "y": 110
                    },
                    {
                        "id": "ani_bg_reveal_sym1",
                        "name": "ani_bg_reveal_sym1",
                        "type": "Spine",
                        "width": 356.85,
                        "height": 279,
                        "image": "ani_reveal",
                        "animationSpeed": 0.2,
                        "playing": false,
                        "loop": false,
                        "visible": true,
                        "effectType": "abc",
                        "maskHeight": 336,
                        "spineAnimName": "reveal_sym",
                        "x": 673,
                        "y": 110,
                        "spinedata": {
                            "spinename": "ani_reveal",
                            "animationname": "reveal_sym",
                            "loop": false,
                            "timeScale": 0.9

                        },
                    },
                    {
                        "name": "bg_reveal_sym2",
                        "image": "bg_reveal_sym",
                        "type": "Image",
                        "layout": true,
                        "uimode": "mobile",
                        "class": "",
                        "anchor": [0.5, 0.5],
                        "visible": false,
                        "width": 66,
                        "height": 66,
                        "x": 752,
                        "y": 110
                    },
                    {
                        "id": "ani_bg_reveal_sym2",
                        "name": "ani_bg_reveal_sym2",
                        "type": "Spine",
                        "width": 356.85,
                        "height": 279,
                        "image": "ani_reveal",
                        "animationSpeed": 0.2,
                        "playing": false,
                        "loop": false,
                        "visible": true,
                        "effectType": "abc",
                        "maskHeight": 336,
                        "spineAnimName": "reveal_sym",
                        "x": 752,
                        "y": 110,
                        "spinedata": {
                            "spinename": "ani_reveal",
                            "animationname": "reveal_sym",
                            "loop": false,
                            "timeScale": 0.9

                        },
                    },
                    {
                        "name": "bg_reveal_sym3",
                        "image": "bg_reveal_sym",
                        "type": "Image",
                        "layout": true,
                        "uimode": "mobile",
                        "class": "",
                        "anchor": [0.5, 0.5],
                        "visible": false,
                        "width": 66,
                        "height": 66,
                        "x": 832,
                        "y": 110
                    },
                    {
                        "id": "ani_bg_reveal_sym3",
                        "name": "ani_bg_reveal_sym3",
                        "type": "Spine",
                        "width": 356.85,
                        "height": 279,
                        "image": "ani_reveal",
                        "animationSpeed": 0.2,
                        "playing": false,
                        "loop": false,
                        "visible": true,
                        "effectType": "abc",
                        "maskHeight": 336,
                        "spineAnimName": "reveal_sym",
                        "x": 832,
                        "y": 110,
                        "spinedata": {
                            "spinename": "ani_reveal",
                            "animationname": "reveal_sym",
                            "loop": false,
                            "timeScale": 0.9

                        },
                    },
                    {
                        "name": "bg_reveal_sym4",
                        "image": "bg_reveal_sym",
                        "type": "Image",
                        "layout": true,
                        "uimode": "mobile",
                        "class": "",
                        "anchor": [0.5, 0.5],
                        "visible": false,
                        "width": 66,
                        "height": 66,
                        "x": 912,
                        "y": 110
                    },
                    {
                        "id": "ani_bg_reveal_sym4",
                        "name": "ani_bg_reveal_sym4",
                        "type": "Spine",
                        "width": 356.85,
                        "height": 279,
                        "image": "ani_reveal",
                        "animationSpeed": 0.2,
                        "playing": false,
                        "loop": false,
                        "visible": true,
                        "effectType": "abc",
                        "maskHeight": 336,
                        "spineAnimName": "reveal_sym",
                        "x": 912,
                        "y": 110,
                        "spinedata": {
                            "spinename": "ani_reveal",
                            "animationname": "reveal_sym",
                            "loop": false,
                            "timeScale": 0.9

                        },
                    },
                    {
                        "name": "bg_reveal_sym5",
                        "image": "bg_reveal_sym",
                        "type": "Image",
                        "layout": true,
                        "uimode": "mobile",
                        "class": "",
                        "anchor": [0.5, 0.5],
                        "visible": false,
                        "width": 66,
                        "height": 66,
                        "x": 992,
                        "y": 110
                    },
                    {
                        "id": "ani_bg_reveal_sym5",
                        "name": "ani_bg_reveal_sym5",
                        "type": "Spine",
                        "width": 356.85,
                        "height": 279,
                        "image": "ani_reveal",
                        "animationSpeed": 0.2,
                        "playing": false,
                        "loop": false,
                        "visible": true,
                        "effectType": "abc",
                        "maskHeight": 336,
                        "spineAnimName": "reveal_sym",
                        "x": 992,
                        "y": 110,
                        "spinedata": {
                            "spinename": "ani_reveal",
                            "animationname": "reveal_sym",
                            "loop": false,
                            "timeScale": 0.9

                        },
                    },
                    {
                        "name": "bg_reveal_sym6",
                        "image": "bg_reveal_sym",
                        "type": "Image",
                        "layout": true,
                        "uimode": "mobile",
                        "class": "",
                        "anchor": [0.5, 0.5],
                        "visible": false,
                        "width": 66,
                        "height": 66,
                        "x": 1072,
                        "y": 110
                    },
                    {
                        "id": "ani_bg_reveal_sym6",
                        "name": "ani_bg_reveal_sym6",
                        "type": "Spine",
                        "width": 356.85,
                        "height": 279,
                        "image": "ani_reveal",
                        "animationSpeed": 0.2,
                        "playing": false,
                        "loop": false,
                        "visible": true,
                        "effectType": "abc",
                        "maskHeight": 336,
                        "spineAnimName": "reveal_sym",
                        "x": 1072,
                        "y": 110,
                        "spinedata": {
                            "spinename": "ani_reveal",
                            "animationname": "reveal_sym",
                            "loop": false,
                            "timeScale": 0.9

                        },
                    },
                    {
                        "name": "bg_reveal_sym7",
                        "image": "bg_reveal_sym",
                        "type": "Image",
                        "layout": true,
                        "uimode": "mobile",
                        "class": "",
                        "anchor": [0.5, 0.5],
                        "visible": false,
                        "width": 66,
                        "height": 66,
                        "x": 1152,
                        "y": 110
                    },
                    {
                        "id": "ani_bg_reveal_sym7",
                        "name": "ani_bg_reveal_sym7",
                        "type": "Spine",
                        "width": 356.85,
                        "height": 279,
                        "image": "ani_reveal",
                        "animationSpeed": 0.2,
                        "playing": false,
                        "loop": false,
                        "visible": true,
                        "effectType": "abc",
                        "maskHeight": 336,
                        "spineAnimName": "reveal_sym",
                        "x": 1152,
                        "y": 110,
                        "spinedata": {
                            "spinename": "ani_reveal",
                            "animationname": "reveal_sym",
                            "loop": false,
                            "timeScale": 0.9

                        },
                    },
                    {
                        "name": "bg_reveal_sym8",
                        "image": "bg_reveal_sym",
                        "type": "Image",
                        "layout": true,
                        "uimode": "mobile",
                        "class": "",
                        "anchor": [0.5, 0.5],
                        "visible": false,
                        "width": 66,
                        "height": 66,
                        "x": 1232,
                        "y": 110
                    },
                    {
                        "id": "ani_bg_reveal_sym8",
                        "name": "ani_bg_reveal_sym8",
                        "type": "Spine",
                        "width": 356.85,
                        "height": 279,
                        "image": "ani_reveal",
                        "animationSpeed": 0.2,
                        "playing": false,
                        "loop": false,
                        "visible": true,
                        "effectType": "abc",
                        "maskHeight": 336,
                        "spineAnimName": "reveal_sym",
                        "x": 1232,
                        "y": 110,
                        "spinedata": {
                            "spinename": "ani_reveal",
                            "animationname": "reveal_sym",
                            "loop": false,
                            "timeScale": 0.9

                        },
                    },
                    {
                        "name": "bg_reveal_sym9",
                        "image": "bg_reveal_sym",
                        "type": "Image",
                        "layout": true,
                        "uimode": "mobile",
                        "class": "",
                        "anchor": [0.5, 0.5],
                        "visible": false,
                        "width": 66,
                        "height": 66,
                        "x": 1312,
                        "y": 110
                    },
                    {
                        "id": "ani_bg_reveal_sym9",
                        "name": "ani_bg_reveal_sym9",
                        "type": "Spine",
                        "width": 356.85,
                        "height": 279,
                        "image": "ani_reveal",
                        "animationSpeed": 0.2,
                        "playing": false,
                        "loop": false,
                        "visible": true,
                        "effectType": "abc",
                        "maskHeight": 336,
                        "spineAnimName": "reveal_sym",
                        "x": 1270,
                        "y": 110,
                        "spinedata": {
                            "spinename": "ani_reveal",
                            "animationname": "reveal_sym",
                            "loop": false,
                            "timeScale": 0.9

                        },
                    },

                ]

            },
        ],
    }

};

export const RevealFeatureConfigurationContext = React.createContext(
    {}
);
