import { frameworkFreeGame, objectTypes } from "@bonanzainteractive/slote_core";

frameworkFreeGame.data = {

    "POS_X": 0,
    "POS_Y": 0,
    "COMPONENTS": [
        {
            "id": "BMFreeGameContainer_baseLayer",
            "name": "BMFreeGameContainer_baseLayer",
            "type": "Container",
            "x": 0,
            "y": 0,
            "filterTypes": [],
            "parentLayer": "baseLayer",
            child: [
                {
                    "id": "BMFreeGameComponent",
                    "name": "GofFreeGameBaseLayer",
                    "type": "Tag",
                    "filterTypes": [],
                    child: [
                        {
                            "name": "freegame_Background",
                            "image": "freegame_Desk_bg",
                            "type": "Image",
                            // "uimode": "desktop",
                            "anchor": [0.5, 0.5],
                            "visible": true,
                            "width": 1920,
                            "height": 1920,
                            "x": 960,
                            "y": 566
                        },
                        // {
                        //     "id": "FGanimationDesktop",
                        //     "name": "freegame_animation",
                        //     "type": "Spine",
                        //     "width": 1922,
                        //     "height": 1082,
                        //     "image": "freegame",
                        //     "uimode": "desktop",
                        //     "animationSpeed": 0.2,
                        //     "playing": false,
                        //     "loop": false,
                        //     "visible": true,
                        //     "effectType": "abc",
                        //     "maskHeight": 336,
                        //     "spineAnimName": "freegame",
                        //     "x": 960,
                        //     "y": 540,
                        //     "spinedata": {
                        //         "spinename": "freegame_animation",
                        //         "animationname": "freegame",
                        //         "loop": true,
                        //         "timeScale": 0.5
                        //     },
                        // },
                        {
                            "name": "freegame_bg",
                            "image": "freegame_bg",
                            "type": "Image",
                            "layout": true,
                            "uimode": "mobile",
                            "anchor": [0.5, 0.5],
                            "visible": true,
                            "width": 1920,
                            "height": 1920,
                            "x": 540,
                            "y": 960
                        },
                        {
                            "name": "FreeGameLogo",
                            "image": "fgLogo",
                            "type": "Image",
                            "layout": true,
                            "parentLayer": "specialAnimationLayer",
                            "visible": true,
                            "width": 327,
                            "height": 286,
                            "x": 2,
                            "y": -77
                        },
                        {
                            "name": "FreeGameLogo_Portrait",
                            "image": "fgLogo_Portrait",
                            "type": "Image",
                            "layout": true,
                            "parentLayer": "specialAnimationLayer",
                            "uimode": "mobile",
                            "visible": true,
                            "width": 587,
                            "height": 1051,
                            "x": 300,
                            "y": -600
                        },
                        {
                            "name": "frame_FG_Image_desktop",
                            "image": "frameFG",
                            "type": "Image",
                            "layout": false,
                            "uimode": "desktop",
                            "visible": true,
                            "width": 1441,
                            "height": 949,
                            "x": 232,
                            "y": 0
                        },
                        {
                            "name": "frame_FG_Image_Mob",
                            "image": "frameFG",
                            "type": "Image",
                            "layout": true,
                            "uimode": "mobile",
                            "visible": true,
                            "width": 1441,
                            "height": 949,
                            "x": -2.5,
                            "y": -3
                        },
                    ]
                }
            ]

        },
        {
            "id": "BMFreeGameContainer_specialLayer",
            "name": "BMFreeGameContainer_specialLayer",
            "type": "Container",
            "x": 0,
            "y": 0,
            "filterTypes": [],
            "parentLayer": "specialAnimationLayer",
            child: [
                {
                    "id": "BMFreeGameComponent",
                    "name": "GofFreeGameSpecialLayer",
                    "type": "Tag",
                    "filterTypes": [],
                    child: [
                        {
                            "name": "FG_gameLogo_Anim_desktop",
                            "type": "Animation",
                            "width": 324,
                            "height": 334,
                            "layout": true,
                            "uimode": "desktop",
                            "image": "bg_gamelogo",
                            "parentLayer": "specialAnimationLayer",
                            "animationSpeed": 0.5,
                            "playing": false,
                            "loop": false,
                            "visible": true,
                            "anchor": [0.5, 0.5],
                            "x": 118.5,
                            "y": 186.5,
                            "animations": {
                                "anim": ["bg_gamelogo"],
                            },
                        },
                        {
                            "name": "FG_gameLogo_Anim_mobile",
                            "type": "Animation",
                            "width": 324,
                            "height": 334,
                            "layout": true,
                            "uimode": "mobile",
                            "image": "bg_gamelogo",
                            "parentLayer": "specialAnimationLayer",
                            "animationSpeed": 0.5,
                            "playing": false,
                            "loop": false,
                            "visible": true,
                            "anchor": [0.5, 0.5],
                            "x": 118.5,
                            "y": 186.5,
                            "animations": {
                                "anim": ["bg_gamelogo"],
                            },
                        },

                        {
                            "name": "featureCountMeter",
                            "image": "featureCountMeter",
                            "type": "Image",
                            "layout": true,
                            "uimode": "desktop",
                            "visible": true,
                            "width": 272,
                            "height": 89,
                            "x": 1618,
                            "y": 350
                        },
                        {
                            "name": "featureCountMeter",
                            "image": "featureCountMeter",
                            "type": "Image",
                            "layout": true,
                            "uimode": "mobile",
                            "visible": true,
                            "width": 272,
                            "height": 78,
                            "x": 730,
                            "y": 530
                        },
                        {
                            "name": "bgGraphic_for_FG",
                            "type": "Graphic",
                            "shape": "rectangle",
                            "visible": false,
                            "alpha": 0.52,
                            "color": "0x000000",
                            "x": 415.5,
                            "y": 237,
                            "width": 1070,
                            "height": 631.5,
                        },
                        {
                            "name": "freeGameCounter",
                            "image": "middleBarFG",
                            "type": "Image",
                            "layout": false,
                            "uimode": "desktop",
                            "visible": true,
                            "width": 333,
                            "height": 78,
                            "x": 1590,
                            "y": 468
                        },

                        {
                            "name": "freeGameCounter",
                            "image": "middleBarFG",
                            "type": "Image",
                            "filterTypes": [],
                            "layout": true,
                            "uimode": "mobile",
                            "visible": true,
                            "width": 345,
                            "height": 78,
                            "x": 10,
                            "y": 530
                        },
                        {
                            "id": "text_10_desktop",
                            "name": "text_FreeGame_value1",
                            "type": "Text",
                            "x": 1690.5,
                            "y": 390,
                            "width": 80,
                            "layout": false,
                            "uimode": "desktop",
                            "visible": true,
                            "text": "00",
                            "scaleToFit": true,
                            "anchor": [0.5, 0.5],
                            "textStyle": {
                                fontFamily: 'Impact',
                                fontSize: 40,
                                fontStyle: 'Normal',
                                align: 'center',
                                fill: ['#fff000', '#f19901'],
                                stroke: '#1b3201',
                                strokeThickness: 1,
                                dropShadow: true,
                                dropShadowColor: '#101f00',
                                dropShadowDistance: 2,
                            }
                        },
                        {
                            "id": "text_10_desktop",
                            "name": "text_FreeGame_value1",
                            "type": "Text",
                            "x": 1152.5,
                            "y": 63,
                            "width": 80,
                            "layout": true,
                            "uimode": "mobile",
                            "visible": true,
                            "text": "00",
                            "scaleToFit": true,
                            "anchor": [0.5, 0.5],
                            "textStyle": {
                                fontFamily: 'MYP Bold',
                                fontSize: 35,
                                fontStyle: 'Normal',
                                align: 'center',
                                fill: ['#fff000', '#f19901'],
                                stroke: '#1b3201',
                                strokeThickness: 1,
                                dropShadow: true,
                                dropShadowColor: '#101f00',
                                dropShadowDistance: 2,
                            }
                        },
                        //ANCHOR - OUT OF TEXT -------------------
                        {
                            "id": "text_11_desktop",
                            "name": "text_FreeGame_OF_label",
                            "type": "Text",
                            "x": 1750.1,
                            "y": 390,
                            "width": 100,
                            "layout": false,
                            "uimode": "desktop",
                            "visible": true,
                            "text": "freegameText3",
                            "scaleToFit": true,
                            "anchor": [0.5, 0.5],
                            "textStyle": {
                                fontFamily: 'Impact',
                                fontSize: 28,
                                fontStyle: 'Normal',
                                align: 'center',
                                fill: ['#ffffff']
                            }
                        },
                        {
                            "id": "text_11_desktop",
                            "name": "text_FreeGame_OF_label",
                            "type": "Text",
                            "x": 1234.5,
                            "y": 63,
                            "width": 100,
                            "layout": true,
                            "uimode": "mobile",
                            "visible": true,
                            "text": "freegameText3",
                            "scaleToFit": true,
                            "anchor": [0.5, 0.5],
                            "textStyle": {
                                fontFamily: 'MYP Bold',
                                fontSize: 28,
                                fontStyle: 'Normal',
                                align: 'center',
                                fill: ['#ffffff']
                            }
                        },
                        {
                            "id": "text_12_desktop",
                            "name": "text_FreeGame_value2",
                            "type": "Text",
                            "x": 1821.4,
                            "y": 390,
                            "width": 80,
                            "class": "",
                            "layout": false,
                            "uimode": "desktop",
                            "visible": true,
                            "text": "00",
                            "scaleToFit": true,
                            "anchor": [0.5, 0.5],
                            "textStyle": {
                                fontFamily: 'Impact',
                                fontSize: 40,
                                fontStyle: 'Normal',
                                align: 'center',
                                fill: ['#fff000', '#f19901'],
                                stroke: '#1b3201',
                                strokeThickness: 1,
                                dropShadow: true,
                                dropShadowColor: '#101f00',
                                dropShadowDistance: 2,
                            }
                        },
                        {
                            "id": "text_12_desktop",
                            "name": "text_FreeGame_value2",
                            "type": "Text",
                            "x": 1323.5,
                            "y": 63,
                            "width": 80,
                            "layout": true,
                            "uimode": "mobile",
                            "visible": true,
                            "text": "00",
                            "scaleToFit": true,
                            "anchor": [0.5, 0.5],
                            "textStyle": {
                                fontFamily: 'MYP Bold',
                                fontSize: 35,
                                fontStyle: 'Normal',
                                align: 'center',
                                fill: ['#fff000', '#f19901'],
                                stroke: '#1b3201',
                                strokeThickness: 1,
                                dropShadow: true,
                                dropShadowColor: '#101f00',
                                dropShadowDistance: 2,
                            }
                        },
                        {
                            "id": "text_14_desktop",
                            "name": "text_TotalWin_value",
                            "type": "Text",
                            "x": 150,
                            "y": 900,
                            "width": 220,
                            "text": "000",
                            "layout": true,
                            "uimode": "desktop",
                            "visible": false,
                            "scaleToFit": true,
                            "anchor": [0.5, 0.5],
                            "textStyle": {
                                fontFamily: 'Arial',
                                fontSize: 35,
                                fill: ['#ffa440', '#ffb864', '#ff9320', '#ffff4e'],
                                fontWeight: 'bold',
                                stroke: '#5c1f03',
                                strokeThickness: 1,
                                dropShadow: true,
                                dropShadowColor: '#000000',
                                dropShadowDistance: 2,
                            },
                            "parentLayer": "specialAnimationLayer",
                        },
                        // ************************************Freegame Button-Panel UI*******************************************

                        {
                            "id": "text_2_mobile",
                            "name": "text_FreeGame_value1_mobileFG",
                            "type": "Text",
                            "x": 0,
                            "y": 0,
                            "width": 806,
                            "text": "00",
                            "visible": false,
                            "layout": true,
                            "uimode": "mobile",
                            "scaleToFit": true,
                            "anchor": [0.5, 0.5],
                            "textStyle": {
                                fontFamily: 'Arial',
                                fontSize: 42,
                                fontWeight: 'bold',
                                fill: ['#ffffff'],
                            },
                            "parentLayer": "specialAnimationLayer",
                        },
                        {
                            "id": "text_3_mobile",
                            "name": "text_FreeGame_OF_label_mobileFG",
                            "type": "Text",
                            "x": 698,
                            "y": 940,
                            "visible": true,
                            "width": 90,
                            "text": "freegameText3",
                            "layout": true,
                            "uimode": "mobile",
                            "scaleToFit": true,
                            "anchor": [0.5, 0.5],
                            "textStyle": {
                                fontFamily: 'Arial',
                                fontSize: 50,
                                fontWeight: 'bold',
                                fill: ['#ffffff'],
                            },
                            "parentLayer": "specialAnimationLayer",
                        },
                        {
                            "id": "text_4_mobile",
                            "name": "text_FreeGame_value2_mobileFG",
                            "type": "Text",
                            "x": 830,
                            "y": 940,
                            "width": 76,
                            "text": "",
                            "visible": true,
                            "layout": true,
                            "uimode": "mobile",
                            "scaleToFit": true,
                            "anchor": [0.5, 0.5],
                            "textStyle": {
                                fontFamily: 'Arial',
                                fontSize: 50,
                                fontWeight: 'bold',
                                fill: ['#ffffff'],
                            },
                            "parentLayer": "specialAnimationLayer",
                        },


                        {
                            "id": "text_5_mobile",
                            "name": "text_TotalWin_label_mobileFG",
                            "type": "Text",
                            "x": 1400,
                            "y": 940,
                            "width": 490,
                            "visible": false,
                            "layout": true,
                            "uimode": "mobile",
                            "text": "freegameText5",
                            "scaleToFit": true,
                            "anchor": [1, 0.5],
                            "textStyle": {
                                fontFamily: 'Arial',
                                fontSize: 50,
                                fontWeight: 'bold',
                                fill: ['#ffffff'],
                            },
                            "parentLayer": "specialAnimationLayer",
                        },
                        {
                            "id": "text_6_mobile",
                            "name": "text_TotalWin_value_mobileFG",
                            "type": "Text",
                            "x": 1308,
                            "y": 940,
                            "width": 820,
                            "layout": true,
                            "uimode": "mobile",
                            "text": "00",
                            "visible": false,
                            "scaleToFit": true,
                            "anchor": [0.5, 0.5],
                            "textStyle": {
                                fontFamily: 'Arial',
                                fontSize: 50,
                                fill: ['#ffffff'],
                                fontWeight: 'bold',
                            },
                            "parentLayer": "specialAnimationLayer",
                        },
                        {
                            "id": "text_7_mobile",
                            "name": "Mobiletext_balance_labelFG",
                            "type": "Text",
                            "layout": true,
                            "uimode": "mobile",
                            "visible": false,
                            "x": 170,
                            "y": 1050,
                            "width": 480,
                            "text": "buttonPanelText_3",
                            "scaleToFit": true,
                            "anchor": [1, 0.5],
                            "textStyle": {
                                fontFamily: 'Arial',
                                fontSize: 32,
                                fontWeight: 'bold',
                                fill: ['#ffffff'],
                            },
                            "parentLayer": "specialAnimationLayer",
                        },
                        {
                            "id": "text_8_mobile",
                            "name": "Mobiletext_mobColonSymbol2FG",
                            "layout": true,
                            "uimode": "mobile",
                            "visible": false,
                            "type": "Text",
                            "x": 315,
                            "y": 1048,
                            "width": 18,
                            "text": "buttonPanelText_13",
                            "scaleToFit": true,
                            "anchor": [0.5, 0.5],
                            "textStyle": {
                                fontFamily: 'Arial',
                                fontSize: 32,
                                fontWeight: 'bold',
                                fill: ['#ffffff'],
                            },
                            "parentLayer": "specialAnimationLayer",
                        },
                        {
                            "id": "text_9_mobile",
                            "name": "Mobiletext_balance_valueFG",
                            "type": "Text",
                            "layout": true,
                            "uimode": "mobile",
                            "visible": false,
                            "x": 330,
                            "y": 1050,
                            "width": 210,
                            "text": "",
                            "scaleToFit": true,
                            "anchor": [0, 0.5],
                            "textStyle": {
                                fontFamily: 'Arial',
                                fontSize: 32,
                                fill: ['#ffffff'],
                            },
                            "parentLayer": "specialAnimationLayer",
                        },

                        {
                            "id": "text_10_mobile",
                            "name": "Mobiletext_bet_labelFG",
                            "type": "Text",
                            "layout": true,
                            "visible": false,
                            "uimode": "mobile",
                            "x": 1683,
                            "y": 1050,
                            "width": 250,
                            "text": "buttonPanelText_1",
                            "scaleToFit": true,
                            "anchor": [1, 0.5],
                            "textStyle": {
                                fontFamily: 'Arial',
                                fontSize: 32,
                                fontWeight: 'bold',
                                fill: ['#ffffff'],
                            },
                            "parentLayer": "specialAnimationLayer",
                        },
                        {
                            "id": "text_11_mobile",
                            "name": "Mobiletext_mobColonSymbol3FG",
                            "layout": true,
                            "visible": false,
                            "uimode": "mobile",
                            "type": "Text",
                            "x": 1693,
                            "y": 1048,
                            "width": 18,
                            "text": "buttonPanelText_13",
                            "scaleToFit": true,
                            "anchor": [0.5, 0.5],
                            "textStyle": {
                                fontFamily: 'Arial',
                                fontSize: 36,
                                fontWeight: 'bold',
                                fill: ['#ffffff'],
                            },
                            "parentLayer": "specialAnimationLayer",
                        },
                        {
                            "id": "text_12_mobile",
                            "name": "Mobiletext_bet_valueFG",
                            "type": "Text",
                            "layout": true,
                            "visible": false,
                            "uimode": "mobile",
                            "x": 1700,
                            "y": 1050,
                            "width": 100,
                            "text": "MobViewButtonPanelText3",
                            "scaleToFit": true,
                            "anchor": [0, 0.5],
                            "textStyle": {
                                fontFamily: 'Arial',
                                fontSize: 32,
                                fill: ['#ffffff'],

                            },
                            "parentLayer": "specialAnimationLayer",
                        },
                        {
                            "id": "text_15_mobile",
                            "name": "Mobiletext_win_value_FG",
                            "type": "Text",
                            "layout": true,
                            "uimode": "mobile",
                            "x": 1068,
                            "y": 940,
                            "width": 200,
                            "text": "MobViewButtonPanelText1",
                            "scaleToFit": true,
                            "anchor": [0.5, 0.5],
                            "textStyle": {
                                fontFamily: 'Arial',
                                fontSize: 60,
                                fill: ['#ffffff'],
                            },
                            "parentLayer": "specialAnimationLayer",
                        },
                        {
                            "name": "FG_reTrigger_blast_Anim_mobile",
                            "type": "Animation",
                            "width": 960,
                            "height": 540,
                            "layout": true,
                            "uimode": "mobile",
                            "image": "FG_reTrigger",
                            "animationSpeed": 0.9,
                            "playing": true,
                            "loop": false,
                            "visible": false,
                            "anchor": [0, 0],
                            "x": 845,
                            "y": 893,
                            "animations": {
                                "anim": ["FG_reTrigger"],
                            },
                            "parentLayer": "specialAnimationLayer",
                        },



                        {
                            "name": "freeGameBlackScreen",
                            "type": "Graphic",
                            "shape": "rectangle",
                            "visible": false,
                            "alpha": 1,
                            "color": "0x000000",
                            "x": 0,
                            "y": 0,
                            "width": 1920,
                            "height": 1080,
                        },
                        {
                            "name": "freeGameBlackScreenPortrait",
                            "type": "Graphic",
                            "shape": "rectangle",
                            "visible": false,
                            "alpha": 1,
                            "color": "0x000000",
                            "x": 0,
                            "y": 0,
                            "width": 1080,
                            "height": 1920,
                        },
                        {
                            "id": "SoundText",
                            "name": "SoundText",
                            "type": "Tag",

                            "parentLayer": "specialAnimationLayer",
                            "filterTypes": [],
                            child: []
                        },
                        {
                            "name": "RevealFeature",
                            "type": "Tag",
                            child: []
                        },
                        {
                            "name": "CoinSymbolAnimation",
                            "type": "Tag",
                            child: []
                        },
                        {
                            "name": "LeftRevealMeter",
                            "type": "Tag",
                            child: []
                        },
                        {
                            "name": "ConvertSymbolAnimation",
                            "type": "Tag",
                            child: []
                        },
                        {
                            "name": "collecter_bg_feature",
                            "image": "wins_digit_base",
                            "type": "Image",
                            "layout": false,
                            "uimode": "desktop",
                            "anchor": [0.5, 0.5],
                            "visible": false,
                            "alpha": 0.5,
                            "width": 1080,
                            "height": 220,
                            "x": 950,
                            "y": 560,
                        },
                        {
                            "name": "collecter_bg_feature",
                            "image": "wins_digit_base",
                            "type": "Image",
                            "layout": true,
                            "uimode": "mobile",
                            "anchor": [0.5, 0.5],
                            "visible": false,
                            "alpha": 0.5,
                            "width": 1060,
                            "height": 220,
                            "x": 540.5,
                            "y": 1098.5,
                        },
                        {
                            "id": "text_13_desktop",
                            "name": "text_FreeGame_levelUp",
                            "type": "Text",
                            "x": 957,
                            "y": 550,
                            "width": 550,
                            "layout": false,
                            "uimode": "desktop",
                            "visible": false,
                            "text": "Level Up",
                            "scaleToFit": true,
                            "anchor": [0.5, 0.5],
                            "textStyle": {
                                fontFamily: 'Impact',
                                fontSize: 188,
                                fontStyle: 'Normal',
                                align: 'center',
                                fill: ['#fff600', '#f19901'],
                                stroke: '#fafd00',
                                strokeThickness: 3,
                                dropShadow: true,
                                dropShadowColor: '#101f00',
                                letterSpacing: 5,
                                dropShadowDistance: 8,
                                distance: 8
                            }
                        },
                        {
                            "id": "text_13_desktop",
                            "name": "text_FreeGame_levelUp",
                            "type": "Text",
                            "x": 540.5,
                            "y": 1086,
                            "width": 550,
                            "layout": true,
                            "uimode": "mobile",
                            "visible": false,
                            "text": "Level Up",
                            // "scaleToFit": true,
                            "anchor": [0.5, 0.5],
                            "textStyle": {
                                // fontFamily: 'Impact',
                                fontFamily: 'MYP Bold',
                                fontSize: 124,
                                fontStyle: 'Normal',
                                align: 'center',
                                fill: ['#fff600', '#f19901'],
                                stroke: '#fafd00',
                                strokeThickness: 3,
                                dropShadow: true,
                                dropShadowColor: '#101f00',
                                letterSpacing: 5,
                                dropShadowDistance: 8,
                                distance: 8
                            }
                        },
                        {
                            "id": "currentCounter",
                            "name": "currentCounter",
                            "type": "Text",
                            "x": 1656.5,
                            "y": 505,
                            "width": 80,
                            "class": "",
                            "layout": false,
                            "uimode": "desktop",
                            "visible": true,
                            "text": "00",
                            "scaleToFit": true,
                            "anchor": [0.8, 0.5],
                            "textStyle": {
                                fontFamily: 'Impact',
                                fontSize: 35,
                                fontStyle: 'Normal',
                                align: 'center',
                                fill: ['#fff000', '#f19901'],
                                stroke: '#1b3201',
                                strokeThickness: 1,
                                dropShadow: true,
                                dropShadowColor: '#101f00',
                                dropShadowDistance: 2,
                            }
                        },
                        {
                            "id": "currentCounter",
                            "name": "currentCounter",
                            "type": "Text",
                            "x": 0,
                            "y": 0,
                            "width": 80,
                            "layout": true,
                            "uimode": "mobile",
                            "visible": true,
                            "text": "00",
                            "scaleToFit": true,
                            "anchor": [0.8, 0.5],
                            "textStyle": {
                                fontFamily: 'MYP Bold',
                                fontSize: 35,
                                fontStyle: 'Normal',
                                align: 'center',
                                fill: ['#fff000', '#f19901'],
                                stroke: '#1b3201',
                                strokeThickness: 1,
                                dropShadow: true,
                                dropShadowColor: '#101f00',
                                dropShadowDistance: 2,
                            }
                        },
                        {
                            "id": "slashText",
                            "name": "slashText",
                            "type": "Text",
                            "x": 1670.9,
                            "y": 505,
                            "width": 28,
                            "layout": false,
                            "uimode": "desktop",
                            "visible": true,
                            "text": "/",
                            "scaleToFit": true,
                            "anchor": [0.5, 0.5],
                            "textStyle": {
                                fontFamily: 'Impact',
                                fontSize: 32,
                                fontStyle: 'Normal',
                                align: 'center',
                                fill: ['#fff000', '#f19901'],
                                stroke: '#fafd00',
                                strokeThickness: 1,
                                dropShadow: true,
                                dropShadowColor: '#101f00',
                                dropShadowDistance: 2,
                            }
                        },
                        {
                            "id": "slashText",
                            "name": "slashText",
                            "type": "Text",
                            "x": 0,
                            "y": 0,
                            "width": 28,
                            "layout": true,
                            "uimode": "mobile",
                            "visible": true,
                            "text": "/",
                            "scaleToFit": true,
                            "anchor": [0.5, 0.5],
                            "textStyle": {
                                fontFamily: 'MYP Regular',
                                fontSize: 30,
                                fontStyle: 'Normal',
                                align: 'center',
                                fill: ['#fff000', '#f19901'],
                                stroke: '#fafd00',
                                strokeThickness: 1,
                                dropShadow: true,
                                dropShadowColor: '#101f00',
                                dropShadowDistance: 2,
                            }
                        },
                        {
                            "id": "totalCounter",
                            "name": "totalCounter",
                            "type": "Text",
                            "x": 1696.5,
                            "y": 505,
                            "width": 80,
                            "layout": false,
                            "uimode": "desktop",
                            "visible": true,
                            "text": "00",
                            "scaleToFit": true,
                            "anchor": [0.5, 0.5],
                            "textStyle": {
                                fontFamily: 'Impact',
                                fontStyle: 'normal',
                                fontSize: 35,
                                fill: ['#fff000', '#f19901'],
                                align: 'center',
                                stroke: '#1b3201',
                                strokeThickness: 1,
                                dropShadow: true,
                                dropShadowColor: '#101f00',
                                dropShadowDistance: 2,
                                dropShadowSize: 2,
                            }
                        },
                        {
                            "id": "totalCounter",
                            "name": "totalCounter",
                            "type": "Text",
                            "x": 669.5,
                            "y": 65,
                            "width": 80,
                            "layout": true,
                            "uimode": "mobile",
                            "visible": true,
                            "text": "00",
                            "scaleToFit": true,
                            "anchor": [0.5, 0.5],
                            "textStyle": {
                                fontFamily: 'MYP Bold',
                                fontStyle: 'normal',
                                fontSize: 35,
                                fill: ['#fff000', '#f19901'],
                                align: 'center',
                                stroke: '#1b3201',
                                strokeThickness: 1,
                                dropShadow: true,
                                dropShadowColor: '#101f00',
                                dropShadowDistance: 2,
                                dropShadowSize: 2,
                            }
                        },
                        {
                            "id": "collectedText",
                            "name": "collectedText",
                            "type": "Text",
                            "x": 1767.5,
                            "y": 505,
                            "width": 156,
                            "height": 42,
                            "layout": false,
                            "uimode": "desktop",
                            "visible": true,
                            "text": "freegameText8",
                            "scaleToFit": true,
                            "anchor": [0.5, 0.5],
                            "textStyle": {
                                fontFamily: 'Impact',
                                fontSize: 22,
                                fontStyle: 'Normal',
                                align: 'center',
                                fill: ['#ffffff']
                            }
                        },
                        {
                            "id": "collectedText",
                            "name": "collectedText",
                            "type": "Text",
                            "x": 0,
                            "y": 0,
                            "width": 156,
                            "height": 42,
                            "layout": true,
                            "uimode": "mobile",
                            "visible": true,
                            "text": "freegameText8",
                            "scaleToFit": true,
                            "anchor": [0.5, 0.5],
                            "textStyle": {
                                fontFamily: 'MYP Bold',
                                fontSize: 22,
                                fontStyle: 'Normal',
                                align: 'center',
                                fill: ['#ffffff']
                            }
                        },
                        {
                            "name": "freegame_ui_base",
                            "image": "ui_base.png",
                            "type": objectTypes.Sprite,
                            "layout": false,
                            "uimode": "desktop",
                            "visible": true,
                            "width": 1920,
                            "height": 124,
                            "x": 0,
                            "y": 958,
                        },
                        {
                            "name": "freegame_ui_base",
                            "image": "ui_base_moblie_landscape.png",
                            "type": objectTypes.Sprite,
                            "layout": false,
                            "uimode": "mobile",
                            "visible": true,
                            "width": 1080,
                            "height": 157,
                            "x": 0,
                            "y": 1762,
                        },
                        {
                            "name": "freegame_ui_landscape",
                            "image": "ui_base_moblie_landscape.png",
                            "type": objectTypes.Sprite,
                            "layout": true,
                            "uimode": "mobile",
                            "visible": true,
                            "width": 1920,
                            "height": 136,
                            "x": 0,
                            "y": 795,
                        },

                        {
                            "name": "MysteryCounter",
                            "type": "Tag",
                            child: []
                        },

                        {
                            "id": "winShowerContainerTag",
                            "name": "WinShower",
                            "type": "Tag",
                            "class": "",
                            "parentLayer": "specialAnimationLayer",
                            "filterTypes": [],
                            child: []
                        },
                        {
                            "name": "FreegameMultiplier",
                            "type": "Tag",
                            child: []
                        },
                        {
                            "id": "winCelebrationContainerTag",
                            "name": "WinCelebration",
                            "type": "Tag",
                            "class": "",
                            "parentLayer": "specialAnimationLayer",
                            "filterTypes": [],
                            child: []
                        },

                        ///================================================== disabe button:===============================================

                        //ANCHOR - Buttons Free Game State ------------------
                        {
                            "id": "Button_4",
                            "name": "btn_bet_decrease",
                            "type": objectTypes.Sprite,
                            "buttonMode": false,
                            "uimode": "desktop",
                            "interactive": false,
                            "layout": false,
                            "x": 1354,
                            "y": 980,
                            "height": 30,
                            "width": 30,
                            "text": "",
                            "visible": true,
                            "buttonState": {
                                up: 'bet_minus_disable.png',
                                out: 'bet_minus_disable.png',
                                down: 'bet_minus_disable.png',
                                disable: 'bet_minus_disable.png',
                                enable: 'bet_minus_disable.png',
                                hover: 'bet_minus_disable.png'
                            },
                            "hitareaVisible": false,
                            "shapeVisible": false,
                            "shape": {}
                        },
                        // Mobile
                        {
                            "id": "Button_4",
                            "name": "btn_bet_decrease",
                            "type": objectTypes.Sprite,
                            "buttonMode": false,
                            "uimode": "mobile",
                            "layout": true,
                            "interactive": true,
                            "x": 1330,
                            "y": 960,
                            "height": 52,
                            "width": 52,
                            "text": "",
                            "visible": true,
                            "buttonState": {
                                up: 'bet_minus_disable_moblie_landscape.png',
                                out: 'bet_minus_disable_moblie_landscape.png',
                                down: 'bet_minus_disable_moblie_landscape.png',
                                disable: 'bet_minus_disable_moblie_landscape.png',
                                enable: 'bet_minus_disable_moblie_landscape.png',
                                hover: 'bet_minus_disable_moblie_landscape.png'
                            },
                            "hitareaVisible": false,
                            "shapeVisible": false,
                            "shape": {}
                        },
                        {
                            "id": "Button_3",
                            "name": "btn_bet_increase",
                            "type": objectTypes.Sprite,
                            "buttonMode": false,
                            "uimode": "desktop",
                            "layout": false,
                            "interactive": true,
                            "x": 1500,
                            "y": 979,
                            "height": 30,
                            "width": 30,
                            "text": "",
                            "visible": true,
                            "buttonState": {
                                up: 'bet_plus_disable.png',
                                out: 'bet_plus_disable.png',
                                down: 'bet_plus_disable.png',
                                disable: 'bet_plus_disable.png',
                                enable: 'bet_plus_disable.png',
                                hover: 'bet_plus_disable.png'
                            },
                            "hitareaVisible": false,
                            "shapeVisible": false,
                            "shape": {}
                        },
                        {
                            "id": "Button_3",
                            "name": "btn_bet_increase",
                            "type": objectTypes.Sprite,
                            "buttonMode": false,
                            "uimode": "mobile",
                            "layout": true,
                            "interactive": true,
                            "x": 1600,
                            "y": 960,
                            "height": 52,
                            "width": 52,
                            "text": "",
                            "visible": true,
                            "buttonState": {
                                up: 'bet_plus_disable_moblie_landscape.png',
                                out: 'bet_plus_disable_moblie_landscape.png',
                                down: 'bet_plus_disable_moblie_landscape.png',
                                disable: 'bet_plus_disable_moblie_landscape.png',
                                enable: 'bet_plus_disable_moblie_landscape.png',
                                hover: 'bet_plus_disable_moblie_landscape.png'
                            },
                            "hitareaVisible": false,
                            "shapeVisible": false,
                            "shape": {}
                        },
                        {
                            "id": "btn_spin",
                            "name": "btn_spin",
                            "type": objectTypes.Sprite,
                            "buttonMode": false,
                            "uimode": "desktop",
                            "layout": false,
                            "interactive": true,
                            "x": 1599,
                            "y": 750,
                            "height": 211,
                            "width": 211,
                            "text": "",
                            "visible": true,
                            "buttonState": {
                                up: 'spin_disable.png',
                                out: 'spin_disable.png',
                                down: 'spin_disable.png',
                                disable: 'spin_disable.png',
                                enable: 'spin_disable.png',
                                hover: 'spin_disable.png'
                            },
                            "hitareaVisible": false,
                            "shapeVisible": false,
                            "shape": {
                                type: "circle",
                                x: 70,
                                y: 60,
                                r: 80,
                            },
                        },
                        {
                            "id": "Button_M2",
                            "name": "btn_spin",
                            "type": objectTypes.Sprite,
                            "interactive": true,
                            "uimode": "mobile",
                            "layout": true,
                            "x": 1620,
                            "y": 440,
                            "height": 292,
                            "width": 292,
                            "text": "",
                            "visible": true,
                            "buttonMode": false,
                            "buttonState": {
                                up: 'spin_disable_moblie_landscape.png',
                                out: 'spin_disable_moblie_landscape.png',
                                down: 'spin_disable_moblie_landscape.png',
                                disable: 'spin_disable_moblie_landscape.png',
                                enable: 'spin_disable_moblie_landscape.png',
                                hover: 'spin_disable_moblie_landscape.png'
                            },
                            "hitareaVisible": false,
                            "shapeVisible": false,
                            "shape": {}
                        },
                        {
                            "id": "Button_2",
                            "name": "btn_paytable",
                            "type": objectTypes.Sprite,
                            "buttonMode": false,
                            "uimode": "desktop",
                            "layout": false,
                            "interactive": true,
                            "x": 150,
                            "y": 969,
                            "height": 48,
                            "width": 48,
                            "text": "",
                            "visible": true,
                            "buttonState": {
                                up: 'info_disable.png',
                                out: 'info_disable.png',
                                down: 'info_disable.png',
                                disable: 'info_disable.png',
                                enable: 'info_disable.png',
                                hover: 'info_disable.png'
                            },
                            "hitareaVisible": false,
                            "shapeVisible": false,
                            "shape": {}
                        },
                        {
                            "id": "Button_2",
                            "name": "btn_paytable",
                            "type": objectTypes.Sprite,
                            "buttonMode": false,
                            "uimode": "mobile",
                            "layout": true,
                            "interactive": true,
                            "x": 60,
                            "y": 700,
                            "height": 74,
                            "width": 74,
                            "text": "",
                            "visible": true,
                            "buttonState": {
                                up: 'info_disable_moblie_landscape.png',
                                out: 'info_disable_moblie_landscape.png',
                                down: 'info_disable_moblie_landscape.png',
                                disable: 'info_disable_moblie_landscape.png',
                                enable: 'info_disable_moblie_landscape.png',
                                hover: 'info_disable_moblie_landscape.png'
                            },
                            "hitareaVisible": false,
                            "shapeVisible": false,
                            "shape": {}
                        },
                        {
                            "id": "btn_menu",
                            "name": "btn_menu",
                            "type": objectTypes.Sprite,
                            "buttonMode": false,
                            "uimode": "desktop",
                            "interactive": true,
                            "layout": false,
                            "x": 30,
                            "y": 969,
                            "height": 48,
                            "width": 48,
                            "text": "",
                            "visible": true,
                            "buttonState": {
                                up: 'menu_disable.png',
                                out: 'menu_disable.png',
                                down: 'menu_disable.png',
                                disable: 'menu_disable.png',
                                enable: 'menu_disable.png',
                                hover: 'menu_disable.png'
                            },
                            "hitareaVisible": false,
                            "shapeVisible": false,
                        },
                        // Mobile
                        {
                            "id": "Button_M4",
                            "name": "btn_menu",
                            "type": objectTypes.Sprite,
                            "buttonMode": false,
                            "layout": true,
                            "uimode": "mobile",
                            "interactive": true,
                            "x": 70,
                            "y": 300,
                            "height": 74,
                            "width": 74,
                            "text": "",
                            "visible": true,
                            "buttonState": {
                                up: 'menu_disable_moblie_landscape.png',
                                out: 'menu_disable_moblie_landscape.png',
                                down: 'menu_disable_moblie_landscape.png',
                                disable: 'menu_disable_moblie_landscape.png',
                                enable: 'menu_disable_moblie_landscape.png',
                                hover: 'menu_disable_moblie_landscape.png'
                            },
                            "hitareaVisible": false,
                            "shapeVisible": false,
                            "shape": {}
                        },
                        {
                            "id": "Button_8",
                            "name": "btn_autoplay_desktop",
                            "type": objectTypes.Sprite,
                            "buttonMode": false,
                            "uimode": "desktop",
                            "interactive": false,
                            "x": 1800.5,
                            "y": 895,
                            "height": 66,
                            "width": 66,
                            "text": "",
                            "visible": false,
                            "buttonState": {
                                up: 'autoplay_disable.png',
                                out: 'autoplay_disable.png',
                                down: 'autoplay_disable.png',
                                disable: 'autoplay_disable.png',
                                enable: 'autoplay_disable.png',
                                hover: 'autoplay_disable.png'
                            },
                            "hitareaVisible": false,
                            "shapeVisible": false,
                            "shape": {
                                type: "rectangle",
                                x: 0,
                                y: 0,
                                w: 160,
                                h: 106
                            },

                        },
                        {
                            "id": "Button_M1",
                            "name": "btn_autoplay_mobile",
                            "type": objectTypes.Sprite,
                            "interactive": true,
                            "layout": true,
                            "uimode": "mobile",
                            "x": 685,
                            "y": 1648,
                            "height": 98,
                            "width": 98,
                            "text": "",
                            "visible": true,
                            "buttonMode": false,
                            "buttonState": {
                                up: 'autoplay_disable_moblie_landscape.png',
                                out: 'autoplay_disable_moblie_landscape.png',
                                down: 'autoplay_disable_moblie_landscape.png',
                                disable: 'autoplay_disable_moblie_landscape.png',
                                enable: 'autoplay_disable_moblie_landscape.png',
                                hover: 'autoplay_disable_moblie_landscape.png'
                            },
                            "hitareaVisible": false,
                            "shapeVisible": false,
                            "shape": {}
                        },
                        {
                            "id": "Button_5",
                            "name": "btn_sound",
                            "type": objectTypes.Sprite,
                            "buttonMode": true,
                            "uimode": "desktop",
                            "layout": false,
                            "interactive": true,
                            "x": 90,
                            "y": 969,
                            "height": 48,
                            "width": 48,
                            "text": "",
                            "visible": true,
                            "buttonState": {
                                up: 'sound_standard.png',
                                out: 'sound_standard.png',
                                down: 'sound_down.png',
                                disable: 'sound_disable.png',
                                enable: 'sound_standard.png',
                                hover: 'sound_hover.png'
                            },
                            "hitareaVisible": false,
                            "shapeVisible": false,
                            "shape": {}
                        },
                        {
                            "id": "Button_12",
                            "name": "btn_soundOff",
                            "type": objectTypes.Sprite,
                            "buttonMode": true,
                            "uimode": "desktop",
                            "layout": false,
                            "interactive": true,
                            "x": 90,
                            "y": 969,
                            "height": 48,
                            "width": 48,
                            "text": "",
                            "visible": true,
                            "buttonState": {
                                up: 'sound_off_symbol_standard.png',
                                out: 'sound_off_symbol_standard.png',
                                down: 'sound_off_symbol_down.png',
                                disable: 'sound_off_symbol_disable.png',
                                enable: 'sound_off_symbol_standard.png',
                                hover: 'sound_off_symbol_hover.png'

                            },
                            "hitareaVisible": false,
                            "shapeVisible": false,
                            "shape": {}
                        },
                        {
                            "id": "Button_5",
                            "name": "btn_sound",
                            "type": objectTypes.Sprite,
                            "buttonMode": true,
                            "uimode": "mobile",
                            "layout": true,
                            "interactive": true,
                            "x": 60,
                            "y": 1585,
                            "height": 74,
                            "width": 74,
                            "text": "",
                            "visible": false,
                            "buttonState": {
                                up: 'sound_standard_moblie_landscape.png',
                                out: 'sound_standard_moblie_landscape.png',
                                down: 'sound_down_moblie_landscape.png',
                                disable: 'sound_standard_moblie_landscape.png',
                                enable: 'sound_standard_moblie_landscape.png',
                                hover: 'sound_hover_moblie_landscape.png'
                            },
                            "hitareaVisible": false,
                            "shapeVisible": false,
                            "shape": {}
                        },
                        {
                            "id": "Button_5",
                            "name": "btn_soundOff",
                            "type": objectTypes.Sprite,
                            "buttonMode": true,
                            "uimode": "mobile",
                            "layout": true,
                            "interactive": true,
                            "x": 60,
                            "y": 1585,
                            "height": 74,
                            "width": 74,
                            "text": "",
                            "visible": true,
                            "buttonState": {
                                up: 'sound_off_symbol_standard_moblie_landscape.png',
                                out: 'sound_off_symbol_standard_moblie_landscape.png',
                                down: 'sound_off_symbol_down_moblie_landscape.png',
                                disable: 'sound_off_symbol_standard_moblie_landscape.png',
                                enable: 'sound_off_symbol_standard_moblie_landscape.png',
                                hover: 'sound_off_symbol_hover_moblie_landscape.png'
                            },
                            "hitareaVisible": false,
                            "shapeVisible": false,
                            "shape": {}
                        },
                        {
                            "id": "btn_turDisable",
                            "name": "btn_turDisable",
                            "type": objectTypes.Sprite,
                            "interactive": true,
                            "layout": false,
                            "uimode": "desktop",
                            "x": 1540.5,
                            "y": 889,
                            "height": 66,
                            "width": 66,
                            "text": "",
                            "visible": true,
                            "buttonMode": true,
                            "buttonState": {
                                up: 'turbo_spin_standard.png',
                                out: 'turbo_spin_standard.png',
                                down: 'turbo_spin_standard.png',
                                disable: 'turbo_spin_standard.png',
                                enable: 'turbo_spin_standard.png',
                                hover: 'turbo_spin_hover.png'
                            },
                            "hitareaVisible": false,
                            "shapeVisible": false,
                            "shape": {}
                        },
                        // {
                        //     "id": "btn_turDisableFreegame",
                        //     "name": "btn_turDisableFreegame",
                        //     "type": objectTypes.Sprite,
                        //     "interactive": true,
                        //     "layout": false,
                        //     "uimode": "desktop",
                        //     "x": 1540.5,
                        //     "y": 889,
                        //     "height": 66,
                        //     "width": 66,
                        //     "text": "",
                        //     "visible": true,
                        //     "buttonMode": true,
                        //     "buttonState": {
                        //         up: 'turbo_spin_on_up.png',
                        //         out: 'turbo_spin_on_down.png',
                        //         down: 'turbo_spin_on_down.png',p
                        //         disable: 'turbo_spin_disable.png',
                        //         enable: 'turbo_spin_on_down.png',
                        //         hover: 'turbo_spin_on_down.png'
                        //     },
                        //     "hitareaVisible": false,
                        //     "shapeVisible": false,
                        //     "shape": {}
                        // },
                        {
                            "id": "btn_turDisable",
                            "name": "btn_turDisable",
                            "type": objectTypes.Sprite,
                            "interactive": true,
                            "layout": true,
                            "uimode": "mobile",
                            "x": 1690,
                            "y": 770,
                            "height": 100,
                            "width": 100,
                            "text": "",
                            "visible": true,
                            "buttonMode": true,
                            "buttonState": {
                                up: 'turbo_spin_standard_moblie_landscape.png',
                                out: 'turbo_spin_standard_moblie_landscape.png',
                                down: 'turbo_spin_on_down_moblie_landscape.png',
                                disable: 'turbo_spin_disable_moblie_landscape.png',
                                enable: 'turbo_spin_standard_moblie_landscape.png',
                                hover: 'turbo_spin_hover_moblie_landscape.png'
                            },
                            "hitareaVisible": false,
                            "shapeVisible": false,
                            "shape": {}
                        },
                        // {
                        //     "id": "btn_turDisableFreegame",
                        //     "name": "btn_turDisableFreegame",
                        //     "type": objectTypes.Sprite,
                        //     "interactive": true,
                        //     "layout": true,
                        //     "uimode": "mobile",
                        //     "x": 1690,
                        //     "y": 770,
                        //     "height": 100,
                        //     "width": 100,
                        //     "text": "",
                        //     "visible": true,
                        //     "buttonMode": true,
                        //     "buttonState": {
                        //         up: 'turbo_spin_on_up_moblie_landscape.png',
                        //         out: 'turbo_spin_on_down_moblie_landscape.png',
                        //         down: 'turbo_spin_down_moblie_landscape.png',
                        //         disable: 'turbo_spin_disable_moblie_landscape.png',
                        //         enable: 'turbo_spin_standard_moblie_landscape.png',
                        //         hover: 'turbo_spin_hover_moblie_landscape.png'
                        //     },
                        //     "hitareaVisible": false,
                        //     "shapeVisible": false,
                        //     "shape": {}
                        // },
                        {
                            "id": "btn_turboEnable",
                            "name": "btn_turboEnable",
                            "type": objectTypes.Sprite,
                            "interactive": true,
                            "uimode": "desktop",
                            "layout": false,
                            "x": 1540.5,
                            "y": 889,
                            "height": 66,
                            "width": 66,
                            "text": "",
                            "visible": true,
                            "buttonMode": true,
                            "buttonState": {
                                up: 'turbo_spin_on_up.png',
                                out: 'turbo_spin_on_down.png',
                                down: 'turbo_spin_on_down.png',
                                disable: 'turbo_spin_disable.png',
                                enable: 'turbo_spin_on_down.png',
                                hover: 'turbo_spin_on_down.png'
                            },
                            "hitareaVisible": false,
                            "shapeVisible": false,
                            "shape": {}
                        },
                        // {
                        //     "id": "btn_turboEnableFreegame",
                        //     "name": "btn_turboEnableFreegame",
                        //     "type": objectTypes.Sprite,
                        //     "interactive": true,
                        //     "uimode": "desktop",
                        //     "layout": false,
                        //     "x": 1540.5,
                        //     "y": 889,
                        //     "height": 66,
                        //     "width": 66,
                        //     "text": "",
                        //     "visible": true,
                        //     "buttonMode": true,
                        //     "buttonState": {
                        //         up: 'turbo_spin_standard.png',
                        //         out: 'turbo_spin_standard.png',
                        //         down: 'turbo_spin_down.png',
                        //         disable: 'turbo_spin_disable.png',
                        //         enable: 'turbo_spin_standard.png',
                        //         hover: 'turbo_spin_hover.png'
                        //     },
                        //     "hitareaVisible": false,
                        //     "shapeVisible": false,
                        //     "shape": {}
                        // },
                        // {
                        //     "id": "btn_turboEnableFreegame",
                        //     "name": "btn_turboEnableFreegame",
                        //     "type": objectTypes.Sprite,
                        //     "interactive": true,
                        //     "uimode": "mobile",
                        //     "layout": true,
                        //     "x": 1690,
                        //     "y": 770,
                        //     "height": 100,
                        //     "width": 100,
                        //     "text": "",
                        //     "visible": true,
                        //     "buttonMode": true,
                        //     "buttonState": {
                        //         up: 'turbo_spin_standard_moblie_landscape.png',
                        //         out: 'turbo_spin_standard_moblie_landscape.png',
                        //         down: 'turbo_spin_on_down_moblie_landscape.png',
                        //         disable: 'turbo_spin_disable_moblie_landscape.png',
                        //         enable: 'turbo_spin_standard_moblie_landscape.png',
                        //         hover: 'turbo_spin_hover_moblie_landscape.png'
                        //     },
                        //     "hitareaVisible": false,
                        //     "shapeVisible": false,
                        //     "shape": {}
                        // },
                        {
                            "id": "btn_turboEnable",
                            "name": "btn_turboEnable",
                            "type": objectTypes.Sprite,
                            "interactive": true,
                            "uimode": "mobile",
                            "layout": true,
                            "x": 1690,
                            "y": 770,
                            "height": 100,
                            "width": 100,
                            "text": "",
                            "visible": true,
                            "buttonMode": true,
                            "buttonState": {
                                up: 'turbo_spin_on_up_moblie_landscape.png',
                                out: 'turbo_spin_on_down_moblie_landscape.png',
                                down: 'turbo_spin_down_moblie_landscape.png',
                                disable: 'turbo_spin_disable_moblie_landscape.png',
                                enable: 'turbo_spin_standard_moblie_landscape.png',
                                hover: 'turbo_spin_hover_moblie_landscape.png'
                            },
                            "hitareaVisible": false,
                            "shapeVisible": false,
                            "shape": {}
                        },
                        {
                            "id": "Button_7",
                            "name": "btn_autoplay_stop",
                            "type": objectTypes.Sprite,
                            "buttonMode": false,
                            "uimode": "desktop",
                            "interactive": false,
                            "layout": false,
                            "x": 1800.5,
                            "y": 895,
                            "height": 66,
                            "width": 66,
                            "text": "",
                            "visible": false,
                            "buttonState": {
                                up: 'autoplay_counter_up.png',
                                out: 'autoplay_counter_up.png',
                                down: 'autoplay_counter_up.png',
                                disable: 'autoplay_counter_up.png',
                                enable: 'autoplay_counter_up.png',
                                hover: 'autoplay_counter_up.png'
                            },
                            "hitareaVisible": false,
                            "shapeVisible": false,
                            "shape": {}
                        },
                        {
                            "id": "Button_M14",
                            "name": "btn_autoplay_stop",
                            "type": objectTypes.Sprite,
                            "buttonMode": true,
                            "uimode": "mobile",
                            "interactive": false,
                            "layout": true,
                            "x": 685,
                            "y": 1648,
                            "height": 98,
                            "width": 98,
                            "text": "",
                            "visible": false,
                            "buttonState": {
                                up: 'autoplay_counter_up_moblie_landscape.png',
                                out: 'autoplay_counter_down_moblie_landscape.png',
                                down: 'autoplay_counter_down_moblie_landscape.png',
                                disable: 'autoplay_counter_down_moblie_landscape.png',
                                enable: 'autoplay_counter_up_moblie_landscape.png',
                                hover: 'autoplay_counter_hover_moblie_landscape.png'
                            },
                            "hitareaVisible": false,
                            "shapeVisible": false,
                            "shape": {}
                        },


                        {
                            "id": "text_24",
                            "name": "Text_COUNT_AP",
                            "type": "Text",
                            "uimode": "desktop",
                            "x": 1832,
                            "y": 930,
                            "text": "",
                            "anchor": [0.5, 0.5],
                            "visible": true,
                            "width": 64,
                            "scaleToFit": true,
                            "textStyle": {
                                fontFamily: 'MYP Bold',
                                fontSize: 18,
                                fontWeight: 'bold',
                                fill: ['#000000'],
                            },
                            "parentLayer": "specialAnimationLayer",
                        },
                        {
                            "id": "text_M10",
                            "name": "Text_COUNT_AP",
                            "type": "Text",
                            "layout": true,
                            "uimode": "mobile",
                            "x": 690,
                            "y": 1645,
                            "text": "",
                            "width": 50,
                            "anchor": [0.5, 0.5],
                            "visible": true,
                            "scaleToFit": true,
                            "textStyle": {
                                fontFamily: 'MYP Bold',
                                fontSize: 28,
                                fontWeight: 'bold',
                                fill: ['#000000'],
                            },
                            "parentLayer": "specialAnimationLayer",
                        },

                    ]
                },
            ]
        }
    ]
}
