import React from "react";
import { Icomponent } from "@bonanzainteractive/slote_core";
import { configGame } from "../../../slot/data/config";

interface IframeworkConvertSymbolAnimationConfiguration {
    data: {
        COMPONENTS: Icomponent[]
    }

}

export const frameworkConvertSymbolAnimationConfiguration: IframeworkConvertSymbolAnimationConfiguration = {

    data: {
        "COMPONENTS": [
           
            {
                "name": "desktopConvertContainer",
                "type": "Container",
                "class": "",
                "x": configGame.REEL_CONTAINER_X,
                "y": configGame.REEL_CONTAINER_Y,
                layout: true,
                // "uimode": "desktop",
                "filterTypes": [],
                child: [
                    {
                        "id": "ConvertWildContainer",
                        "name": "ConvertWildContainer",
                        "type": "Container",
                        "x": 0,
                        "y": 0,
                        "visible": false,
                        "filterTypes": [],
                        child: [
                            /*    {
                                   "id": "StreakEffectContainer",
                                   "name": "StreakEffectContainer",
                                   "type": "Tag",
                                   "class": "",
                                   "parentLayer": "specialAnimationLayer",
                                   "filterTypes": [],
                                   child: []
                               }, */
        
                        ]
                    },
                    {
                        "name": "ani_reveal00",
                        "type": "Spine",
                        "width": 2012,
                        "height": 1284,
                        "image": "ani_reveal",
                        "animationSpeed": 0.2,
                        "playing": false,
                        "loop": false,
                        "visible": false,
                        "uimode": "desktop",
                        "spineAnimName": "reveal",
                        "anchor": [0, 0],
                        "x": 530,
                        "y": 340,
                        "spinedata": {
                            "spinename": "ani_reveal",
                            "animationname": "reveal",
                            "loop": false,
                            "timeScale": 0.9

                        },
                    },
                    {
                        "id": "ani_reveal00",
                        "name": "ani_reveal00",
                        "type": "Spine",
                        "width": 2012,
                        "height": 1284,
                        "image": "ani_reveal",
                        "animationSpeed": 0.2,
                        "playing": false,
                        "loop": false,
                        "visible": false,
                        "uimode": "mobile",
                        "layout": true,
                        "spineAnimName": "reveal",
                        "anchor": [0, 0],
                        "x": 80,
                        "y": 110.5,
                        "spinedata": {
                            "spinename": "ani_reveal",
                            "animationname": "reveal",
                            "loop": false,
                            "timeScale": 0.9
                        },
                    },
                    {
                        "name": "ani_reveal01",
                        "type": "Spine",
                        "width": 2012,
                        "height": 1284,
                        "image": "ani_reveal",
                        "animationSpeed": 0.2,
                        "playing": false,
                        "loop": false,
                        "visible": false,
                        "uimode": "desktop",
                        "spineAnimName": "reveal",
                        "anchor": [0, 0],
                        "x": 530,
                        "y": 340 + configGame.SYMBOL_HEIGHT,
                        "spinedata": {
                            "spinename": "ani_reveal",
                            "animationname": "reveal",
                            "loop": false,
                            "timeScale": 0.9

                        },
                    },
                    {
                        "id": "ani_reveal01",
                        "name": "ani_reveal01",
                        "type": "Spine",
                        "width": 2012,
                        "height": 1284,
                        "image": "ani_reveal",
                        "animationSpeed": 0.2,
                        "playing": false,
                        "loop": false,
                        "visible": false,
                        "uimode": "mobile",
                         "layout": true,
                        "spineAnimName": "reveal",
                        "anchor": [0, 0],
                        "x": 100,
                        "y": 90.5 + configGame.SYMBOL_HEIGHT,
                        "spinedata": {
                            "spinename": "ani_reveal",
                            "animationname": "reveal",
                            "loop": false,
                            "timeScale": 0.9

                        },
                    },
                    {
                        "name": "ani_reveal02",
                        "type": "Spine",
                        "width": 2012,
                        "height": 1284,
                        "image": "ani_reveal",
                        "animationSpeed": 0.2,
                        "playing": false,
                        "loop": false,
                        "visible": false,
                        "uimode": "desktop",
                        "spineAnimName": "reveal",
                        "anchor": [0, 0],
                        "x": 530,
                        "y": 340 + configGame.SYMBOL_HEIGHT * 2,
                        "spinedata": {
                            "spinename": "ani_reveal",
                            "animationname": "reveal",
                            "loop": false,
                            "timeScale": 0.9

                        },
                    },
                    {
                        "id": "ani_reveal02",
                        "name": "ani_reveal02",
                        "type": "Spine",
                        "width": 2012,
                        "height": 1284,
                        "image": "ani_reveal",
                        "animationSpeed": 0.2,
                        "playing": false,
                        "loop": false,
                        "visible": false,
                         "uimode": "mobile",
                         "layout": true,
                        "spineAnimName": "reveal",
                        "anchor": [0, 0],
                        "x": 100,
                        "y": 30.5 + configGame.SYMBOL_HEIGHT * 2,
                        "spinedata": {
                            "spinename": "ani_reveal",
                            "animationname": "reveal",
                            "loop": false,
                            "timeScale": 0.9

                        },
                    },
    
//SECTION - 10

                    {
                        "name": "ani_reveal10",
                        "type": "Spine",
                        "width": 2012,
                        "height": 1284,
                        "image": "ani_reveal",
                        "animationSpeed": 0.2,
                        "playing": false,
                        "loop": false,
                        "visible": false,
                        "uimode": "desktop",
                        "spineAnimName": "reveal",
                        "anchor": [0, 0],
                        "x": 530 + configGame.REEL_GAP + configGame.SYMBOL_WIDTH,
                        "y": 340,
                        "spinedata": {
                            "spinename": "ani_reveal",
                            "animationname": "reveal",
                            "loop": false,
                            "timeScale": 0.9
                        },
                    },
                    {
                        "id": "ani_reveal10",
                        "name": "ani_reveal10",
                        "type": "Spine",
                        "width": 2012,
                        "height": 1284,
                        "image": "ani_reveal",
                        "animationSpeed": 0.2,
                        "playing": false,
                        "loop": false,
                        "visible": false,
                         "uimode": "mobile",
                         "layout": true,
                        "spineAnimName": "reveal",
                        "anchor": [0, 0],
                        "x": 30 + configGame.REEL_GAP + configGame.SYMBOL_WIDTH,
                        "y": 110.5,
                        "spinedata": {
                            "spinename": "ani_reveal",
                            "animationname": "reveal",
                            "loop": false,
                            "timeScale": 0.9
                        },
                    },
                    {
                        "name": "ani_reveal11",
                        "type": "Spine",
                        "width": 2012,
                        "height": 1284,
                        "image": "ani_reveal",
                        "animationSpeed": 0.2,
                        "playing": false,
                        "loop": false,
                        "visible": false,
                        "uimode": "desktop",
                        "spineAnimName": "reveal",
                        "anchor": [0, 0],
                        "x": 530 + configGame.REEL_GAP + configGame.SYMBOL_WIDTH,
                        "y": 340 + configGame.SYMBOL_HEIGHT,
                        "spinedata": {
                            "spinename": "ani_reveal",
                            "animationname": "reveal",
                            "loop": false,
                            "timeScale": 0.9
                        },
                    },
                    {
                        "id": "ani_reveal11",
                        "name": "ani_reveal11",
                        "type": "Spine",
                        "width": 2012,
                        "height": 1284,
                        "image": "ani_reveal",
                        "animationSpeed": 0.2,
                        "playing": false,
                        "loop": false,
                        "visible": false,
                         "uimode": "mobile",
                         "layout": true,
                        "spineAnimName": "reveal",
                        "anchor": [0, 0],
                        "x": 50 + configGame.REEL_GAP + configGame.SYMBOL_WIDTH,
                        "y": 75.5 + configGame.SYMBOL_HEIGHT,
                        "spinedata": {
                            "spinename": "ani_reveal",
                            "animationname": "reveal",
                            "loop": false,
                            "timeScale": 0.9
                        },
                    },
                    {
                        "name": "ani_reveal12",
                        "type": "Spine",
                        "width": 2012,
                        "height": 1284,
                        "image": "ani_reveal",
                        "animationSpeed": 0.2,
                        "playing": false,
                        "loop": false,
                        "visible": false,
                        "uimode": "desktop",
                        "spineAnimName": "reveal",
                        "anchor": [0, 0],
                        "x": 530 + configGame.REEL_GAP + configGame.SYMBOL_WIDTH,
                        "y": 340 + configGame.SYMBOL_HEIGHT * 2,
                        "spinedata": {
                            "spinename": "ani_reveal",
                            "animationname": "reveal",
                            "loop": false,
                            "timeScale": 0.9
                        },
                    },
                    {
                        "id": "ani_reveal12",
                        "name": "ani_reveal12",
                        "type": "Spine",
                        "width": 2012,
                        "height": 1284,
                        "image": "ani_reveal",
                        "animationSpeed": 0.2,
                        "playing": false,
                        "loop": false,
                        "visible": false,
                         "uimode": "mobile",
                         "layout": true,
                        "spineAnimName": "reveal",
                        "anchor": [0, 0],
                        "x": 50 + configGame.REEL_GAP + configGame.SYMBOL_WIDTH,
                        "y": 30.5 + configGame.SYMBOL_HEIGHT * 2,
                        "spinedata": {
                            "spinename": "ani_reveal",
                            "animationname": "reveal",
                            "loop": false,
                            "timeScale": 0.9
                        },
                    },
//SECTION - 20
                    {
                        "name": "ani_reveal20",
                        "type": "Spine",
                        "width": 2012,
                        "height": 1284,
                        "image": "ani_reveal",
                        "animationSpeed": 0.2,
                        "playing": false,
                        "loop": false,
                        "visible": false,
                        "uimode": "desktop",
                        "spineAnimName": "reveal",
                        "anchor": [0, 0],
                        "x": 530 + (configGame.REEL_GAP + configGame.SYMBOL_WIDTH) * 2,
                        "y": 340,
                        "spinedata": {
                            "spinename": "ani_reveal",
                            "animationname": "reveal",
                            "loop": false,
                            "timeScale": 0.9
                        },
                    },
                    {
                        "id": "ani_reveal20",
                        "name": "ani_reveal20",
                        "type": "Spine",
                        "width": 2012,
                        "height": 1284,
                        "image": "ani_reveal",
                        "animationSpeed": 0.2,
                        "playing": false,
                        "loop": false,
                        "visible": false,
                         "uimode": "mobile",
                         "layout": true,
                        "spineAnimName": "reveal",
                        "anchor": [0, 0],
                        "x": 0 + (configGame.REEL_GAP + configGame.SYMBOL_WIDTH) * 2,
                        "y": 110.5,
                        "spinedata": {
                            "spinename": "ani_reveal",
                            "animationname": "reveal",
                            "loop": false,
                            "timeScale": 0.9
                        },
                    },
                    {
                        "name": "ani_reveal21",
                        "type": "Spine",
                        "width": 2012,
                        "height": 1284,
                        "image": "ani_reveal",
                        "animationSpeed": 0.2,
                        "playing": false,
                        "loop": false,
                        "visible": false,
                        "uimode": "desktop",
                        "spineAnimName": "reveal",
                        "anchor": [0, 0],
                        "x": 530 + (configGame.REEL_GAP + configGame.SYMBOL_WIDTH) * 2,
                        "y": 340 + configGame.SYMBOL_HEIGHT,
                        "spinedata": {
                            "spinename": "ani_reveal",
                            "animationname": "reveal",
                            "loop": false,
                            "timeScale": 0.9
                        },
                    },
                    {
                        "id": "ani_reveal21",
                        "name": "ani_reveal21",
                        "type": "Spine",
                        "width": 2012,
                        "height": 1284,
                        "image": "ani_reveal",
                        "animationSpeed": 0.2,
                        "playing": false,
                        "loop": false,
                        "visible": false,
                         "uimode": "mobile",
                         "layout": true,
                        "spineAnimName": "reveal",
                        "anchor": [0, 0],
                        "x": 0 + (configGame.REEL_GAP + configGame.SYMBOL_WIDTH) * 2,
                        "y": 70.5 + configGame.SYMBOL_HEIGHT,
                        "spinedata": {
                            "spinename": "ani_reveal",
                            "animationname": "reveal",
                            "loop": false,
                            "timeScale": 0.9
                        },
                    },
                    {
                        "name": "ani_reveal22",
                        "type": "Spine",
                        "width": 2012,
                        "height": 1284,
                        "image": "ani_reveal",
                        "animationSpeed": 0.2,
                        "playing": false,
                        "loop": false,
                        "visible": false,
                        "uimode": "desktop",
                        "spineAnimName": "reveal",
                        "anchor": [0, 0],
                        "x": 530 + (configGame.REEL_GAP + configGame.SYMBOL_WIDTH) * 2,
                        "y": 340 + configGame.SYMBOL_HEIGHT * 2,
                        "spinedata": {
                            "spinename": "ani_reveal",
                            "animationname": "reveal",
                            "loop": false,
                            "timeScale": 0.9
                        },
                    },
                    {
                        "id": "ani_reveal22",
                        "name": "ani_reveal22",
                        "type": "Spine",
                        "width": 2012,
                        "height": 1284,
                        "image": "ani_reveal",
                        "animationSpeed": 0.2,
                        "playing": false,
                        "loop": false,
                        "visible": false,
                         "uimode": "mobile",
                         "layout": true,
                        "spineAnimName": "reveal",
                        "anchor": [0, 0],
                        "x": 0 + (configGame.REEL_GAP + configGame.SYMBOL_WIDTH) * 2,
                        "y": 30.5 + configGame.SYMBOL_HEIGHT * 2,
                        "spinedata": {
                            "spinename": "ani_reveal",
                            "animationname": "reveal",
                            "loop": false,
                            "timeScale": 0.9
                        },
                    },
//SECTION - 30
                    {
                        "name": "ani_reveal30",
                        "type": "Spine",
                        "width": 2012,
                        "height": 1284,
                        "image": "ani_reveal",
                        "animationSpeed": 0.2,
                        "playing": false,
                        "loop": false,
                        "visible": false,
                        "uimode": "desktop",
                        "anchor": [0, 0],
                        "spineAnimName": "reveal",                      
                        "x": 530 + (configGame.REEL_GAP + configGame.SYMBOL_WIDTH) * 3,
                        "y": 340,
                        "spinedata": {
                            "spinename": "ani_reveal",
                            "animationname": "reveal",
                            "loop": false,
                            "timeScale": 0.9
                        },
                    },
                    {
                        "id": "ani_reveal30",
                        "name": "ani_reveal30",
                        "type": "Spine",
                        "width": 2012,
                        "height": 1284,
                        "image": "ani_reveal",
                        "animationSpeed": 0.2,
                        "playing": false,
                        "loop": false,
                        "visible": false,
                         "uimode": "mobile",
                         "layout": true,
                        "spineAnimName": "reveal",
                        "anchor": [0, 0],
                        "x": -51 + (configGame.REEL_GAP + configGame.SYMBOL_WIDTH) * 3,
                        "y": 110.5,
                        "spinedata": {
                            "spinename": "ani_reveal",
                            "animationname": "reveal",
                            "loop": false,
                            "timeScale": 0.9
                        },
                    },
                    {
                        "name": "ani_reveal31",
                        "type": "Spine",
                        "width": 2012,
                        "height": 1284,
                        "image": "ani_reveal",
                        "animationSpeed": 0.2,
                        "playing": false,
                        "loop": false,
                        "visible": false,
                        "uimode": "desktop",
                        "spineAnimName": "reveal",
                        "anchor": [0, 0],
                        "x": 530 + (configGame.REEL_GAP + configGame.SYMBOL_WIDTH) * 3,
                        "y": 340 + configGame.SYMBOL_HEIGHT,
                        "spinedata": {
                            "spinename": "ani_reveal",
                            "animationname": "reveal",
                            "loop": false,
                            "timeScale": 0.9
                        },
                    },
                    {
                        "id": "ani_reveal31",
                        "name": "ani_reveal31",
                        "type": "Spine",
                        "width": 2012,
                        "height": 1284,
                        "image": "ani_reveal",
                        "animationSpeed": 0.2,
                        "playing": false,
                        "loop": false,
                        "visible": false,
                         "uimode": "mobile",
                         "layout": true,
                        "spineAnimName": "reveal",
                        "anchor": [0, 0],
                        "x": -51 + (configGame.REEL_GAP + configGame.SYMBOL_WIDTH) * 3,
                        "y": 70.5 + configGame.SYMBOL_HEIGHT,
                        "spinedata": {
                            "spinename": "ani_reveal",
                            "animationname": "reveal",
                            "loop": false,
                            "timeScale": 0.9
                        },
                    },
                    {
                        "name": "ani_reveal32",
                        "type": "Spine",
                        "width": 2012,
                        "height": 1284,
                        "image": "ani_reveal",
                        "animationSpeed": 0.2,
                        "playing": false,
                        "loop": false,
                        "visible": false,
                        "uimode": "desktop",
                        "spineAnimName": "reveal",
                        "anchor": [0, 0],
                        "x": 530 + (configGame.REEL_GAP + configGame.SYMBOL_WIDTH) * 3,
                        "y": 340 + configGame.SYMBOL_HEIGHT * 2,
                        "spinedata": {
                            "spinename": "ani_reveal",
                            "animationname": "reveal",
                            "loop": false,
                            "timeScale": 0.9
                        },
                    },
                    {
                        "id": "ani_reveal32",
                        "name": "ani_reveal32",
                        "type": "Spine",
                        "width": 2012,
                        "height": 1284,
                        "image": "ani_reveal",
                        "animationSpeed": 0.2,
                        "playing": false,
                        "loop": false,
                        "visible": false,
                         "uimode": "mobile",
                         "layout": true,
                        "spineAnimName": "reveal",
                        "anchor": [0, 0],
                        "x": -51 + (configGame.REEL_GAP + configGame.SYMBOL_WIDTH) * 3,
                        "y": 30.5 + configGame.SYMBOL_HEIGHT * 2,
                        "spinedata": {
                            "spinename": "ani_reveal",
                            "animationname": "reveal",
                            "loop": false,
                            "timeScale": 0.9
                        },
                    },

//SECTION - 40
                    {
                        "name": "ani_reveal40",
                        "type": "Spine",
                        "width": 2012,
                        "height": 1284,
                        "image": "ani_reveal",
                        "animationSpeed": 0.2,
                        "playing": false,
                        "loop": false,
                        "visible": false,
                        "uimode": "desktop",
                        "spineAnimName": "reveal",
                        "anchor": [0, 0],
                        "x": 530 + (configGame.REEL_GAP + configGame.SYMBOL_WIDTH) * 4,
                        "y": 340,
                        "spinedata": {
                            "spinename": "ani_reveal",
                            "animationname": "reveal",
                            "loop": false,
                            "timeScale": 0.9
                        },
                    },
                    {
                        "id": "ani_reveal40",
                        "name": "ani_reveal40",
                        "type": "Spine",
                        "width": 2012,
                        "height": 1284,
                        "image": "ani_reveal",
                        "animationSpeed": 0.2,
                        "playing": false,
                        "loop": false,
                        "visible": false,
                         "uimode": "mobile",
                         "layout": true,
                        "spineAnimName": "reveal",
                        "anchor": [0, 0],
                        "x": -90 + (configGame.REEL_GAP + configGame.SYMBOL_WIDTH) * 4,
                        "y": 110.5,
                        "spinedata": {
                            "spinename": "ani_reveal",
                            "animationname": "reveal",
                            "loop": false,
                            "timeScale": 0.9
                        },
                    },
                    {
                        "name": "ani_reveal41",
                        "type": "Spine",
                        "width": 2012,
                        "height": 1284,
                        "image": "ani_reveal",
                        "animationSpeed": 0.2,
                        "playing": false,
                        "loop": false,
                        "visible": false,
                        "uimode": "desktop",
                        "spineAnimName": "reveal",
                        "anchor": [0, 0],
                        "x": 530 + (configGame.REEL_GAP + configGame.SYMBOL_WIDTH) * 4,
                        "y": 340 + configGame.SYMBOL_HEIGHT,
                        "spinedata": {
                            "spinename": "ani_reveal",
                            "animationname": "reveal",
                            "loop": false,
                            "timeScale": 0.9
                        },
                    },
                    {
                        "id": "ani_reveal41",
                        "name": "ani_reveal41",
                        "type": "Spine",
                        "width": 2012,
                        "height": 1284,
                        "image": "ani_reveal",
                        "animationSpeed": 0.2,
                        "playing": false,
                        "loop": false,
                        "visible": false,
                         "uimode": "mobile",
                         "layout": true,
                        "spineAnimName": "reveal",
                        "anchor": [0, 0],
                        "x": -90 + (configGame.REEL_GAP + configGame.SYMBOL_WIDTH) * 4,
                        "y": 70.5 + configGame.SYMBOL_HEIGHT,
                        "spinedata": {
                            "spinename": "ani_reveal",
                            "animationname": "reveal",
                            "loop": false,
                            "timeScale": 0.9
                        },
                    },
                    {
                        "name": "ani_reveal42",
                        "type": "Spine",
                        "width": 2012,
                        "height": 1284,
                        "image": "ani_reveal",
                        "animationSpeed": 0.2,
                        "playing": false,
                        "loop": false,
                        "visible": false,
                        "uimode": "desktop",
                        "spineAnimName": "reveal",
                        "anchor": [0, 0],
                        "x": 530 + (configGame.REEL_GAP + configGame.SYMBOL_WIDTH) * 4,
                        "y": 340 + configGame.SYMBOL_HEIGHT * 2,
                        "spinedata": {
                            "spinename": "ani_reveal",
                            "animationname": "reveal",
                            "loop": false,
                            "timeScale": 0.9
                        },
                    },
                    {
                        "id": "ani_reveal42",
                        "name": "ani_reveal42",
                        "type": "Spine",
                        "width": 2012,
                        "height": 1284,
                        "image": "ani_reveal",
                        "animationSpeed": 0.2,
                        "playing": false,
                        "loop": false,
                        "visible": false,
                         "uimode": "mobile",
                         "layout": true,
                        "spineAnimName": "reveal",
                        "anchor": [0, 0],
                        "x": -90 + (configGame.REEL_GAP + configGame.SYMBOL_WIDTH) * 4,
                        "y": 30.5 + configGame.SYMBOL_HEIGHT * 2,
                        "spinedata": {
                            "spinename": "ani_reveal",
                            "animationname": "reveal",
                            "loop": false,
                            "timeScale": 0.9
                        },
                    },
                ]
            },
         
        ],
    }

};

export const ConvertSymbolAnimationContext = React.createContext(
    {}
);
