import React from "react";
import { configGame } from "../../../slot/data/config";
interface IframeworkMysteryCounterConfiguration {
    data: {
    }
}

export const frameworkMysteryCounterConfiguration: IframeworkMysteryCounterConfiguration = {

    data: {
        "COMPONENTS": [
            {
                "name": "mysteryCounterDesktop",
                "type": "Container",
                "x": 0,
                "y": 0,
                "layout": false,
                "uimode": "desktop",
                child: [
                    {
                        "name": "butterFLy_0",
                        "type": "Spine",
                        "width": 2001,
                        "height": 523,
                        "image": "leftMeterAnim",
                        "animationSpeed": 0.9,
                        "playing": true,
                        "loop": true,
                        "visible": false,
                        "spineAnimName": "collectd_mtr_butterfly",
                        x: 449,
                        y: 305,
                        "spinedata": {
                            "spinename": "leftMeterAnim",
                            "animationname": "collectd_mtr_butterfly",
                            "loop": true,
                            "timeScale": 0.9,
                        },
                    },
                    {
                        "name": "butterFLy_1",
                        "type": "Spine",
                        "width": 2001,
                        "height": 523,
                        "image": "leftMeterAnim",
                        "animationSpeed": 0.9,
                        "playing": true,
                        "loop": true,
                        "visible": false,
                        "spineAnimName": "collectd_mtr_butterfly",
                        x: 694,
                        y: 305,
                        "spinedata": {
                            "spinename": "leftMeterAnim",
                            "animationname": "collectd_mtr_butterfly",
                            "loop": true,
                            "timeScale": 0.9,
                        },
                    },
                    {
                        "name": "butterFLy_2",
                        "type": "Spine",
                        "width": 2001,
                        "height": 523,
                        "image": "leftMeterAnim",
                        "animationSpeed": 0.9,
                        "playing": true,
                        "loop": true,
                        "visible": false,
                        "spineAnimName": "collectd_mtr_butterfly",
                        x: 957,
                        y: 305,
                        "spinedata": {
                            "spinename": "leftMeterAnim",
                            "animationname": "collectd_mtr_butterfly",
                            "loop": true,
                            "timeScale": 0.9,
                        },
                    },
                    {
                        "name": "butterFLy_3",
                        "type": "Spine",
                        "width": 2001,
                        "height": 523,
                        "image": "leftMeterAnim",
                        "animationSpeed": 0.9,
                        "playing": true,
                        "loop": true,
                        "visible": false,
                        "spineAnimName": "collectd_mtr_butterfly",
                        x: 212,
                        y: 374,
                        "spinedata": {
                            "spinename": "leftMeterAnim",
                            "animationname": "collectd_mtr_butterfly",
                            "loop": true,
                            "timeScale": 0.9,
                        },
                    },
                    {
                        "name": "butterFLy_4",
                        "type": "Spine",
                        "width": 2001,
                        "height": 523,
                        "image": "leftMeterAnim",
                        "animationSpeed": 0.9,
                        "playing": true,
                        "loop": true,
                        "visible": false,
                        "spineAnimName": "collectd_mtr_butterfly",
                        x: 212,
                        y: 374,
                        "spinedata": {
                            "spinename": "leftMeterAnim",
                            "animationname": "collectd_mtr_butterfly",
                            "loop": true,
                            "timeScale": 0.9,
                        },
                    },
                    {
                        "name": "butterFLy_5",
                        "type": "Spine",
                        "width": 2001,
                        "height": 523,
                        "image": "leftMeterAnim",
                        "animationSpeed": 0.9,
                        "playing": true,
                        "loop": true,
                        "visible": false,
                        "spineAnimName": "collectd_mtr_butterfly",
                        x: 212,
                        y: 374,
                        "spinedata": {
                            "spinename": "leftMeterAnim",
                            "animationname": "collectd_mtr_butterfly",
                            "loop": true,
                            "timeScale": 0.9,
                        },
                    },
                    {
                        "name": "butterFLy_6",
                        "type": "Spine",
                        "width": 2001,
                        "height": 523,
                        "image": "leftMeterAnim",
                        "animationSpeed": 0.9,
                        "playing": true,
                        "loop": true,
                        "visible": false,
                        "spineAnimName": "collectd_mtr_butterfly",
                        x: 212,
                        y: 374,
                        "spinedata": {
                            "spinename": "leftMeterAnim",
                            "animationname": "collectd_mtr_butterfly",
                            "loop": true,
                            "timeScale": 0.9,
                        },
                    },
                    {
                        "name": "butterFLy_7",
                        "type": "Spine",
                        "width": 2001,
                        "height": 523,
                        "image": "leftMeterAnim",
                        "animationSpeed": 0.9,
                        "playing": true,
                        "loop": true,
                        "visible": false,
                        "spineAnimName": "collectd_mtr_butterfly",
                        x: 212,
                        y: 374,
                        "spinedata": {
                            "spinename": "leftMeterAnim",
                            "animationname": "collectd_mtr_butterfly",
                            "loop": true,
                            "timeScale": 0.9,
                        },
                    },
                    {
                        "name": "butterFLy_8",
                        "type": "Spine",
                        "width": 2001,
                        "height": 523,
                        "image": "leftMeterAnim",
                        "animationSpeed": 0.9,
                        "playing": true,
                        "loop": true,
                        "visible": false,
                        "spineAnimName": "collectd_mtr_butterfly",
                        x: 212,
                        y: 374,
                        "spinedata": {
                            "spinename": "leftMeterAnim",
                            "animationname": "collectd_mtr_butterfly",
                            "loop": true,
                            "timeScale": 0.9,
                        },
                    },
                    {
                        "name": "butterFLy_9",
                        "type": "Spine",
                        "width": 2001,
                        "height": 523,
                        "image": "leftMeterAnim",
                        "animationSpeed": 0.9,
                        "playing": true,
                        "loop": true,
                        "visible": false,
                        "spineAnimName": "collectd_mtr_butterfly",
                        x: 212,
                        y: 374,
                        "spinedata": {
                            "spinename": "leftMeterAnim",
                            "animationname": "collectd_mtr_butterfly",
                            "loop": true,
                            "timeScale": 0.9,
                        },
                    },


                ]
            },
            {
                "name": "mysteryCounterMobile",
                "type": "Container",
                x: configGame.REEL_CONTAINER_X_IN_PORTRAIT,
                y: configGame.REEL_CONTAINER_Y_IN_PORTRAIT,
                "layout": true,
                "uimode": "mobile",
                child: [
                    {
                        "name": "butterFLy_0",
                        "type": "Spine",
                        "width": 2001,
                        "height": 523,
                        "image": "leftMeterAnim",
                        "animationSpeed": 0.9,
                        "playing": true,
                        "loop": true,
                        "visible": false,
                        "spineAnimName": "collectd_mtr_butterfly",
                        x: 449,
                        y: 305,
                        "spinedata": {
                            "spinename": "leftMeterAnim",
                            "animationname": "collectd_mtr_butterfly",
                            "loop": true,
                            "timeScale": 0.9,
                        },
                    },
                    {
                        "name": "butterFLy_1",
                        "type": "Spine",
                        "width": 2001,
                        "height": 523,
                        "image": "leftMeterAnim",
                        "animationSpeed": 0.9,
                        "playing": true,
                        "loop": true,
                        "visible": false,
                        "spineAnimName": "collectd_mtr_butterfly",
                        x: 694,
                        y: 305,
                        "spinedata": {
                            "spinename": "leftMeterAnim",
                            "animationname": "collectd_mtr_butterfly",
                            "loop": true,
                            "timeScale": 0.9,
                        },
                    },
                    {
                        "name": "butterFLy_2",
                        "type": "Spine",
                        "width": 2001,
                        "height": 523,
                        "image": "leftMeterAnim",
                        "animationSpeed": 0.9,
                        "playing": true,
                        "loop": true,
                        "visible": false,
                        "spineAnimName": "collectd_mtr_butterfly",
                        x: 957,
                        y: 305,
                        "spinedata": {
                            "spinename": "leftMeterAnim",
                            "animationname": "collectd_mtr_butterfly",
                            "loop": true,
                            "timeScale": 0.9,
                        },
                    },
                    {
                        "name": "butterFLy_3",
                        "type": "Spine",
                        "width": 2001,
                        "height": 523,
                        "image": "leftMeterAnim",
                        "animationSpeed": 0.9,
                        "playing": true,
                        "loop": true,
                        "visible": false,
                        "spineAnimName": "collectd_mtr_butterfly",
                        x: 212,
                        y: 374,
                        "spinedata": {
                            "spinename": "leftMeterAnim",
                            "animationname": "collectd_mtr_butterfly",
                            "loop": true,
                            "timeScale": 0.9,
                        },
                    },
                    {
                        "name": "butterFLy_4",
                        "type": "Spine",
                        "width": 2001,
                        "height": 523,
                        "image": "leftMeterAnim",
                        "animationSpeed": 0.9,
                        "playing": true,
                        "loop": true,
                        "visible": false,
                        "spineAnimName": "collectd_mtr_butterfly",
                        x: 212,
                        y: 374,
                        "spinedata": {
                            "spinename": "leftMeterAnim",
                            "animationname": "collectd_mtr_butterfly",
                            "loop": true,
                            "timeScale": 0.9,
                        },
                    },
                    {
                        "name": "butterFLy_5",
                        "type": "Spine",
                        "width": 2001,
                        "height": 523,
                        "image": "leftMeterAnim",
                        "animationSpeed": 0.9,
                        "playing": true,
                        "loop": true,
                        "visible": false,
                        "spineAnimName": "collectd_mtr_butterfly",
                        x: 212,
                        y: 374,
                        "spinedata": {
                            "spinename": "leftMeterAnim",
                            "animationname": "collectd_mtr_butterfly",
                            "loop": true,
                            "timeScale": 0.9,
                        },
                    },
                    {
                        "name": "butterFLy_6",
                        "type": "Spine",
                        "width": 2001,
                        "height": 523,
                        "image": "leftMeterAnim",
                        "animationSpeed": 0.9,
                        "playing": true,
                        "loop": true,
                        "visible": false,
                        "spineAnimName": "collectd_mtr_butterfly",
                        x: 212,
                        y: 374,
                        "spinedata": {
                            "spinename": "leftMeterAnim",
                            "animationname": "collectd_mtr_butterfly",
                            "loop": true,
                            "timeScale": 0.9,
                        },
                    },
                    {
                        "name": "butterFLy_7",
                        "type": "Spine",
                        "width": 2001,
                        "height": 523,
                        "image": "leftMeterAnim",
                        "animationSpeed": 0.9,
                        "playing": true,
                        "loop": true,
                        "visible": false,
                        "spineAnimName": "collectd_mtr_butterfly",
                        x: 212,
                        y: 374,
                        "spinedata": {
                            "spinename": "leftMeterAnim",
                            "animationname": "collectd_mtr_butterfly",
                            "loop": true,
                            "timeScale": 0.9,
                        },
                    },
                    {
                        "name": "butterFLy_8",
                        "type": "Spine",
                        "width": 2001,
                        "height": 523,
                        "image": "leftMeterAnim",
                        "animationSpeed": 0.9,
                        "playing": true,
                        "loop": true,
                        "visible": false,
                        "spineAnimName": "collectd_mtr_butterfly",
                        x: 212,
                        y: 374,
                        "spinedata": {
                            "spinename": "leftMeterAnim",
                            "animationname": "collectd_mtr_butterfly",
                            "loop": true,
                            "timeScale": 0.9,
                        },
                    },
                    {
                        "name": "butterFLy_9",
                        "type": "Spine",
                        "width": 2001,
                        "height": 523,
                        "image": "leftMeterAnim",
                        "animationSpeed": 0.9,
                        "playing": true,
                        "loop": true,
                        "visible": false,
                        "spineAnimName": "collectd_mtr_butterfly",
                        x: 212,
                        y: 374,
                        "spinedata": {
                            "spinename": "leftMeterAnim",
                            "animationname": "collectd_mtr_butterfly",
                            "loop": true,
                            "timeScale": 0.9,
                        },
                    },


                ]
            },
        ],
    }

};

export const MysteryCounterContext = React.createContext(
    {}
);