import { frameworkBanner } from "@bonanzainteractive/slote_core";
import { objectTypes } from "@bonanzainteractive/slote_core";


frameworkBanner.data = {
    "BANNER_CONTAINER_X": 0,
    "BANNER_CONTAINER_Y": 0,
    "COMPONENTS": [
        {
            "id": "endBanner",
            "name": "endBanner",
            "type": "Container",
            "x": 0,
            "y": 0,
            "filterTypes": [],
            "group": "Outro",
            "parentLayer": "baseLayer",
            child: [
                //ANCHOR - OUTRO BANNER ######################################################################
                {
                    "id": "gofBannerOutro",
                    "name": "gofBannerContainerOutro",
                    "type": "Container",
                    "x": 0,
                    "y": 0,
                    "filterTypes": [],
                    "group": "Outro",
                    "visible": true,
                    "parentLayer": "baseLayer",
                    "uimode": "both",
                    child: [
                        {
                            "id": "gofBannerComponentOutro",
                            "name": "GofBanner",
                            "type": "Tag",
                            "group": "Outro",
                            "filterTypes": [],
                            child: [
                                // Outro Background graphic------------------------------
                                {
                                    "name": "introGraphic",
                                    "image": "introGraphic",
                                    "type": "Image",
                                    "layout": false,
                                    "visible": true,
                                    "group": "Outro",
                                    "width": 1920,
                                    "height": 1080,
                                    "x": 0,
                                    "y": 0,
                                },
                                //  intro_frame -------------------------------
                                {
                                    "name": "intro_frame",
                                    "image": "intro_frame",
                                    "type": "Image",
                                    "layout": false,
                                    "visible": true,
                                    "uimode":"desktop",
                                    "group": "Outro",
                                    "width": 1239,
                                    "height": 752,
                                    "x": 336.8,
                                    "y": 150.7,
                                },
                                {
                                    "name": "intro_frame",
                                    "image": "intro_frame",
                                    "type": "Image",
                                    "layout": true,
                                    "visible": true,
                                    "uimode":"mobile",
                                    "group": "Outro",
                                    "width": 1059.77,
                                    "height": 781.47,
                                    "x": 0,
                                    "y": 0,
                                },
                                // Congratulations Text---------------------------------
                                {
                                    "id": "congratulations_Text",
                                    "name": "outroText1_desktop",
                                    "type": "Text",
                                    "x": 960.5,
                                    "y": 320,
                                    "width": 900,
                                    "layout": false,
                                    "uimode": "desktop",
                                    "visible": true,
                                    "group": "Outro",
                                    "text": "outrotext_1",
                                    "scaleToFit": true,
                                    "anchor": [0.5, 0.5],
                                    "textStyle": {
                                        fontFamily: 'MYP Bold',
                                        fontSize: 94,
                                        fontStyle: 'normal',
                                        fill: ['#aee9c4','#ffffff', '#8fdbac', '#cdf562'],
                                        letterSpacing: 4,
                                        dropShadow: true,
                                        dropShadowColor: '#101f00',
                                        dropShadowDistance: 4,
                                        dropShadowSize: 4,
                                    }
                                },
                                {
                                    "id": "betterlucknext",
                                    "name": "betterlucknext",
                                    "type": "Container",
                                    "x": 0,
                                    "y": 0,
                                    "filterTypes": [],
                                    "group": "Outro",
                                    "visible": false,
                                    "parentLayer": "baseLayer",
                                    "uimode": "both",
                                    child: [
                                        {
                                            "id": "betterlucknext_Text",
                                            "name": "betterlucknext_desktop",
                                            "type": "Text",
                                            "x": 970,
                                            "y": 320,
                                            "width": 900,
                                            "layout": false,
                                            "uimode": "desktop",
                                            "visible": true,
                                            "group": "Outro",
                                            "text": "outrotext_4",
                                            "scaleToFit": true,
                                            "anchor": [0.5, 0.5],
                                            "textStyle": {
                                                fontFamily: 'MYP Bold',
                                                fontSize: 94,
                                                fontStyle: 'normal',
                                                fill: ['#aee9c4','#ffffff', '#8fdbac', '#cdf562'],
                                                letterSpacing: 4,
                                                dropShadow: true,
                                                dropShadowColor: '#101f00',
                                                dropShadowDistance: 4,
                                                dropShadowSize: 4,
                                            }
                                        },
                                        {
                                            "id": "betterlucknext_Text",
                                            "name": "betterlucknext_mobile",
                                            "type": "Text",
                                            "x": 533.5,
                                            "y": 852,
                                            "width": 900,
                                            "layout": true,
                                            "uimode": "mobile",
                                            "visible": false,
                                            "group": "Outro",
                                            "text": "outrotext_4",
                                            "scaleToFit": true,
                                            "anchor": [0.5, 0.5],
                                            "textStyle": {
                                                fontFamily: 'MYP Bold',
                                                fontSize: 130,
                                                fontStyle: 'normal',
                                                align: 'center',
                                                fill: ['#aee9c4','#ffffff', '#8fdbac', '#cdf562'],
                                                letterSpacing: 4,
                                                dropShadow: true,
                                                dropShadowColor: '#101f00',
                                                dropShadowDistance: 4,
                                                dropShadowSize: 4,
                                            }
                                        },
                                    ]
                                },
                                {
                                    "id": "congratulations_Text",
                                    "name": "outroText1_mobile",
                                    "type": "Text",
                                    "x": 0,
                                    "y": 0,
                                    "width": 720,
                                    "layout": true,
                                    "uimode": "mobile",
                                    "visible": true,
                                    "group": "Outro",
                                    "text": "outrotext_1",
                                    "scaleToFit": true,
                                    "anchor": [0.5, 0.5],
                                    "textStyle": {
                                        fontFamily: 'MYP Bold',
                                        fontSize: 130,
                                        fontStyle: 'normal',
                                        align: 'center',
                                        fill: ['#aee9c4','#ffffff', '#8fdbac', '#cdf562'],
                                        letterSpacing: 4,
                                        dropShadow: true,
                                        dropShadowColor: '#101f00',
                                        dropShadowDistance: 4,
                                        dropShadowSize: 4,
                                    }
                                },

                                // You have won Text---------------------------------
                                {
                                    "id": "YouHaveWon_Text",
                                    "name": "outroText2_desktop",
                                    "type": "Text",
                                    "x": 972,
                                    "y": 431.5,
                                    "height": 100,
                                    "width": 600,
                                    "layout": false,
                                    "uimode": "desktop",
                                    "visible": true,
                                    "group": "Outro",
                                    "text": "outrotext_2",
                                    "scaleToFit": true,
                                    "anchor": [0.5, 0.5],
                                    "textStyle": {
                                        fontFamily: 'MYP Bold',
                                        fontSize: 70,
                                        fontStyle: 'normal',
                                        fill: ['#aee9c4','#ffffff', '#8fdbac', '#cdf562'],
                                        letterSpacing: 4,
                                        dropShadow: true,
                                        dropShadowColor: '#101f00',
                                        dropShadowDistance: 4,
                                        dropShadowSize: 4,
                                    }
                                },
                                {
                                    "id": "YouHaveWon_Text",
                                    "name": "outroText2_mobile",
                                    "type": "Text",
                                    "x": 0,
                                    "y": 0,
                                    "height": 80,
                                    "width": 480,
                                    "layout": true,
                                    "uimode": "mobile",
                                    "visible": true,
                                    "group": "Outro",
                                    "text": "outrotext_2",
                                    "scaleToFit": true,
                                    "anchor": [0.5, 0.5],
                                    "textStyle": {
                                        fontFamily: 'MYP Bold',
                                        fontSize: 100,
                                        fontStyle: 'normal',
                                        align: 'center',
                                        fill: ['#aee9c4','#ffffff', '#8fdbac', '#cdf562'],
                                        letterSpacing: 4,
                                        dropShadow: true,
                                        dropShadowColor: '#101f00',
                                        dropShadowDistance: 4,
                                        dropShadowSize: 4,
                                    }
                                },


                                //Outro Total Win value after Free spins ---------------------------------
                                {
                                    "name": "Wintext_Outro_desktop",
                                    "type": "Text",
                                    "x": 970,
                                    "y": 573.7,
                                    "width": 500,
                                    "layout": false,
                                    "uimode": "desktop",
                                    "visible": true,
                                    "group": "Outro",
                                    "scaleToFit": true,
                                    "anchor": [0.5, 0.5],
                                    "textStyle": {
                                        fontFamily: 'MYP Bold',
                                        fontSize: 140,
                                        fontStyle: 'normal',
                                        fill: ['#fff600', '#f19901'],
                                        stroke: '#fafd00',
                                        letterSpacing: 6.1,
                                        strokeThickness: 3,
                                        dropShadow: true,
                                        dropShadowColor: '#101f00',
                                        dropShadowDistance: 8,
                                        dropShadowSize: 4,
                                    }
                                },
                                {
                                    "name": "Wintext_Outro_mobile",
                                    "type": "Text",
                                    "x": 0,
                                    "y": 0,
                                    "width": 500,
                                    "layout": true,
                                    "uimode": "mobile",
                                    "visible": true,
                                    "group": "Outro",
                                    "text": "buttonPanelText_16",
                                    "scaleToFit": true,
                                    "anchor": [0.5, 0.5],
                                    "textStyle": {
                                        fontFamily: 'MYP Bold',
                                        fontSize: 126,
                                        fontStyle: 'normal',
                                        align: 'center',
                                        fill: ['#fff600', '#f19901'],
                                        stroke: '#fafd00',
                                        letterSpacing: 6.1,
                                        strokeThickness: 3,
                                        dropShadow: true,
                                        dropShadowColor: '#101f00',
                                        dropShadowDistance: 8,
                                        dropShadowSize: 4,
                                    }
                                },

                                // Continue Button Text---------------------------------
                                {
                                    "id": "ContinueButton_desktop",
                                    "name": "ContinueButton_desktop",
                                    "type": objectTypes.Sprite,
                                    "image": "continue_Button",
                                    "x": 954.5,
                                    "y": 765.1,
                                    "interactive": true,
                                    "layout": false,
                                    "uimode": "desktop",
                                    "group": "Outro",
                                    "anchor": [0.5, 0.5],
                                    "visible": true,
                                    "buttonMode": true,
                                    "buttonState": {
                                        up: 'banner_continue_up.png',
                                        out: 'banner_continue_up.png',
                                        down: 'banner_continue_down.png',
                                        disable: 'banner_continue_up.png',
                                        enable: 'banner_continue_up.png',
                                        hover: 'banner_continue_hover.png'
                                    },
                                    "hitareaVisible": false,
                                    "shapeVisible": false,
                                },
                                {
                                    "id": "ContinueButton_mobile",
                                    "name": "ContinueButton_mobile",
                                    "type": objectTypes.Sprite,
                                    "image": "continue_Button",
                                    "x": 0,
                                    "y": 0,
                                    "interactive": true,
                                    "layout": true,
                                    "uimode": "mobile",
                                    "group": "Intro",
                                    "anchor": [0.5, 0.5],
                                    "visible": true,
                                    "buttonMode": true,
                                    "buttonState": {
                                        up: 'banner_continue_up.png',
                                        out: 'banner_continue_up.png',
                                        down: 'banner_continue_down.png',
                                        disable: 'banner_continue_up.png',
                                        enable: 'banner_continue_up.png',
                                        hover: 'banner_continue_hover.png'
                                    },
                                    "hitareaVisible": false,
                                    "shapeVisible": false,
                                },
                            ]
                        },
                    ]
                },
            ]
        },

        {
            "id": "startBanner",
            "name": "startBanner",
            "type": "Container",
            "x": 0,
            "y": 0,
            "filterTypes": [],
            "group": "Intro",
            "visible": true,
            "parentLayer": "baseLayer",
            child: [
                //ANCHOR - INTRO BANNER ######################################################################
                {
                    "id": "gofBannerIntro",
                    "name": "gofBannerContainerIntro",
                    "type": "Container",
                    "x": 0,
                    "y": 0,
                    "filterTypes": [],
                    "group": "Intro",
                    "uimode": "both",
                    "parentLayer": "baseLayer",
                    child: [
                        {
                            "id": "gofBannerComponentIntro",
                            "name": "GofBanner",
                            "type": "Tag",
                            "x": 0,
                            "y": 0,
                            "group": "Intro",
                            "filterTypes": [],
                            child: [

                                //  Intro Graphic-------------------------------
                                {
                                    "name": "introGraphic",
                                    "image": "introGraphic",
                                    "type": "Image",
                                    "layout": false,
                                    "visible": true,
                                    "interactive": false,
                                    "buttonMode": false,
                                    "group": "Intro",
                                    "width": 1920,
                                    "height": 1080,
                                    "x": 0,
                                    "y": 0,
                                },
                                //  intro_frame -------------------------------
                                {
                                    "name": "intro_frame",
                                    "image": "intro_frame",
                                    "type": "Image",
                                    "layout": false,
                                    "visible": true,
                                    "uimode" : "desktop",
                                    "group": "Intro",
                                    "width": 1239,
                                    "height": 752,
                                    "x": 336.8,
                                    "y": 150.7,
                                },
                                {
                                    "name": "intro_frame",
                                    "image": "intro_frame",
                                    "type": "Image",
                                    "layout": true,
                                    "visible": true,
                                    "uimode" : "mobile",
                                    "group": "Intro",
                                    "width": 1059.77,
                                    "height": 781.47,
                                    "x": 0,
                                    "y": 0,
                                },
                                // Congratulations Text---------------------------------
                                {
                                    "id": "text_3_intro_desktop",
                                    "name": "text_3_intro_desktop",
                                    "type": "Text",
                                    "x": 958,
                                    "y": 301.5,
                                    "width": 900,
                                    "layout": false,
                                    "uimode": "desktop",
                                    "visible": true,
                                    "group": "Intro",
                                    "text": "outrotext_1",
                                    "scaleToFit": true,
                                    "anchor": [0.5, 0.5],
                                    "textStyle": {
                                        fontFamily: 'MYP Bold',
                                        fontStyle: 'normal',
                                        fontSize: 94,
                                        fill: ['#aee9c4','#ffffff', '#8fdbac', '#cdf562'],
                                        letterSpacing: 4,
                                        dropShadow: true,
                                        dropShadowColor: '#101f00',
                                        dropShadowDistance: 4,
                                        dropShadowSize: 4,
                                    }
                                },
                                {

                                    "id": "text_3_intro_mobile",
                                    "name": "text_3_intro_mobile",
                                    "type": "Text",
                                    "x": 0,
                                    "y": 0,
                                    "width": 720,
                                    "layout": true,
                                    "uimode": "mobile",
                                    "visible": true,
                                    "group": "Intro",
                                    "text": "outrotext_1",
                                    "scaleToFit": true,
                                    "anchor": [0.5, 0.5],
                                    "textStyle": {
                                        fontFamily: 'MYP Bold',
                                        fontSize: 104,
                                        fontStyle: 'normal',
                                        align: 'center',
                                        letterSpacing: 4,
                                        fill: ['#aee9c4','#ffffff', '#8fdbac', '#cdf562'],
                                        dropShadowColor: '#101f00',
                                        dropShadowDistance: 4,
                                        dropShadowSize: 4,
                                    }
                                },

                                // You have won Text---------------------------------
                                {
                                    "id": "YouHaveWon_Text",
                                    "name": "text_2_Intro_desktop",
                                    "type": "Text",
                                    "x": 952,
                                    "y": 404.1,
                                    "height": 100,
                                    "width": 600,
                                    "layout": false,
                                    "uimode": "desktop",
                                    "visible": true,
                                    "group": "Intro",
                                    "text": "outrotext_2",
                                    "scaleToFit": true,
                                    "anchor": [0.5, 0.5],
                                    "textStyle": {
                                        fontFamily: 'MYP Bold',
                                        fontSize: 70,
                                        fontStyle: 'normal',
                                        fill: ['#aee9c4','#ffffff', '#8fdbac', '#cdf562'],
                                        letterSpacing: 4,
                                        dropShadow: true,
                                        dropShadowColor: '#101f00',
                                        dropShadowDistance: 4,
                                        dropShadowSize: 4,
                                    }
                                },
                                {
                                    "id": "YouHaveWon_Text",
                                    "name": "text_2_intro_mobile",
                                    "type": "Text",
                                    "x": 0,
                                    "y": 0,
                                    "height": 80,
                                    "width": 480,
                                    "layout": true,
                                    "uimode": "mobile",
                                    "visible": true,
                                    "group": "Intro",
                                    "text": "outrotext_2",
                                    "scaleToFit": true,
                                    "anchor": [0.5, 0.5],
                                    "textStyle": {
                                        fontFamily: 'MYP Bold',
                                        fontSize: 80,
                                        fontStyle: 'normal',
                                        align: 'center',
                                        letterSpacing: 4,
                                        fill: ['#aee9c4','#ffffff', '#8fdbac', '#cdf562'],
                                        dropShadowColor: '#101f00',
                                        dropShadowDistance: 4,
                                        dropShadowSize: 4,
                                    }
                                },
                                // 10 Text---------------------------------
                                {
                                    "id": "FreeSpinWonValue_desktop",
                                    "name": "text_IntroScreenFG_desktop",
                                    "type": "Text",
                                    "x": 950,
                                    "y": 539.5,
                                    "height": 100,
                                    "width": 500,
                                    "layout": false,
                                    "uimode": "desktop",
                                    "visible": true,
                                    "group": "Intro",
                                    "text": "introtext_4",
                                    "scaleToFit": true,
                                    "anchor": [0.5, 0.5],
                                    "textStyle": {
                                        fontFamily: 'MYP Bold',
                                        fontSize: 140,
                                        fontStyle: 'normal',
                                        fill: ['#fff600', '#f19901'],
                                        stroke: '#fafd00',
                                        letterSpacing: 6.1,
                                        strokeThickness: 3,
                                        dropShadow: true,
                                        dropShadowColor: '#101f00',
                                        dropShadowDistance: 8,
                                        dropShadowSize: 4,
                                    }
                                },
                                {
                                    "id": "FreeSpinWonValue_mobile",
                                    "name": "text_IntroScreenFG_mobile",
                                    "type": "Text",
                                    "x": 0,
                                    "y": 0,
                                    "height": 80,
                                    "width": 400,
                                    "layout": true,
                                    "uimode": "mobile",
                                    "visible": true,
                                    "group": "Intro",
                                    "text": "introtext_4",
                                    "scaleToFit": true,
                                    "anchor": [0.5, 0.5],
                                    "textStyle": {
                                        fontFamily: 'MYP Bold',
                                        fontSize: 126,
                                        fontStyle: 'normal',
                                        align: 'center',
                                        fill: ['#fff600', '#f19901'],
                                        stroke: '#fafd00',
                                        letterSpacing: 6.1,
                                        strokeThickness: 3,
                                        dropShadow: true,
                                        dropShadowColor: '#101f00',
                                        dropShadowDistance: 8,
                                        dropShadowSize: 4,
                                    }
                                },

                                // Continue Button ---------------------------------
                                {
                                    "id": "intro_ContinueButton_desktop",
                                    "name": "btn_introBanner_desktop",
                                    "type": objectTypes.Sprite,
                                    "image": "continue_Button",
                                    "x": 954.5,
                                    "y": 765.1,
                                    "interactive": true,
                                    "layout": false,
                                    "uimode": "desktop",
                                    "group": "Intro",
                                    "anchor": [0.5, 0.5],
                                    "visible": true,
                                    "buttonMode": true,
                                    "buttonState": {
                                        up: 'banner_continue_up.png',
                                        out: 'banner_continue_up.png',
                                        down: 'banner_continue_down.png',
                                        disable: 'banner_continue_up.png',
                                        enable: 'banner_continue_up.png',
                                        hover: 'banner_continue_hover.png'
                                    },
                                    "hitareaVisible": false,
                                    "shapeVisible": false,
                                },
                                {
                                    "id": "intro_ContinueButton_desktop",
                                    "name": "btn_introBanner_mobile",
                                    "type": objectTypes.Sprite,
                                    "image": "continue_Button",
                                    "x": 0,
                                    "y": 0,
                                    "interactive": true,
                                    "layout": true,
                                    "uimode": "mobile",
                                    "group": "Intro",
                                    "anchor": [0.5, 0.5],
                                    "visible": true,
                                    "buttonMode": true,
                                    "buttonState": {
                                        up: 'banner_continue_up.png',
                                        out: 'banner_continue_up.png',
                                        down: 'banner_continue_down.png',
                                        disable: 'banner_continue_up.png',
                                        enable: 'banner_continue_up.png',
                                        hover: 'banner_continue_hover.png'
                                    },
                                    "hitareaVisible": false,
                                    "shapeVisible": false,
                                },
                                {
                                    "name": "text_freeSpinAward_desktop",
                                    "type": "Text",
                                    "x": 954.5,
                                    "y": 669.5,
                                    "width": 440,
                                    "layout": false,
                                    "uimode": "desktop",
                                    "visible": true,
                                    "group": "Intro",
                                    "text": "freeSpinAward",
                                    "scaleToFit": true,
                                    "anchor": [0.5, 0.5],
                                    "textStyle": {
                                        fontFamily: 'MYP Bold',
                                        fontSize: 70,
                                        fontStyle: 'normal',
                                        fill: ['#aee9c4','#ffffff', '#8fdbac', '#cdf562'],
                                        letterSpacing: 4,
                                        dropShadow: true,
                                        dropShadowColor: '#101f00',
                                        dropShadowDistance: 4,
                                        dropShadowSize: 4,
                                    }
                                },
                                {
                                    "name": "text_freeSpinAward_mobile",
                                    "type": "Text",
                                    "x": 0,
                                    "y": 0,
                                    "width": 352,
                                    "layout": true,
                                    "uimode": "mobile",
                                    "visible": true,
                                    "group": "Intro",
                                    "text": "freeSpinAward",
                                    "scaleToFit": true,
                                    "anchor": [0.5, 0.5],
                                    "textStyle": {
                                        fontFamily: 'MYP Bold',
                                        fontSize: 80,
                                        fontStyle: 'normal',
                                        align: 'center',
                                        fill: ['#aee9c4','#ffffff', '#8fdbac', '#cdf562'],
                                        letterSpacing: 6,
                                        dropShadow: true,
                                        dropShadowColor: '#101f00',
                                        dropShadowDistance: 4,
                                        dropShadowSize: 4,
                                    }
                                },
                            ]
                        }
                    ]
                },
            ]
        }
    ]
};
