import { objectTypes, frameworkIntroductionScreen } from "@bonanzainteractive/slote_core";

frameworkIntroductionScreen.data = {
    "COMPONENTS": [
        {
            "id": "IntroductionInCanvas",
            "name": "IntroductionInCanvas",
            "type": "Tag",
            "class": "",
            "filterTypes": [],
            child: [
                {
                    "name": "backgroundImageOfIntroductionPage",
                    "type": "Graphic",
                    "shape": "rectangle",
                    "uimode": "desktop",
                    "visible": true,
                    "alpha": 1,
                    "color": "0x000000",
                    "width": 1920,
                    "height": 1080,
                    "x": 0,
                    "y": 0,
                },
                {
                    "name": "backgroundImageOfIntroductionPage_portrait",
                    "type": "Graphic",
                    "shape": "rectangle",
                    "uimode": "mobile",
                    "visible": true,
                    "alpha": 1,
                    "color": "0x000000",
                    "width": 1080,
                    "height": 1920,
                    "x": 0,
                    "y": 0,
                },


                {
                    "id": "GameIntroductionScreen_baseLayer",
                    "name": "GameIntroductionScreen_baseLayer",
                    "type": "Container",
                    "class": "",
                    "x": 0,
                    "y": 0,
                    "filterTypes": [],
                    child: [
                        {
                            "id": "GameIntroductionScreen",
                            "name": "GameIntroductionScreen",
                            "type": "Tag",
                            "class": "",
                            "filterTypes": [],
                            child: [
                                {
                                    "name": "GameIntroductionScreenIntroWithoutBg",
                                    "type": "Container",
                                    "x": 0,
                                    "y": 0,
                                    "uimode": "desktop",
                                    "visible": true,
                                    child: [
                                        {
                                            "name": "image_game_logo",
                                            "image": "IntroJQLogo",
                                            "type": "Image",
                                            "visible": true,
                                            "width": 441,
                                            "height": 273,
                                            "x": 750,
                                            "y": 0,
                                        },
                                        //ANCHOR -  - postIntro_Page1 Container desktop ------------------------
                                        {
                                            "name": "postIntro_Page1",
                                            "type": "Container",
                                            "visible": true,
                                            "x": 0,
                                            "y": 0,
                                            "width": 1920,
                                            "height": 1080,
                                            child: [
                                                {
                                                    "name": "page1Image1",
                                                    "image": "Intro_page_1_slide_1",
                                                    "type": "Image",
                                                    "visible": true,
                                                    "width": 796.38,
                                                    "height": 524.94,
                                                    "x": 130,
                                                    "y": 276.5,
                                                },
                                                {
                                                    "name": "page1Text1",
                                                    "type": "Text",
                                                    "x": 1448,
                                                    "y": 390,
                                                    "visible": true,
                                                    "scaleToFit": true,
                                                    "text": "IntroHeading1",
                                                    "width": 450,
                                                    "anchor": [0.5, 0.5],
                                                    "textStyle": {
                                                        fontFamily: 'MYP Bold',
                                                        fontSize: 48,
                                                        fontStyle: 'bold',
                                                        fill: ['#fdc210'],

                                                    },
                                                },
                                                {
                                                    "name": "page1Text2",
                                                    "type": "Text",
                                                    "x": 1470,
                                                    "y": 480,
                                                    "width": 1200,
                                                    "visible": true,
                                                    "text": "introductiontext_1",
                                                    "scaleToFit": true,
                                                    "anchor": [0.5, 0.5],
                                                    "textStyle": {
                                                        fontFamily: 'Arial',
                                                        // fontWeight: 'bold',
                                                        fontSize: 34,
                                                        fontStyle: 'normal',
                                                        fill: ['#ffffff'],
                                                        align: 'center',
                                                        wordWrap: true,
                                                        wordWrapWidth: 800,
                                                        breakWords: true,
                                                    }
                                                },

                                                {
                                                    "name": "page1Text3",
                                                    "type": "Text",
                                                    "x": 1470,
                                                    "y": 610,
                                                    "width": 1220,
                                                    "visible": true,
                                                    "text": "introductiontext_2",
                                                    "scaleToFit": true,
                                                    "anchor": [0.5, 0.5],
                                                    "textStyle": {
                                                        fontFamily: 'Arial',

                                                        fontSize: 34,
                                                        fontStyle: 'normal',
                                                        fill: ['#ffffff'],
                                                        wordWrap: true,
                                                        wordWrapWidth: 700,
                                                        breakWords: true,
                                                        align: 'center',
                                                    }
                                                },
                                            ]
                                        },
                                        //ANCHOR -  - postIntro_Page2 Container desktop ------------------------
                                        {
                                            "name": "postIntro_Page2",
                                            "type": "Container",
                                            "visible": false,
                                            "x": 0,
                                            "y": 0,
                                            "width": 1920,
                                            "height": 1080,
                                            child: [
                                                {
                                                    "name": "page2Image1",
                                                    "image": "Intro_page_1_slide_2",
                                                    "type": "Image",
                                                    "class": "",
                                                    "layout": true,
                                                    "uimode": "desktop",
                                                    "visible": true,
                                                    "width": 796.38,
                                                    "height": 524.94,
                                                    "x": 130,
                                                    "y": 276.5,
                                                },

                                                {
                                                    "name": "page1Text1",
                                                    "type": "Text",
                                                    "x": 1448,
                                                    "y": 390,
                                                    "visible": true,
                                                    "scaleToFit": true,
                                                    "text": "IntroHeading1",
                                                    "width": 450,
                                                    "anchor": [0.5, 0.5],
                                                    "textStyle": {
                                                        fontFamily: 'MYP Bold',
                                                        fontSize: 48,
                                                        fontStyle: 'bold',
                                                        fill: ['#fdc210'],

                                                    },
                                                },
                                                {
                                                    "name": "page1Text2",
                                                    "type": "Text",
                                                    "x": 1470,
                                                    "y": 480,
                                                    "width": 1200,
                                                    "visible": true,
                                                    "text": "introductiontext_1",
                                                    "scaleToFit": true,
                                                    "anchor": [0.5, 0.5],
                                                    "textStyle": {
                                                        fontFamily: 'Arial',
                                                        // fontWeight: 'bold',
                                                        fontSize: 34,
                                                        fontStyle: 'normal',
                                                        fill: ['#ffffff'],
                                                        align: 'center',
                                                        wordWrap: true,
                                                        wordWrapWidth: 800,
                                                        breakWords: true,
                                                    }
                                                },

                                                {
                                                    "name": "page1Text3",
                                                    "type": "Text",
                                                    "x": 1470,
                                                    "y": 610,
                                                    "width": 1220,
                                                    "visible": true,
                                                    "text": "introductiontext_2",
                                                    "scaleToFit": true,
                                                    "anchor": [0.5, 0.5],
                                                    "textStyle": {
                                                        fontFamily: 'Arial',

                                                        fontSize: 34,
                                                        fontStyle: 'normal',
                                                        fill: ['#ffffff'],
                                                        wordWrap: true,
                                                        wordWrapWidth: 700,
                                                        breakWords: true,
                                                        align: 'center',
                                                    }
                                                },
                                            ]
                                        },
                                        //ANCHOR -  - postIntro_Page3 Container desktop ------------------------
                                        {
                                            "name": "postIntro_Page3",
                                            "type": "Container",
                                            "visible": false,
                                            "x": 0,
                                            "y": 0,
                                            "width": 1920,
                                            "height": 1080,
                                            child: [
                                                {
                                                    "name": "page3Image1",
                                                    "image": "Intro_page_2_slide_1",
                                                    "type": "Image",
                                                    "class": "",
                                                    "layout": true,
                                                    "uimode": "desktop",
                                                    "visible": true,
                                                    "width": 796.38,
                                                    "height": 524.94,
                                                    "x": 130,
                                                    "y": 276.5,
                                                },


                                                {
                                                    "name": "page1Text1",
                                                    "type": "Text",
                                                    "x": 1448,
                                                    "y": 490,
                                                    "visible": true,
                                                    "scaleToFit": true,
                                                    "text": "IntroHeading2",
                                                    "width": 450,
                                                    "anchor": [0.5, 0.5],
                                                    "textStyle": {
                                                        fontFamily: 'MYP Bold',
                                                        fontSize: 48,
                                                        fontStyle: 'bold',
                                                        fill: ['#fdc210'],

                                                    },
                                                },
                                                {
                                                    "name": "page1Text2",
                                                    "type": "Text",
                                                    "x": 1470,
                                                    "y": 580,
                                                    "width": 1200,
                                                    "visible": true,
                                                    "text": "introductiontext_22",
                                                    "scaleToFit": true,
                                                    "anchor": [0.5, 0.5],
                                                    "textStyle": {
                                                        fontFamily: 'Arial',
                                                        // fontWeight: 'bold',
                                                        fontSize: 34,
                                                        fontStyle: 'normal',
                                                        fill: ['#ffffff'],
                                                        align: 'center',
                                                        wordWrap: true,
                                                        wordWrapWidth: 800,
                                                        breakWords: true,
                                                    }
                                                },
                                            ]
                                        },
                                        //ANCHOR -  - postIntro_Page4 Container desktop ------------------------
                                        {
                                            "name": "postIntro_Page4",
                                            "type": "Container",
                                            "visible": false,
                                            "x": 0,
                                            "y": 0,
                                            "width": 1920,
                                            "height": 1080,
                                            child: [
                                                {
                                                    "name": "page4Image1",
                                                    "image": "Intro_page_2_slide_2",
                                                    "type": "Image",
                                                    "class": "",
                                                    "layout": true,
                                                    "uimode": "desktop",
                                                    "visible": true,
                                                    "width": 796.38,
                                                    "height": 524.94,
                                                    "x": 130,
                                                    "y": 276.5,
                                                },

                                                {
                                                    "name": "page1Text1",
                                                    "type": "Text",
                                                    "x": 1448,
                                                    "y": 490,
                                                    "visible": true,
                                                    "scaleToFit": true,
                                                    "text": "IntroHeading2",
                                                    "width": 450,
                                                    "anchor": [0.5, 0.5],
                                                    "textStyle": {
                                                        fontFamily: 'MYP Bold',
                                                        fontSize: 48,
                                                        fontStyle: 'bold',
                                                        fill: ['#fdc210'],

                                                    },
                                                },
                                                {
                                                    "name": "page1Text2",
                                                    "type": "Text",
                                                    "x": 1470,
                                                    "y": 580,
                                                    "width": 1200,
                                                    "visible": true,
                                                    "text": "introductiontext_22",
                                                    "scaleToFit": true,
                                                    "anchor": [0.5, 0.5],
                                                    "textStyle": {
                                                        fontFamily: 'Arial',
                                                        // fontWeight: 'bold',
                                                        fontSize: 34,
                                                        fontStyle: 'normal',
                                                        fill: ['#ffffff'],
                                                        align: 'center',
                                                        wordWrap: true,
                                                        wordWrapWidth: 800,
                                                        breakWords: true,
                                                    }
                                                },
                                            ]
                                        },
                                        //ANCHOR -  - postIntro_Page5 Container desktop ------------------------
                                        {
                                            "name": "postIntro_Page5",
                                            "type": "Container",
                                            "visible": false,
                                            "x": 0,
                                            "y": 0,
                                            "width": 1920,
                                            "height": 1080,
                                            child: [
                                                {
                                                    "name": "page5Image1",
                                                    "image": "Intro_page_2_slide_3",
                                                    "type": "Image",
                                                    "class": "",
                                                    "layout": true,
                                                    "uimode": "desktop",
                                                    "visible": true,
                                                    "width": 796.38,
                                                    "height": 524.94,
                                                    "x": 130,
                                                    "y": 276.5,
                                                },

                                                {
                                                    "name": "page1Text1",
                                                    "type": "Text",
                                                    "x": 1448,
                                                    "y": 490,
                                                    "visible": true,
                                                    "scaleToFit": true,
                                                    "text": "IntroHeading2",
                                                    "width": 450,
                                                    "anchor": [0.5, 0.5],
                                                    "textStyle": {
                                                        fontFamily: 'MYP Bold',
                                                        fontSize: 48,
                                                        fontStyle: 'bold',
                                                        fill: ['#fdc210'],

                                                    },
                                                },
                                                {
                                                    "name": "page1Text2",
                                                    "type": "Text",
                                                    "x": 1470,
                                                    "y": 580,
                                                    "width": 1200,
                                                    "visible": true,
                                                    "text": "introductiontext_22",
                                                    "scaleToFit": true,
                                                    "anchor": [0.5, 0.5],
                                                    "textStyle": {
                                                        fontFamily: 'Arial',
                                                        // fontWeight: 'bold',
                                                        fontSize: 34,
                                                        fontStyle: 'normal',
                                                        fill: ['#ffffff'],
                                                        align: 'center',
                                                        wordWrap: true,
                                                        wordWrapWidth: 800,
                                                        breakWords: true,
                                                    }
                                                },
                                            ]
                                        },
                                    ]
                                },
                                //NOTE -  Mobile Container -------------------------
                                {
                                    "name": "GameIntroductionScreenIntroWithoutBg",
                                    "type": "Container",
                                    "x": 0,
                                    "y": 0,
                                    "uimode": "mobile",
                                    "layout": true,
                                    "visible": true,
                                    child: [
                                        {
                                            "name": "image_game_logo",
                                            "image": "IntroJQLogo",
                                            "type": "Image",
                                            "uimode": "mobile",
                                            "layout": true,
                                            "visible": true,
                                            "width": 551,
                                            "height": 360,
                                            "x": 250,
                                            "y": 0,
                                        },
                                        //ANCHOR -  - postIntro_Page1 Container mobile ------------------------
                                        {
                                            "name": "postIntro_Page1",
                                            "type": "Container",
                                            "visible": true,
                                            "x": 0,
                                            "y": 0,
                                            "width": 1920,
                                            "height": 1080,
                                            child: [
                                                {
                                                    "name": "page1Image1",
                                                    "image": "Intro_page_1_slide_1",
                                                    "type": "Image",
                                                    "visible": true,
                                                    "width": 1021,
                                                    "height": 673,
                                                    "x": 30,
                                                    "y": 350,
                                                },
                                                {
                                                    "name": "page1Image1Text1",
                                                    "type": "Text",
                                                    "x": 550,
                                                    "y": 1130,
                                                    "visible": true,
                                                    "scaleToFit": true,
                                                    "text": "IntroHeading1",
                                                    "width": 450,
                                                    "anchor": [0.5, 0.5],
                                                    "textStyle": {
                                                        fontFamily: 'MYP Bold',
                                                        fontSize: 48,
                                                        fontStyle: 'bold',
                                                        fill: ['#fdc210'],
                                                    },
                                                },
                                                {
                                                    "name": "page1Image1Text2",
                                                    "type": "Text",
                                                    "x": 550,
                                                    "y": 1250,
                                                    "width": 1200,
                                                    "visible": true,
                                                    "text": "introductiontext_1",
                                                    "scaleToFit": true,
                                                    "anchor": [0.5, 0.5],
                                                    "textStyle": {
                                                        fontFamily: 'Arial',
                                                        fontSize: 34,
                                                        fontStyle: 'normal',
                                                        fill: ['#ffffff'],
                                                        align: 'center',
                                                        wordWrap: true,
                                                        wordWrapWidth: 800,
                                                        breakWords: true,
                                                    }
                                                },
                                                {
                                                    "name": "page1Image1Text3",
                                                    "type": "Text",
                                                    "x": 550,
                                                    "y": 1400,
                                                    "width": 1220,
                                                    "visible": true,
                                                    "text": "introductiontext_2",
                                                    "scaleToFit": true,
                                                    "anchor": [0.5, 0.5],
                                                    "textStyle": {
                                                        fontFamily: 'Arial',
                                                        fontSize: 34,
                                                        fontStyle: 'normal',
                                                        fill: ['#ffffff'],
                                                        wordWrap: true,
                                                        wordWrapWidth: 700,
                                                        breakWords: true,
                                                        align: 'center',
                                                    }
                                                },
                                            ]
                                        },
                                        //ANCHOR -  - postIntro_Page2 Container mobile ------------------------
                                        {
                                            "name": "postIntro_Page2",
                                            "type": "Container",
                                            "visible": false,
                                            "x": 0,
                                            "y": 0,
                                            "width": 1920,
                                            "height": 1080,
                                            child: [
                                                {
                                                    "name": "page2Image1",
                                                    "image": "Intro_page_1_slide_2",
                                                    "type": "Image",
                                                    "class": "",
                                                    "layout": true,
                                                    "uimode": "desktop",
                                                    "visible": true,
                                                    "width": 1021,
                                                    "height": 673,
                                                    "x": 30,
                                                    "y": 350,
                                                },

                                                {
                                                    "name": "page2Image1Text1",
                                                    "type": "Text",
                                                    "x": 550,
                                                    "y": 1130,
                                                    "visible": true,
                                                    "scaleToFit": true,
                                                    "text": "IntroHeading1",
                                                    "width": 450,
                                                    "anchor": [0.5, 0.5],
                                                    "textStyle": {
                                                        fontFamily: 'MYP Bold',
                                                        fontSize: 48,
                                                        fontStyle: 'bold',
                                                        fill: ['#fdc210'],
                                                    },
                                                },
                                                {
                                                    "name": "page2Image1Text2",
                                                    "type": "Text",
                                                    "x": 550,
                                                    "y": 1250,
                                                    "width": 1200,
                                                    "visible": true,
                                                    "text": "introductiontext_1",
                                                    "scaleToFit": true,
                                                    "anchor": [0.5, 0.5],
                                                    "textStyle": {
                                                        fontFamily: 'Arial',
                                                        fontSize: 34,
                                                        fontStyle: 'normal',
                                                        fill: ['#ffffff'],
                                                        align: 'center',
                                                        wordWrap: true,
                                                        wordWrapWidth: 800,
                                                        breakWords: true,
                                                    }
                                                },

                                                {
                                                    "name": "page2Image1Text3",
                                                    "type": "Text",
                                                    "x": 550,
                                                    "y": 1400,
                                                    "width": 1220,
                                                    "visible": true,
                                                    "text": "introductiontext_2",
                                                    "scaleToFit": true,
                                                    "anchor": [0.5, 0.5],
                                                    "textStyle": {
                                                        fontFamily: 'Arial',

                                                        fontSize: 34,
                                                        fontStyle: 'normal',
                                                        fill: ['#ffffff'],
                                                        wordWrap: true,
                                                        wordWrapWidth: 700,
                                                        breakWords: true,
                                                        align: 'center',
                                                    }
                                                },
                                            ]
                                        },
                                        //ANCHOR -  - postIntro_Page3 Container mobile ------------------------
                                        {
                                            "name": "postIntro_Page3",
                                            "type": "Container",
                                            "visible": false,
                                            "x": 0,
                                            "y": 0,
                                            "width": 1920,
                                            "height": 1080,
                                            child: [
                                                {
                                                    "name": "page3Image1",
                                                    "image": "Intro_page_2_slide_1",
                                                    "type": "Image",
                                                    "class": "",
                                                    "layout": true,
                                                    "uimode": "desktop",
                                                    "visible": true,
                                                    "width": 1021,
                                                    "height": 673,
                                                    "x": 30,
                                                    "y": 350,
                                                },


                                                {
                                                    "name": "page3Image1Text1",
                                                    "type": "Text",
                                                    "x": 550,
                                                    "y": 1130,
                                                    "visible": true,
                                                    "scaleToFit": true,
                                                    "text": "IntroHeading2",
                                                    "width": 450,
                                                    "anchor": [0.5, 0.5],
                                                    "textStyle": {
                                                        fontFamily: 'MYP Bold',
                                                        fontSize: 48,
                                                        fontStyle: 'bold',
                                                        fill: ['#fdc210'],
                                                    },
                                                },
                                                {
                                                    "name": "page3Image1Text2",
                                                    "type": "Text",
                                                    "x": 550,
                                                    "y": 1250,
                                                    "width": 1200,
                                                    "visible": true,
                                                    "text": "introductiontext_22",
                                                    "scaleToFit": true,
                                                    "anchor": [0.5, 0.5],
                                                    "textStyle": {
                                                        fontFamily: 'Arial',
                                                        // fontWeight: 'bold',
                                                        fontSize: 34,
                                                        fontStyle: 'normal',
                                                        fill: ['#ffffff'],
                                                        align: 'center',
                                                        wordWrap: true,
                                                        wordWrapWidth: 800,
                                                        breakWords: true,
                                                    }
                                                },
                                            ]
                                        },
                                        //ANCHOR -  - postIntro_Page4 Container mobile ------------------------
                                        {
                                            "name": "postIntro_Page4",
                                            "type": "Container",
                                            "visible": false,
                                            "x": 0,
                                            "y": 0,
                                            "width": 1920,
                                            "height": 1080,
                                            child: [
                                                {
                                                    "name": "page4Image1",
                                                    "image": "Intro_page_2_slide_2",
                                                    "type": "Image",
                                                    "class": "",
                                                    "layout": true,
                                                    "uimode": "desktop",
                                                    "visible": true,
                                                    "width": 1021,
                                                    "height": 673,
                                                    "x": 30,
                                                    "y": 350,
                                                },

                                                {
                                                    "name": "page4Image1Text1",
                                                    "type": "Text",
                                                    "x": 550,
                                                    "y": 1130,
                                                    "visible": true,
                                                    "scaleToFit": true,
                                                    "text": "IntroHeading2",
                                                    "width": 450,
                                                    "anchor": [0.5, 0.5],
                                                    "textStyle": {
                                                        fontFamily: 'MYP Bold',
                                                        fontSize: 48,
                                                        fontStyle: 'bold',
                                                        fill: ['#fdc210'],
                                                    },
                                                },
                                                {
                                                    "name": "page4Image1Text2",
                                                    "type": "Text",
                                                    "x": 550,
                                                    "y": 1250,
                                                    "width": 1200,
                                                    "visible": true,
                                                    "text": "introductiontext_22",
                                                    "scaleToFit": true,
                                                    "anchor": [0.5, 0.5],
                                                    "textStyle": {
                                                        fontFamily: 'Arial',
                                                        // fontWeight: 'bold',
                                                        fontSize: 34,
                                                        fontStyle: 'normal',
                                                        fill: ['#ffffff'],
                                                        align: 'center',
                                                        wordWrap: true,
                                                        wordWrapWidth: 800,
                                                        breakWords: true,
                                                    }
                                                },
                                            ]
                                        },
                                        //ANCHOR -  - postIntro_Page5 Container mobile ------------------------
                                        {
                                            "name": "postIntro_Page5",
                                            "type": "Container",
                                            "visible": false,
                                            "x": 0,
                                            "y": 0,
                                            "width": 1920,
                                            "height": 1080,
                                            child: [
                                                {
                                                    "name": "page5Image1",
                                                    "image": "Intro_page_2_slide_3",
                                                    "type": "Image",
                                                    "class": "",
                                                    "layout": true,
                                                    "uimode": "desktop",
                                                    "visible": true,
                                                    "width": 1021,
                                                    "height": 673,
                                                    "x": 30,
                                                    "y": 350,
                                                },

                                                {
                                                    "name": "page5Image1Text1",
                                                    "type": "Text",
                                                    "x": 550,
                                                    "y": 1130,
                                                    "visible": true,
                                                    "scaleToFit": true,
                                                    "text": "IntroHeading2",
                                                    "width": 450,
                                                    "anchor": [0.5, 0.5],
                                                    "textStyle": {
                                                        fontFamily: 'MYP Bold',
                                                        fontSize: 48,
                                                        fontStyle: 'bold',
                                                        fill: ['#fdc210'],

                                                    },
                                                },
                                                {
                                                    "name": "page5Image1Text2",
                                                    "type": "Text",
                                                    "x": 550,
                                                    "y": 1250,
                                                    "width": 1200,
                                                    "visible": true,
                                                    "text": "introductiontext_22",
                                                    "scaleToFit": true,
                                                    "anchor": [0.5, 0.5],
                                                    "textStyle": {
                                                        fontFamily: 'Arial',
                                                        // fontWeight: 'bold',
                                                        fontSize: 34,
                                                        fontStyle: 'normal',
                                                        fill: ['#ffffff'],
                                                        align: 'center',
                                                        wordWrap: true,
                                                        wordWrapWidth: 800,
                                                        breakWords: true,
                                                    }
                                                },
                                            ]
                                        },
                                    ]
                                },
                                //ANCHOR -  - Intro_page_inActive_1 ------------------------
                                {
                                    "name": "Intro_page_inActive_1",
                                    "image": "Intro_page_inActive",
                                    "type": objectTypes.Sprite,
                                    "class": "",
                                    "layout": true,
                                    "uimode": "desktop",
                                    "visible": true,
                                    "width": 28,
                                    "height": 28,
                                    "x": 880,
                                    "y": 850,
                                    "buttonState": {

                                    },
                                    "interactive": true,
                                    "buttonMode": true,
                                },
                                {
                                    "name": "Intro_page_inActive_1",
                                    "image": "Intro_page_inActive",
                                    "type": objectTypes.Sprite,
                                    "class": "",
                                    "layout": true,
                                    "uimode": "mobile",
                                    "visible": true,
                                    "width": 28,
                                    "height": 28,
                                    "x": 400,
                                    "y": 1600,
                                    "buttonState": {

                                    },
                                    "interactive": true,
                                    "buttonMode": true,
                                },
                                {
                                    "name": "Intro_page_active_1",
                                    "image": "Intro_page_active",
                                    "type": objectTypes.Sprite,
                                    "class": "",
                                    "layout": true,
                                    "uimode": "desktop",
                                    "visible": true,
                                    "width": 28,
                                    "height": 28,
                                    "x": 880,
                                    "y": 850,
                                    "buttonState": {

                                    },
                                    "interactive": true,
                                    "buttonMode": true,
                                },
                                {
                                    "name": "Intro_page_active_1",
                                    "image": "Intro_page_active",
                                    "type": objectTypes.Sprite,
                                    "class": "",
                                    "layout": true,
                                    "uimode": "mobile",
                                    "visible": true,
                                    "width": 28,
                                    "height": 28,
                                    "x": 400,
                                    "y": 1600,
                                    "buttonState": {

                                    },
                                    "interactive": true,
                                    "buttonMode": true,
                                },
                                //ANCHOR -  - Intro_page_active_2 ------------------------
                                {
                                    "name": "Intro_page_active_2",
                                    "image": "Intro_page_active",
                                    "type": objectTypes.Sprite,
                                    "class": "",
                                    "layout": true,
                                    "uimode": "desktop",
                                    "visible": true,
                                    "width": 28,
                                    "height": 28,
                                    "x": 920,
                                    "y": 850,
                                    "buttonState": {

                                    },
                                    "interactive": true,
                                    "buttonMode": true,
                                },
                                {
                                    "name": "Intro_page_active_2",
                                    "image": "Intro_page_active",
                                    "type": objectTypes.Sprite,
                                    "class": "",
                                    "layout": true,
                                    "uimode": "mobile",
                                    "visible": true,
                                    "width": 28,
                                    "height": 28,
                                    "x": 473,
                                    "y": 1600,
                                    "buttonState": {

                                    },
                                    "interactive": true,
                                    "buttonMode": true,
                                },
                                {
                                    "name": "Intro_page_inActive_2",
                                    "image": "Intro_page_inActive",
                                    "type": objectTypes.Sprite,
                                    "class": "",
                                    "layout": true,
                                    "uimode": "desktop",
                                    "visible": true,
                                    "width": 28,
                                    "height": 28,
                                    "x": 920,
                                    "y": 850,
                                    "buttonState": {

                                    },
                                    "interactive": true,
                                    "buttonMode": true,
                                },
                                {
                                    "name": "Intro_page_inActive_2",
                                    "image": "Intro_page_inActive",
                                    "type": objectTypes.Sprite,
                                    "class": "",
                                    "layout": true,
                                    "uimode": "mobile",
                                    "visible": true,
                                    "width": 28,
                                    "height": 28,
                                    "x": 473,
                                    "y": 1600,
                                    "buttonState": {

                                    },
                                    "interactive": true,
                                    "buttonMode": true,
                                },
                                //ANCHOR -  - Intro_page_active_3 ------------------------
                                {
                                    "name": "Intro_page_active_3",
                                    "image": "Intro_page_active",
                                    "type": objectTypes.Sprite,
                                    "class": "",
                                    "layout": true,
                                    "uimode": "desktop",
                                    "visible": true,
                                    "width": 28,
                                    "height": 28,
                                    "x": 960,
                                    "y": 850,
                                    "buttonState": {

                                    },
                                    "interactive": true,
                                    "buttonMode": true,
                                },
                                {
                                    "name": "Intro_page_active_3",
                                    "image": "Intro_page_active",
                                    "type": objectTypes.Sprite,
                                    "class": "",
                                    "layout": true,
                                    "uimode": "mobile",
                                    "visible": true,
                                    "width": 28,
                                    "height": 28,
                                    "x": 546,
                                    "y": 1600,
                                    "buttonState": {

                                    },
                                    "interactive": true,
                                    "buttonMode": true,
                                },
                                {
                                    "name": "Intro_page_inActive_3",
                                    "image": "Intro_page_inActive",
                                    "type": objectTypes.Sprite,
                                    "class": "",
                                    "layout": true,
                                    "uimode": "desktop",
                                    "visible": true,
                                    "width": 28,
                                    "height": 28,
                                    "x": 960,
                                    "y": 850,
                                    "buttonState": {

                                    },
                                    "interactive": true,
                                    "buttonMode": true,
                                },
                                {
                                    "name": "Intro_page_inActive_3",
                                    "image": "Intro_page_inActive",
                                    "type": objectTypes.Sprite,
                                    "class": "",
                                    "layout": true,
                                    "uimode": "mobile",
                                    "visible": true,
                                    "width": 28,
                                    "height": 28,
                                    "x": 546,
                                    "y": 1600,
                                    "buttonState": {

                                    },
                                    "interactive": true,
                                    "buttonMode": true,
                                },
                                //ANCHOR -  - Intro_page_active_4 ------------------------
                                {
                                    "name": "Intro_page_active_4",
                                    "image": "Intro_page_active",
                                    "type": objectTypes.Sprite,
                                    "class": "",
                                    "layout": true,
                                    "uimode": "desktop",
                                    "visible": true,
                                    "width": 28,
                                    "height": 28,
                                    "x": 1000,
                                    "y": 850,
                                    "buttonState": {

                                    },
                                    "interactive": true,
                                    "buttonMode": true,
                                },
                                {
                                    "name": "Intro_page_active_4",
                                    "image": "Intro_page_active",
                                    "type": objectTypes.Sprite,
                                    "class": "",
                                    "layout": true,
                                    "uimode": "mobile",
                                    "visible": true,
                                    "width": 28,
                                    "height": 28,
                                    "x": 610,
                                    "y": 1600,
                                    "buttonState": {

                                    },
                                    "interactive": true,
                                    "buttonMode": true,
                                },
                                {
                                    "name": "Intro_page_inActive_4",
                                    "image": "Intro_page_inActive",
                                    "type": objectTypes.Sprite,
                                    "class": "",
                                    "layout": true,
                                    "uimode": "desktop",
                                    "visible": true,
                                    "width": 28,
                                    "height": 28,
                                    "x": 1000,
                                    "y": 850,
                                    "buttonState": {

                                    },
                                    "interactive": true,
                                    "buttonMode": true,
                                },
                                {
                                    "name": "Intro_page_inActive_4",
                                    "image": "Intro_page_inActive",
                                    "type": objectTypes.Sprite,
                                    "class": "",
                                    "layout": true,
                                    "uimode": "mobile",
                                    "visible": true,
                                    "width": 28,
                                    "height": 28,
                                    "x": 610,
                                    "y": 1600,
                                    "buttonState": {

                                    },
                                    "interactive": true,
                                    "buttonMode": true,
                                },
                                ///ANCHOR -  - Intro_page_active_5 ------------------------
                                {
                                    "name": "Intro_page_active_5",
                                    "image": "Intro_page_active",
                                    "type": objectTypes.Sprite,
                                    "class": "",
                                    "layout": true,
                                    "uimode": "desktop",
                                    "visible": true,
                                    "width": 28,
                                    "height": 28,
                                    "x": 1040,
                                    "y": 850,
                                    "buttonState": {

                                    },
                                    "interactive": true,
                                    "buttonMode": true,
                                },
                                {
                                    "name": "Intro_page_active_5",
                                    "image": "Intro_page_active",
                                    "type": objectTypes.Sprite,
                                    "class": "",
                                    "layout": true,
                                    "uimode": "mobile",
                                    "visible": true,
                                    "width": 28,
                                    "height": 28,
                                    "x": 670,
                                    "y": 1600,
                                    "buttonState": {

                                    },
                                    "interactive": true,
                                    "buttonMode": true,
                                },
                                {
                                    "name": "Intro_page_inActive_5",
                                    "image": "Intro_page_inActive",
                                    "type": objectTypes.Sprite,
                                    "class": "",
                                    "layout": true,
                                    "uimode": "desktop",
                                    "visible": true,
                                    "width": 28,
                                    "height": 28,
                                    "x": 1040,
                                    "y": 850,
                                    "buttonState": {

                                    },
                                    "interactive": true,
                                    "buttonMode": true,
                                },
                                {
                                    "name": "Intro_page_inActive_5",
                                    "image": "Intro_page_inActive",
                                    "type": objectTypes.Sprite,
                                    "class": "",
                                    "layout": true,
                                    "uimode": "mobile",
                                    "visible": true,
                                    "width": 28,
                                    "height": 28,
                                    "x": 670,
                                    "y": 1600,
                                    "buttonState": {

                                    },
                                    "interactive": true,
                                    "buttonMode": true,
                                },
                            ],
                        }
                    ]
                },
                //ANCHOR - Continue Button -----------------
                {
                    "id": "Button_1_desktop",
                    "name": "postIntro_continueButton_desktop",
                    "image": "continueButtonOfIntro",
                    "type": objectTypes.Sprite,
                    "interactive": true,
                    "layout": false,
                    "uimode": "desktop",
                    "x": 840,
                    "y": 915,
                    "height": 102,
                    "width": 260,
                    "text": "",
                    "visible": true,
                    "buttonMode": true,
                    "buttonState": {
                        up: 'continue_button_up.png',
                        out: 'continue_button_up.png',
                        down: 'continue_button_down.png',
                        disable: 'continue_button_disabled.png',
                        enable: 'continue_button_up.png',
                        hover: 'continue_button_over.png'
                    },
                    "hitareaVisible": false,
                    "shapeVisible": false,
                    "shape": {}
                },
                {
                    "id": "Button_1_mobile",
                    "name": "postIntro_continueButton_mobile",
                    "image": "continueButtonOfIntro",
                    "type": objectTypes.Sprite,
                    "interactive": false,
                    "layout": true,
                    "uimode": "mobile",
                    "x": 415,
                    "y": 1700,
                    "height": 102,
                    "width": 262,
                    "text": "",
                    "visible": true,
                    "buttonMode": true,
                    "buttonState": {
                        up: 'continue_button_up.png',
                        out: 'continue_button_up.png',
                        down: 'continue_button_down.png',
                        disable: 'continue_button_disabled.png',
                        enable: 'continue_button_up.png',
                        hover: 'continue_button_over.png'
                    },
                    "hitareaVisible": false,
                    "shapeVisible": false,
                    "shape": {}
                },
                {
                    "id": "text_1_desktop",
                    "name": "Text_Continue_desktop",
                    "type": "Text",
                    "x": 970,
                    "y": 965,
                    "layout": false,
                    "uimode": "desktop",
                    "visible": true,
                    "text": "continueIntroText",
                    "anchor": [0.5, 0.5],
                    "width": 280,
                    "scaleToFit": true,
                    "textStyle": {
                        fontFamily: 'Impact',
                        fontSize: 48,
                        fill: ['#ffc11a'],
                        dropShadow: true,
                        dropShadowColor: '#101902',
                        dropShadowDistance: 4,
                    },
                    "parentLayer": "specialAnimationLayer",
                },
                {
                    "id": "text_1_desktop",
                    "name": "Text_Continue_mobile",
                    "type": "Text",
                    "x": 550,
                    "y": 1750,
                    "layout": true,
                    "uimode": "mobile",
                    "visible": true,
                    "text": "continueIntroText",
                    "anchor": [0.5, 0.5],
                    "width": 280,
                    "scaleToFit": true,
                    "textStyle": {
                        fontFamily: 'Impact',
                        fontSize: 48,
                        fill: ['#ffc11a'],
                        dropShadow: true,
                        dropShadowColor: '#101902',
                        dropShadowDistance: 4,
                    },
                    "parentLayer": "specialAnimationLayer",
                },
            ]
        },

    ]
}
